// Minute Mantra — Part 3 of 4
// Days 183-273
// Auto-generated from mantras.json

module.exports = [
  {
    day_of_year: 183,
    original_script: 'ॐ मणि पद्मे हूँ',
    transliteration: 'Om Mani Padme Hum',
    english_translation: 'Om — the jewel in the lotus — hum.',
    tradition: 'buddhist',
    intention: 'Compassion',
    phonetic_guide: 'OHM mah-NEE pahd-MAY hoom',
    context_note: 'The mantra of Avalokiteshvara — the bodhisattva of compassion. The most widely chanted mantra in the world. The jewel is the awakened mind; the lotus is the world.',
    audio_filename: 'mantra-183.mp3',
    go_deeper_teaser: 'Om Mani Padme Hum: the six syllables of compassion →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 184,
    original_script: 'ॐ तारे तुत्तारे तुरे स्वाहा',
    transliteration: 'Om Tare Tuttare Ture Svaha',
    english_translation: 'Om — Tara who liberates — Tara who liberates swiftly — Tara who protects — so be it.',
    tradition: 'buddhist',
    intention: 'Liberation',
    phonetic_guide: 'OHM TAH-ray too-TAH-ray TOO-ray svah-HAH',
    context_note: 'The mantra of Green Tara — the swift-acting bodhisattva who saves from the eight fears. Tare means "she who liberates."',
    audio_filename: 'mantra-184.mp3',
    go_deeper_teaser: 'Green Tara: the swift liberator →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 185,
    original_script: 'ॐ अमिताभ हृदय',
    transliteration: 'Om Amitabha Hridaya',
    english_translation: 'Om — the heart of Amitabha — the buddha of infinite light.',
    tradition: 'buddhist',
    intention: 'Light',
    phonetic_guide: 'OHM ah-mee-TAH-bhah hrih-DAH-yah',
    context_note: 'Amitabha — "infinite light" — is the buddha of the western pure land. His light reaches all beings without exception.',
    audio_filename: 'mantra-185.mp3',
    go_deeper_teaser: 'Amitabha Buddha: the pure land of infinite light →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 186,
    original_script: 'नमो अमिताभाय',
    transliteration: 'Namo Amitabhaya',
    english_translation: 'I take refuge in Amitabha — the buddha of infinite light.',
    tradition: 'buddhist',
    intention: 'Refuge',
    phonetic_guide: 'nah-MOH ah-mee-TAH-bhah-yah',
    context_note: 'The nembutsu — the central practice of Pure Land Buddhism. Reciting Amitabha\'s name with sincere faith is said to ensure rebirth in the pure land.',
    audio_filename: 'mantra-186.mp3',
    go_deeper_teaser: 'The nembutsu: the simplest Buddhist practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 187,
    original_script: 'ॐ अह हूँ वज्र गुरु पद्म सिद्धि हूँ',
    transliteration: 'Om Ah Hum Vajra Guru Padma Siddhi Hum',
    english_translation: 'Om Ah Hum — Vajra Guru — lotus-born — accomplishment — Hum.',
    tradition: 'buddhist',
    intention: 'Mastery',
    phonetic_guide: 'OHM ah hoom VAHJ-rah GOO-roo PAHD-mah SID-dhee hoom',
    context_note: 'The mantra of Padmasambhava — Guru Rinpoche — who brought Buddhism to Tibet. The most important mantra in Vajrayana Buddhism.',
    audio_filename: 'mantra-187.mp3',
    go_deeper_teaser: 'Padmasambhava: the lotus-born master of Tibet →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 188,
    original_script: 'ॐ बज्र सत्त्व हूँ',
    transliteration: 'Om Vajrasattva Hum',
    english_translation: 'Om — Vajrasattva — the diamond being — Hum.',
    tradition: 'buddhist',
    intention: 'Purification',
    phonetic_guide: 'OHM VAHJ-rah-saht-tvah hoom',
    context_note: 'The short mantra of Vajrasattva — the buddha of purification. Vajra means "diamond" or "thunderbolt" — indestructible and pure.',
    audio_filename: 'mantra-188.mp3',
    go_deeper_teaser: 'Vajrasattva: the 100-syllable purification practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 189,
    original_script: 'ॐ नमो मञ्जुश्रीये',
    transliteration: 'Om Namo Manjushriye',
    english_translation: 'Om, I bow to Manjushri — the bodhisattva of wisdom.',
    tradition: 'buddhist',
    intention: 'Wisdom',
    phonetic_guide: 'OHM nah-MOH mahn-JOO-shree-yay',
    context_note: 'Manjushri holds a flaming sword to cut through ignorance and a book of wisdom. He is the embodiment of prajna — transcendent wisdom.',
    audio_filename: 'mantra-189.mp3',
    go_deeper_teaser: 'Manjushri\'s sword: cutting through ignorance →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 190,
    original_script: 'ॐ अ रा पा चा ना धीः',
    transliteration: 'Om A Ra Pa Ca Na Dhih',
    english_translation: 'Om — the five wisdom syllables — the seed of wisdom.',
    tradition: 'buddhist',
    intention: 'Wisdom',
    phonetic_guide: 'OHM ah rah pah chah nah dhee',
    context_note: 'The mantra of Manjushri. Each syllable represents a wisdom teaching. Dhih is the seed syllable of wisdom — the most important syllable.',
    audio_filename: 'mantra-190.mp3',
    go_deeper_teaser: 'The five wisdom syllables of Manjushri →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 191,
    original_script: 'ॐ गते गते पारगते पारसंगते बोधि स्वाहा',
    transliteration: 'Om Gate Gate Paragate Parasamgate Bodhi Svaha',
    english_translation: 'Gone, gone, gone beyond, gone completely beyond — awakening — so be it.',
    tradition: 'buddhist',
    intention: 'Transcendence',
    phonetic_guide: 'OHM GAH-tay GAH-tay pah-rah-GAH-tay pah-rah-sahm-GAH-tay BOH-dhee svah-HAH',
    context_note: 'The dharani from the Heart Sutra — the most concise expression of the Buddha\'s teaching on emptiness and transcendence.',
    audio_filename: 'mantra-191.mp3',
    go_deeper_teaser: 'The Heart Sutra: the Buddha\'s teaching on emptiness →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 192,
    original_script: 'बुद्धं शरणं गच्छामि',
    transliteration: 'Buddham Saranam Gacchami',
    english_translation: 'I take refuge in the Buddha.',
    tradition: 'buddhist',
    intention: 'Refuge',
    phonetic_guide: 'BOOD-dhahm shah-RAH-nahm GAHCH-chah-mee',
    context_note: 'The first of the Three Jewels — the triple refuge that is the foundation of all Buddhist practice. The Buddha is the awakened teacher.',
    audio_filename: 'mantra-192.mp3',
    go_deeper_teaser: 'The Three Jewels: the foundation of Buddhist practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 193,
    original_script: 'धम्मं शरणं गच्छामि',
    transliteration: 'Dhammam Saranam Gacchami',
    english_translation: 'I take refuge in the Dharma — the teaching.',
    tradition: 'buddhist',
    intention: 'Guidance',
    phonetic_guide: 'DHAHM-mahm shah-RAH-nahm GAHCH-chah-mee',
    context_note: 'The second of the Three Jewels. Dharma is the Buddha\'s teaching — the path that leads to liberation from suffering.',
    audio_filename: 'mantra-193.mp3',
    go_deeper_teaser: 'The Dharma: what the Buddha actually taught →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 194,
    original_script: 'संघं शरणं गच्छामि',
    transliteration: 'Sangham Saranam Gacchami',
    english_translation: 'I take refuge in the Sangha — the community.',
    tradition: 'buddhist',
    intention: 'Community',
    phonetic_guide: 'SAHNG-ghahm shah-RAH-nahm GAHCH-chah-mee',
    context_note: 'The third of the Three Jewels. Sangha is the community of practitioners — those who walk the path together.',
    audio_filename: 'mantra-194.mp3',
    go_deeper_teaser: 'Sangha: why community is essential for awakening →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 195,
    original_script: 'सर्वे सत्त्वाः सुखिनो भवन्तु',
    transliteration: 'Sarve Sattvah Sukhino Bhavantu',
    english_translation: 'May all beings be happy.',
    tradition: 'buddhist',
    intention: 'Loving-Kindness',
    phonetic_guide: 'SAHR-vay saht-TVAH soo-KHIH-noh bhah-VAHN-too',
    context_note: 'The metta (loving-kindness) prayer — the foundation of Buddhist compassion practice. It begins with all beings and works inward.',
    audio_filename: 'mantra-195.mp3',
    go_deeper_teaser: 'Metta meditation: the practice of loving-kindness →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 196,
    original_script: 'सर्वे सत्त्वाः निरामयाः',
    transliteration: 'Sarve Sattvah Niramayah',
    english_translation: 'May all beings be free from suffering.',
    tradition: 'buddhist',
    intention: 'Compassion',
    phonetic_guide: 'SAHR-vay saht-TVAH nih-rah-MAH-yah',
    context_note: 'The second line of the metta prayer. Niramaya — "free from disease" — extends to all forms of suffering, physical and mental.',
    audio_filename: 'mantra-196.mp3',
    go_deeper_teaser: 'Karuna: the practice of compassion →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 197,
    original_script: 'सर्वे सत्त्वाः सुखिताः भवन्तु',
    transliteration: 'Sarve Sattvah Sukhitah Bhavantu',
    english_translation: 'May all beings be at ease.',
    tradition: 'buddhist',
    intention: 'Ease',
    phonetic_guide: 'SAHR-vay saht-TVAH soo-KHIH-tah bhah-VAHN-too',
    context_note: 'The third line of the metta prayer. Sukhita — "at ease" — is a deeper wish than happiness: the ease of a mind free from struggle.',
    audio_filename: 'mantra-197.mp3',
    go_deeper_teaser: 'Upekkha: the practice of equanimity →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 198,
    original_script: 'ॐ स्वस्ति प्रजाभ्यः',
    transliteration: 'Om Svasti Prajabhyah',
    english_translation: 'Om, may all beings be well.',
    tradition: 'buddhist',
    intention: 'Wellbeing',
    phonetic_guide: 'OHM SVAHS-tee prah-JAH-bhyah',
    context_note: 'A universal Buddhist blessing. Svasti — "well-being" — is the root of the Sanskrit word swastika, an ancient symbol of auspiciousness.',
    audio_filename: 'mantra-198.mp3',
    go_deeper_teaser: 'Svasti: the original meaning of the swastika →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 199,
    original_script: 'ॐ नमो बुद्धाय',
    transliteration: 'Om Namo Buddhaya',
    english_translation: 'Om, I bow to the Buddha — the awakened one.',
    tradition: 'buddhist',
    intention: 'Awakening',
    phonetic_guide: 'OHM nah-MOH BOOD-dhah-yah',
    context_note: 'A simple, direct invocation of the Buddha. Buddha means "the awakened one" — one who has seen through the illusion of the separate self.',
    audio_filename: 'mantra-199.mp3',
    go_deeper_teaser: 'What does it mean to be awakened? →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 200,
    original_script: 'ॐ नमो धर्माय',
    transliteration: 'Om Namo Dharmaya',
    english_translation: 'Om, I bow to the Dharma — the truth.',
    tradition: 'buddhist',
    intention: 'Truth',
    phonetic_guide: 'OHM nah-MOH DHAHR-mah-yah',
    context_note: 'Bowing to the Dharma is bowing to truth itself — the way things actually are, beyond our concepts and preferences.',
    audio_filename: 'mantra-200.mp3',
    go_deeper_teaser: 'The Dharma: the Buddha\'s four noble truths →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 201,
    original_script: 'ॐ नमो संघाय',
    transliteration: 'Om Namo Sanghaya',
    english_translation: 'Om, I bow to the Sangha — the community of practitioners.',
    tradition: 'buddhist',
    intention: 'Community',
    phonetic_guide: 'OHM nah-MOH SAHNG-ghah-yah',
    context_note: 'The sangha is not just monks — it is all beings who walk the path of awakening. We are never alone on this journey.',
    audio_filename: 'mantra-201.mp3',
    go_deeper_teaser: 'The bodhisattva vow: awakening for all beings →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 202,
    original_script: 'ॐ अमोघपाश हूँ',
    transliteration: 'Om Amoghapasha Hum',
    english_translation: 'Om — the infallible lasso of compassion — Hum.',
    tradition: 'buddhist',
    intention: 'Compassion',
    phonetic_guide: 'OHM ah-MOH-ghah-PAH-shah hoom',
    context_note: 'Amoghapasha — "infallible lasso" — is a form of Avalokiteshvara who catches all beings in the net of compassion, leaving none behind.',
    audio_filename: 'mantra-202.mp3',
    go_deeper_teaser: 'Avalokiteshvara: the bodhisattva who hears all cries →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 203,
    original_script: 'ॐ नमो भगवते अमिताभाय',
    transliteration: 'Om Namo Bhagavate Amitabhaya',
    english_translation: 'Om, I bow to the blessed Amitabha.',
    tradition: 'buddhist',
    intention: 'Light',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay ah-mee-TAH-bhah-yah',
    context_note: 'The full refuge mantra of Amitabha Buddha. Bhagavate — "blessed one" — is the honorific used for all buddhas.',
    audio_filename: 'mantra-203.mp3',
    go_deeper_teaser: 'The pure land: is it real or metaphorical? →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 204,
    original_script: 'ॐ मेत्ता मेत्ता मेत्ता',
    transliteration: 'Om Metta Metta Metta',
    english_translation: 'Om — loving-kindness, loving-kindness, loving-kindness.',
    tradition: 'buddhist',
    intention: 'Loving-Kindness',
    phonetic_guide: 'OHM MET-tah MET-tah MET-tah',
    context_note: 'Metta (Pali) or Maitri (Sanskrit) — loving-kindness — is the first of the four brahmaviharas, the divine abodes. Triple repetition deepens the intention.',
    audio_filename: 'mantra-204.mp3',
    go_deeper_teaser: 'The four brahmaviharas: the divine abodes →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 205,
    original_script: 'ॐ करुणा करुणा करुणा',
    transliteration: 'Om Karuna Karuna Karuna',
    english_translation: 'Om — compassion, compassion, compassion.',
    tradition: 'buddhist',
    intention: 'Compassion',
    phonetic_guide: 'OHM kah-ROO-nah kah-ROO-nah kah-ROO-nah',
    context_note: 'Karuna — compassion — is the second brahmavihara. It is the wish for all beings to be free from suffering.',
    audio_filename: 'mantra-205.mp3',
    go_deeper_teaser: 'Karuna: the difference between compassion and pity →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 206,
    original_script: 'ॐ मुदिता मुदिता मुदिता',
    transliteration: 'Om Mudita Mudita Mudita',
    english_translation: 'Om — sympathetic joy, sympathetic joy, sympathetic joy.',
    tradition: 'buddhist',
    intention: 'Joy',
    phonetic_guide: 'OHM moo-DIH-tah moo-DIH-tah moo-DIH-tah',
    context_note: 'Mudita — "sympathetic joy" — is the third brahmavihara: the ability to rejoice in the happiness of others without envy.',
    audio_filename: 'mantra-206.mp3',
    go_deeper_teaser: 'Mudita: the antidote to envy →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 207,
    original_script: 'ॐ उपेक्षा उपेक्षा उपेक्षा',
    transliteration: 'Om Upekkha Upekkha Upekkha',
    english_translation: 'Om — equanimity, equanimity, equanimity.',
    tradition: 'buddhist',
    intention: 'Equanimity',
    phonetic_guide: 'OHM oo-PEK-shah oo-PEK-shah oo-PEK-shah',
    context_note: 'Upekkha — equanimity — is the fourth brahmavihara: the ability to remain balanced and undisturbed in all circumstances.',
    audio_filename: 'mantra-207.mp3',
    go_deeper_teaser: 'Equanimity: the highest of the four divine abodes →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 208,
    original_script: 'ॐ शान्ति शान्ति शान्ति',
    transliteration: 'Om Shanti Shanti Shanti',
    english_translation: 'Om — peace, peace, peace.',
    tradition: 'buddhist',
    intention: 'Peace',
    phonetic_guide: 'OHM SHAHN-tee SHAHN-tee SHAHN-tee',
    context_note: 'The universal peace invocation. Three repetitions address the three sources of disturbance: body, speech, and mind.',
    audio_filename: 'mantra-208.mp3',
    go_deeper_teaser: 'The three levels of peace: body, speech, and mind →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 209,
    original_script: 'ॐ नमो रत्नत्रयाय',
    transliteration: 'Om Namo Ratnatrayaya',
    english_translation: 'Om, I bow to the three jewels.',
    tradition: 'buddhist',
    intention: 'Refuge',
    phonetic_guide: 'OHM nah-MOH raht-nah-TRAH-yah-yah',
    context_note: 'Ratnatraya — "three jewels" — are the Buddha, Dharma, and Sangha. Taking refuge in them is the foundation of all Buddhist practice.',
    audio_filename: 'mantra-209.mp3',
    go_deeper_teaser: 'Taking refuge: what it really means →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 210,
    original_script: 'ॐ नमो भगवते शाक्यमुनये',
    transliteration: 'Om Namo Bhagavate Shakyamunaye',
    english_translation: 'Om, I bow to the blessed Shakyamuni — the sage of the Shakya clan.',
    tradition: 'buddhist',
    intention: 'Gratitude',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay SHAHK-yah-moo-nah-yay',
    context_note: 'Shakyamuni — "sage of the Shakyas" — is the historical Buddha, Siddhartha Gautama. This mantra honors the human teacher who showed the way.',
    audio_filename: 'mantra-210.mp3',
    go_deeper_teaser: 'The historical Buddha: his life and awakening →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 211,
    original_script: 'ॐ अह हूँ',
    transliteration: 'Om Ah Hum',
    english_translation: 'Om — body, speech, mind — Hum.',
    tradition: 'buddhist',
    intention: 'Integration',
    phonetic_guide: 'OHM ah hoom',
    context_note: 'The three seed syllables of Vajrayana Buddhism: Om purifies the body, Ah purifies speech, Hum purifies the mind.',
    audio_filename: 'mantra-211.mp3',
    go_deeper_teaser: 'Om Ah Hum: the three vajras of body, speech, and mind →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 212,
    original_script: 'ॐ वज्रसत्त्व समयम्',
    transliteration: 'Om Vajrasattva Samayam',
    english_translation: 'Om — Vajrasattva — the sacred commitment.',
    tradition: 'buddhist',
    intention: 'Commitment',
    phonetic_guide: 'OHM VAHJ-rah-saht-tvah sah-MAH-yahm',
    context_note: 'The opening of the Vajrasattva 100-syllable mantra. Samaya — "sacred commitment" — is the vow between student and teacher, between practitioner and the divine.',
    audio_filename: 'mantra-212.mp3',
    go_deeper_teaser: 'Samaya: the sacred vow of Vajrayana →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 213,
    original_script: 'अनुपालय',
    transliteration: 'Anupalaya',
    english_translation: 'Please uphold me.',
    tradition: 'buddhist',
    intention: 'Support',
    phonetic_guide: 'ah-noo-PAH-lah-yah',
    context_note: 'From the Vajrasattva mantra. A prayer for the divine to uphold and sustain the practitioner on the path.',
    audio_filename: 'mantra-213.mp3',
    go_deeper_teaser: 'The 100-syllable Vajrasattva mantra: complete guide →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 214,
    original_script: 'ॐ नमो मञ्जुश्रीये नमः',
    transliteration: 'Om Namo Manjushriye Namah',
    english_translation: 'Om, I bow to Manjushri — the gentle-voiced one.',
    tradition: 'buddhist',
    intention: 'Learning',
    phonetic_guide: 'OHM nah-MOH mahn-JOO-shree-yay nah-MAH',
    context_note: 'Manjushri — "gentle glory" — is the bodhisattva of wisdom. His name means "gentle-voiced" — wisdom is always gentle, never harsh.',
    audio_filename: 'mantra-214.mp3',
    go_deeper_teaser: 'Manjushri: the bodhisattva of wisdom →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 215,
    original_script: 'ॐ वज्रपाणये नमः',
    transliteration: 'Om Vajrapanaye Namah',
    english_translation: 'Om, I bow to Vajrapani — the thunderbolt-wielder.',
    tradition: 'buddhist',
    intention: 'Power',
    phonetic_guide: 'OHM VAHJ-rah-PAH-nah-yay nah-MAH',
    context_note: 'Vajrapani — "thunderbolt in hand" — is the bodhisattva of power. He represents the power of the awakened mind to cut through all obstacles.',
    audio_filename: 'mantra-215.mp3',
    go_deeper_teaser: 'Vajrapani: the power of the awakened mind →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 216,
    original_script: 'ॐ नमो भगवते भैषज्यगुरु',
    transliteration: 'Om Namo Bhagavate Bhaishajyaguru',
    english_translation: 'Om, I bow to the blessed Medicine Buddha.',
    tradition: 'buddhist',
    intention: 'Healing',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay bhay-SHAHJ-yah-GOO-roo',
    context_note: 'Bhaishajyaguru — "Medicine Buddha" — is the buddha of healing. His body is lapis lazuli blue, and he holds a medicine bowl.',
    audio_filename: 'mantra-216.mp3',
    go_deeper_teaser: 'Medicine Buddha: the healing practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 217,
    original_script: 'वैडूर्यप्रभाराजाय',
    transliteration: 'Vaiduryaprabharajaya',
    english_translation: 'To the king of lapis lazuli light.',
    tradition: 'buddhist',
    intention: 'Healing',
    phonetic_guide: 'vay-DOO-ryah-PRAH-bhah-RAH-jah-yah',
    context_note: 'Part of the Medicine Buddha mantra. Vaidurya — "lapis lazuli" — is the deep blue stone that represents the clarity of the awakened mind.',
    audio_filename: 'mantra-217.mp3',
    go_deeper_teaser: 'Lapis lazuli: the stone of the Medicine Buddha →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 218,
    original_script: 'तथागताय',
    transliteration: 'Tathagataya',
    english_translation: 'To the thus-gone one — the one who has gone to suchness.',
    tradition: 'buddhist',
    intention: 'Suchness',
    phonetic_guide: 'tah-TAH-gah-tah-yah',
    context_note: 'Tathagata — "thus-gone" or "thus-come" — is the Buddha\'s own name for himself. It points to the nature of reality: things are just as they are.',
    audio_filename: 'mantra-218.mp3',
    go_deeper_teaser: 'Tathata: the Buddhist concept of suchness →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 219,
    original_script: 'ॐ भेकन्द्जे भेकन्द्जे',
    transliteration: 'Om Bekandze Bekandze',
    english_translation: 'Om — eliminate, eliminate — the pain of illness.',
    tradition: 'buddhist',
    intention: 'Healing',
    phonetic_guide: 'OHM bay-KAHN-dzay bay-KAHN-dzay',
    context_note: 'The heart of the Medicine Buddha mantra. Bekandze means "eliminate pain" — the mantra is said to heal both physical illness and the illness of ignorance.',
    audio_filename: 'mantra-219.mp3',
    go_deeper_teaser: 'The Medicine Buddha mantra: healing body and mind →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 220,
    original_script: 'महाभेकन्द्जे राद्जा समुद्गते स्वाहा',
    transliteration: 'Maha Bekandze Radza Samudgate Svaha',
    english_translation: 'Great elimination — king — the supreme arising — so be it.',
    tradition: 'buddhist',
    intention: 'Complete Healing',
    phonetic_guide: 'mah-HAH bay-KAHN-dzay RAHD-zah sah-mood-GAH-tay svah-HAH',
    context_note: 'The conclusion of the Medicine Buddha mantra. Samudgate — "supreme arising" — points to the arising of the awakened mind that heals all.',
    audio_filename: 'mantra-220.mp3',
    go_deeper_teaser: 'The complete Medicine Buddha practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 221,
    original_script: 'ॐ नमो भगवते अमितायुषे',
    transliteration: 'Om Namo Bhagavate Amitayushe',
    english_translation: 'Om, I bow to the blessed one of infinite life.',
    tradition: 'buddhist',
    intention: 'Longevity',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay ah-mee-TAH-yoo-shay',
    context_note: 'Amitayus — "infinite life" — is the longevity aspect of Amitabha Buddha. This mantra is chanted for long life and the extension of the teaching.',
    audio_filename: 'mantra-221.mp3',
    go_deeper_teaser: 'Amitayus: the Buddha of infinite life →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 222,
    original_script: 'ॐ अमरणि जीवन्तये स्वाहा',
    transliteration: 'Om Amarani Jivantaye Svaha',
    english_translation: 'Om — immortal life — living — so be it.',
    tradition: 'buddhist',
    intention: 'Life Force',
    phonetic_guide: 'OHM ah-mah-RAH-nih jee-VAHN-tah-yay svah-HAH',
    context_note: 'The Amitayus mantra. Amarani — "immortal" — refers not to physical immortality but to the deathless nature of the awakened mind.',
    audio_filename: 'mantra-222.mp3',
    go_deeper_teaser: 'The deathless: what the Buddha meant by nirvana →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 223,
    original_script: 'ॐ नमो भगवते सर्वदुर्गतिपरिशोधनाय',
    transliteration: 'Om Namo Bhagavate Sarvadurgatiparisodhana',
    english_translation: 'Om, I bow to the one who purifies all lower realms.',
    tradition: 'buddhist',
    intention: 'Purification',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay sahr-vah-door-gah-tih-pah-rih-SOH-dhah-nah',
    context_note: 'The opening of the Stainless Beam mantra — one of the most powerful purification mantras in Tibetan Buddhism.',
    audio_filename: 'mantra-223.mp3',
    go_deeper_teaser: 'The Stainless Beam mantra: purifying all karma →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 224,
    original_script: 'ॐ बोधिचित्त उत्पादयामि',
    transliteration: 'Om Bodhicitta Utpadayami',
    english_translation: 'Om, I generate the awakening mind.',
    tradition: 'buddhist',
    intention: 'Awakening',
    phonetic_guide: 'OHM BOH-dhih-chiht-tah oot-PAH-dah-YAH-mih',
    context_note: 'Bodhicitta — "awakening mind" — is the aspiration to achieve enlightenment for the benefit of all beings. It is the heart of Mahayana Buddhism.',
    audio_filename: 'mantra-224.mp3',
    go_deeper_teaser: 'Bodhicitta: the most precious mind →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 225,
    original_script: 'ॐ नमो भगवते प्रज्ञापारमिताये',
    transliteration: 'Om Namo Bhagavate Prajnaparamitaye',
    english_translation: 'Om, I bow to the blessed perfection of wisdom.',
    tradition: 'buddhist',
    intention: 'Wisdom',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay PRAHJ-nyah-PAH-rah-mih-TAH-yay',
    context_note: 'Prajnaparamita — "perfection of wisdom" — is personified as a goddess and is the "mother of all buddhas." The Heart Sutra is her teaching.',
    audio_filename: 'mantra-225.mp3',
    go_deeper_teaser: 'Prajnaparamita: the mother of all buddhas →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 226,
    original_script: 'ॐ नमो भगवते अक्षोभ्याय',
    transliteration: 'Om Namo Bhagavate Akshobhyaya',
    english_translation: 'Om, I bow to the blessed Akshobhya — the imperturbable.',
    tradition: 'buddhist',
    intention: 'Imperturbability',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay ahk-SHOH-bhyah-yah',
    context_note: 'Akshobhya — "imperturbable" — is the buddha of the east, representing mirror-like wisdom. His dark blue color represents the depth of the awakened mind.',
    audio_filename: 'mantra-226.mp3',
    go_deeper_teaser: 'The five dhyani buddhas: a complete map of awakening →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 227,
    original_script: 'ॐ नमो भगवते रत्नसम्भवाय',
    transliteration: 'Om Namo Bhagavate Ratnasambhavaya',
    english_translation: 'Om, I bow to the blessed Ratnasambhava — the jewel-born.',
    tradition: 'buddhist',
    intention: 'Abundance',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay raht-nah-SAHM-bhah-vah-yah',
    context_note: 'Ratnasambhava — "jewel-born" — is the buddha of the south, representing the wisdom of equality. All beings are equally precious jewels.',
    audio_filename: 'mantra-227.mp3',
    go_deeper_teaser: 'Ratnasambhava: the wisdom of equality →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 228,
    original_script: 'ॐ नमो भगवते अमोघसिद्धये',
    transliteration: 'Om Namo Bhagavate Amoghasiddhaye',
    english_translation: 'Om, I bow to the blessed Amoghasiddhi — the infallible accomplisher.',
    tradition: 'buddhist',
    intention: 'Accomplishment',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay ah-MOH-ghah-SID-dhah-yay',
    context_note: 'Amoghasiddhi — "infallible accomplishment" — is the buddha of the north, representing all-accomplishing wisdom.',
    audio_filename: 'mantra-228.mp3',
    go_deeper_teaser: 'Amoghasiddhi: the all-accomplishing wisdom →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 229,
    original_script: 'ॐ नमो भगवते वैरोचनाय',
    transliteration: 'Om Namo Bhagavate Vairochana',
    english_translation: 'Om, I bow to the blessed Vairochana — the illuminator.',
    tradition: 'buddhist',
    intention: 'Illumination',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay vay-ROH-chah-nah',
    context_note: 'Vairochana — "the illuminator" — is the central buddha of the five dhyani buddhas, representing the dharmadhatu wisdom — the wisdom of all-encompassing space.',
    audio_filename: 'mantra-229.mp3',
    go_deeper_teaser: 'Vairochana: the central buddha of the mandala →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 230,
    original_script: 'ॐ आह्राह् हूँ',
    transliteration: 'Om Ah Ra Pa Ca Na Dhih Dhih Dhih',
    english_translation: 'Om — the wisdom syllables — wisdom, wisdom, wisdom.',
    tradition: 'buddhist',
    intention: 'Wisdom',
    phonetic_guide: 'OHM ah rah pah chah nah dhee dhee dhee',
    context_note: 'The extended Manjushri mantra with triple Dhih. Dhih is the seed syllable of wisdom — repeating it three times intensifies the awakening of prajna.',
    audio_filename: 'mantra-230.mp3',
    go_deeper_teaser: 'Prajna: the wisdom that liberates →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 231,
    original_script: 'ॐ सुप्रतिष्ठित स्वाहा',
    transliteration: 'Om Supratishthita Svaha',
    english_translation: 'Om — well-established — so be it.',
    tradition: 'buddhist',
    intention: 'Stability',
    phonetic_guide: 'OHM soo-prah-TISH-thih-tah svah-HAH',
    context_note: 'Supratishthita — "well-established" — is a dharani for establishing the practice firmly. Svaha seals the intention.',
    audio_filename: 'mantra-231.mp3',
    go_deeper_teaser: 'Establishing a daily practice: the Buddhist approach →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 232,
    original_script: 'ॐ धरणी धरणी स्वाहा',
    transliteration: 'Om Dharani Dharani Svaha',
    english_translation: 'Om — earth-holder, earth-holder — so be it.',
    tradition: 'buddhist',
    intention: 'Grounding',
    phonetic_guide: 'OHM dhah-RAH-nih dhah-RAH-nih svah-HAH',
    context_note: 'Dharani means both "earth" and "that which holds." This mantra grounds the practice in the earth of reality.',
    audio_filename: 'mantra-232.mp3',
    go_deeper_teaser: 'Dharani: the mantras that hold the earth →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 233,
    original_script: 'ॐ नमो भगवते वज्रपाणये',
    transliteration: 'Om Namo Bhagavate Vajrapanaye',
    english_translation: 'Om, I bow to the blessed Vajrapani.',
    tradition: 'buddhist',
    intention: 'Power',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay VAHJ-rah-PAH-nah-yay',
    context_note: 'Vajrapani\'s thunderbolt cuts through the three poisons: greed, hatred, and delusion. This mantra invokes the power to overcome inner obstacles.',
    audio_filename: 'mantra-233.mp3',
    go_deeper_teaser: 'The three poisons: greed, hatred, and delusion →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 234,
    original_script: 'ॐ नमो भगवते कुरुकुल्लायै',
    transliteration: 'Om Namo Bhagavate Kurukulle',
    english_translation: 'Om, I bow to the blessed Kurukulle — the goddess of enchantment.',
    tradition: 'buddhist',
    intention: 'Attraction',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay koo-roo-KOOL-lay',
    context_note: 'Kurukulle is a tantric goddess who enchants and magnetizes — drawing beings toward the Dharma through the power of love.',
    audio_filename: 'mantra-234.mp3',
    go_deeper_teaser: 'Kurukulle: the goddess who draws beings to the Dharma →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 235,
    original_script: 'ॐ नमो भगवते चुन्द्रायै',
    transliteration: 'Om Namo Bhagavate Cundrayai',
    english_translation: 'Om, I bow to the blessed Cunda — the goddess of awakening.',
    tradition: 'buddhist',
    intention: 'Awakening',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay CHOON-drah-yay',
    context_note: 'Cunda (or Chunda) is a bodhisattva associated with the awakening mind. She is depicted with multiple arms representing her many activities.',
    audio_filename: 'mantra-235.mp3',
    go_deeper_teaser: 'The female bodhisattvas: wisdom in feminine form →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 236,
    original_script: 'ॐ नमो भगवते वज्रसारप्रमर्दने',
    transliteration: 'Om Namo Bhagavate Vajrasarapramardane',
    english_translation: 'Om, I bow to the crusher of the vajra essence.',
    tradition: 'buddhist',
    intention: 'Purification',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay VAHJ-rah-SAH-rah-prah-MAHR-dah-nay',
    context_note: 'A powerful purification dharani. Pramardane — "crusher" — refers to the crushing of karmic obscurations.',
    audio_filename: 'mantra-236.mp3',
    go_deeper_teaser: 'Karma: what it really means and how to purify it →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 237,
    original_script: 'ॐ सर्वपापविशोधन',
    transliteration: 'Om Sarvapapavishoshana',
    english_translation: 'Om — purifier of all sins.',
    tradition: 'buddhist',
    intention: 'Purification',
    phonetic_guide: 'OHM sahr-vah-PAH-pah-vih-SOH-shah-nah',
    context_note: 'A dharani for purifying all negative karma. Vishoshana — "drying up" — suggests that negative karma is dried up like water in sunlight.',
    audio_filename: 'mantra-237.mp3',
    go_deeper_teaser: 'Purification practices in Buddhism →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 238,
    original_script: 'ॐ नमो भगवते सर्वतथागत',
    transliteration: 'Om Namo Bhagavate Sarvatathagata',
    english_translation: 'Om, I bow to all the blessed thus-gone ones.',
    tradition: 'buddhist',
    intention: 'Reverence',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay sahr-vah-tah-TAH-gah-tah',
    context_note: 'A universal salutation to all buddhas of all times and directions. The awakened ones are infinite in number.',
    audio_filename: 'mantra-238.mp3',
    go_deeper_teaser: 'The infinite buddhas: the Buddhist vision of awakening →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 239,
    original_script: 'ॐ धर्मधातु स्वभाव',
    transliteration: 'Om Dharmadhatu Svabhava',
    english_translation: 'Om — the nature of the dharma realm.',
    tradition: 'buddhist',
    intention: 'Nature of Mind',
    phonetic_guide: 'OHM DHAHR-mah-DAH-too svah-BHAH-vah',
    context_note: 'Dharmadhatu — "dharma realm" — is the totality of all phenomena as they truly are. Svabhava — "own nature" — points to the intrinsic nature of mind.',
    audio_filename: 'mantra-239.mp3',
    go_deeper_teaser: 'Dharmadhatu: the realm of truth →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 240,
    original_script: 'ॐ स्वभाव शुद्धाः सर्वधर्माः',
    transliteration: 'Om Svabhava Shuddha Sarvadharmah',
    english_translation: 'Om — by nature pure are all phenomena.',
    tradition: 'buddhist',
    intention: 'Purity',
    phonetic_guide: 'OHM svah-BHAH-vah SHOO-dhah sahr-vah-DHAHR-mah',
    context_note: 'The emptiness mantra — all phenomena are pure by nature. This is the Madhyamaka view: nothing is inherently defiled.',
    audio_filename: 'mantra-240.mp3',
    go_deeper_teaser: 'Emptiness: the most misunderstood Buddhist teaching →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 241,
    original_script: 'स्वभाव शुद्धो ऽहम्',
    transliteration: 'Svabhava Shuddho\'ham',
    english_translation: 'I am pure by nature.',
    tradition: 'buddhist',
    intention: 'Purity',
    phonetic_guide: 'svah-BHAH-vah SHOO-dhoh-hahm',
    context_note: 'The personal application of the emptiness mantra. Your true nature is pure — not because you have purified it, but because it was never defiled.',
    audio_filename: 'mantra-241.mp3',
    go_deeper_teaser: 'Buddha nature: the purity that was always there →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 242,
    original_script: 'ॐ नमो भगवते तथागत',
    transliteration: 'Om Namo Bhagavate Tathagata',
    english_translation: 'Om, I bow to the blessed thus-gone one.',
    tradition: 'buddhist',
    intention: 'Suchness',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay tah-TAH-gah-tah',
    context_note: 'A simple, universal invocation of the Buddha. Tathagata — "thus-gone" — points to the nature of awakening: going beyond all concepts.',
    audio_filename: 'mantra-242.mp3',
    go_deeper_teaser: 'Tathagata: the Buddha\'s most profound name →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 243,
    original_script: 'ॐ भव भव महाभव',
    transliteration: 'Om Bhava Bhava Mahabhava',
    english_translation: 'Om — become, become, greatly become.',
    tradition: 'buddhist',
    intention: 'Becoming',
    phonetic_guide: 'OHM BHAH-vah BHAH-vah mah-hah-BHAH-vah',
    context_note: 'A mantra of transformation. Bhava — "becoming" — is the process of continuous change. The mantra invites full participation in the process of becoming.',
    audio_filename: 'mantra-243.mp3',
    go_deeper_teaser: 'Impermanence: the Buddhist teaching on change →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 244,
    original_script: 'ॐ सम्बोधि सम्बोधि',
    transliteration: 'Om Sambodhi Sambodhi',
    english_translation: 'Om — complete awakening, complete awakening.',
    tradition: 'buddhist',
    intention: 'Awakening',
    phonetic_guide: 'OHM sahm-BOH-dhee sahm-BOH-dhee',
    context_note: 'Sambodhi — "complete awakening" — is the full enlightenment of a buddha. Repeating it twice affirms the aspiration for complete awakening.',
    audio_filename: 'mantra-244.mp3',
    go_deeper_teaser: 'Sambodhi: what complete awakening actually means →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 245,
    original_script: 'ॐ बोधि बोधि महाबोधि',
    transliteration: 'Om Bodhi Bodhi Mahabodhi',
    english_translation: 'Om — awakening, awakening, great awakening.',
    tradition: 'buddhist',
    intention: 'Awakening',
    phonetic_guide: 'OHM BOH-dhee BOH-dhee mah-hah-BOH-dhee',
    context_note: 'A mantra of progressive awakening. Bodhi — "awakening" — grows from individual to great, from partial to complete.',
    audio_filename: 'mantra-245.mp3',
    go_deeper_teaser: 'The stages of awakening in Buddhism →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 246,
    original_script: 'ॐ नमो भगवते अवलोकितेश्वराय',
    transliteration: 'Om Namo Bhagavate Avalokiteshvaraya',
    english_translation: 'Om, I bow to the blessed Avalokiteshvara — the one who hears all cries.',
    tradition: 'buddhist',
    intention: 'Compassion',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay ah-vah-loh-kih-TAYSH-vah-rah-yah',
    context_note: 'Avalokiteshvara — "the one who looks down with compassion" — is the bodhisattva who hears all cries of suffering and responds with compassion.',
    audio_filename: 'mantra-246.mp3',
    go_deeper_teaser: 'Avalokiteshvara: the bodhisattva of universal compassion →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 247,
    original_script: 'ॐ सर्वज्ञाय नमः',
    transliteration: 'Om Sarvajnaya Namah',
    english_translation: 'Om, I bow to the all-knowing one.',
    tradition: 'buddhist',
    intention: 'Omniscience',
    phonetic_guide: 'OHM sahr-VAHJ-nyah-yah nah-MAH',
    context_note: 'Sarvajnaya — "all-knowing" — is an epithet of the Buddha. Omniscience is not supernatural; it is the natural result of a completely purified mind.',
    audio_filename: 'mantra-247.mp3',
    go_deeper_teaser: 'Omniscience: the Buddhist understanding →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 248,
    original_script: 'ॐ नमो भगवते मैत्रेयाय',
    transliteration: 'Om Namo Bhagavate Maitreya',
    english_translation: 'Om, I bow to the blessed Maitreya — the future Buddha of loving-kindness.',
    tradition: 'buddhist',
    intention: 'Loving-Kindness',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay my-TRAY-yah',
    context_note: 'Maitreya — "the loving one" — is the future Buddha who will appear when the Dharma has been forgotten. His name is the root of the word "metta."',
    audio_filename: 'mantra-248.mp3',
    go_deeper_teaser: 'Maitreya: the future Buddha of loving-kindness →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 249,
    original_script: 'ॐ नमो भगवते क्षितिगर्भाय',
    transliteration: 'Om Namo Bhagavate Kshitigarbhaya',
    english_translation: 'Om, I bow to the blessed Kshitigarbha — the earth treasury.',
    tradition: 'buddhist',
    intention: 'Compassion',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay kshih-tih-GAHR-bhah-yah',
    context_note: 'Kshitigarbha — "earth treasury" — is the bodhisattva who vowed to save all beings from the hell realms before becoming a buddha.',
    audio_filename: 'mantra-249.mp3',
    go_deeper_teaser: 'Kshitigarbha: the bodhisattva who descends to hell →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 250,
    original_script: 'ॐ सम्पद्यन्ते स्वाहा',
    transliteration: 'Om Sampadyante Svaha',
    english_translation: 'Om — may it be accomplished — so be it.',
    tradition: 'buddhist',
    intention: 'Accomplishment',
    phonetic_guide: 'OHM sahm-PAHD-yahn-tay svah-HAH',
    context_note: 'A completion mantra. Sampadyante — "may it be accomplished" — seals any practice or intention with the wish for its fulfillment.',
    audio_filename: 'mantra-250.mp3',
    go_deeper_teaser: 'Sealing a practice: the importance of dedication →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 251,
    original_script: 'ੴ ਸਤਿ ਨਾਮੁ',
    transliteration: 'Ik Onkar Sat Nam',
    english_translation: 'One God — True Name.',
    tradition: 'sikh',
    intention: 'Unity',
    phonetic_guide: 'ik OHN-kahr saht nahm',
    context_note: 'The Mool Mantar — the root mantra of Sikhism, composed by Guru Nanak. Ik Onkar — "One God" — is the foundational truth of Sikh theology.',
    audio_filename: 'mantra-251.mp3',
    go_deeper_teaser: 'The Mool Mantar: Sikhism\'s most sacred teaching →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 252,
    original_script: 'ਕਰਤਾ ਪੁਰਖੁ',
    transliteration: 'Karta Purakh',
    english_translation: 'The Creator Being.',
    tradition: 'sikh',
    intention: 'Creation',
    phonetic_guide: 'KAHR-tah POO-rahkh',
    context_note: 'From the Mool Mantar. Karta — "creator" — Purakh — "being" or "person." The divine is not an abstract force but a personal creator.',
    audio_filename: 'mantra-252.mp3',
    go_deeper_teaser: 'Karta Purakh: the personal God of Sikhism →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 253,
    original_script: 'ਨਿਰਭਉ ਨਿਰਵੈਰੁ',
    transliteration: 'Nirbhau Nirvair',
    english_translation: 'Without fear, without enmity.',
    tradition: 'sikh',
    intention: 'Fearlessness',
    phonetic_guide: 'nih-BHOW nih-VAIR',
    context_note: 'From the Mool Mantar. The divine has no fear and no enemies. Meditating on these qualities transforms the practitioner.',
    audio_filename: 'mantra-253.mp3',
    go_deeper_teaser: 'Nirbhau: the fearless God of Guru Nanak →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 254,
    original_script: 'ਅਕਾਲ ਮੂਰਤਿ',
    transliteration: 'Akal Murat',
    english_translation: 'Timeless form — beyond time and death.',
    tradition: 'sikh',
    intention: 'Eternity',
    phonetic_guide: 'ah-KAHL MOO-raht',
    context_note: 'From the Mool Mantar. Akal — "beyond time" — Murat — "form." The divine is the timeless presence that underlies all temporal forms.',
    audio_filename: 'mantra-254.mp3',
    go_deeper_teaser: 'Akal: the timeless God of Sikhism →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 255,
    original_script: 'ਅਜੂਨੀ ਸੈਭੰ',
    transliteration: 'Ajuni Saibhang',
    english_translation: 'Unborn, self-illumined.',
    tradition: 'sikh',
    intention: 'Self-Sufficiency',
    phonetic_guide: 'ah-JOO-nih SAY-bhahng',
    context_note: 'From the Mool Mantar. The divine was not born and does not need anything outside itself. Saibhang — "self-illumined" — the divine is its own light.',
    audio_filename: 'mantra-255.mp3',
    go_deeper_teaser: 'Saibhang: the self-illumined nature of God →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 256,
    original_script: 'ਗੁਰ ਪ੍ਰਸਾਦਿ',
    transliteration: 'Gur Prasad',
    english_translation: 'By the grace of the Guru.',
    tradition: 'sikh',
    intention: 'Grace',
    phonetic_guide: 'goor prah-SAHD',
    context_note: 'The final phrase of the Mool Mantar. All spiritual realization comes by the grace of the Guru — not by personal effort alone.',
    audio_filename: 'mantra-256.mp3',
    go_deeper_teaser: 'Gur Prasad: the grace that makes everything possible →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 257,
    original_script: 'ਵਾਹਿਗੁਰੂ',
    transliteration: 'Waheguru',
    english_translation: 'Wondrous Guru — the divine that fills us with wonder.',
    tradition: 'sikh',
    intention: 'Wonder',
    phonetic_guide: 'WAH-hay-goo-roo',
    context_note: 'The most important mantra in Sikhism. Wahe — "wondrous" — Guru — "teacher." The divine is the teacher who fills us with wonder.',
    audio_filename: 'mantra-257.mp3',
    go_deeper_teaser: 'Waheguru: the wonder at the heart of Sikhism →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 258,
    original_script: 'ਸਤਿ ਨਾਮੁ ਵਾਹਿਗੁਰੂ',
    transliteration: 'Sat Nam Waheguru',
    english_translation: 'True Name — Wondrous Guru.',
    tradition: 'sikh',
    intention: 'Truth',
    phonetic_guide: 'saht nahm WAH-hay-goo-roo',
    context_note: 'The most common Sikh mantra combination. Sat Nam — "True Name" — is the identity of the divine. Waheguru is the expression of wonder at that truth.',
    audio_filename: 'mantra-258.mp3',
    go_deeper_teaser: 'Sat Nam: the true name of God →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 259,
    original_script: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ',
    transliteration: 'Sat Sri Akal',
    english_translation: 'True, great, and timeless.',
    tradition: 'sikh',
    intention: 'Truth',
    phonetic_guide: 'saht sree ah-KAHL',
    context_note: 'The Sikh greeting and battle cry. Sri — "great" or "radiant" — Akal — "timeless." A reminder that truth is eternal.',
    audio_filename: 'mantra-259.mp3',
    go_deeper_teaser: 'Sat Sri Akal: the Sikh greeting and its meaning →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 260,
    original_script: 'ਨਾਨਕ ਨਾਮ ਚੜ੍ਹਦੀ ਕਲਾ',
    transliteration: 'Nanak Nam Chardi Kala',
    english_translation: 'Nanak, through the Name, may there be ever-rising spirit.',
    tradition: 'sikh',
    intention: 'Optimism',
    phonetic_guide: 'NAH-nahk nahm CHAHR-dee kah-LAH',
    context_note: 'Chardi Kala — "ever-rising spirit" — is the Sikh concept of eternal optimism. No matter what happens, the spirit rises. This is the Sikh response to adversity.',
    audio_filename: 'mantra-260.mp3',
    go_deeper_teaser: 'Chardi Kala: the Sikh practice of eternal optimism →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 261,
    original_script: 'ਤੇਰੇ ਭਾਣੇ ਸਰਬਤ ਦਾ ਭਲਾ',
    transliteration: 'Tere Bhane Sarbat Da Bhala',
    english_translation: 'In your will, may all prosper.',
    tradition: 'sikh',
    intention: 'Universal Welfare',
    phonetic_guide: 'TAY-ray BHAH-nay SAHR-baht dah BHAH-lah',
    context_note: 'The Ardas prayer\'s closing line. Sarbat — "all" — Da Bhala — "welfare." The Sikh prayer always ends with a wish for the welfare of all humanity.',
    audio_filename: 'mantra-261.mp3',
    go_deeper_teaser: 'Ardas: the Sikh prayer for all humanity →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 262,
    original_script: 'ਸਿਮਰਨ ਸਿਮਰਨ ਸਿਮਰਨ',
    transliteration: 'Simran Simran Simran',
    english_translation: 'Remembrance, remembrance, remembrance.',
    tradition: 'sikh',
    intention: 'Remembrance',
    phonetic_guide: 'SIM-rahn SIM-rahn SIM-rahn',
    context_note: 'Simran — "remembrance" or "meditation" — is the central Sikh practice. To remember God\'s name in every breath is the highest spiritual discipline.',
    audio_filename: 'mantra-262.mp3',
    go_deeper_teaser: 'Simran: the Sikh practice of divine remembrance →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 263,
    original_script: 'ਹਰਿ ਹਰਿ ਹਰਿ ਹਰਿ',
    transliteration: 'Har Har Har Har',
    english_translation: 'God, God, God, God — the creative infinity.',
    tradition: 'sikh',
    intention: 'Creativity',
    phonetic_guide: 'hahr hahr hahr hahr',
    context_note: 'Har is the Sikh name for God as the creative force. Repeating it activates the navel center and the creative power of the divine.',
    audio_filename: 'mantra-263.mp3',
    go_deeper_teaser: 'Har: the creative name of God in Sikhism →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 264,
    original_script: 'ਹਰਿ ਨਾਮੁ ਜਪਹੁ',
    transliteration: 'Har Nam Japahu',
    english_translation: 'Chant the name of God.',
    tradition: 'sikh',
    intention: 'Practice',
    phonetic_guide: 'hahr nahm JAH-pah-hoo',
    context_note: 'From the Guru Granth Sahib. Japahu — "chant" — is the imperative form. The Guru\'s instruction is direct: chant the name.',
    audio_filename: 'mantra-264.mp3',
    go_deeper_teaser: 'Japa: the practice of mantra repetition →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 265,
    original_script: 'ਰਾਮ ਰਾਮ ਰਾਮ ਰਾਮ',
    transliteration: 'Ram Ram Ram Ram',
    english_translation: 'Ram, Ram, Ram, Ram — the divine joy.',
    tradition: 'sikh',
    intention: 'Joy',
    phonetic_guide: 'rahm rahm rahm rahm',
    context_note: 'In Sikhism, Ram is not just the avatar but the divine name meaning "the one who permeates all." The Gurus used many divine names interchangeably.',
    audio_filename: 'mantra-265.mp3',
    go_deeper_teaser: 'Ram in Sikhism: the all-pervasive divine →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 266,
    original_script: 'ਗੋਬਿੰਦ ਗੋਬਿੰਦ ਗੋਬਿੰਦ ਸੰਗਿ',
    transliteration: 'Gobind Gobind Gobind Sang',
    english_translation: 'Gobind, Gobind, Gobind — in the company of God.',
    tradition: 'sikh',
    intention: 'Companionship',
    phonetic_guide: 'GOH-bind GOH-bind GOH-bind sahng',
    context_note: 'From the Guru Granth Sahib. Gobind — "sustainer of the world" — is repeated three times, then "sang" — "in the company of." We are never alone.',
    audio_filename: 'mantra-266.mp3',
    go_deeper_teaser: 'Sangat: the Sikh community of truth →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 267,
    original_script: 'ਨਾਮੁ ਜਪਤ ਅਰਪੋ ਤਨੁ ਮਨੁ',
    transliteration: 'Nam Japat Arpo Tan Man',
    english_translation: 'Chanting the Name, offer body and mind.',
    tradition: 'sikh',
    intention: 'Surrender',
    phonetic_guide: 'nahm JAH-paht AHR-poh tahn mahn',
    context_note: 'From the Guru Granth Sahib. The complete offering in Sikhism is not just words but the whole self — body and mind — surrendered to the divine name.',
    audio_filename: 'mantra-267.mp3',
    go_deeper_teaser: 'Total surrender: the Sikh path of devotion →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 268,
    original_script: 'ਸਾਸ ਸਾਸ ਸਿਮਰਹੁ ਗੋਬਿੰਦ',
    transliteration: 'Sas Sas Simrahu Gobind',
    english_translation: 'With every breath, remember Gobind.',
    tradition: 'sikh',
    intention: 'Breath Practice',
    phonetic_guide: 'sahs sahs SIM-rah-hoo GOH-bind',
    context_note: 'From the Guru Granth Sahib. Sas — "breath." The Sikh practice of remembering God with every breath transforms ordinary breathing into prayer.',
    audio_filename: 'mantra-268.mp3',
    go_deeper_teaser: 'Breath as prayer: the Sikh practice of Sas Sas →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 269,
    original_script: 'ਮਨ ਤੂੰ ਜੋਤਿ ਸਰੂਪੁ ਹੈ',
    transliteration: 'Man Tu Jot Sarup Hai',
    english_translation: 'O mind, you are the image of divine light.',
    tradition: 'sikh',
    intention: 'Self-Realization',
    phonetic_guide: 'mahn too joht sah-ROOP hay',
    context_note: 'From the Guru Granth Sahib. Jot — "light" — Sarup — "form" or "image." The mind is not the enemy but the image of divine light.',
    audio_filename: 'mantra-269.mp3',
    go_deeper_teaser: 'Jot Sarup: the light within you →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 270,
    original_script: 'ਅਪਣਾ ਮੂਲੁ ਪਛਾਣੁ',
    transliteration: 'Apna Mul Pachhan',
    english_translation: 'Recognize your own origin.',
    tradition: 'sikh',
    intention: 'Self-Knowledge',
    phonetic_guide: 'ahp-NAH mool pah-CHAHN',
    context_note: 'From the Guru Granth Sahib. Mul — "root" or "origin." The Guru\'s instruction: know where you come from. Your origin is divine.',
    audio_filename: 'mantra-270.mp3',
    go_deeper_teaser: 'Mul: returning to the root of your being →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 271,
    original_script: 'ਜਿਉ ਜਿਉ ਤੇਰੀ ਰਜਾਇ',
    transliteration: 'Jio Jio Teri Raza',
    english_translation: 'As is your will, so be it.',
    tradition: 'sikh',
    intention: 'Acceptance',
    phonetic_guide: 'jee-OH jee-OH TAY-ree rah-ZAH',
    context_note: 'From the Guru Granth Sahib. Raza — "will" or "pleasure." Complete acceptance of the divine will is the highest Sikh spiritual state.',
    audio_filename: 'mantra-271.mp3',
    go_deeper_teaser: 'Raza: the Sikh practice of divine will acceptance →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 272,
    original_script: 'ਨਾਨਕ ਦਾਸ ਤੇਰੇ ਦਰ ਕਾ',
    transliteration: 'Nanak Das Tere Dar Ka',
    english_translation: 'Nanak is the servant at your door.',
    tradition: 'sikh',
    intention: 'Humility',
    phonetic_guide: 'NAH-nahk dahs TAY-ray dahr kah',
    context_note: 'Guru Nanak\'s signature of humility. Das — "servant." The greatest teacher called himself a servant at the divine door.',
    audio_filename: 'mantra-272.mp3',
    go_deeper_teaser: 'Guru Nanak: the servant who became the teacher →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 273,
    original_script: 'ਤੁਧੁ ਬਿਨੁ ਦੂਜਾ ਨਾਹੀ ਕੋਇ',
    transliteration: 'Tudh Bin Duja Nahi Koi',
    english_translation: 'Without you, there is no other.',
    tradition: 'sikh',
    intention: 'Oneness',
    phonetic_guide: 'too-DHOO bin DOO-jah nah-HEE koh-EE',
    context_note: 'From the Guru Granth Sahib. A declaration of non-duality: there is only God. Everything else is the play of the one divine reality.',
    audio_filename: 'mantra-273.mp3',
    go_deeper_teaser: 'Sikh non-dualism: there is only one →',
    go_deeper_url: 'https://paulwagner.com',
  },
];
