// Minute Mantra — Part 4 of 4
// Days 274-365
// Auto-generated from mantras.json

module.exports = [
  {
    day_of_year: 274,
    original_script: 'ਸਰਬ ਕਲਾ ਭਰਪੂਰ',
    transliteration: 'Sarab Kala Bharpoor',
    english_translation: 'Fully pervading all with all powers.',
    tradition: 'sikh',
    intention: 'Omnipresence',
    phonetic_guide: 'sah-RAHB kah-LAH bhar-POOR',
    context_note: 'From the Guru Granth Sahib. Sarab — "all" — Kala — "powers" — Bharpoor — "fully pervading." The divine is fully present everywhere with all its powers.',
    audio_filename: 'mantra-274.mp3',
    go_deeper_teaser: 'The omnipresent God of the Guru Granth Sahib →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 275,
    original_script: 'ॐ',
    transliteration: 'Om',
    english_translation: 'The primordial sound — the vibration from which all creation arises.',
    tradition: 'universal',
    intention: 'Source',
    phonetic_guide: 'OHM (hold for 5-7 seconds)',
    context_note: 'Om is the first sound — the vibration of pure consciousness before it becomes words or thoughts. It contains all sounds within it.',
    audio_filename: 'mantra-275.mp3',
    go_deeper_teaser: 'The physics of Om: why it is the primordial sound →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 276,
    original_script: 'ॐ ॐ ॐ',
    transliteration: 'Om Om Om',
    english_translation: 'Three Oms — for body, speech, and mind.',
    tradition: 'universal',
    intention: 'Integration',
    phonetic_guide: 'OHM... OHM... OHM... (pause between each)',
    context_note: 'Three Oms purify the three aspects of our being: the physical body, speech and breath, and the mind. A complete practice in three sounds.',
    audio_filename: 'mantra-276.mp3',
    go_deeper_teaser: 'The three Oms: a complete purification practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 277,
    original_script: 'ॐ शान्तिः शान्तिः शान्तिः',
    transliteration: 'Om Shantih Shantih Shantih',
    english_translation: 'Om — peace, peace, peace.',
    tradition: 'universal',
    intention: 'Peace',
    phonetic_guide: 'OHM SHAHN-tih SHAHN-tih SHAHN-tih',
    context_note: 'The universal peace invocation ending all Vedic prayers. Three repetitions address the three sources of suffering: adhyatmika (self), adhibhautika (others), adhidaivika (cosmos).',
    audio_filename: 'mantra-277.mp3',
    go_deeper_teaser: 'The three sources of suffering and their antidote →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 278,
    original_script: 'सोऽहम्',
    transliteration: 'So\'ham',
    english_translation: 'I am that — the breath itself is the mantra.',
    tradition: 'universal',
    intention: 'Identity',
    phonetic_guide: 'SOH-hahm (So on inhale, Ham on exhale)',
    context_note: 'So\'ham is the natural sound of the breath: So on the inhale, Ham on the exhale. The breath itself is saying "I am that" 21,600 times per day.',
    audio_filename: 'mantra-278.mp3',
    go_deeper_teaser: 'So\'ham: the mantra you\'ve been chanting since birth →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 279,
    original_script: 'हंसः',
    transliteration: 'Hamsa',
    english_translation: 'The swan — the breath — I am that.',
    tradition: 'universal',
    intention: 'Breath',
    phonetic_guide: 'HAHM-sah (Ham on exhale, Sa on inhale)',
    context_note: 'Hamsa — "swan" or "I am that" — is So\'ham reversed. The swan is the symbol of the discriminating mind that separates milk from water.',
    audio_filename: 'mantra-279.mp3',
    go_deeper_teaser: 'Hamsa: the swan of discernment →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 280,
    original_script: 'अहम् ब्रह्मास्मि',
    transliteration: 'Aham Brahmasmi',
    english_translation: 'I am Brahman — I am the infinite.',
    tradition: 'universal',
    intention: 'Self-Realization',
    phonetic_guide: 'AH-hahm BRAH-mahs-mih',
    context_note: 'One of the four mahavakyas — great sayings — of the Upanishads. From the Brihadaranyaka Upanishad. The direct declaration of identity with the infinite.',
    audio_filename: 'mantra-280.mp3',
    go_deeper_teaser: 'The four mahavakyas: the Upanishads\' greatest declarations →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 281,
    original_script: 'तत् त्वम् असि',
    transliteration: 'Tat Tvam Asi',
    english_translation: 'That thou art — you are that infinite reality.',
    tradition: 'universal',
    intention: 'Non-Duality',
    phonetic_guide: 'taht tvahm AH-see',
    context_note: 'The second mahavakya from the Chandogya Upanishad. The teacher\'s declaration to the student: you are not separate from the infinite.',
    audio_filename: 'mantra-281.mp3',
    go_deeper_teaser: 'Tat tvam asi: the teaching that changes everything →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 282,
    original_script: 'प्रज्ञानं ब्रह्म',
    transliteration: 'Prajnanam Brahma',
    english_translation: 'Consciousness is Brahman — awareness is the infinite.',
    tradition: 'universal',
    intention: 'Consciousness',
    phonetic_guide: 'PRAHJ-nyah-nahm BRAH-mah',
    context_note: 'The third mahavakya from the Aitareya Upanishad. Prajna — "consciousness" or "awareness" — is identified with the infinite ground of being.',
    audio_filename: 'mantra-282.mp3',
    go_deeper_teaser: 'Consciousness as the ground of being →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 283,
    original_script: 'अयम् आत्मा ब्रह्म',
    transliteration: 'Ayam Atma Brahma',
    english_translation: 'This self is Brahman — the individual self is the universal self.',
    tradition: 'universal',
    intention: 'Unity',
    phonetic_guide: 'AH-yahm AHT-mah BRAH-mah',
    context_note: 'The fourth mahavakya from the Mandukya Upanishad. The individual self (atman) is declared identical to the universal ground of being (brahman). The simplest and most direct of the four great sayings.',
    audio_filename: 'mantra-283.mp3',
    go_deeper_teaser: 'The four mahavakyas: the great declarations of non-duality →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 284,
    original_script: 'I Release What No Longer Serves Me',
    transliteration: 'I Release What No Longer Serves Me',
    english_translation: 'I lovingly release all patterns, beliefs, and attachments that no longer serve my highest good.',
    tradition: 'english_affirmation',
    intention: 'Liberation',
    phonetic_guide: 'I release what no longer serves me',
    context_note: 'Letting go is not loss — it is making space for grace. Every release is an act of trust in the divine unfolding of your life.',
    audio_filename: 'mantra-284.mp3',
    go_deeper_teaser: 'The sacred art of letting go →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 285,
    original_script: 'My Heart Is Open and Fearless',
    transliteration: 'My Heart Is Open and Fearless',
    english_translation: 'I open my heart fully, without fear, trusting in the protection of divine love.',
    tradition: 'english_affirmation',
    intention: 'Courage',
    phonetic_guide: 'My heart is open and fearless',
    context_note: 'An open heart is the most powerful force in the universe. When you lead with love, fear dissolves like shadows in sunlight.',
    audio_filename: 'mantra-285.mp3',
    go_deeper_teaser: 'Why an open heart is your greatest strength →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 286,
    original_script: 'I Trust the Unfolding of My Life',
    transliteration: 'I Trust the Unfolding of My Life',
    english_translation: 'I surrender to the divine timing and perfect unfolding of my soul\'s journey.',
    tradition: 'english_affirmation',
    intention: 'Surrender',
    phonetic_guide: 'I trust the unfolding of my life',
    context_note: 'Your life is not random — it is orchestrated by a wisdom far greater than the mind can comprehend. Trust the process.',
    audio_filename: 'mantra-286.mp3',
    go_deeper_teaser: 'Surrendering to divine timing →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 287,
    original_script: 'ॐ सच्चिदानन्द',
    transliteration: 'Om Satchidananda',
    english_translation: 'Om — existence, consciousness, bliss.',
    tradition: 'universal',
    intention: 'Bliss',
    phonetic_guide: 'OHM saht-chid-AH-nahn-dah',
    context_note: 'Sat-Chit-Ananda — the three qualities of Brahman: pure existence, pure consciousness, and pure bliss. This is the nature of ultimate reality.',
    audio_filename: 'mantra-287.mp3',
    go_deeper_teaser: 'Satchidananda: the nature of ultimate reality →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 288,
    original_script: 'I Am the Witness of My Thoughts',
    transliteration: 'I Am the Witness of My Thoughts',
    english_translation: 'I am not my thoughts — I am the vast, silent awareness that observes them all.',
    tradition: 'english_affirmation',
    intention: 'Awareness',
    phonetic_guide: 'I am the witness of my thoughts',
    context_note: 'The moment you realize you are watching your thoughts, you have stepped into your true nature — pure consciousness itself.',
    audio_filename: 'mantra-288.mp3',
    go_deeper_teaser: 'The observer effect in spiritual practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 289,
    original_script: 'I Choose Peace in Every Moment',
    transliteration: 'I Choose Peace in Every Moment',
    english_translation: 'In every situation, I consciously choose the peace that already lives within me.',
    tradition: 'english_affirmation',
    intention: 'Inner Peace',
    phonetic_guide: 'I choose peace in every moment',
    context_note: 'Peace is not the absence of chaos — it is the presence of awareness. You can access it anywhere, anytime, by turning inward.',
    audio_filename: 'mantra-289.mp3',
    go_deeper_teaser: 'Finding peace in the eye of the storm →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 290,
    original_script: 'I Am Connected to All Living Beings',
    transliteration: 'I Am Connected to All Living Beings',
    english_translation: 'I honor the sacred thread of consciousness that connects me to every living being.',
    tradition: 'english_affirmation',
    intention: 'Unity',
    phonetic_guide: 'I am connected to all living beings',
    context_note: 'Separation is the great illusion. The same divine spark that animates your heart beats in every creature on Earth.',
    audio_filename: 'mantra-290.mp3',
    go_deeper_teaser: 'The Vedantic truth of oneness →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 291,
    original_script: 'Abundance Flows to Me Naturally',
    transliteration: 'Abundance Flows to Me Naturally',
    english_translation: 'I am a natural channel for abundance in all its forms — love, health, wisdom, and prosperity.',
    tradition: 'english_affirmation',
    intention: 'Abundance',
    phonetic_guide: 'Abundance flows to me naturally',
    context_note: 'Abundance is not something you chase — it is something you align with. When you vibrate at the frequency of gratitude, abundance finds you.',
    audio_filename: 'mantra-291.mp3',
    go_deeper_teaser: 'Aligning with the flow of abundance →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 292,
    original_script: 'ॐ ऐं सरस्वत्यै नमः',
    transliteration: 'Om Aim Sarasvatyai Namah',
    english_translation: 'Om — seed of Saraswati — I bow to the goddess of wisdom.',
    tradition: 'universal',
    intention: 'Wisdom',
    phonetic_guide: 'OHM aim sah-rahs-VAHT-yay nah-MAH',
    context_note: 'Saraswati is the goddess of learning, music, and wisdom. Aim is her seed syllable. This mantra is chanted before study and creative work.',
    audio_filename: 'mantra-292.mp3',
    go_deeper_teaser: 'Saraswati: the goddess of creative wisdom →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 293,
    original_script: 'ॐ दुं दुर्गायै नमः',
    transliteration: 'Om Dum Durgayai Namah',
    english_translation: 'Om — seed of Durga — I bow to the invincible one.',
    tradition: 'universal',
    intention: 'Courage',
    phonetic_guide: 'OHM doom door-GAH-yay nah-MAH',
    context_note: 'Durga — "the invincible" — is the warrior goddess who protects against all evil. Dum is her seed syllable. This mantra invokes inner strength.',
    audio_filename: 'mantra-293.mp3',
    go_deeper_teaser: 'Durga: the warrior goddess within you →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 294,
    original_script: 'ॐ क्लीं कृष्णाय नमः',
    transliteration: 'Om Klim Krishnaya Namah',
    english_translation: 'Om — seed of attraction — I bow to Krishna.',
    tradition: 'universal',
    intention: 'Love',
    phonetic_guide: 'OHM kleem krish-NAH-yah nah-MAH',
    context_note: 'Klim is the seed syllable of attraction and love. This mantra invokes Krishna\'s quality of divine love — the love that draws all things toward the divine.',
    audio_filename: 'mantra-294.mp3',
    go_deeper_teaser: 'Klim: the seed syllable of divine love →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 295,
    original_script: 'I Forgive Myself Completely',
    transliteration: 'I Forgive Myself Completely',
    english_translation: 'I release all self-judgment and embrace myself with the same compassion I would offer a dear friend.',
    tradition: 'english_affirmation',
    intention: 'Self-Forgiveness',
    phonetic_guide: 'I forgive myself completely',
    context_note: 'Self-forgiveness is not weakness — it is the bravest act of love. You cannot heal what you refuse to hold with compassion.',
    audio_filename: 'mantra-295.mp3',
    go_deeper_teaser: 'Why forgiveness is not what you think →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 296,
    original_script: 'ॐ तत् सत्',
    transliteration: 'Om Tat Sat',
    english_translation: 'Om — that — truth.',
    tradition: 'universal',
    intention: 'Truth',
    phonetic_guide: 'OHM taht saht',
    context_note: 'From the Bhagavad Gita. Om Tat Sat — the three designations of Brahman. Om is the sound, Tat is the pointer, Sat is the reality.',
    audio_filename: 'mantra-296.mp3',
    go_deeper_teaser: 'Om Tat Sat: the three names of the absolute →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 297,
    original_script: 'I Am Enough Exactly as I Am',
    transliteration: 'I Am Enough Exactly as I Am',
    english_translation: 'I do not need to become anything — I am already whole, complete, and enough.',
    tradition: 'english_affirmation',
    intention: 'Self-Acceptance',
    phonetic_guide: 'I am enough exactly as I am',
    context_note: 'The spiritual path is not about becoming someone new — it is about remembering who you have always been beneath the layers of conditioning.',
    audio_filename: 'mantra-297.mp3',
    go_deeper_teaser: 'The radical truth of self-acceptance →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 298,
    original_script: 'ॐ श्री रामाय नमः',
    transliteration: 'Om Sri Ramaya Namah',
    english_translation: 'Om — I bow to the radiant Ram.',
    tradition: 'universal',
    intention: 'Virtue',
    phonetic_guide: 'OHM shree RAH-mah-yah nah-MAH',
    context_note: 'Ram — "the one who delights" — is the avatar of Vishnu who embodies dharma. Sri adds radiance and auspiciousness to the invocation.',
    audio_filename: 'mantra-298.mp3',
    go_deeper_teaser: 'Ram: the avatar of perfect virtue →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 299,
    original_script: 'राम राम राम',
    transliteration: 'Ram Ram Ram',
    english_translation: 'Ram, Ram, Ram — the name that is the Vedas.',
    tradition: 'universal',
    intention: 'Liberation',
    phonetic_guide: 'rahm rahm rahm',
    context_note: 'Gandhi\'s dying words were "Hey Ram." The name Ram is said to contain the essence of all the Vedas. Simple, direct, and infinitely deep.',
    audio_filename: 'mantra-299.mp3',
    go_deeper_teaser: 'Why Gandhi\'s last words were "Hey Ram" →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 300,
    original_script: 'ॐ हनुमते नमः',
    transliteration: 'Om Hanumate Namah',
    english_translation: 'Om — I bow to Hanuman — the devoted servant.',
    tradition: 'universal',
    intention: 'Devotion',
    phonetic_guide: 'OHM hah-noo-MAH-tay nah-MAH',
    context_note: 'Hanuman is the embodiment of devotion, strength, and selfless service. His devotion to Ram is the model for all spiritual practice.',
    audio_filename: 'mantra-300.mp3',
    go_deeper_teaser: 'Hanuman: the perfect devotee →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 301,
    original_script: 'ॐ श्री हनुमते नमः',
    transliteration: 'Om Sri Hanumate Namah',
    english_translation: 'Om — I bow to the radiant Hanuman.',
    tradition: 'universal',
    intention: 'Strength',
    phonetic_guide: 'OHM shree hah-noo-MAH-tay nah-MAH',
    context_note: 'Hanuman\'s strength comes from his devotion — not from ego or personal power. This mantra invokes strength that is rooted in love.',
    audio_filename: 'mantra-301.mp3',
    go_deeper_teaser: 'Strength through devotion: Hanuman\'s secret →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 302,
    original_script: 'I Honor the Teacher Within Me',
    transliteration: 'I Honor the Teacher Within Me',
    english_translation: 'I recognize that the greatest guru lives within my own heart — the voice of my soul.',
    tradition: 'english_affirmation',
    intention: 'Inner Wisdom',
    phonetic_guide: 'I honor the teacher within me',
    context_note: 'Every external teacher points you back to the same truth — the guru within. Your own consciousness is the ultimate guide.',
    audio_filename: 'mantra-302.mp3',
    go_deeper_teaser: 'The inner guru awakens →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 303,
    original_script: 'My Breath Is My Anchor',
    transliteration: 'My Breath Is My Anchor',
    english_translation: 'With every conscious breath, I return to the present moment — the only place where life truly exists.',
    tradition: 'english_affirmation',
    intention: 'Presence',
    phonetic_guide: 'My breath is my anchor',
    context_note: 'The breath is the bridge between body and spirit. Each conscious breath is a prayer, a return to the sacred now.',
    audio_filename: 'mantra-303.mp3',
    go_deeper_teaser: 'The sacred art of breathwork →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 304,
    original_script: 'I Am Safe in the Arms of the Universe',
    transliteration: 'I Am Safe in the Arms of the Universe',
    english_translation: 'I am held, protected, and deeply loved by the infinite intelligence of the cosmos.',
    tradition: 'english_affirmation',
    intention: 'Trust',
    phonetic_guide: 'I am safe in the arms of the universe',
    context_note: 'You are never alone. The same force that spins galaxies and grows forests is holding you right now.',
    audio_filename: 'mantra-304.mp3',
    go_deeper_teaser: 'Trusting the cosmic embrace →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 305,
    original_script: 'I Radiate Love Without Condition',
    transliteration: 'I Radiate Love Without Condition',
    english_translation: 'I give love freely, without expectation, knowing that love is the very fabric of my being.',
    tradition: 'english_affirmation',
    intention: 'Unconditional Love',
    phonetic_guide: 'I radiate love without condition',
    context_note: 'Unconditional love is not something you practice — it is what you are when you stop pretending to be something else.',
    audio_filename: 'mantra-305.mp3',
    go_deeper_teaser: 'Love as spiritual practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 306,
    original_script: 'ॐ भूमि माता',
    transliteration: 'Om Bhumi Mata',
    english_translation: 'Om — Earth Mother.',
    tradition: 'universal',
    intention: 'Earth',
    phonetic_guide: 'OHM BHOO-mih MAH-tah',
    context_note: 'A universal invocation of the earth as mother. All spiritual traditions recognize the earth as sacred. We are born from her and return to her.',
    audio_filename: 'mantra-306.mp3',
    go_deeper_teaser: 'Earth as mother: the universal teaching →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 307,
    original_script: 'ॐ द्यौः पिता',
    transliteration: 'Om Dyauh Pita',
    english_translation: 'Om — Sky Father.',
    tradition: 'universal',
    intention: 'Sky',
    phonetic_guide: 'OHM dyow PIH-tah',
    context_note: 'The sky as father — the vast, open awareness that contains all experience. The earth is our mother; the sky is our father. We are children of both.',
    audio_filename: 'mantra-307.mp3',
    go_deeper_teaser: 'Sky and earth: the universal parents →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 308,
    original_script: 'ॐ अन्तरिक्षम्',
    transliteration: 'Om Antariksha',
    english_translation: 'Om — the space between — the intermediate realm.',
    tradition: 'universal',
    intention: 'Space',
    phonetic_guide: 'OHM ahn-TAH-rik-shahm',
    context_note: 'Antariksha — "the space between" — is the intermediate realm between earth and sky. It represents the liminal space of transformation.',
    audio_filename: 'mantra-308.mp3',
    go_deeper_teaser: 'The space between: where transformation happens →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 309,
    original_script: 'Every Challenge Is My Teacher',
    transliteration: 'Every Challenge Is My Teacher',
    english_translation: 'I welcome every challenge as a sacred opportunity for growth, healing, and deeper understanding.',
    tradition: 'english_affirmation',
    intention: 'Growth',
    phonetic_guide: 'Every challenge is my teacher',
    context_note: 'The soul does not grow in comfort — it grows in the fire of transformation. Every difficulty is grace in disguise.',
    audio_filename: 'mantra-309.mp3',
    go_deeper_teaser: 'Transforming obstacles into awakening →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 310,
    original_script: 'I Am Grateful for This Moment',
    transliteration: 'I Am Grateful for This Moment',
    english_translation: 'I choose gratitude as my default state, recognizing the miracle of this present moment.',
    tradition: 'english_affirmation',
    intention: 'Gratitude',
    phonetic_guide: 'I am grateful for this moment',
    context_note: 'Gratitude is not just a feeling — it is a frequency. When you vibrate with thankfulness, the entire universe conspires in your favor.',
    audio_filename: 'mantra-310.mp3',
    go_deeper_teaser: 'The transformative power of gratitude →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 311,
    original_script: 'I Send Love to All Beings',
    transliteration: 'I Send Love to All Beings',
    english_translation: 'From the depths of my heart, I send love and healing light to every being in existence.',
    tradition: 'english_affirmation',
    intention: 'Compassion',
    phonetic_guide: 'I send love to all beings',
    context_note: 'When you send love outward, it multiplies and returns to you a thousandfold. This is the law of the heart.',
    audio_filename: 'mantra-311.mp3',
    go_deeper_teaser: 'The ripple effect of compassion →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 312,
    original_script: 'My Body Is a Sacred Temple',
    transliteration: 'My Body Is a Sacred Temple',
    english_translation: 'I honor my body as the sacred vessel through which my soul experiences this beautiful life.',
    tradition: 'english_affirmation',
    intention: 'Body Reverence',
    phonetic_guide: 'My body is a sacred temple',
    context_note: 'Your body is not separate from spirit — it is spirit made visible. Treat it with the reverence it deserves.',
    audio_filename: 'mantra-312.mp3',
    go_deeper_teaser: 'The body as spiritual technology →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 313,
    original_script: 'I Am the Stillness Beneath the Storm',
    transliteration: 'I Am the Stillness Beneath the Storm',
    english_translation: 'No matter what swirls around me, I remain rooted in the unshakable stillness of my true nature.',
    tradition: 'english_affirmation',
    intention: 'Equanimity',
    phonetic_guide: 'I am the stillness beneath the storm',
    context_note: 'The ocean\'s surface may rage, but its depths remain forever still. You are that depth.',
    audio_filename: 'mantra-313.mp3',
    go_deeper_teaser: 'Finding your unshakable center →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 314,
    original_script: 'I Welcome Healing into Every Cell',
    transliteration: 'I Welcome Healing into Every Cell',
    english_translation: 'I invite divine healing energy to flow through every cell, every fiber, every corner of my being.',
    tradition: 'english_affirmation',
    intention: 'Healing',
    phonetic_guide: 'I welcome healing into every cell',
    context_note: 'Healing is not something that happens to you — it is something that happens through you when you stop resisting the flow of grace.',
    audio_filename: 'mantra-314.mp3',
    go_deeper_teaser: 'The body\'s innate wisdom to heal →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 315,
    original_script: 'I Walk in Truth and Integrity',
    transliteration: 'I Walk in Truth and Integrity',
    english_translation: 'I align my thoughts, words, and actions with the highest truth I know.',
    tradition: 'english_affirmation',
    intention: 'Truth',
    phonetic_guide: 'I walk in truth and integrity',
    context_note: 'Truth is not a concept — it is a vibration. When you live in alignment with truth, every part of your life begins to harmonize.',
    audio_filename: 'mantra-315.mp3',
    go_deeper_teaser: 'Living in radical truth →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 316,
    original_script: 'I Am a Channel for Divine Grace',
    transliteration: 'I Am a Channel for Divine Grace',
    english_translation: 'I allow divine grace to flow through me, blessing everyone I encounter.',
    tradition: 'english_affirmation',
    intention: 'Grace',
    phonetic_guide: 'I am a channel for divine grace',
    context_note: 'You do not need to generate grace — you need only to stop blocking it. Remove the resistance, and grace floods in.',
    audio_filename: 'mantra-316.mp3',
    go_deeper_teaser: 'Becoming a vessel for grace →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 317,
    original_script: 'I Transform Pain into Wisdom',
    transliteration: 'I Transform Pain into Wisdom',
    english_translation: 'Every wound I carry becomes a wellspring of wisdom, compassion, and strength.',
    tradition: 'english_affirmation',
    intention: 'Transformation',
    phonetic_guide: 'I transform pain into wisdom',
    context_note: 'Your deepest pain holds your greatest teaching. The soul chose these experiences not to punish you, but to awaken you.',
    audio_filename: 'mantra-317.mp3',
    go_deeper_teaser: 'The alchemy of suffering →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 318,
    original_script: 'ॐ लोकाः समस्ताः सुखिनो भवन्तु',
    transliteration: 'Om Lokah Samastah Sukhino Bhavantu',
    english_translation: 'Om — may all beings in all worlds be happy and free.',
    tradition: 'universal',
    intention: 'Universal Welfare',
    phonetic_guide: 'OHM LOH-kah sah-MAHS-tah soo-KHIH-noh bhah-VAHN-too',
    context_note: 'The most universal of all mantras. Lokah — "worlds" — Samastah — "all." This prayer extends to all beings in all dimensions of existence.',
    audio_filename: 'mantra-318.mp3',
    go_deeper_teaser: 'Lokah Samastah: the prayer that changes the world →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 319,
    original_script: 'I Am Boundless Consciousness',
    transliteration: 'I Am Boundless Consciousness',
    english_translation: 'I am not this body, not this mind — I am the infinite, boundless consciousness that pervades all things.',
    tradition: 'english_affirmation',
    intention: 'Self-Realization',
    phonetic_guide: 'I am boundless consciousness',
    context_note: 'This is the core teaching of Vedanta — you are Brahman, the absolute reality. Everything else is appearance.',
    audio_filename: 'mantra-319.mp3',
    go_deeper_teaser: 'The Vedantic truth of who you are →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 320,
    original_script: 'My Soul Knows the Way',
    transliteration: 'My Soul Knows the Way',
    english_translation: 'I trust the deep knowing of my soul to guide me through every crossroad and every uncertainty.',
    tradition: 'english_affirmation',
    intention: 'Inner Guidance',
    phonetic_guide: 'My soul knows the way',
    context_note: 'Your soul has walked a thousand lifetimes. It knows things your mind cannot fathom. Learn to listen.',
    audio_filename: 'mantra-320.mp3',
    go_deeper_teaser: 'Listening to your soul\'s wisdom →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 321,
    original_script: 'I Am Held by Something Greater',
    transliteration: 'I Am Held by Something Greater',
    english_translation: 'Even when I cannot see the path, I know I am held by a love and intelligence far greater than my own.',
    tradition: 'english_affirmation',
    intention: 'Faith',
    phonetic_guide: 'I am held by something greater',
    context_note: 'Faith is not believing without evidence — it is trusting the evidence of your own direct experience of the divine.',
    audio_filename: 'mantra-321.mp3',
    go_deeper_teaser: 'The difference between belief and faith →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 322,
    original_script: 'I Deserve Joy Without Guilt',
    transliteration: 'I Deserve Joy Without Guilt',
    english_translation: 'I give myself full permission to experience deep, unbounded joy without apology or guilt.',
    tradition: 'english_affirmation',
    intention: 'Joy',
    phonetic_guide: 'I deserve joy without guilt',
    context_note: 'Joy is not frivolous — it is your natural state. The guilt around joy is a learned pattern, not a spiritual truth.',
    audio_filename: 'mantra-322.mp3',
    go_deeper_teaser: 'Reclaiming your birthright of joy →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 323,
    original_script: 'ॐ ह्रीं',
    transliteration: 'Om Hrim',
    english_translation: 'Om — the maya bija — the seed of divine power.',
    tradition: 'universal',
    intention: 'Power',
    phonetic_guide: 'OHM hreem',
    context_note: 'Hrim is the bija (seed syllable) of the goddess — the sound of maya, the creative power of the divine. It is the most powerful single syllable after Om.',
    audio_filename: 'mantra-323.mp3',
    go_deeper_teaser: 'Hrim: the seed syllable of the goddess →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 324,
    original_script: 'ॐ श्रीं',
    transliteration: 'Om Shrim',
    english_translation: 'Om — the Lakshmi bija — the seed of abundance.',
    tradition: 'universal',
    intention: 'Abundance',
    phonetic_guide: 'OHM shreem',
    context_note: 'Shrim is the bija of Lakshmi — the sound of abundance, beauty, and grace. It attracts all forms of prosperity: material, emotional, and spiritual.',
    audio_filename: 'mantra-324.mp3',
    go_deeper_teaser: 'Shrim: the sound of abundance →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 325,
    original_script: 'ॐ ऐं',
    transliteration: 'Om Aim',
    english_translation: 'Om — the Saraswati bija — the seed of wisdom.',
    tradition: 'universal',
    intention: 'Wisdom',
    phonetic_guide: 'OHM aim (rhymes with "time")',
    context_note: 'Aim is the bija of Saraswati — the sound of wisdom, learning, and creative intelligence. It activates the higher mind.',
    audio_filename: 'mantra-325.mp3',
    go_deeper_teaser: 'Aim: the seed syllable of wisdom →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 326,
    original_script: 'ॐ क्लीं',
    transliteration: 'Om Klim',
    english_translation: 'Om — the Kama bija — the seed of love and attraction.',
    tradition: 'universal',
    intention: 'Love',
    phonetic_guide: 'OHM kleem',
    context_note: 'Klim is the bija of Kama — divine love and attraction. It draws all good things toward you and opens the heart to love.',
    audio_filename: 'mantra-326.mp3',
    go_deeper_teaser: 'Klim: the seed syllable of divine love →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 327,
    original_script: 'ॐ क्रीं',
    transliteration: 'Om Krim',
    english_translation: 'Om — the Kali bija — the seed of transformation.',
    tradition: 'universal',
    intention: 'Transformation',
    phonetic_guide: 'OHM kreem',
    context_note: 'Krim is the bija of Kali — the sound of radical transformation. It destroys what is false and reveals what is true.',
    audio_filename: 'mantra-327.mp3',
    go_deeper_teaser: 'Krim: the seed syllable of transformation →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 328,
    original_script: 'ॐ हूँ',
    transliteration: 'Om Hum',
    english_translation: 'Om — the Shiva bija — the seed of fire and protection.',
    tradition: 'universal',
    intention: 'Protection',
    phonetic_guide: 'OHM hoom',
    context_note: 'Hum is the bija of Shiva — the sound of fire, protection, and the destruction of obstacles. It is also the seed of the awakened mind in Buddhism.',
    audio_filename: 'mantra-328.mp3',
    go_deeper_teaser: 'Hum: the seed syllable of fire and protection →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 329,
    original_script: 'ॐ फट्',
    transliteration: 'Om Phat',
    english_translation: 'Om — the weapon bija — the sound that cuts through all obstacles.',
    tradition: 'universal',
    intention: 'Cutting Through',
    phonetic_guide: 'OHM phaht (sharp, explosive)',
    context_note: 'Phat is the weapon bija — the sound of a sword cutting through obstacles. It is used at the end of protective mantras to seal and strengthen them.',
    audio_filename: 'mantra-329.mp3',
    go_deeper_teaser: 'The weapon mantras: cutting through obstacles →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 330,
    original_script: 'ॐ स्वाहा',
    transliteration: 'Om Svaha',
    english_translation: 'Om — so be it — I offer this.',
    tradition: 'universal',
    intention: 'Offering',
    phonetic_guide: 'OHM svah-HAH',
    context_note: 'Svaha is the offering bija — the sound of fire sacrifice. It seals all offerings and prayers, surrendering them to the divine.',
    audio_filename: 'mantra-330.mp3',
    go_deeper_teaser: 'Svaha: the sound of sacred offering →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 331,
    original_script: 'ॐ नमः',
    transliteration: 'Om Namah',
    english_translation: 'Om — I bow — I offer myself.',
    tradition: 'universal',
    intention: 'Surrender',
    phonetic_guide: 'OHM nah-MAH',
    context_note: 'Namah — "I bow" — is the most universal act of spiritual surrender. It is the recognition that the divine is greater than the ego.',
    audio_filename: 'mantra-331.mp3',
    go_deeper_teaser: 'Namah: the power of bowing →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 332,
    original_script: 'ॐ नमस्ते',
    transliteration: 'Om Namaste',
    english_translation: 'Om — I bow to the divine in you.',
    tradition: 'universal',
    intention: 'Recognition',
    phonetic_guide: 'OHM nah-mahs-TAY',
    context_note: 'Namaste — "I bow to the divine in you" — is the recognition that every being is a form of the divine. This is the most radical spiritual teaching.',
    audio_filename: 'mantra-332.mp3',
    go_deeper_teaser: 'Namaste: the greeting that changes how you see the world →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 333,
    original_script: 'ॐ तत् त्वम् असि',
    transliteration: 'Om Tat Tvam Asi',
    english_translation: 'Om — that thou art — you are the infinite.',
    tradition: 'universal',
    intention: 'Non-Duality',
    phonetic_guide: 'OHM taht tvahm AH-see',
    context_note: 'Day 333 — a triple number — for the triple teaching: the teacher (Tat), the student (Tvam), and the identity between them (Asi).',
    audio_filename: 'mantra-333.mp3',
    go_deeper_teaser: 'The teacher-student relationship in non-dual wisdom →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 334,
    original_script: 'ॐ अयम् आत्मा ब्रह्म',
    transliteration: 'Om Ayam Atma Brahma',
    english_translation: 'Om — this self is Brahman.',
    tradition: 'universal',
    intention: 'Self-Realization',
    phonetic_guide: 'OHM AH-yahm AHT-mah BRAH-mah',
    context_note: 'The Mandukya Upanishad mahavakya. This self — the one reading these words right now — is the infinite. Not after enlightenment. Now.',
    audio_filename: 'mantra-334.mp3',
    go_deeper_teaser: 'The Mandukya Upanishad: the shortest and deepest Upanishad →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 335,
    original_script: 'ॐ प्रज्ञानं ब्रह्म',
    transliteration: 'Om Prajnanam Brahma',
    english_translation: 'Om — consciousness is Brahman.',
    tradition: 'universal',
    intention: 'Consciousness',
    phonetic_guide: 'OHM PRAHJ-nyah-nahm BRAH-mah',
    context_note: 'The Aitareya Upanishad mahavakya. The very awareness that is reading these words is the infinite. Consciousness is not produced by the brain — it is the ground of being.',
    audio_filename: 'mantra-335.mp3',
    go_deeper_teaser: 'Consciousness: the hard problem and the Upanishadic answer →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 336,
    original_script: 'ॐ अहम् ब्रह्मास्मि',
    transliteration: 'Om Aham Brahmasmi',
    english_translation: 'Om — I am Brahman.',
    tradition: 'universal',
    intention: 'Identity',
    phonetic_guide: 'OHM AH-hahm BRAH-mahs-mih',
    context_note: 'The Brihadaranyaka Upanishad mahavakya. The most direct declaration of identity with the infinite. Not a belief — a recognition.',
    audio_filename: 'mantra-336.mp3',
    go_deeper_teaser: 'Aham Brahmasmi: the most radical statement in human history →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 337,
    original_script: 'I Am the Love I Have Been Seeking',
    transliteration: 'I Am the Love I Have Been Seeking',
    english_translation: 'Everything I have searched for in others already lives within me — I am the love I seek.',
    tradition: 'english_affirmation',
    intention: 'Self-Love',
    phonetic_guide: 'I am the love I have been seeking',
    context_note: 'The greatest love story is the one between you and your own soul. Stop searching outside for what has always been within.',
    audio_filename: 'mantra-337.mp3',
    go_deeper_teaser: 'The inner beloved awakens →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 338,
    original_script: 'I Surrender Control and Embrace Flow',
    transliteration: 'I Surrender Control and Embrace Flow',
    english_translation: 'I release my grip on how things should be and open to the miraculous flow of how things are.',
    tradition: 'english_affirmation',
    intention: 'Surrender',
    phonetic_guide: 'I surrender control and embrace flow',
    context_note: 'Control is the mind\'s attempt to manage fear. Surrender is the soul\'s invitation to dance with the divine.',
    audio_filename: 'mantra-338.mp3',
    go_deeper_teaser: 'The freedom in letting go →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 339,
    original_script: 'ॐ नित्यानन्द',
    transliteration: 'Om Nityananda',
    english_translation: 'Om — eternal bliss.',
    tradition: 'universal',
    intention: 'Bliss',
    phonetic_guide: 'OHM nih-TYAH-nahn-dah',
    context_note: 'Nityananda — "eternal bliss" — is the name of several great masters. It points to the bliss that is the natural state of the self, not dependent on circumstances.',
    audio_filename: 'mantra-339.mp3',
    go_deeper_teaser: 'Nityananda: the eternal bliss that is your nature →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 340,
    original_script: 'ॐ परमानन्द',
    transliteration: 'Om Paramananda',
    english_translation: 'Om — supreme bliss.',
    tradition: 'universal',
    intention: 'Supreme Joy',
    phonetic_guide: 'OHM pah-rah-MAH-nahn-dah',
    context_note: 'Paramananda — "supreme bliss" — is the highest state of consciousness. It is not an experience that comes and goes but the very nature of pure awareness.',
    audio_filename: 'mantra-340.mp3',
    go_deeper_teaser: 'Ananda: the bliss that is the nature of the self →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 341,
    original_script: 'ॐ सोऽहम् सोऽहम् सोऽहम्',
    transliteration: 'Om Soham Soham Soham',
    english_translation: 'Om — I am that, I am that, I am that.',
    tradition: 'universal',
    intention: 'Identity',
    phonetic_guide: 'OHM SOH-hahm SOH-hahm SOH-hahm',
    context_note: 'Triple Soham — the breath mantra repeated three times to deepen the recognition. With every breath, the universe is saying: "I am that."',
    audio_filename: 'mantra-341.mp3',
    go_deeper_teaser: 'The breath as the teacher: the Soham practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 342,
    original_script: 'I Am Made of Stardust and Spirit',
    transliteration: 'I Am Made of Stardust and Spirit',
    english_translation: 'Every atom in my body was forged in the heart of a star — I am the cosmos experiencing itself.',
    tradition: 'english_affirmation',
    intention: 'Wonder',
    phonetic_guide: 'I am made of stardust and spirit',
    context_note: 'This is not metaphor — this is physics. The iron in your blood, the calcium in your bones, all of it was born in stellar furnaces billions of years ago.',
    audio_filename: 'mantra-342.mp3',
    go_deeper_teaser: 'You are made of stardust — literally →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 343,
    original_script: 'My Presence Is My Power',
    transliteration: 'My Presence Is My Power',
    english_translation: 'I do not need to do anything to be powerful — my conscious presence alone transforms everything it touches.',
    tradition: 'english_affirmation',
    intention: 'Presence',
    phonetic_guide: 'My presence is my power',
    context_note: 'The most powerful thing you can bring to any situation is your full, undivided presence. It is the rarest gift in the modern world.',
    audio_filename: 'mantra-343.mp3',
    go_deeper_teaser: 'The power of conscious presence →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 344,
    original_script: 'I Am Free from the Stories of My Past',
    transliteration: 'I Am Free from the Stories of My Past',
    english_translation: 'I release the narratives that once defined me and step into the freedom of who I am becoming.',
    tradition: 'english_affirmation',
    intention: 'Liberation',
    phonetic_guide: 'I am free from the stories of my past',
    context_note: 'You are not your history. You are the awareness that can observe that history and choose a different path forward.',
    audio_filename: 'mantra-344.mp3',
    go_deeper_teaser: 'Breaking free from karmic patterns →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 345,
    original_script: 'I Embrace My Shadow with Love',
    transliteration: 'I Embrace My Shadow with Love',
    english_translation: 'I welcome every part of myself — light and shadow — knowing that wholeness includes it all.',
    tradition: 'english_affirmation',
    intention: 'Integration',
    phonetic_guide: 'I embrace my shadow with love',
    context_note: 'The parts of yourself you reject become the chains that bind you. The parts you embrace become the wings that free you.',
    audio_filename: 'mantra-345.mp3',
    go_deeper_teaser: 'Shadow work as spiritual practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 346,
    original_script: 'I Am the Silence Between My Thoughts',
    transliteration: 'I Am the Silence Between My Thoughts',
    english_translation: 'In the gap between thoughts, I discover the infinite space of my true self.',
    tradition: 'english_affirmation',
    intention: 'Meditation',
    phonetic_guide: 'I am the silence between my thoughts',
    context_note: 'Meditation is not about stopping thoughts — it is about discovering the vast silence that was always there, holding every thought like the sky holds clouds.',
    audio_filename: 'mantra-346.mp3',
    go_deeper_teaser: 'The space between thoughts →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 347,
    original_script: 'I Give Myself Permission to Rest',
    transliteration: 'I Give Myself Permission to Rest',
    english_translation: 'I honor my need for rest, knowing that stillness is not laziness — it is sacred restoration.',
    tradition: 'english_affirmation',
    intention: 'Rest',
    phonetic_guide: 'I give myself permission to rest',
    context_note: 'In a world that glorifies hustle, choosing rest is a radical act of self-love. Your soul needs space to integrate and renew.',
    audio_filename: 'mantra-347.mp3',
    go_deeper_teaser: 'The spiritual necessity of rest →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 348,
    original_script: 'My Vulnerability Is My Strength',
    transliteration: 'My Vulnerability Is My Strength',
    english_translation: 'I find my greatest strength not in armor, but in the courage to be fully, authentically open.',
    tradition: 'english_affirmation',
    intention: 'Authenticity',
    phonetic_guide: 'My vulnerability is my strength',
    context_note: 'The spiritual warrior does not hide behind walls — they stand in the open field of their own heart, undefended and unafraid.',
    audio_filename: 'mantra-348.mp3',
    go_deeper_teaser: 'The courage of radical openness →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 349,
    original_script: 'I Am Exactly Where I Need to Be',
    transliteration: 'I Am Exactly Where I Need to Be',
    english_translation: 'This moment, this place, this breath — everything is perfectly aligned for my highest evolution.',
    tradition: 'english_affirmation',
    intention: 'Trust',
    phonetic_guide: 'I am exactly where I need to be',
    context_note: 'There are no wrong turns on the soul\'s journey. Every detour was a necessary lesson. You are right on time.',
    audio_filename: 'mantra-349.mp3',
    go_deeper_teaser: 'Trusting your soul\'s perfect timing →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 350,
    original_script: 'I Breathe In Love, I Breathe Out Fear',
    transliteration: 'I Breathe In Love, I Breathe Out Fear',
    english_translation: 'With each breath, I consciously choose to fill myself with love and release all fear.',
    tradition: 'english_affirmation',
    intention: 'Transmutation',
    phonetic_guide: 'I breathe in love, I breathe out fear',
    context_note: 'The breath is the most powerful tool for emotional alchemy. Use it consciously and watch your inner world transform.',
    audio_filename: 'mantra-350.mp3',
    go_deeper_teaser: 'Breathwork as emotional alchemy →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 351,
    original_script: 'I Am the Ocean, Not the Wave',
    transliteration: 'I Am the Ocean, Not the Wave',
    english_translation: 'I am not the temporary emotions that rise and fall — I am the vast ocean of consciousness beneath them all.',
    tradition: 'english_affirmation',
    intention: 'Perspective',
    phonetic_guide: 'I am the ocean, not the wave',
    context_note: 'This is the essence of Vedantic teaching — you are not the passing phenomena, you are the eternal substrate upon which all phenomena arise.',
    audio_filename: 'mantra-351.mp3',
    go_deeper_teaser: 'The ocean of consciousness →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 352,
    original_script: 'I Honor My Journey Without Comparison',
    transliteration: 'I Honor My Journey Without Comparison',
    english_translation: 'My path is uniquely mine — I release all comparison and celebrate my own sacred unfolding.',
    tradition: 'english_affirmation',
    intention: 'Self-Honor',
    phonetic_guide: 'I honor my journey without comparison',
    context_note: 'Comparison is the thief of joy and the enemy of spiritual growth. Your soul chose this exact path for reasons only it understands.',
    audio_filename: 'mantra-352.mp3',
    go_deeper_teaser: 'Their highlight reel vs your raw footage →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 353,
    original_script: 'ॐ नमो गुरवे',
    transliteration: 'Om Namo Gurave',
    english_translation: 'Om — I bow to the Guru.',
    tradition: 'universal',
    intention: 'Gratitude',
    phonetic_guide: 'OHM nah-MOH GOO-rah-vay',
    context_note: 'A simple, direct bow to the teacher. The Guru is not a person — the Guru is the principle of awakening that appears in many forms.',
    audio_filename: 'mantra-353.mp3',
    go_deeper_teaser: 'The Guru principle: beyond the personal teacher →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 354,
    original_script: 'ॐ सर्वे भवन्तु सुखिनः सर्वे सन्तु निरामयाः',
    transliteration: 'Om Sarve Bhavantu Sukhinah Sarve Santu Niramayah',
    english_translation: 'Om — may all be happy — may all be free from disease.',
    tradition: 'universal',
    intention: 'Universal Welfare',
    phonetic_guide: 'OHM SAHR-vay bhah-VAHN-too soo-KHIH-nah SAHR-vay SAHN-too nih-rah-MAH-yah',
    context_note: 'The first two lines of the universal prayer together. As the year nears its end, we return to the most basic wish: may all be happy and free from suffering.',
    audio_filename: 'mantra-354.mp3',
    go_deeper_teaser: 'The universal prayer as a year-end practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 355,
    original_script: 'सर्वे भद्राणि पश्यन्तु मा कश्चिद् दुःखभाग् भवेत्',
    transliteration: 'Sarve Bhadrani Pashyantu Ma Kashchid Duhkhabhag Bhavet',
    english_translation: 'May all see what is auspicious — may no one suffer.',
    tradition: 'universal',
    intention: 'Compassion',
    phonetic_guide: 'SAHR-vay BHAHD-rah-nih PAHSH-yahn-too mah KAHSH-chid DOOH-khah-bhahg BHAH-vayt',
    context_note: 'The final two lines of the universal prayer together. The complete prayer for all beings in four wishes.',
    audio_filename: 'mantra-355.mp3',
    go_deeper_teaser: 'The complete universal prayer: a year-end reflection →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 356,
    original_script: 'I Am a Miracle Walking',
    transliteration: 'I Am a Miracle Walking',
    english_translation: 'The very fact that I exist — that consciousness chose this form — is the greatest miracle of all.',
    tradition: 'english_affirmation',
    intention: 'Wonder',
    phonetic_guide: 'I am a miracle walking',
    context_note: 'The probability of you existing exactly as you are is essentially zero — and yet here you are. You are the universe\'s way of knowing itself.',
    audio_filename: 'mantra-356.mp3',
    go_deeper_teaser: 'The miracle of your existence →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 357,
    original_script: 'ॐ असतो मा सद्गमय तमसो मा ज्योतिर्गमय',
    transliteration: 'Om Asato Ma Sadgamaya Tamaso Ma Jyotirgamaya',
    english_translation: 'Om — lead me from unreal to real — from darkness to light.',
    tradition: 'universal',
    intention: 'Awakening',
    phonetic_guide: 'OHM ah-SAH-toh mah sahd-GAH-mah-yah tah-MAH-soh mah JYOH-tir-gah-mah-yah',
    context_note: 'The first two lines of the Pavamana Mantra together. As the year ends, we renew the prayer: lead me from what is false to what is true.',
    audio_filename: 'mantra-357.mp3',
    go_deeper_teaser: 'The Pavamana Mantra: the three great transitions →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 358,
    original_script: 'मृत्योर्मा अमृतं गमय ॐ शान्तिः शान्तिः शान्तिः',
    transliteration: 'Mrityorma Amritam Gamaya Om Shantih Shantih Shantih',
    english_translation: 'Lead me from death to immortality — Om peace, peace, peace.',
    tradition: 'universal',
    intention: 'Immortality',
    phonetic_guide: 'mrih-TYOR-mah AHM-rih-tahm GAH-mah-yah OHM SHAHN-tih SHAHN-tih SHAHN-tih',
    context_note: 'The complete Pavamana Mantra with its closing peace invocation. The three prayers and the three peaces — a complete practice.',
    audio_filename: 'mantra-358.mp3',
    go_deeper_teaser: 'The complete Pavamana Mantra: a year-end practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 359,
    original_script: 'I Am Whole and I Am Holy',
    transliteration: 'I Am Whole and I Am Holy',
    english_translation: 'There is nothing broken in me that needs fixing — I am whole, I am holy, I am home.',
    tradition: 'english_affirmation',
    intention: 'Wholeness',
    phonetic_guide: 'I am whole and I am holy',
    context_note: 'The word \'holy\' comes from the same root as \'whole.\' To be holy is simply to be complete — and you already are.',
    audio_filename: 'mantra-359.mp3',
    go_deeper_teaser: 'Remembering your original wholeness →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 360,
    original_script: 'I Celebrate the Light in Others',
    transliteration: 'I Celebrate the Light in Others',
    english_translation: 'When I see the divine light shining in another, I celebrate it — knowing it is the same light within me.',
    tradition: 'english_affirmation',
    intention: 'Namaste',
    phonetic_guide: 'I celebrate the light in others',
    context_note: 'Namaste in action — recognizing the divine in every face you encounter. Their light does not diminish yours; it amplifies it.',
    audio_filename: 'mantra-360.mp3',
    go_deeper_teaser: 'Seeing the divine in everyone →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 361,
    original_script: 'I Am Existence, Consciousness, Bliss',
    transliteration: 'I Am Existence, Consciousness, Bliss',
    english_translation: 'My true nature is Sat-Chit-Ananda — pure existence, pure consciousness, pure bliss.',
    tradition: 'english_affirmation',
    intention: 'Self-Knowledge',
    phonetic_guide: 'I am existence, consciousness, bliss',
    context_note: 'This is the English expression of the highest Vedantic truth. You are not seeking bliss — you ARE bliss, temporarily forgetting itself.',
    audio_filename: 'mantra-361.mp3',
    go_deeper_teaser: 'Sat-Chit-Ananda: your true nature →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 362,
    original_script: 'ॐ शिवोऽहम् शिवोऽहम्',
    transliteration: 'Om Shivoham Shivoham',
    english_translation: 'Om — I am Shiva, I am Shiva.',
    tradition: 'universal',
    intention: 'Identity',
    phonetic_guide: 'OHM shih-VOH-hahm shih-VOH-hahm',
    context_note: 'Day 362 — four days from the end. The recognition deepens: not just "I am that" but "I am Shiva" — pure consciousness, pure bliss, pure awareness.',
    audio_filename: 'mantra-362.mp3',
    go_deeper_teaser: 'The recognition that deepens with practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 363,
    original_script: 'I Am That I Am',
    transliteration: 'I Am That I Am',
    english_translation: 'Beyond all names and forms, beyond all roles and identities — I simply am.',
    tradition: 'english_affirmation',
    intention: 'Being',
    phonetic_guide: 'I am that I am',
    context_note: 'The most ancient declaration of truth, found in every wisdom tradition. Not I am this or that — simply I AM.',
    audio_filename: 'mantra-363.mp3',
    go_deeper_teaser: 'The power of pure being →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 364,
    original_script: 'Tomorrow I Begin Again with Love',
    transliteration: 'Tomorrow I Begin Again with Love',
    english_translation: 'Each new day is a fresh canvas — I greet it with an open heart and renewed devotion.',
    tradition: 'english_affirmation',
    intention: 'Renewal',
    phonetic_guide: 'Tomorrow I begin again with love',
    context_note: 'Every sunrise is an invitation to start fresh. No matter what yesterday held, today you can choose love again.',
    audio_filename: 'mantra-364.mp3',
    go_deeper_teaser: 'The gift of new beginnings →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 365,
    original_script: 'I Am Home',
    transliteration: 'I Am Home',
    english_translation: 'After all the seeking, all the searching — I arrive at the truth that I was always home, always held, always loved.',
    tradition: 'english_affirmation',
    intention: 'Completion',
    phonetic_guide: 'I am home',
    context_note: 'The final mantra of the year — a recognition that the entire journey was a circle leading you back to yourself. You are home.',
    audio_filename: 'mantra-365.mp3',
    go_deeper_teaser: 'The journey home to yourself →',
    go_deeper_url: 'https://paulwagner.com',
  },
];
