// Mantras Part 3: Days 137–365 — Vedic Solar, Buddhist, Sikh, Universal

module.exports = [
  // ── VEDIC SOLAR (days 137–182) ────────────────────────────────────────────
  {
    day_of_year: 137,
    original_script: 'ॐ भूर्भुवः स्वः',
    transliteration: 'Om Bhur Bhuvah Svah',
    english_translation: 'Om — the physical world, the vital world, the celestial world.',
    tradition: 'vedic_solar',
    intention: 'Wholeness',
    phonetic_guide: 'OHM bhoor BHOO-vah svah',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The Vyahritis — three sacred utterances that open the Gayatri Mantra. They represent the three planes of existence and the three states of consciousness.',
    go_deeper_teaser: 'The three worlds of the Gayatri: a map of consciousness →',
  },
  {
    day_of_year: 138,
    original_script: 'तत् सवितुर् वरेण्यम्',
    transliteration: 'Tat Savitur Varenyam',
    english_translation: 'That divine solar radiance which is most adorable.',
    tradition: 'vedic_solar',
    intention: 'Reverence',
    phonetic_guide: 'taht sah-VEE-toor vah-REN-yahm',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The second line of the Gayatri Mantra. Savitri is the solar deity — the divine light that illuminates both the outer sun and the inner light of consciousness.',
    go_deeper_teaser: 'Savitri: the solar deity behind the Gayatri →',
  },
  {
    day_of_year: 139,
    original_script: 'भर्गो देवस्य धीमहि',
    transliteration: 'Bhargo Devasya Dhimahi',
    english_translation: 'May we meditate on the divine radiance.',
    tradition: 'vedic_solar',
    intention: 'Meditation',
    phonetic_guide: 'BHAHR-goh DAY-vahs-yah dhee-MAH-hee',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The third line of the Gayatri. Bhargo means "radiance" or "splendor" — the light that burns away ignorance.',
    go_deeper_teaser: 'Bhargo: the light that destroys darkness →',
  },
  {
    day_of_year: 140,
    original_script: 'धियो यो नः प्रचोदयात्',
    transliteration: 'Dhiyo Yo Nah Prachodayat',
    english_translation: 'May that divine light inspire and illuminate our intellect.',
    tradition: 'vedic_solar',
    intention: 'Illumination',
    phonetic_guide: 'DHEE-yoh yoh nah prah-choh-DAH-yaht',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The final line of the Gayatri Mantra. Dhiyo — "intellect" — is what we offer to the divine light for purification and illumination.',
    go_deeper_teaser: 'The Gayatri Mantra: the most powerful mantra in the Vedas →',
  },
  {
    day_of_year: 141,
    original_script: 'ॐ भूर्भुवः स्वः तत् सवितुर् वरेण्यम् भर्गो देवस्य धीमहि धियो यो नः प्रचोदयात्',
    transliteration: 'Om Bhur Bhuvah Svah Tat Savitur Varenyam Bhargo Devasya Dhimahi Dhiyo Yo Nah Prachodayat',
    english_translation: 'Om — the three worlds — that divine solar radiance which is most adorable — may we meditate on it — may it inspire our intellect.',
    tradition: 'vedic_solar',
    intention: 'Complete Practice',
    phonetic_guide: 'OHM bhoor BHOO-vah svah taht sah-VEE-toor vah-REN-yahm BHAHR-goh DAY-vahs-yah dhee-MAH-hee DHEE-yoh yoh nah prah-choh-DAH-yaht',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The complete Gayatri Mantra — the most sacred mantra of the Vedic tradition, chanted at sunrise and sunset for thousands of years.',
    go_deeper_teaser: 'Chanting the Gayatri at sunrise: the complete practice →',
  },
  {
    day_of_year: 142,
    original_script: 'ॐ सूर्याय नमः',
    transliteration: 'Om Suryaya Namah',
    english_translation: 'Om, I bow to Surya — the solar deity, the source of all light.',
    tradition: 'vedic_solar',
    intention: 'Vitality',
    phonetic_guide: 'OHM SOOR-yah-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Surya is the solar deity — the visible form of the divine. The sun is the source of all life on earth and a symbol of the inner light of consciousness.',
    go_deeper_teaser: 'Surya Namaskar: the sun salutation as prayer →',
  },
  {
    day_of_year: 143,
    original_script: 'ॐ आदित्याय नमः',
    transliteration: 'Om Adityaya Namah',
    english_translation: 'Om, I bow to Aditya — the son of Aditi, the infinite.',
    tradition: 'vedic_solar',
    intention: 'Infinity',
    phonetic_guide: 'OHM ah-DIT-yah-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Aditya — "son of Aditi" — is the sun as the child of the infinite. Aditi means "the boundless" — the cosmic mother of all the gods.',
    go_deeper_teaser: 'Aditi: the infinite mother of the gods →',
  },
  {
    day_of_year: 144,
    original_script: 'ॐ मित्राय नमः',
    transliteration: 'Om Mitraya Namah',
    english_translation: 'Om, I bow to Mitra — the sun as the universal friend.',
    tradition: 'vedic_solar',
    intention: 'Friendship',
    phonetic_guide: 'OHM MEET-rah-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Mitra — "friend" — is the sun as the universal benefactor. The sun shines equally on all without discrimination.',
    go_deeper_teaser: 'Mitra: the sun as the friend of all beings →',
  },
  {
    day_of_year: 145,
    original_script: 'ॐ रवये नमः',
    transliteration: 'Om Ravaye Namah',
    english_translation: 'Om, I bow to Ravi — the radiant one.',
    tradition: 'vedic_solar',
    intention: 'Radiance',
    phonetic_guide: 'OHM RAH-vah-yay nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Ravi — "the radiant" — is one of the twelve names of the sun recited during Surya Namaskar. Radiance is the sun\'s essential nature.',
    go_deeper_teaser: 'The 12 names of the sun: the Surya Namaskar mantras →',
  },
  {
    day_of_year: 146,
    original_script: 'ॐ सूर्याय नमः भास्कराय नमः',
    transliteration: 'Om Suryaya Namah Bhaskaraya Namah',
    english_translation: 'Om, I bow to Surya, I bow to Bhaskara — the one who illuminates.',
    tradition: 'vedic_solar',
    intention: 'Clarity',
    phonetic_guide: 'OHM SOOR-yah-yah nah-MAH BHAHS-kah-rah-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Bhaskara — "the illuminator" — is the sun as the force that makes all things visible and knowable.',
    go_deeper_teaser: 'Light as a metaphor for consciousness →',
  },
  {
    day_of_year: 147,
    original_script: 'ॐ खगाय नमः',
    transliteration: 'Om Khagaya Namah',
    english_translation: 'Om, I bow to Khaga — the one who moves through the sky.',
    tradition: 'vedic_solar',
    intention: 'Freedom',
    phonetic_guide: 'OHM khah-GAH-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Khaga — "sky-mover" — honors the sun\'s daily journey across the heavens. The sun\'s freedom of movement is a symbol of liberated consciousness.',
    go_deeper_teaser: 'The sun\'s daily journey: a meditation on freedom →',
  },
  {
    day_of_year: 148,
    original_script: 'ॐ पूष्णे नमः',
    transliteration: 'Om Pushne Namah',
    english_translation: 'Om, I bow to Pushan — the nourisher of all.',
    tradition: 'vedic_solar',
    intention: 'Nourishment',
    phonetic_guide: 'OHM POOSH-nay nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Pushan — "the nourisher" — is the sun as the source of all food and sustenance. The sun nourishes every living being without exception.',
    go_deeper_teaser: 'Pushan: the sun as the cosmic nourisher →',
  },
  {
    day_of_year: 149,
    original_script: 'ॐ हिरण्यगर्भाय नमः',
    transliteration: 'Om Hiranyagarbhaya Namah',
    english_translation: 'Om, I bow to Hiranyagarbha — the golden womb of creation.',
    tradition: 'vedic_solar',
    intention: 'Creation',
    phonetic_guide: 'OHM hih-rahn-yah-GAHR-bhah-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Hiranyagarbha — "golden womb" — is the cosmic egg from which the universe was born. The sun is its visible manifestation.',
    go_deeper_teaser: 'Hiranyagarbha: the golden egg of creation →',
  },
  {
    day_of_year: 150,
    original_script: 'ॐ मरीचये नमः',
    transliteration: 'Om Marichaye Namah',
    english_translation: 'Om, I bow to Marichi — the ray of light.',
    tradition: 'vedic_solar',
    intention: 'Subtlety',
    phonetic_guide: 'OHM mah-REE-chah-yay nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Marichi — "ray of light" — honors the individual rays of the sun. Each ray is both part of the sun and distinct from it — like each soul in relation to the divine.',
    go_deeper_teaser: 'The ray and the sun: the relationship between soul and God →',
  },
  {
    day_of_year: 151,
    original_script: 'ॐ आदित्याय सवित्रे नमः',
    transliteration: 'Om Adityaya Savitre Namah',
    english_translation: 'Om, I bow to Aditya-Savitri — the solar deity who animates all life.',
    tradition: 'vedic_solar',
    intention: 'Animation',
    phonetic_guide: 'OHM ah-DIT-yah-yah sah-VIT-ray nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Savitri — "the animating one" — is the sun as the force that animates all living beings. Without the sun, there is no life.',
    go_deeper_teaser: 'Prana: the solar life force within you →',
  },
  {
    day_of_year: 152,
    original_script: 'ॐ दिवाकराय नमः',
    transliteration: 'Om Divakaraya Namah',
    english_translation: 'Om, I bow to Divakara — the maker of the day.',
    tradition: 'vedic_solar',
    intention: 'New Day',
    phonetic_guide: 'OHM dee-vah-KAH-rah-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Divakara — "day-maker" — honors the sun as the creator of each new day. Every sunrise is a new beginning, a fresh opportunity.',
    go_deeper_teaser: 'The gift of each new day: a morning practice →',
  },
  {
    day_of_year: 153,
    original_script: 'ॐ प्रभाकराय नमः',
    transliteration: 'Om Prabhakaraya Namah',
    english_translation: 'Om, I bow to Prabhakara — the maker of light.',
    tradition: 'vedic_solar',
    intention: 'Enlightenment',
    phonetic_guide: 'OHM prah-bhah-KAH-rah-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Prabhakara — "maker of light" — honors the sun as the source of all illumination, both physical and spiritual.',
    go_deeper_teaser: 'Enlightenment: what it really means →',
  },
  {
    day_of_year: 154,
    original_script: 'ॐ विवस्वते नमः',
    transliteration: 'Om Vivasvate Namah',
    english_translation: 'Om, I bow to Vivasvat — the brilliant, shining one.',
    tradition: 'vedic_solar',
    intention: 'Brilliance',
    phonetic_guide: 'OHM vih-VAHS-vah-tay nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Vivasvat — "the brilliant" — is the Vedic name of the sun. In the Bhagavad Gita, Krishna says he first taught this yoga to Vivasvat.',
    go_deeper_teaser: 'The eternal yoga: Krishna\'s teaching to the sun →',
  },
  {
    day_of_year: 155,
    original_script: 'ॐ सवित्रे नमः',
    transliteration: 'Om Savitre Namah',
    english_translation: 'Om, I bow to Savitri — the solar deity of the Gayatri.',
    tradition: 'vedic_solar',
    intention: 'Inspiration',
    phonetic_guide: 'OHM sah-VIT-ray nah-MAH',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Savitri is the specific solar deity invoked in the Gayatri Mantra. The name means "one who inspires" or "one who animates."',
    go_deeper_teaser: 'Savitri: the goddess behind the Gayatri Mantra →',
  },
  {
    day_of_year: 156,
    original_script: 'ॐ आर्काय नमः',
    transliteration: 'Om Arkaya Namah',
    english_translation: 'Om, I bow to Arka — the sun as the worthy of praise.',
    tradition: 'vedic_solar',
    intention: 'Gratitude',
    phonetic_guide: 'OHM AHR-kah-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Arka — "worthy of praise" — honors the sun as the most visible and constant blessing in our lives. Gratitude for the sun is gratitude for life itself.',
    go_deeper_teaser: 'Gratitude as a spiritual practice →',
  },
  {
    day_of_year: 157,
    original_script: 'ॐ भानवे नमः',
    transliteration: 'Om Bhanave Namah',
    english_translation: 'Om, I bow to Bhanu — the luminous one.',
    tradition: 'vedic_solar',
    intention: 'Luminosity',
    phonetic_guide: 'OHM BHAH-nah-vay nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Bhanu — "luminous" — is one of the twelve names of the sun. Luminosity is the sun\'s nature; it cannot help but shine.',
    go_deeper_teaser: 'Your natural luminosity: the practice of shining →',
  },
  {
    day_of_year: 158,
    original_script: 'ॐ इन्द्राय नमः',
    transliteration: 'Om Indraya Namah',
    english_translation: 'Om, I bow to Indra — the king of the gods, lord of lightning.',
    tradition: 'vedic_solar',
    intention: 'Power',
    phonetic_guide: 'OHM IN-drah-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Indra is the king of the Vedic gods, wielder of the thunderbolt (vajra). He represents the power of the awakened mind.',
    go_deeper_teaser: 'Indra and the thunderbolt: the power of awakening →',
  },
  {
    day_of_year: 159,
    original_script: 'ॐ वरुणाय नमः',
    transliteration: 'Om Varunaya Namah',
    english_translation: 'Om, I bow to Varuna — the lord of cosmic order and the waters.',
    tradition: 'vedic_solar',
    intention: 'Order',
    phonetic_guide: 'OHM vah-ROO-nah-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Varuna is the Vedic god of cosmic order (rita) and the waters. He sees all actions and maintains the moral order of the universe.',
    go_deeper_teaser: 'Rita: the cosmic order that underlies all existence →',
  },
  {
    day_of_year: 160,
    original_script: 'ॐ अग्नये नमः',
    transliteration: 'Om Agnaye Namah',
    english_translation: 'Om, I bow to Agni — the sacred fire, the divine messenger.',
    tradition: 'vedic_solar',
    intention: 'Purification',
    phonetic_guide: 'OHM AHG-nah-yay nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Agni is the first word of the Rigveda. The sacred fire is the divine messenger between humans and gods, and the purifier of all offerings.',
    go_deeper_teaser: 'Agni: the first word of the Vedas →',
  },
  {
    day_of_year: 161,
    original_script: 'ॐ वायवे नमः',
    transliteration: 'Om Vayave Namah',
    english_translation: 'Om, I bow to Vayu — the wind, the breath of life.',
    tradition: 'vedic_solar',
    intention: 'Breath',
    phonetic_guide: 'OHM VAH-yah-vay nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Vayu — "wind" or "breath" — is the Vedic god of air and prana. The breath is the most direct link between the physical and spiritual.',
    go_deeper_teaser: 'Pranayama: the yoga of the breath →',
  },
  {
    day_of_year: 162,
    original_script: 'ॐ पृथिव्यै नमः',
    transliteration: 'Om Prithivyai Namah',
    english_translation: 'Om, I bow to Prithivi — the earth, our mother.',
    tradition: 'vedic_solar',
    intention: 'Grounding',
    phonetic_guide: 'OHM prih-THIV-yay nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Prithivi — "the broad one" — is the Vedic earth goddess. The earth supports all life without discrimination. Grounding is the foundation of all practice.',
    go_deeper_teaser: 'Prithivi: the earth as the divine mother →',
  },
  {
    day_of_year: 163,
    original_script: 'ॐ आपः शान्तिः',
    transliteration: 'Om Apah Shantih',
    english_translation: 'Om, may the waters bring peace.',
    tradition: 'vedic_solar',
    intention: 'Peace',
    phonetic_guide: 'OHM AH-pah SHAHN-tih',
    sacred_geometry_type: 'lotus',
    context_note: 'From the Shanti Patha — the Vedic peace invocation. The waters (apah) represent the flow of life and the cleansing power of grace.',
    go_deeper_teaser: 'The Shanti Patha: the Vedic prayer for universal peace →',
  },
  {
    day_of_year: 164,
    original_script: 'ॐ ओषधयः शान्तिः',
    transliteration: 'Om Oshadhayah Shantih',
    english_translation: 'Om, may the herbs and plants bring peace.',
    tradition: 'vedic_solar',
    intention: 'Healing',
    phonetic_guide: 'OHM oh-shah-DHAH-yah SHAHN-tih',
    sacred_geometry_type: 'lotus',
    context_note: 'From the Shanti Patha. The healing plants of the earth are invoked for peace — honoring the medicinal wisdom of the natural world.',
    go_deeper_teaser: 'Ayurveda: the Vedic science of healing →',
  },
  {
    day_of_year: 165,
    original_script: 'ॐ विश्वानि देव सवितर्',
    transliteration: 'Om Vishwani Deva Savitar',
    english_translation: 'O divine Savitri, remove all that is harmful from us.',
    tradition: 'vedic_solar',
    intention: 'Purification',
    phonetic_guide: 'OHM vish-WAH-nih DAY-vah sah-VEE-tahr',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'From the Yajurveda. A prayer to the solar deity to remove all that is harmful and bring only what is beneficial.',
    go_deeper_teaser: 'The Yajurveda: the Veda of ritual action →',
  },
  {
    day_of_year: 166,
    original_script: 'दुरितानि परासुव',
    transliteration: 'Duritani Parasuva',
    english_translation: 'Remove all our sins and shortcomings.',
    tradition: 'vedic_solar',
    intention: 'Forgiveness',
    phonetic_guide: 'doo-rih-TAH-nih pah-rah-SOO-vah',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The second line of the Vishwani prayer. Duritani means "that which causes pain" — the prayer asks for removal of all inner obstacles.',
    go_deeper_teaser: 'Forgiveness as a spiritual practice →',
  },
  {
    day_of_year: 167,
    original_script: 'यद् भद्रं तन्न आसुव',
    transliteration: 'Yad Bhadram Tanna Asuva',
    english_translation: 'And bring to us all that is auspicious.',
    tradition: 'vedic_solar',
    intention: 'Auspiciousness',
    phonetic_guide: 'yahd BHAHD-rahm tahn-NAH ah-SOO-vah',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The final line of the Vishwani prayer. Bhadram — "auspicious" — is the Vedic word for all that is good, beautiful, and beneficial.',
    go_deeper_teaser: 'Bhadram: the Vedic vision of the good life →',
  },
  {
    day_of_year: 168,
    original_script: 'ॐ सूर्य नमस्कार',
    transliteration: 'Om Surya Namaskar',
    english_translation: 'Om, salutation to the sun.',
    tradition: 'vedic_solar',
    intention: 'Gratitude',
    phonetic_guide: 'OHM SOOR-yah nah-mahs-KAHR',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Surya Namaskar — "sun salutation" — is both a physical yoga practice and a devotional act. Each movement is accompanied by a mantra to the sun.',
    go_deeper_teaser: 'The complete Surya Namaskar practice →',
  },
  {
    day_of_year: 169,
    original_script: 'ॐ ह्रां ह्रीं ह्रौं सः सूर्याय नमः',
    transliteration: 'Om Hram Hrim Hraum Sah Suryaya Namah',
    english_translation: 'Om — the three solar bija mantras — I am that — I bow to Surya.',
    tradition: 'vedic_solar',
    intention: 'Solar Power',
    phonetic_guide: 'OHM hrahm hreem hrowm sah SOOR-yah-yah nah-MAH',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The complete solar bija mantra. Hram, Hrim, Hraum are the three seed syllables of the sun, representing its three aspects: rising, noon, and setting.',
    go_deeper_teaser: 'Solar bija mantras: seeds of solar power →',
  },
  {
    day_of_year: 170,
    original_script: 'ॐ जपाकुसुमसङ्काशम्',
    transliteration: 'Om Japaakusumasankasham',
    english_translation: 'Om, the one who resembles the hibiscus flower.',
    tradition: 'vedic_solar',
    intention: 'Beauty',
    phonetic_guide: 'OHM jah-pah-koo-soo-mah-sahn-KAH-shahm',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'The opening of the Aditya Hridayam — the solar hymn from the Ramayana. The sun is compared to the red hibiscus flower at dawn.',
    go_deeper_teaser: 'The Aditya Hridayam: the heart of the sun →',
  },
  {
    day_of_year: 171,
    original_script: 'काश्यपेयं महाद्युतिम्',
    transliteration: 'Kashyapeyam Mahadyutim',
    english_translation: 'The son of Kashyapa, of great radiance.',
    tradition: 'vedic_solar',
    intention: 'Lineage',
    phonetic_guide: 'KAHSH-yah-pay-yahm mah-hah-DYOO-tihm',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'The second line of the Aditya Hridayam. The sun is the son of the sage Kashyapa — reminding us that even the sun has a lineage and a teacher.',
    go_deeper_teaser: 'Kashyapa: the progenitor of all life →',
  },
  {
    day_of_year: 172,
    original_script: 'तमोऽरिं सर्वपापघ्नम्',
    transliteration: 'Tamoriṃ Sarvapapagnam',
    english_translation: 'The enemy of darkness, the destroyer of all sins.',
    tradition: 'vedic_solar',
    intention: 'Liberation',
    phonetic_guide: 'tah-MOH-rim sahr-vah-PAH-pahg-nahm',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The third line of the Aditya Hridayam. The sun destroys both physical darkness and the inner darkness of ignorance and sin.',
    go_deeper_teaser: 'The Aditya Hridayam: how Rama defeated Ravana →',
  },
  {
    day_of_year: 173,
    original_script: 'प्रणतोऽस्मि दिवाकरम्',
    transliteration: 'Pranato\'smi Divakaram',
    english_translation: 'I bow to the maker of the day.',
    tradition: 'vedic_solar',
    intention: 'Humility',
    phonetic_guide: 'prah-NAH-tohs-mih dee-vah-KAH-rahm',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'The final line of the Aditya Hridayam opening verse. Pranata — "bowing" — is the posture of humility before the divine light.',
    go_deeper_teaser: 'Pranama: the practice of sacred bowing →',
  },
  {
    day_of_year: 174,
    original_script: 'ॐ नमः सूर्याय शान्ताय',
    transliteration: 'Om Namah Suryaya Shantaya',
    english_translation: 'Om, I bow to the peaceful sun.',
    tradition: 'vedic_solar',
    intention: 'Equanimity',
    phonetic_guide: 'OHM nah-MAH SOOR-yah-yah SHAHN-tah-yah',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'The sun is peaceful — it shines without effort, without preference, without agitation. This mantra invokes solar equanimity.',
    go_deeper_teaser: 'Equanimity: the sun\'s greatest teaching →',
  },
  {
    day_of_year: 175,
    original_script: 'ॐ नमः सूर्याय सर्वदाय',
    transliteration: 'Om Namah Suryaya Sarvadaya',
    english_translation: 'Om, I bow to the sun who gives everything.',
    tradition: 'vedic_solar',
    intention: 'Generosity',
    phonetic_guide: 'OHM nah-MAH SOOR-yah-yah sahr-VAH-dah-yah',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'The sun gives its light freely to all — the saint and the sinner, the rich and the poor. This mantra invokes divine generosity.',
    go_deeper_teaser: 'The sun\'s generosity: giving without expectation →',
  },
  {
    day_of_year: 176,
    original_script: 'ॐ सूर्य देव नमोऽस्तु ते',
    transliteration: 'Om Surya Deva Namostu Te',
    english_translation: 'Om, I bow to you, O solar deity.',
    tradition: 'vedic_solar',
    intention: 'Reverence',
    phonetic_guide: 'OHM SOOR-yah DAY-vah nah-MOHS-too tay',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'A simple, direct salutation to the sun. Namostu — "may there be bowing" — expresses perpetual reverence.',
    go_deeper_teaser: 'Daily sun practice: the simplest solar sadhana →',
  },
  {
    day_of_year: 177,
    original_script: 'ॐ प्रसीद प्रसीद प्रभो',
    transliteration: 'Om Prasida Prasida Prabho',
    english_translation: 'Om, be pleased, be pleased, O Lord.',
    tradition: 'vedic_solar',
    intention: 'Grace',
    phonetic_guide: 'OHM prah-SEE-dah prah-SEE-dah PRAH-bhoh',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Prasida — "be pleased" or "be gracious" — is a prayer for divine grace. The triple repetition intensifies the request.',
    go_deeper_teaser: 'Prasada: the grace that flows from the divine →',
  },
  {
    day_of_year: 178,
    original_script: 'ॐ सर्वदेवनमस्कारः',
    transliteration: 'Om Sarvadevanamaskarah',
    english_translation: 'Om, salutation to all the gods.',
    tradition: 'vedic_solar',
    intention: 'Inclusivity',
    phonetic_guide: 'OHM sahr-vah-DAY-vah-nah-mahs-KAH-rah',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'A universal salutation to all divine forms. The Vedas teach that all gods are aspects of the one divine reality.',
    go_deeper_teaser: 'Ekam sat vipra bahudha vadanti: one truth, many names →',
  },
  {
    day_of_year: 179,
    original_script: 'केशवं प्रति गच्छति',
    transliteration: 'Keshavam Prati Gacchati',
    english_translation: 'Reaches Keshava (the supreme).',
    tradition: 'vedic_solar',
    intention: 'Unity',
    phonetic_guide: 'KAY-shah-vahm PRAH-tih GAHCH-chah-tih',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'The second line of the universal salutation verse: "Salutation to all gods reaches the supreme." All paths lead to the same destination.',
    go_deeper_teaser: 'All paths lead to the same peak →',
  },
  {
    day_of_year: 180,
    original_script: 'ॐ तेजोऽसि तेजो मयि धेहि',
    transliteration: 'Om Tejo\'si Tejo Mayi Dhehi',
    english_translation: 'Om, you are radiance — place that radiance in me.',
    tradition: 'vedic_solar',
    intention: 'Empowerment',
    phonetic_guide: 'OHM tay-JOH-see tay-JOH mah-YEE DHAY-hee',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'From the Yajurveda. A prayer to receive the sun\'s radiance — not just its physical light, but its inner quality of brilliance and clarity.',
    go_deeper_teaser: 'Tejas: the inner radiance of the awakened person →',
  },
  {
    day_of_year: 181,
    original_script: 'ॐ वीर्यमसि वीर्यं मयि धेहि',
    transliteration: 'Om Viryamasi Viryam Mayi Dhehi',
    english_translation: 'Om, you are vitality — place that vitality in me.',
    tradition: 'vedic_solar',
    intention: 'Vitality',
    phonetic_guide: 'OHM veer-YAHM-ah-see veer-YAHM mah-YEE DHAY-hee',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'From the Yajurveda. Virya — "vitality" or "heroic energy" — is the solar quality of dynamic, purposeful action.',
    go_deeper_teaser: 'Virya: the heroic energy of the spiritual warrior →',
  },
  {
    day_of_year: 182,
    original_script: 'ॐ बलमसि बलं मयि धेहि',
    transliteration: 'Om Balamasi Balam Mayi Dhehi',
    english_translation: 'Om, you are strength — place that strength in me.',
    tradition: 'vedic_solar',
    intention: 'Strength',
    phonetic_guide: 'OHM bah-LAHM-ah-see bah-LAHM mah-YEE DHAY-hee',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'From the Yajurveda. Bala — "strength" — is the solar quality of physical and spiritual fortitude. The sun never wavers; neither should we.',
    go_deeper_teaser: 'Bala: the strength that comes from practice →',
  },

  // ── BUDDHIST (days 183–274) ───────────────────────────────────────────────
  {
    day_of_year: 183,
    original_script: 'ॐ मणि पद्मे हूँ',
    transliteration: 'Om Mani Padme Hum',
    english_translation: 'Om — the jewel in the lotus — hum.',
    tradition: 'buddhist',
    intention: 'Compassion',
    phonetic_guide: 'OHM mah-NEE pahd-MAY hoom',
    sacred_geometry_type: 'lotus',
    context_note: 'The mantra of Avalokiteshvara — the bodhisattva of compassion. The most widely chanted mantra in the world. The jewel is the awakened mind; the lotus is the world.',
    go_deeper_teaser: 'Om Mani Padme Hum: the six syllables of compassion →',
  },
  {
    day_of_year: 184,
    original_script: 'ॐ तारे तुत्तारे तुरे स्वाहा',
    transliteration: 'Om Tare Tuttare Ture Svaha',
    english_translation: 'Om — Tara who liberates — Tara who liberates swiftly — Tara who protects — so be it.',
    tradition: 'buddhist',
    intention: 'Liberation',
    phonetic_guide: 'OHM TAH-ray too-TAH-ray TOO-ray svah-HAH',
    sacred_geometry_type: 'lotus',
    context_note: 'The mantra of Green Tara — the swift-acting bodhisattva who saves from the eight fears. Tare means "she who liberates."',
    go_deeper_teaser: 'Green Tara: the swift liberator →',
  },
  {
    day_of_year: 185,
    original_script: 'ॐ अमिताभ हृदय',
    transliteration: 'Om Amitabha Hridaya',
    english_translation: 'Om — the heart of Amitabha — the buddha of infinite light.',
    tradition: 'buddhist',
    intention: 'Light',
    phonetic_guide: 'OHM ah-mee-TAH-bhah hrih-DAH-yah',
    sacred_geometry_type: 'lotus',
    context_note: 'Amitabha — "infinite light" — is the buddha of the western pure land. His light reaches all beings without exception.',
    go_deeper_teaser: 'Amitabha Buddha: the pure land of infinite light →',
  },
  {
    day_of_year: 186,
    original_script: 'नमो अमिताभाय',
    transliteration: 'Namo Amitabhaya',
    english_translation: 'I take refuge in Amitabha — the buddha of infinite light.',
    tradition: 'buddhist',
    intention: 'Refuge',
    phonetic_guide: 'nah-MOH ah-mee-TAH-bhah-yah',
    sacred_geometry_type: 'lotus',
    context_note: 'The nembutsu — the central practice of Pure Land Buddhism. Reciting Amitabha\'s name with sincere faith is said to ensure rebirth in the pure land.',
    go_deeper_teaser: 'The nembutsu: the simplest Buddhist practice →',
  },
  {
    day_of_year: 187,
    original_script: 'ॐ अह हूँ वज्र गुरु पद्म सिद्धि हूँ',
    transliteration: 'Om Ah Hum Vajra Guru Padma Siddhi Hum',
    english_translation: 'Om Ah Hum — Vajra Guru — lotus-born — accomplishment — Hum.',
    tradition: 'buddhist',
    intention: 'Mastery',
    phonetic_guide: 'OHM ah hoom VAHJ-rah GOO-roo PAHD-mah SID-dhee hoom',
    sacred_geometry_type: 'lotus',
    context_note: 'The mantra of Padmasambhava — Guru Rinpoche — who brought Buddhism to Tibet. The most important mantra in Vajrayana Buddhism.',
    go_deeper_teaser: 'Padmasambhava: the lotus-born master of Tibet →',
  },
  {
    day_of_year: 188,
    original_script: 'ॐ बज्र सत्त्व हूँ',
    transliteration: 'Om Vajrasattva Hum',
    english_translation: 'Om — Vajrasattva — the diamond being — Hum.',
    tradition: 'buddhist',
    intention: 'Purification',
    phonetic_guide: 'OHM VAHJ-rah-saht-tvah hoom',
    sacred_geometry_type: 'lotus',
    context_note: 'The short mantra of Vajrasattva — the buddha of purification. Vajra means "diamond" or "thunderbolt" — indestructible and pure.',
    go_deeper_teaser: 'Vajrasattva: the 100-syllable purification practice →',
  },
  {
    day_of_year: 189,
    original_script: 'ॐ नमो मञ्जुश्रीये',
    transliteration: 'Om Namo Manjushriye',
    english_translation: 'Om, I bow to Manjushri — the bodhisattva of wisdom.',
    tradition: 'buddhist',
    intention: 'Wisdom',
    phonetic_guide: 'OHM nah-MOH mahn-JOO-shree-yay',
    sacred_geometry_type: 'lotus',
    context_note: 'Manjushri holds a flaming sword to cut through ignorance and a book of wisdom. He is the embodiment of prajna — transcendent wisdom.',
    go_deeper_teaser: 'Manjushri\'s sword: cutting through ignorance →',
  },
  {
    day_of_year: 190,
    original_script: 'ॐ अ रा पा चा ना धीः',
    transliteration: 'Om A Ra Pa Ca Na Dhih',
    english_translation: 'Om — the five wisdom syllables — the seed of wisdom.',
    tradition: 'buddhist',
    intention: 'Wisdom',
    phonetic_guide: 'OHM ah rah pah chah nah dhee',
    sacred_geometry_type: 'lotus',
    context_note: 'The mantra of Manjushri. Each syllable represents a wisdom teaching. Dhih is the seed syllable of wisdom — the most important syllable.',
    go_deeper_teaser: 'The five wisdom syllables of Manjushri →',
  },
  {
    day_of_year: 191,
    original_script: 'ॐ गते गते पारगते पारसंगते बोधि स्वाहा',
    transliteration: 'Om Gate Gate Paragate Parasamgate Bodhi Svaha',
    english_translation: 'Gone, gone, gone beyond, gone completely beyond — awakening — so be it.',
    tradition: 'buddhist',
    intention: 'Transcendence',
    phonetic_guide: 'OHM GAH-tay GAH-tay pah-rah-GAH-tay pah-rah-sahm-GAH-tay BOH-dhee svah-HAH',
    sacred_geometry_type: 'lotus',
    context_note: 'The dharani from the Heart Sutra — the most concise expression of the Buddha\'s teaching on emptiness and transcendence.',
    go_deeper_teaser: 'The Heart Sutra: the Buddha\'s teaching on emptiness →',
  },
  {
    day_of_year: 192,
    original_script: 'बुद्धं शरणं गच्छामि',
    transliteration: 'Buddham Saranam Gacchami',
    english_translation: 'I take refuge in the Buddha.',
    tradition: 'buddhist',
    intention: 'Refuge',
    phonetic_guide: 'BOOD-dhahm shah-RAH-nahm GAHCH-chah-mee',
    sacred_geometry_type: 'lotus',
    context_note: 'The first of the Three Jewels — the triple refuge that is the foundation of all Buddhist practice. The Buddha is the awakened teacher.',
    go_deeper_teaser: 'The Three Jewels: the foundation of Buddhist practice →',
  },
  {
    day_of_year: 193,
    original_script: 'धम्मं शरणं गच्छामि',
    transliteration: 'Dhammam Saranam Gacchami',
    english_translation: 'I take refuge in the Dharma — the teaching.',
    tradition: 'buddhist',
    intention: 'Guidance',
    phonetic_guide: 'DHAHM-mahm shah-RAH-nahm GAHCH-chah-mee',
    sacred_geometry_type: 'lotus',
    context_note: 'The second of the Three Jewels. Dharma is the Buddha\'s teaching — the path that leads to liberation from suffering.',
    go_deeper_teaser: 'The Dharma: what the Buddha actually taught →',
  },
  {
    day_of_year: 194,
    original_script: 'संघं शरणं गच्छामि',
    transliteration: 'Sangham Saranam Gacchami',
    english_translation: 'I take refuge in the Sangha — the community.',
    tradition: 'buddhist',
    intention: 'Community',
    phonetic_guide: 'SAHNG-ghahm shah-RAH-nahm GAHCH-chah-mee',
    sacred_geometry_type: 'lotus',
    context_note: 'The third of the Three Jewels. Sangha is the community of practitioners — those who walk the path together.',
    go_deeper_teaser: 'Sangha: why community is essential for awakening →',
  },
  {
    day_of_year: 195,
    original_script: 'सर्वे सत्त्वाः सुखिनो भवन्तु',
    transliteration: 'Sarve Sattvah Sukhino Bhavantu',
    english_translation: 'May all beings be happy.',
    tradition: 'buddhist',
    intention: 'Loving-Kindness',
    phonetic_guide: 'SAHR-vay saht-TVAH soo-KHIH-noh bhah-VAHN-too',
    sacred_geometry_type: 'lotus',
    context_note: 'The metta (loving-kindness) prayer — the foundation of Buddhist compassion practice. It begins with all beings and works inward.',
    go_deeper_teaser: 'Metta meditation: the practice of loving-kindness →',
  },
  {
    day_of_year: 196,
    original_script: 'सर्वे सत्त्वाः निरामयाः',
    transliteration: 'Sarve Sattvah Niramayah',
    english_translation: 'May all beings be free from suffering.',
    tradition: 'buddhist',
    intention: 'Compassion',
    phonetic_guide: 'SAHR-vay saht-TVAH nih-rah-MAH-yah',
    sacred_geometry_type: 'lotus',
    context_note: 'The second line of the metta prayer. Niramaya — "free from disease" — extends to all forms of suffering, physical and mental.',
    go_deeper_teaser: 'Karuna: the practice of compassion →',
  },
  {
    day_of_year: 197,
    original_script: 'सर्वे सत्त्वाः सुखिताः भवन्तु',
    transliteration: 'Sarve Sattvah Sukhitah Bhavantu',
    english_translation: 'May all beings be at ease.',
    tradition: 'buddhist',
    intention: 'Ease',
    phonetic_guide: 'SAHR-vay saht-TVAH soo-KHIH-tah bhah-VAHN-too',
    sacred_geometry_type: 'lotus',
    context_note: 'The third line of the metta prayer. Sukhita — "at ease" — is a deeper wish than happiness: the ease of a mind free from struggle.',
    go_deeper_teaser: 'Upekkha: the practice of equanimity →',
  },
  {
    day_of_year: 198,
    original_script: 'ॐ स्वस्ति प्रजाभ्यः',
    transliteration: 'Om Svasti Prajabhyah',
    english_translation: 'Om, may all beings be well.',
    tradition: 'buddhist',
    intention: 'Wellbeing',
    phonetic_guide: 'OHM SVAHS-tee prah-JAH-bhyah',
    sacred_geometry_type: 'lotus',
    context_note: 'A universal Buddhist blessing. Svasti — "well-being" — is the root of the Sanskrit word swastika, an ancient symbol of auspiciousness.',
    go_deeper_teaser: 'Svasti: the original meaning of the swastika →',
  },
  {
    day_of_year: 199,
    original_script: 'ॐ नमो बुद्धाय',
    transliteration: 'Om Namo Buddhaya',
    english_translation: 'Om, I bow to the Buddha — the awakened one.',
    tradition: 'buddhist',
    intention: 'Awakening',
    phonetic_guide: 'OHM nah-MOH BOOD-dhah-yah',
    sacred_geometry_type: 'lotus',
    context_note: 'A simple, direct invocation of the Buddha. Buddha means "the awakened one" — one who has seen through the illusion of the separate self.',
    go_deeper_teaser: 'What does it mean to be awakened? →',
  },
  {
    day_of_year: 200,
    original_script: 'ॐ नमो धर्माय',
    transliteration: 'Om Namo Dharmaya',
    english_translation: 'Om, I bow to the Dharma — the truth.',
    tradition: 'buddhist',
    intention: 'Truth',
    phonetic_guide: 'OHM nah-MOH DHAHR-mah-yah',
    sacred_geometry_type: 'lotus',
    context_note: 'Bowing to the Dharma is bowing to truth itself — the way things actually are, beyond our concepts and preferences.',
    go_deeper_teaser: 'The Dharma: the Buddha\'s four noble truths →',
  },
  {
    day_of_year: 201,
    original_script: 'ॐ नमो संघाय',
    transliteration: 'Om Namo Sanghaya',
    english_translation: 'Om, I bow to the Sangha — the community of practitioners.',
    tradition: 'buddhist',
    intention: 'Community',
    phonetic_guide: 'OHM nah-MOH SAHNG-ghah-yah',
    sacred_geometry_type: 'lotus',
    context_note: 'The sangha is not just monks — it is all beings who walk the path of awakening. We are never alone on this journey.',
    go_deeper_teaser: 'The bodhisattva vow: awakening for all beings →',
  },
  {
    day_of_year: 202,
    original_script: 'ॐ अमोघपाश हूँ',
    transliteration: 'Om Amoghapasha Hum',
    english_translation: 'Om — the infallible lasso of compassion — Hum.',
    tradition: 'buddhist',
    intention: 'Compassion',
    phonetic_guide: 'OHM ah-MOH-ghah-PAH-shah hoom',
    sacred_geometry_type: 'lotus',
    context_note: 'Amoghapasha — "infallible lasso" — is a form of Avalokiteshvara who catches all beings in the net of compassion, leaving none behind.',
    go_deeper_teaser: 'Avalokiteshvara: the bodhisattva who hears all cries →',
  },
  {
    day_of_year: 203,
    original_script: 'ॐ नमो भगवते अमिताभाय',
    transliteration: 'Om Namo Bhagavate Amitabhaya',
    english_translation: 'Om, I bow to the blessed Amitabha.',
    tradition: 'buddhist',
    intention: 'Light',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay ah-mee-TAH-bhah-yah',
    sacred_geometry_type: 'lotus',
    context_note: 'The full refuge mantra of Amitabha Buddha. Bhagavate — "blessed one" — is the honorific used for all buddhas.',
    go_deeper_teaser: 'The pure land: is it real or metaphorical? →',
  },
  {
    day_of_year: 204,
    original_script: 'ॐ मेत्ता मेत्ता मेत्ता',
    transliteration: 'Om Metta Metta Metta',
    english_translation: 'Om — loving-kindness, loving-kindness, loving-kindness.',
    tradition: 'buddhist',
    intention: 'Loving-Kindness',
    phonetic_guide: 'OHM MET-tah MET-tah MET-tah',
    sacred_geometry_type: 'lotus',
    context_note: 'Metta (Pali) or Maitri (Sanskrit) — loving-kindness — is the first of the four brahmaviharas, the divine abodes. Triple repetition deepens the intention.',
    go_deeper_teaser: 'The four brahmaviharas: the divine abodes →',
  },
  {
    day_of_year: 205,
    original_script: 'ॐ करुणा करुणा करुणा',
    transliteration: 'Om Karuna Karuna Karuna',
    english_translation: 'Om — compassion, compassion, compassion.',
    tradition: 'buddhist',
    intention: 'Compassion',
    phonetic_guide: 'OHM kah-ROO-nah kah-ROO-nah kah-ROO-nah',
    sacred_geometry_type: 'lotus',
    context_note: 'Karuna — compassion — is the second brahmavihara. It is the wish for all beings to be free from suffering.',
    go_deeper_teaser: 'Karuna: the difference between compassion and pity →',
  },
  {
    day_of_year: 206,
    original_script: 'ॐ मुदिता मुदिता मुदिता',
    transliteration: 'Om Mudita Mudita Mudita',
    english_translation: 'Om — sympathetic joy, sympathetic joy, sympathetic joy.',
    tradition: 'buddhist',
    intention: 'Joy',
    phonetic_guide: 'OHM moo-DIH-tah moo-DIH-tah moo-DIH-tah',
    sacred_geometry_type: 'lotus',
    context_note: 'Mudita — "sympathetic joy" — is the third brahmavihara: the ability to rejoice in the happiness of others without envy.',
    go_deeper_teaser: 'Mudita: the antidote to envy →',
  },
  {
    day_of_year: 207,
    original_script: 'ॐ उपेक्षा उपेक्षा उपेक्षा',
    transliteration: 'Om Upekkha Upekkha Upekkha',
    english_translation: 'Om — equanimity, equanimity, equanimity.',
    tradition: 'buddhist',
    intention: 'Equanimity',
    phonetic_guide: 'OHM oo-PEK-shah oo-PEK-shah oo-PEK-shah',
    sacred_geometry_type: 'lotus',
    context_note: 'Upekkha — equanimity — is the fourth brahmavihara: the ability to remain balanced and undisturbed in all circumstances.',
    go_deeper_teaser: 'Equanimity: the highest of the four divine abodes →',
  },
  {
    day_of_year: 208,
    original_script: 'ॐ शान्ति शान्ति शान्ति',
    transliteration: 'Om Shanti Shanti Shanti',
    english_translation: 'Om — peace, peace, peace.',
    tradition: 'buddhist',
    intention: 'Peace',
    phonetic_guide: 'OHM SHAHN-tee SHAHN-tee SHAHN-tee',
    sacred_geometry_type: 'lotus',
    context_note: 'The universal peace invocation. Three repetitions address the three sources of disturbance: body, speech, and mind.',
    go_deeper_teaser: 'The three levels of peace: body, speech, and mind →',
  },
  {
    day_of_year: 209,
    original_script: 'ॐ नमो रत्नत्रयाय',
    transliteration: 'Om Namo Ratnatrayaya',
    english_translation: 'Om, I bow to the three jewels.',
    tradition: 'buddhist',
    intention: 'Refuge',
    phonetic_guide: 'OHM nah-MOH raht-nah-TRAH-yah-yah',
    sacred_geometry_type: 'lotus',
    context_note: 'Ratnatraya — "three jewels" — are the Buddha, Dharma, and Sangha. Taking refuge in them is the foundation of all Buddhist practice.',
    go_deeper_teaser: 'Taking refuge: what it really means →',
  },
  {
    day_of_year: 210,
    original_script: 'ॐ नमो भगवते शाक्यमुनये',
    transliteration: 'Om Namo Bhagavate Shakyamunaye',
    english_translation: 'Om, I bow to the blessed Shakyamuni — the sage of the Shakya clan.',
    tradition: 'buddhist',
    intention: 'Gratitude',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay SHAHK-yah-moo-nah-yay',
    sacred_geometry_type: 'lotus',
    context_note: 'Shakyamuni — "sage of the Shakyas" — is the historical Buddha, Siddhartha Gautama. This mantra honors the human teacher who showed the way.',
    go_deeper_teaser: 'The historical Buddha: his life and awakening →',
  },
  {
    day_of_year: 211,
    original_script: 'ॐ अह हूँ',
    transliteration: 'Om Ah Hum',
    english_translation: 'Om — body, speech, mind — Hum.',
    tradition: 'buddhist',
    intention: 'Integration',
    phonetic_guide: 'OHM ah hoom',
    sacred_geometry_type: 'lotus',
    context_note: 'The three seed syllables of Vajrayana Buddhism: Om purifies the body, Ah purifies speech, Hum purifies the mind.',
    go_deeper_teaser: 'Om Ah Hum: the three vajras of body, speech, and mind →',
  },
  {
    day_of_year: 212,
    original_script: 'ॐ वज्रसत्त्व समयम्',
    transliteration: 'Om Vajrasattva Samayam',
    english_translation: 'Om — Vajrasattva — the sacred commitment.',
    tradition: 'buddhist',
    intention: 'Commitment',
    phonetic_guide: 'OHM VAHJ-rah-saht-tvah sah-MAH-yahm',
    sacred_geometry_type: 'lotus',
    context_note: 'The opening of the Vajrasattva 100-syllable mantra. Samaya — "sacred commitment" — is the vow between student and teacher, between practitioner and the divine.',
    go_deeper_teaser: 'Samaya: the sacred vow of Vajrayana →',
  },
  {
    day_of_year: 213,
    original_script: 'अनुपालय',
    transliteration: 'Anupalaya',
    english_translation: 'Please uphold me.',
    tradition: 'buddhist',
    intention: 'Support',
    phonetic_guide: 'ah-noo-PAH-lah-yah',
    sacred_geometry_type: 'lotus',
    context_note: 'From the Vajrasattva mantra. A prayer for the divine to uphold and sustain the practitioner on the path.',
    go_deeper_teaser: 'The 100-syllable Vajrasattva mantra: complete guide →',
  },
  {
    day_of_year: 214,
    original_script: 'ॐ नमो मञ्जुश्रीये नमः',
    transliteration: 'Om Namo Manjushriye Namah',
    english_translation: 'Om, I bow to Manjushri — the gentle-voiced one.',
    tradition: 'buddhist',
    intention: 'Learning',
    phonetic_guide: 'OHM nah-MOH mahn-JOO-shree-yay nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Manjushri — "gentle glory" — is the bodhisattva of wisdom. His name means "gentle-voiced" — wisdom is always gentle, never harsh.',
    go_deeper_teaser: 'Manjushri: the bodhisattva of wisdom →',
  },
  {
    day_of_year: 215,
    original_script: 'ॐ वज्रपाणये नमः',
    transliteration: 'Om Vajrapanaye Namah',
    english_translation: 'Om, I bow to Vajrapani — the thunderbolt-wielder.',
    tradition: 'buddhist',
    intention: 'Power',
    phonetic_guide: 'OHM VAHJ-rah-PAH-nah-yay nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Vajrapani — "thunderbolt in hand" — is the bodhisattva of power. He represents the power of the awakened mind to cut through all obstacles.',
    go_deeper_teaser: 'Vajrapani: the power of the awakened mind →',
  },
  {
    day_of_year: 216,
    original_script: 'ॐ नमो भगवते भैषज्यगुरु',
    transliteration: 'Om Namo Bhagavate Bhaishajyaguru',
    english_translation: 'Om, I bow to the blessed Medicine Buddha.',
    tradition: 'buddhist',
    intention: 'Healing',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay bhay-SHAHJ-yah-GOO-roo',
    sacred_geometry_type: 'lotus',
    context_note: 'Bhaishajyaguru — "Medicine Buddha" — is the buddha of healing. His body is lapis lazuli blue, and he holds a medicine bowl.',
    go_deeper_teaser: 'Medicine Buddha: the healing practice →',
  },
  {
    day_of_year: 217,
    original_script: 'वैडूर्यप्रभाराजाय',
    transliteration: 'Vaiduryaprabharajaya',
    english_translation: 'To the king of lapis lazuli light.',
    tradition: 'buddhist',
    intention: 'Healing',
    phonetic_guide: 'vay-DOO-ryah-PRAH-bhah-RAH-jah-yah',
    sacred_geometry_type: 'lotus',
    context_note: 'Part of the Medicine Buddha mantra. Vaidurya — "lapis lazuli" — is the deep blue stone that represents the clarity of the awakened mind.',
    go_deeper_teaser: 'Lapis lazuli: the stone of the Medicine Buddha →',
  },
  {
    day_of_year: 218,
    original_script: 'तथागताय',
    transliteration: 'Tathagataya',
    english_translation: 'To the thus-gone one — the one who has gone to suchness.',
    tradition: 'buddhist',
    intention: 'Suchness',
    phonetic_guide: 'tah-TAH-gah-tah-yah',
    sacred_geometry_type: 'lotus',
    context_note: 'Tathagata — "thus-gone" or "thus-come" — is the Buddha\'s own name for himself. It points to the nature of reality: things are just as they are.',
    go_deeper_teaser: 'Tathata: the Buddhist concept of suchness →',
  },
  {
    day_of_year: 219,
    original_script: 'ॐ भेकन्द्जे भेकन्द्जे',
    transliteration: 'Om Bekandze Bekandze',
    english_translation: 'Om — eliminate, eliminate — the pain of illness.',
    tradition: 'buddhist',
    intention: 'Healing',
    phonetic_guide: 'OHM bay-KAHN-dzay bay-KAHN-dzay',
    sacred_geometry_type: 'lotus',
    context_note: 'The heart of the Medicine Buddha mantra. Bekandze means "eliminate pain" — the mantra is said to heal both physical illness and the illness of ignorance.',
    go_deeper_teaser: 'The Medicine Buddha mantra: healing body and mind →',
  },
  {
    day_of_year: 220,
    original_script: 'महाभेकन्द्जे राद्जा समुद्गते स्वाहा',
    transliteration: 'Maha Bekandze Radza Samudgate Svaha',
    english_translation: 'Great elimination — king — the supreme arising — so be it.',
    tradition: 'buddhist',
    intention: 'Complete Healing',
    phonetic_guide: 'mah-HAH bay-KAHN-dzay RAHD-zah sah-mood-GAH-tay svah-HAH',
    sacred_geometry_type: 'lotus',
    context_note: 'The conclusion of the Medicine Buddha mantra. Samudgate — "supreme arising" — points to the arising of the awakened mind that heals all.',
    go_deeper_teaser: 'The complete Medicine Buddha practice →',
  },
  {
    day_of_year: 221,
    original_script: 'ॐ नमो भगवते अमितायुषे',
    transliteration: 'Om Namo Bhagavate Amitayushe',
    english_translation: 'Om, I bow to the blessed one of infinite life.',
    tradition: 'buddhist',
    intention: 'Longevity',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay ah-mee-TAH-yoo-shay',
    sacred_geometry_type: 'lotus',
    context_note: 'Amitayus — "infinite life" — is the longevity aspect of Amitabha Buddha. This mantra is chanted for long life and the extension of the teaching.',
    go_deeper_teaser: 'Amitayus: the Buddha of infinite life →',
  },
  {
    day_of_year: 222,
    original_script: 'ॐ अमरणि जीवन्तये स्वाहा',
    transliteration: 'Om Amarani Jivantaye Svaha',
    english_translation: 'Om — immortal life — living — so be it.',
    tradition: 'buddhist',
    intention: 'Life Force',
    phonetic_guide: 'OHM ah-mah-RAH-nih jee-VAHN-tah-yay svah-HAH',
    sacred_geometry_type: 'lotus',
    context_note: 'The Amitayus mantra. Amarani — "immortal" — refers not to physical immortality but to the deathless nature of the awakened mind.',
    go_deeper_teaser: 'The deathless: what the Buddha meant by nirvana →',
  },
  {
    day_of_year: 223,
    original_script: 'ॐ नमो भगवते सर्वदुर्गतिपरिशोधनाय',
    transliteration: 'Om Namo Bhagavate Sarvadurgatiparisodhana',
    english_translation: 'Om, I bow to the one who purifies all lower realms.',
    tradition: 'buddhist',
    intention: 'Purification',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay sahr-vah-door-gah-tih-pah-rih-SOH-dhah-nah',
    sacred_geometry_type: 'lotus',
    context_note: 'The opening of the Stainless Beam mantra — one of the most powerful purification mantras in Tibetan Buddhism.',
    go_deeper_teaser: 'The Stainless Beam mantra: purifying all karma →',
  },
  {
    day_of_year: 224,
    original_script: 'ॐ बोधिचित्त उत्पादयामि',
    transliteration: 'Om Bodhicitta Utpadayami',
    english_translation: 'Om, I generate the awakening mind.',
    tradition: 'buddhist',
    intention: 'Awakening',
    phonetic_guide: 'OHM BOH-dhih-chiht-tah oot-PAH-dah-YAH-mih',
    sacred_geometry_type: 'lotus',
    context_note: 'Bodhicitta — "awakening mind" — is the aspiration to achieve enlightenment for the benefit of all beings. It is the heart of Mahayana Buddhism.',
    go_deeper_teaser: 'Bodhicitta: the most precious mind →',
  },
  {
    day_of_year: 225,
    original_script: 'ॐ नमो भगवते प्रज्ञापारमिताये',
    transliteration: 'Om Namo Bhagavate Prajnaparamitaye',
    english_translation: 'Om, I bow to the blessed perfection of wisdom.',
    tradition: 'buddhist',
    intention: 'Wisdom',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay PRAHJ-nyah-PAH-rah-mih-TAH-yay',
    sacred_geometry_type: 'lotus',
    context_note: 'Prajnaparamita — "perfection of wisdom" — is personified as a goddess and is the "mother of all buddhas." The Heart Sutra is her teaching.',
    go_deeper_teaser: 'Prajnaparamita: the mother of all buddhas →',
  },
  {
    day_of_year: 226,
    original_script: 'ॐ नमो भगवते अक्षोभ्याय',
    transliteration: 'Om Namo Bhagavate Akshobhyaya',
    english_translation: 'Om, I bow to the blessed Akshobhya — the imperturbable.',
    tradition: 'buddhist',
    intention: 'Imperturbability',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay ahk-SHOH-bhyah-yah',
    sacred_geometry_type: 'lotus',
    context_note: 'Akshobhya — "imperturbable" — is the buddha of the east, representing mirror-like wisdom. His dark blue color represents the depth of the awakened mind.',
    go_deeper_teaser: 'The five dhyani buddhas: a complete map of awakening →',
  },
  {
    day_of_year: 227,
    original_script: 'ॐ नमो भगवते रत्नसम्भवाय',
    transliteration: 'Om Namo Bhagavate Ratnasambhavaya',
    english_translation: 'Om, I bow to the blessed Ratnasambhava — the jewel-born.',
    tradition: 'buddhist',
    intention: 'Abundance',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay raht-nah-SAHM-bhah-vah-yah',
    sacred_geometry_type: 'lotus',
    context_note: 'Ratnasambhava — "jewel-born" — is the buddha of the south, representing the wisdom of equality. All beings are equally precious jewels.',
    go_deeper_teaser: 'Ratnasambhava: the wisdom of equality →',
  },
  {
    day_of_year: 228,
    original_script: 'ॐ नमो भगवते अमोघसिद्धये',
    transliteration: 'Om Namo Bhagavate Amoghasiddhaye',
    english_translation: 'Om, I bow to the blessed Amoghasiddhi — the infallible accomplisher.',
    tradition: 'buddhist',
    intention: 'Accomplishment',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay ah-MOH-ghah-SID-dhah-yay',
    sacred_geometry_type: 'lotus',
    context_note: 'Amoghasiddhi — "infallible accomplishment" — is the buddha of the north, representing all-accomplishing wisdom.',
    go_deeper_teaser: 'Amoghasiddhi: the all-accomplishing wisdom →',
  },
  {
    day_of_year: 229,
    original_script: 'ॐ नमो भगवते वैरोचनाय',
    transliteration: 'Om Namo Bhagavate Vairochana',
    english_translation: 'Om, I bow to the blessed Vairochana — the illuminator.',
    tradition: 'buddhist',
    intention: 'Illumination',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay vay-ROH-chah-nah',
    sacred_geometry_type: 'lotus',
    context_note: 'Vairochana — "the illuminator" — is the central buddha of the five dhyani buddhas, representing the dharmadhatu wisdom — the wisdom of all-encompassing space.',
    go_deeper_teaser: 'Vairochana: the central buddha of the mandala →',
  },
  {
    day_of_year: 230,
    original_script: 'ॐ आह्राह् हूँ',
    transliteration: 'Om Ah Ra Pa Ca Na Dhih Dhih Dhih',
    english_translation: 'Om — the wisdom syllables — wisdom, wisdom, wisdom.',
    tradition: 'buddhist',
    intention: 'Wisdom',
    phonetic_guide: 'OHM ah rah pah chah nah dhee dhee dhee',
    sacred_geometry_type: 'lotus',
    context_note: 'The extended Manjushri mantra with triple Dhih. Dhih is the seed syllable of wisdom — repeating it three times intensifies the awakening of prajna.',
    go_deeper_teaser: 'Prajna: the wisdom that liberates →',
  },
  {
    day_of_year: 231,
    original_script: 'ॐ सुप्रतिष्ठित स्वाहा',
    transliteration: 'Om Supratishthita Svaha',
    english_translation: 'Om — well-established — so be it.',
    tradition: 'buddhist',
    intention: 'Stability',
    phonetic_guide: 'OHM soo-prah-TISH-thih-tah svah-HAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Supratishthita — "well-established" — is a dharani for establishing the practice firmly. Svaha seals the intention.',
    go_deeper_teaser: 'Establishing a daily practice: the Buddhist approach →',
  },
  {
    day_of_year: 232,
    original_script: 'ॐ धरणी धरणी स्वाहा',
    transliteration: 'Om Dharani Dharani Svaha',
    english_translation: 'Om — earth-holder, earth-holder — so be it.',
    tradition: 'buddhist',
    intention: 'Grounding',
    phonetic_guide: 'OHM dhah-RAH-nih dhah-RAH-nih svah-HAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Dharani means both "earth" and "that which holds." This mantra grounds the practice in the earth of reality.',
    go_deeper_teaser: 'Dharani: the mantras that hold the earth →',
  },
  {
    day_of_year: 233,
    original_script: 'ॐ नमो भगवते वज्रपाणये',
    transliteration: 'Om Namo Bhagavate Vajrapanaye',
    english_translation: 'Om, I bow to the blessed Vajrapani.',
    tradition: 'buddhist',
    intention: 'Power',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay VAHJ-rah-PAH-nah-yay',
    sacred_geometry_type: 'lotus',
    context_note: 'Vajrapani\'s thunderbolt cuts through the three poisons: greed, hatred, and delusion. This mantra invokes the power to overcome inner obstacles.',
    go_deeper_teaser: 'The three poisons: greed, hatred, and delusion →',
  },
  {
    day_of_year: 234,
    original_script: 'ॐ नमो भगवते कुरुकुल्लायै',
    transliteration: 'Om Namo Bhagavate Kurukulle',
    english_translation: 'Om, I bow to the blessed Kurukulle — the goddess of enchantment.',
    tradition: 'buddhist',
    intention: 'Attraction',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay koo-roo-KOOL-lay',
    sacred_geometry_type: 'lotus',
    context_note: 'Kurukulle is a tantric goddess who enchants and magnetizes — drawing beings toward the Dharma through the power of love.',
    go_deeper_teaser: 'Kurukulle: the goddess who draws beings to the Dharma →',
  },
  {
    day_of_year: 235,
    original_script: 'ॐ नमो भगवते चुन्द्रायै',
    transliteration: 'Om Namo Bhagavate Cundrayai',
    english_translation: 'Om, I bow to the blessed Cunda — the goddess of awakening.',
    tradition: 'buddhist',
    intention: 'Awakening',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay CHOON-drah-yay',
    sacred_geometry_type: 'lotus',
    context_note: 'Cunda (or Chunda) is a bodhisattva associated with the awakening mind. She is depicted with multiple arms representing her many activities.',
    go_deeper_teaser: 'The female bodhisattvas: wisdom in feminine form →',
  },
  {
    day_of_year: 236,
    original_script: 'ॐ नमो भगवते वज्रसारप्रमर्दने',
    transliteration: 'Om Namo Bhagavate Vajrasarapramardane',
    english_translation: 'Om, I bow to the crusher of the vajra essence.',
    tradition: 'buddhist',
    intention: 'Purification',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay VAHJ-rah-SAH-rah-prah-MAHR-dah-nay',
    sacred_geometry_type: 'lotus',
    context_note: 'A powerful purification dharani. Pramardane — "crusher" — refers to the crushing of karmic obscurations.',
    go_deeper_teaser: 'Karma: what it really means and how to purify it →',
  },
  {
    day_of_year: 237,
    original_script: 'ॐ सर्वपापविशोधन',
    transliteration: 'Om Sarvapapavishoshana',
    english_translation: 'Om — purifier of all sins.',
    tradition: 'buddhist',
    intention: 'Purification',
    phonetic_guide: 'OHM sahr-vah-PAH-pah-vih-SOH-shah-nah',
    sacred_geometry_type: 'lotus',
    context_note: 'A dharani for purifying all negative karma. Vishoshana — "drying up" — suggests that negative karma is dried up like water in sunlight.',
    go_deeper_teaser: 'Purification practices in Buddhism →',
  },
  {
    day_of_year: 238,
    original_script: 'ॐ नमो भगवते सर्वतथागत',
    transliteration: 'Om Namo Bhagavate Sarvatathagata',
    english_translation: 'Om, I bow to all the blessed thus-gone ones.',
    tradition: 'buddhist',
    intention: 'Reverence',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay sahr-vah-tah-TAH-gah-tah',
    sacred_geometry_type: 'lotus',
    context_note: 'A universal salutation to all buddhas of all times and directions. The awakened ones are infinite in number.',
    go_deeper_teaser: 'The infinite buddhas: the Buddhist vision of awakening →',
  },
  {
    day_of_year: 239,
    original_script: 'ॐ धर्मधातु स्वभाव',
    transliteration: 'Om Dharmadhatu Svabhava',
    english_translation: 'Om — the nature of the dharma realm.',
    tradition: 'buddhist',
    intention: 'Nature of Mind',
    phonetic_guide: 'OHM DHAHR-mah-DAH-too svah-BHAH-vah',
    sacred_geometry_type: 'lotus',
    context_note: 'Dharmadhatu — "dharma realm" — is the totality of all phenomena as they truly are. Svabhava — "own nature" — points to the intrinsic nature of mind.',
    go_deeper_teaser: 'Dharmadhatu: the realm of truth →',
  },
  {
    day_of_year: 240,
    original_script: 'ॐ स्वभाव शुद्धाः सर्वधर्माः',
    transliteration: 'Om Svabhava Shuddha Sarvadharmah',
    english_translation: 'Om — by nature pure are all phenomena.',
    tradition: 'buddhist',
    intention: 'Purity',
    phonetic_guide: 'OHM svah-BHAH-vah SHOO-dhah sahr-vah-DHAHR-mah',
    sacred_geometry_type: 'lotus',
    context_note: 'The emptiness mantra — all phenomena are pure by nature. This is the Madhyamaka view: nothing is inherently defiled.',
    go_deeper_teaser: 'Emptiness: the most misunderstood Buddhist teaching →',
  },
  {
    day_of_year: 241,
    original_script: 'स्वभाव शुद्धो ऽहम्',
    transliteration: 'Svabhava Shuddho\'ham',
    english_translation: 'I am pure by nature.',
    tradition: 'buddhist',
    intention: 'Purity',
    phonetic_guide: 'svah-BHAH-vah SHOO-dhoh-hahm',
    sacred_geometry_type: 'lotus',
    context_note: 'The personal application of the emptiness mantra. Your true nature is pure — not because you have purified it, but because it was never defiled.',
    go_deeper_teaser: 'Buddha nature: the purity that was always there →',
  },
  {
    day_of_year: 242,
    original_script: 'ॐ नमो भगवते तथागत',
    transliteration: 'Om Namo Bhagavate Tathagata',
    english_translation: 'Om, I bow to the blessed thus-gone one.',
    tradition: 'buddhist',
    intention: 'Suchness',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay tah-TAH-gah-tah',
    sacred_geometry_type: 'lotus',
    context_note: 'A simple, universal invocation of the Buddha. Tathagata — "thus-gone" — points to the nature of awakening: going beyond all concepts.',
    go_deeper_teaser: 'Tathagata: the Buddha\'s most profound name →',
  },
  {
    day_of_year: 243,
    original_script: 'ॐ भव भव महाभव',
    transliteration: 'Om Bhava Bhava Mahabhava',
    english_translation: 'Om — become, become, greatly become.',
    tradition: 'buddhist',
    intention: 'Becoming',
    phonetic_guide: 'OHM BHAH-vah BHAH-vah mah-hah-BHAH-vah',
    sacred_geometry_type: 'lotus',
    context_note: 'A mantra of transformation. Bhava — "becoming" — is the process of continuous change. The mantra invites full participation in the process of becoming.',
    go_deeper_teaser: 'Impermanence: the Buddhist teaching on change →',
  },
  {
    day_of_year: 244,
    original_script: 'ॐ सम्बोधि सम्बोधि',
    transliteration: 'Om Sambodhi Sambodhi',
    english_translation: 'Om — complete awakening, complete awakening.',
    tradition: 'buddhist',
    intention: 'Awakening',
    phonetic_guide: 'OHM sahm-BOH-dhee sahm-BOH-dhee',
    sacred_geometry_type: 'lotus',
    context_note: 'Sambodhi — "complete awakening" — is the full enlightenment of a buddha. Repeating it twice affirms the aspiration for complete awakening.',
    go_deeper_teaser: 'Sambodhi: what complete awakening actually means →',
  },
  {
    day_of_year: 245,
    original_script: 'ॐ बोधि बोधि महाबोधि',
    transliteration: 'Om Bodhi Bodhi Mahabodhi',
    english_translation: 'Om — awakening, awakening, great awakening.',
    tradition: 'buddhist',
    intention: 'Awakening',
    phonetic_guide: 'OHM BOH-dhee BOH-dhee mah-hah-BOH-dhee',
    sacred_geometry_type: 'lotus',
    context_note: 'A mantra of progressive awakening. Bodhi — "awakening" — grows from individual to great, from partial to complete.',
    go_deeper_teaser: 'The stages of awakening in Buddhism →',
  },
  {
    day_of_year: 246,
    original_script: 'ॐ नमो भगवते अवलोकितेश्वराय',
    transliteration: 'Om Namo Bhagavate Avalokiteshvaraya',
    english_translation: 'Om, I bow to the blessed Avalokiteshvara — the one who hears all cries.',
    tradition: 'buddhist',
    intention: 'Compassion',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay ah-vah-loh-kih-TAYSH-vah-rah-yah',
    sacred_geometry_type: 'lotus',
    context_note: 'Avalokiteshvara — "the one who looks down with compassion" — is the bodhisattva who hears all cries of suffering and responds with compassion.',
    go_deeper_teaser: 'Avalokiteshvara: the bodhisattva of universal compassion →',
  },
  {
    day_of_year: 247,
    original_script: 'ॐ सर्वज्ञाय नमः',
    transliteration: 'Om Sarvajnaya Namah',
    english_translation: 'Om, I bow to the all-knowing one.',
    tradition: 'buddhist',
    intention: 'Omniscience',
    phonetic_guide: 'OHM sahr-VAHJ-nyah-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Sarvajnaya — "all-knowing" — is an epithet of the Buddha. Omniscience is not supernatural; it is the natural result of a completely purified mind.',
    go_deeper_teaser: 'Omniscience: the Buddhist understanding →',
  },
  {
    day_of_year: 248,
    original_script: 'ॐ नमो भगवते मैत्रेयाय',
    transliteration: 'Om Namo Bhagavate Maitreya',
    english_translation: 'Om, I bow to the blessed Maitreya — the future Buddha of loving-kindness.',
    tradition: 'buddhist',
    intention: 'Loving-Kindness',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay my-TRAY-yah',
    sacred_geometry_type: 'lotus',
    context_note: 'Maitreya — "the loving one" — is the future Buddha who will appear when the Dharma has been forgotten. His name is the root of the word "metta."',
    go_deeper_teaser: 'Maitreya: the future Buddha of loving-kindness →',
  },
  {
    day_of_year: 249,
    original_script: 'ॐ नमो भगवते क्षितिगर्भाय',
    transliteration: 'Om Namo Bhagavate Kshitigarbhaya',
    english_translation: 'Om, I bow to the blessed Kshitigarbha — the earth treasury.',
    tradition: 'buddhist',
    intention: 'Compassion',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay kshih-tih-GAHR-bhah-yah',
    sacred_geometry_type: 'lotus',
    context_note: 'Kshitigarbha — "earth treasury" — is the bodhisattva who vowed to save all beings from the hell realms before becoming a buddha.',
    go_deeper_teaser: 'Kshitigarbha: the bodhisattva who descends to hell →',
  },
  {
    day_of_year: 250,
    original_script: 'ॐ सम्पद्यन्ते स्वाहा',
    transliteration: 'Om Sampadyante Svaha',
    english_translation: 'Om — may it be accomplished — so be it.',
    tradition: 'buddhist',
    intention: 'Accomplishment',
    phonetic_guide: 'OHM sahm-PAHD-yahn-tay svah-HAH',
    sacred_geometry_type: 'lotus',
    context_note: 'A completion mantra. Sampadyante — "may it be accomplished" — seals any practice or intention with the wish for its fulfillment.',
    go_deeper_teaser: 'Sealing a practice: the importance of dedication →',
  },

  // ── SIKH / GURBANI (days 251–319) ─────────────────────────────────────────
  {
    day_of_year: 251,
    original_script: 'ੴ ਸਤਿ ਨਾਮੁ',
    transliteration: 'Ik Onkar Sat Nam',
    english_translation: 'One God — True Name.',
    tradition: 'sikh',
    intention: 'Unity',
    phonetic_guide: 'ik OHN-kahr saht nahm',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'The Mool Mantar — the root mantra of Sikhism, composed by Guru Nanak. Ik Onkar — "One God" — is the foundational truth of Sikh theology.',
    go_deeper_teaser: 'The Mool Mantar: Sikhism\'s most sacred teaching →',
  },
  {
    day_of_year: 252,
    original_script: 'ਕਰਤਾ ਪੁਰਖੁ',
    transliteration: 'Karta Purakh',
    english_translation: 'The Creator Being.',
    tradition: 'sikh',
    intention: 'Creation',
    phonetic_guide: 'KAHR-tah POO-rahkh',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'From the Mool Mantar. Karta — "creator" — Purakh — "being" or "person." The divine is not an abstract force but a personal creator.',
    go_deeper_teaser: 'Karta Purakh: the personal God of Sikhism →',
  },
  {
    day_of_year: 253,
    original_script: 'ਨਿਰਭਉ ਨਿਰਵੈਰੁ',
    transliteration: 'Nirbhau Nirvair',
    english_translation: 'Without fear, without enmity.',
    tradition: 'sikh',
    intention: 'Fearlessness',
    phonetic_guide: 'nih-BHOW nih-VAIR',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'From the Mool Mantar. The divine has no fear and no enemies. Meditating on these qualities transforms the practitioner.',
    go_deeper_teaser: 'Nirbhau: the fearless God of Guru Nanak →',
  },
  {
    day_of_year: 254,
    original_script: 'ਅਕਾਲ ਮੂਰਤਿ',
    transliteration: 'Akal Murat',
    english_translation: 'Timeless form — beyond time and death.',
    tradition: 'sikh',
    intention: 'Eternity',
    phonetic_guide: 'ah-KAHL MOO-raht',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'From the Mool Mantar. Akal — "beyond time" — Murat — "form." The divine is the timeless presence that underlies all temporal forms.',
    go_deeper_teaser: 'Akal: the timeless God of Sikhism →',
  },
  {
    day_of_year: 255,
    original_script: 'ਅਜੂਨੀ ਸੈਭੰ',
    transliteration: 'Ajuni Saibhang',
    english_translation: 'Unborn, self-illumined.',
    tradition: 'sikh',
    intention: 'Self-Sufficiency',
    phonetic_guide: 'ah-JOO-nih SAY-bhahng',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'From the Mool Mantar. The divine was not born and does not need anything outside itself. Saibhang — "self-illumined" — the divine is its own light.',
    go_deeper_teaser: 'Saibhang: the self-illumined nature of God →',
  },
  {
    day_of_year: 256,
    original_script: 'ਗੁਰ ਪ੍ਰਸਾਦਿ',
    transliteration: 'Gur Prasad',
    english_translation: 'By the grace of the Guru.',
    tradition: 'sikh',
    intention: 'Grace',
    phonetic_guide: 'goor prah-SAHD',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'The final phrase of the Mool Mantar. All spiritual realization comes by the grace of the Guru — not by personal effort alone.',
    go_deeper_teaser: 'Gur Prasad: the grace that makes everything possible →',
  },
  {
    day_of_year: 257,
    original_script: 'ਵਾਹਿਗੁਰੂ',
    transliteration: 'Waheguru',
    english_translation: 'Wondrous Guru — the divine that fills us with wonder.',
    tradition: 'sikh',
    intention: 'Wonder',
    phonetic_guide: 'WAH-hay-goo-roo',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'The most important mantra in Sikhism. Wahe — "wondrous" — Guru — "teacher." The divine is the teacher who fills us with wonder.',
    go_deeper_teaser: 'Waheguru: the wonder at the heart of Sikhism →',
  },
  {
    day_of_year: 258,
    original_script: 'ਸਤਿ ਨਾਮੁ ਵਾਹਿਗੁਰੂ',
    transliteration: 'Sat Nam Waheguru',
    english_translation: 'True Name — Wondrous Guru.',
    tradition: 'sikh',
    intention: 'Truth',
    phonetic_guide: 'saht nahm WAH-hay-goo-roo',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'The most common Sikh mantra combination. Sat Nam — "True Name" — is the identity of the divine. Waheguru is the expression of wonder at that truth.',
    go_deeper_teaser: 'Sat Nam: the true name of God →',
  },
  {
    day_of_year: 259,
    original_script: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ',
    transliteration: 'Sat Sri Akal',
    english_translation: 'True, great, and timeless.',
    tradition: 'sikh',
    intention: 'Truth',
    phonetic_guide: 'saht sree ah-KAHL',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'The Sikh greeting and battle cry. Sri — "great" or "radiant" — Akal — "timeless." A reminder that truth is eternal.',
    go_deeper_teaser: 'Sat Sri Akal: the Sikh greeting and its meaning →',
  },
  {
    day_of_year: 260,
    original_script: 'ਨਾਨਕ ਨਾਮ ਚੜ੍ਹਦੀ ਕਲਾ',
    transliteration: 'Nanak Nam Chardi Kala',
    english_translation: 'Nanak, through the Name, may there be ever-rising spirit.',
    tradition: 'sikh',
    intention: 'Optimism',
    phonetic_guide: 'NAH-nahk nahm CHAHR-dee kah-LAH',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Chardi Kala — "ever-rising spirit" — is the Sikh concept of eternal optimism. No matter what happens, the spirit rises. This is the Sikh response to adversity.',
    go_deeper_teaser: 'Chardi Kala: the Sikh practice of eternal optimism →',
  },
  {
    day_of_year: 261,
    original_script: 'ਤੇਰੇ ਭਾਣੇ ਸਰਬਤ ਦਾ ਭਲਾ',
    transliteration: 'Tere Bhane Sarbat Da Bhala',
    english_translation: 'In your will, may all prosper.',
    tradition: 'sikh',
    intention: 'Universal Welfare',
    phonetic_guide: 'TAY-ray BHAH-nay SAHR-baht dah BHAH-lah',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'The Ardas prayer\'s closing line. Sarbat — "all" — Da Bhala — "welfare." The Sikh prayer always ends with a wish for the welfare of all humanity.',
    go_deeper_teaser: 'Ardas: the Sikh prayer for all humanity →',
  },
  {
    day_of_year: 262,
    original_script: 'ਸਿਮਰਨ ਸਿਮਰਨ ਸਿਮਰਨ',
    transliteration: 'Simran Simran Simran',
    english_translation: 'Remembrance, remembrance, remembrance.',
    tradition: 'sikh',
    intention: 'Remembrance',
    phonetic_guide: 'SIM-rahn SIM-rahn SIM-rahn',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Simran — "remembrance" or "meditation" — is the central Sikh practice. To remember God\'s name in every breath is the highest spiritual discipline.',
    go_deeper_teaser: 'Simran: the Sikh practice of divine remembrance →',
  },
  {
    day_of_year: 263,
    original_script: 'ਹਰਿ ਹਰਿ ਹਰਿ ਹਰਿ',
    transliteration: 'Har Har Har Har',
    english_translation: 'God, God, God, God — the creative infinity.',
    tradition: 'sikh',
    intention: 'Creativity',
    phonetic_guide: 'hahr hahr hahr hahr',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Har is the Sikh name for God as the creative force. Repeating it activates the navel center and the creative power of the divine.',
    go_deeper_teaser: 'Har: the creative name of God in Sikhism →',
  },
  {
    day_of_year: 264,
    original_script: 'ਹਰਿ ਨਾਮੁ ਜਪਹੁ',
    transliteration: 'Har Nam Japahu',
    english_translation: 'Chant the name of God.',
    tradition: 'sikh',
    intention: 'Practice',
    phonetic_guide: 'hahr nahm JAH-pah-hoo',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'From the Guru Granth Sahib. Japahu — "chant" — is the imperative form. The Guru\'s instruction is direct: chant the name.',
    go_deeper_teaser: 'Japa: the practice of mantra repetition →',
  },
  {
    day_of_year: 265,
    original_script: 'ਰਾਮ ਰਾਮ ਰਾਮ ਰਾਮ',
    transliteration: 'Ram Ram Ram Ram',
    english_translation: 'Ram, Ram, Ram, Ram — the divine joy.',
    tradition: 'sikh',
    intention: 'Joy',
    phonetic_guide: 'rahm rahm rahm rahm',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'In Sikhism, Ram is not just the avatar but the divine name meaning "the one who permeates all." The Gurus used many divine names interchangeably.',
    go_deeper_teaser: 'Ram in Sikhism: the all-pervasive divine →',
  },
  {
    day_of_year: 266,
    original_script: 'ਗੋਬਿੰਦ ਗੋਬਿੰਦ ਗੋਬਿੰਦ ਸੰਗਿ',
    transliteration: 'Gobind Gobind Gobind Sang',
    english_translation: 'Gobind, Gobind, Gobind — in the company of God.',
    tradition: 'sikh',
    intention: 'Companionship',
    phonetic_guide: 'GOH-bind GOH-bind GOH-bind sahng',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'From the Guru Granth Sahib. Gobind — "sustainer of the world" — is repeated three times, then "sang" — "in the company of." We are never alone.',
    go_deeper_teaser: 'Sangat: the Sikh community of truth →',
  },
  {
    day_of_year: 267,
    original_script: 'ਨਾਮੁ ਜਪਤ ਅਰਪੋ ਤਨੁ ਮਨੁ',
    transliteration: 'Nam Japat Arpo Tan Man',
    english_translation: 'Chanting the Name, offer body and mind.',
    tradition: 'sikh',
    intention: 'Surrender',
    phonetic_guide: 'nahm JAH-paht AHR-poh tahn mahn',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'From the Guru Granth Sahib. The complete offering in Sikhism is not just words but the whole self — body and mind — surrendered to the divine name.',
    go_deeper_teaser: 'Total surrender: the Sikh path of devotion →',
  },
  {
    day_of_year: 268,
    original_script: 'ਸਾਸ ਸਾਸ ਸਿਮਰਹੁ ਗੋਬਿੰਦ',
    transliteration: 'Sas Sas Simrahu Gobind',
    english_translation: 'With every breath, remember Gobind.',
    tradition: 'sikh',
    intention: 'Breath Practice',
    phonetic_guide: 'sahs sahs SIM-rah-hoo GOH-bind',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'From the Guru Granth Sahib. Sas — "breath." The Sikh practice of remembering God with every breath transforms ordinary breathing into prayer.',
    go_deeper_teaser: 'Breath as prayer: the Sikh practice of Sas Sas →',
  },
  {
    day_of_year: 269,
    original_script: 'ਮਨ ਤੂੰ ਜੋਤਿ ਸਰੂਪੁ ਹੈ',
    transliteration: 'Man Tu Jot Sarup Hai',
    english_translation: 'O mind, you are the image of divine light.',
    tradition: 'sikh',
    intention: 'Self-Realization',
    phonetic_guide: 'mahn too joht sah-ROOP hay',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'From the Guru Granth Sahib. Jot — "light" — Sarup — "form" or "image." The mind is not the enemy but the image of divine light.',
    go_deeper_teaser: 'Jot Sarup: the light within you →',
  },
  {
    day_of_year: 270,
    original_script: 'ਅਪਣਾ ਮੂਲੁ ਪਛਾਣੁ',
    transliteration: 'Apna Mul Pachhan',
    english_translation: 'Recognize your own origin.',
    tradition: 'sikh',
    intention: 'Self-Knowledge',
    phonetic_guide: 'ahp-NAH mool pah-CHAHN',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'From the Guru Granth Sahib. Mul — "root" or "origin." The Guru\'s instruction: know where you come from. Your origin is divine.',
    go_deeper_teaser: 'Mul: returning to the root of your being →',
  },
  {
    day_of_year: 271,
    original_script: 'ਜਿਉ ਜਿਉ ਤੇਰੀ ਰਜਾਇ',
    transliteration: 'Jio Jio Teri Raza',
    english_translation: 'As is your will, so be it.',
    tradition: 'sikh',
    intention: 'Acceptance',
    phonetic_guide: 'jee-OH jee-OH TAY-ree rah-ZAH',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'From the Guru Granth Sahib. Raza — "will" or "pleasure." Complete acceptance of the divine will is the highest Sikh spiritual state.',
    go_deeper_teaser: 'Raza: the Sikh practice of divine will acceptance →',
  },
  {
    day_of_year: 272,
    original_script: 'ਨਾਨਕ ਦਾਸ ਤੇਰੇ ਦਰ ਕਾ',
    transliteration: 'Nanak Das Tere Dar Ka',
    english_translation: 'Nanak is the servant at your door.',
    tradition: 'sikh',
    intention: 'Humility',
    phonetic_guide: 'NAH-nahk dahs TAY-ray dahr kah',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Guru Nanak\'s signature of humility. Das — "servant." The greatest teacher called himself a servant at the divine door.',
    go_deeper_teaser: 'Guru Nanak: the servant who became the teacher →',
  },
  {
    day_of_year: 273,
    original_script: 'ਤੁਧੁ ਬਿਨੁ ਦੂਜਾ ਨਾਹੀ ਕੋਇ',
    transliteration: 'Tudh Bin Duja Nahi Koi',
    english_translation: 'Without you, there is no other.',
    tradition: 'sikh',
    intention: 'Oneness',
    phonetic_guide: 'too-DHOO bin DOO-jah nah-HEE koh-EE',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'From the Guru Granth Sahib. A declaration of non-duality: there is only God. Everything else is the play of the one divine reality.',
    go_deeper_teaser: 'Sikh non-dualism: there is only one →',
  },
  {
    day_of_year: 274,
    original_script: 'ਸਰਬ ਕਲਾ ਭਰਪੂਰ',
    transliteration: 'Sarab Kala Bharpoor',
    english_translation: 'Fully pervading all with all powers.',
    tradition: 'sikh',
    intention: 'Omnipresence',
    phonetic_guide: 'sah-RAHB kah-LAH bhar-POOR',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'From the Guru Granth Sahib. Sarab — "all" — Kala — "powers" — Bharpoor — "fully pervading." The divine is fully present everywhere with all its powers.',
    go_deeper_teaser: 'The omnipresent God of the Guru Granth Sahib →',
  },

  // ── UNIVERSAL (days 275–365) ──────────────────────────────────────────────
  {
    day_of_year: 275,
    original_script: 'ॐ',
    transliteration: 'Om',
    english_translation: 'The primordial sound — the vibration from which all creation arises.',
    tradition: 'universal',
    intention: 'Source',
    phonetic_guide: 'OHM (hold for 5-7 seconds)',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Om is the first sound — the vibration of pure consciousness before it becomes words or thoughts. It contains all sounds within it.',
    go_deeper_teaser: 'The physics of Om: why it is the primordial sound →',
  },
  {
    day_of_year: 276,
    original_script: 'ॐ ॐ ॐ',
    transliteration: 'Om Om Om',
    english_translation: 'Three Oms — for body, speech, and mind.',
    tradition: 'universal',
    intention: 'Integration',
    phonetic_guide: 'OHM... OHM... OHM... (pause between each)',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Three Oms purify the three aspects of our being: the physical body, speech and breath, and the mind. A complete practice in three sounds.',
    go_deeper_teaser: 'The three Oms: a complete purification practice →',
  },
  {
    day_of_year: 277,
    original_script: 'ॐ शान्तिः शान्तिः शान्तिः',
    transliteration: 'Om Shantih Shantih Shantih',
    english_translation: 'Om — peace, peace, peace.',
    tradition: 'universal',
    intention: 'Peace',
    phonetic_guide: 'OHM SHAHN-tih SHAHN-tih SHAHN-tih',
    sacred_geometry_type: 'lotus',
    context_note: 'The universal peace invocation ending all Vedic prayers. Three repetitions address the three sources of suffering: adhyatmika (self), adhibhautika (others), adhidaivika (cosmos).',
    go_deeper_teaser: 'The three sources of suffering and their antidote →',
  },
  {
    day_of_year: 278,
    original_script: 'सोऽहम्',
    transliteration: 'So\'ham',
    english_translation: 'I am that — the breath itself is the mantra.',
    tradition: 'universal',
    intention: 'Identity',
    phonetic_guide: 'SOH-hahm (So on inhale, Ham on exhale)',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'So\'ham is the natural sound of the breath: So on the inhale, Ham on the exhale. The breath itself is saying "I am that" 21,600 times per day.',
    go_deeper_teaser: 'So\'ham: the mantra you\'ve been chanting since birth →',
  },
  {
    day_of_year: 279,
    original_script: 'हंसः',
    transliteration: 'Hamsa',
    english_translation: 'The swan — the breath — I am that.',
    tradition: 'universal',
    intention: 'Breath',
    phonetic_guide: 'HAHM-sah (Ham on exhale, Sa on inhale)',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Hamsa — "swan" or "I am that" — is So\'ham reversed. The swan is the symbol of the discriminating mind that separates milk from water.',
    go_deeper_teaser: 'Hamsa: the swan of discernment →',
  },
  {
    day_of_year: 280,
    original_script: 'अहम् ब्रह्मास्मि',
    transliteration: 'Aham Brahmasmi',
    english_translation: 'I am Brahman — I am the infinite.',
    tradition: 'universal',
    intention: 'Self-Realization',
    phonetic_guide: 'AH-hahm BRAH-mahs-mih',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'One of the four mahavakyas — great sayings — of the Upanishads. From the Brihadaranyaka Upanishad. The direct declaration of identity with the infinite.',
    go_deeper_teaser: 'The four mahavakyas: the Upanishads\' greatest declarations →',
  },
  {
    day_of_year: 281,
    original_script: 'तत् त्वम् असि',
    transliteration: 'Tat Tvam Asi',
    english_translation: 'That thou art — you are that infinite reality.',
    tradition: 'universal',
    intention: 'Non-Duality',
    phonetic_guide: 'taht tvahm AH-see',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The second mahavakya from the Chandogya Upanishad. The teacher\'s declaration to the student: you are not separate from the infinite.',
    go_deeper_teaser: 'Tat tvam asi: the teaching that changes everything →',
  },
  {
    day_of_year: 282,
    original_script: 'प्रज्ञानं ब्रह्म',
    transliteration: 'Prajnanam Brahma',
    english_translation: 'Consciousness is Brahman — awareness is the infinite.',
    tradition: 'universal',
    intention: 'Consciousness',
    phonetic_guide: 'PRAHJ-nyah-nahm BRAH-mah',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The third mahavakya from the Aitareya Upanishad. Prajna — "consciousness" or "awareness" — is identified with the infinite ground of being.',
    go_deeper_teaser: 'Consciousness as the ground of being →',
  },
  {
    day_of_year: 283,
    original_script: 'अयम् आत्मा ब्रह्म',
    transliteration: 'Ayam Atma Brahma',
    english_translation: 'This self is Brahman — the individual self is the universal self.',
    tradition: 'universal',
    intention: 'Unity',
    phonetic_guide: 'AH-yahm AHT-mah BRAH-mah',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The fourth mahavakya from the Mandukya Upanishad. The individual self (atman) is declared identical to the universal ground of being (brahman). The simplest and most direct of the four great sayings.',
    go_deeper_teaser: 'The four mahavakyas: the great declarations of non-duality →',
  },
];
