// Mantras Part 1: Days 1–91 — Vedic / Shaivite tradition
// Each entry: day_of_year, original_script, transliteration, english_translation,
//             tradition, intention, phonetic_guide, sacred_geometry_type, context_note, go_deeper_teaser

module.exports = [
  // ── VEDIC SHIVA (days 1–45) ──────────────────────────────────────────────
  {
    day_of_year: 1,
    original_script: 'ॐ नमः शिवाय',
    transliteration: 'Om Namah Shivaya',
    english_translation: 'I bow to Shiva — the auspicious one, the pure consciousness within all.',
    tradition: 'vedic_shiva',
    intention: 'Purification',
    phonetic_guide: 'OHM nah-MAH shih-VAH-yah',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'The Panchakshara mantra — five sacred syllables representing the five elements. The most widely chanted Shaivite mantra.',
    go_deeper_teaser: 'Why Om Namah Shivaya changes your nervous system →',
  },
  {
    day_of_year: 2,
    original_script: 'ॐ त्र्यम्बकं यजामहे',
    transliteration: 'Om Tryambakam Yajamahe',
    english_translation: 'We worship the three-eyed one who nourishes and liberates us from the bondage of death.',
    tradition: 'vedic_shiva',
    intention: 'Healing',
    phonetic_guide: 'OHM tree-AHM-bah-kahm yah-JAH-mah-hay',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'The Maha Mrityunjaya mantra from the Rigveda. Chanted for healing, longevity, and liberation from fear.',
    go_deeper_teaser: 'The science of the Maha Mrityunjaya mantra →',
  },
  {
    day_of_year: 3,
    original_script: 'ॐ नमः शिवाय शुभम् शुभम् करु',
    transliteration: 'Om Namah Shivaya Shubham Shubham Kuru',
    english_translation: 'Om, I bow to Shiva — bring auspiciousness, bring auspiciousness.',
    tradition: 'vedic_shiva',
    intention: 'Blessings',
    phonetic_guide: 'OHM nah-MAH shih-VAH-yah SHOO-bahm SHOO-bahm KOO-roo',
    sacred_geometry_type: 'lotus',
    context_note: 'An expanded form of the Panchakshara invoking blessings and positive energy into daily life.',
    go_deeper_teaser: 'Morning mantras that shift your entire day →',
  },
  {
    day_of_year: 4,
    original_script: 'शिवोऽहम् शिवोऽहम्',
    transliteration: 'Shivo\'ham Shivo\'ham',
    english_translation: 'I am Shiva. I am Shiva.',
    tradition: 'vedic_shiva',
    intention: 'Self-realization',
    phonetic_guide: 'shih-VOH-hahm shih-VOH-hahm',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'From Adi Shankaracharya\'s Nirvana Shatakam. A direct affirmation of identity with pure consciousness.',
    go_deeper_teaser: 'The Nirvana Shatakam: Shankara\'s greatest poem →',
  },
  {
    day_of_year: 5,
    original_script: 'ॐ हौं जूं सः',
    transliteration: 'Om Haum Jum Sah',
    english_translation: 'Om — the seed of Shiva — the seed of life — I am that.',
    tradition: 'vedic_shiva',
    intention: 'Vitality',
    phonetic_guide: 'OHM howm joom sah',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'The Maha Mrityunjaya bija mantra. Haum is the seed syllable of Shiva; Jum is the seed of life force.',
    go_deeper_teaser: 'Bija mantras: seeds of cosmic power →',
  },
  {
    day_of_year: 6,
    original_script: 'ॐ नमः शिवाय नमः',
    transliteration: 'Om Namah Shivaya Namah',
    english_translation: 'Om, I bow to Shiva, I bow.',
    tradition: 'vedic_shiva',
    intention: 'Devotion',
    phonetic_guide: 'OHM nah-MAH shih-VAH-yah nah-MAH',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'An extended form adding a second namah — deepening the gesture of surrender and reverence.',
    go_deeper_teaser: 'What surrender really means in spiritual practice →',
  },
  {
    day_of_year: 7,
    original_script: 'ॐ शं शिवाय नमः',
    transliteration: 'Om Sham Shivaya Namah',
    english_translation: 'Om, I bow to Shiva who brings peace and auspiciousness.',
    tradition: 'vedic_shiva',
    intention: 'Peace',
    phonetic_guide: 'OHM shahm shih-VAH-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Sham is the bija of peace and cooling. This mantra soothes the nervous system and calms mental agitation.',
    go_deeper_teaser: 'How mantra activates the parasympathetic nervous system →',
  },
  {
    day_of_year: 8,
    original_script: 'ॐ शिव शक्ति नमः',
    transliteration: 'Om Shiva Shakti Namah',
    english_translation: 'Om, I bow to the union of Shiva and Shakti — consciousness and energy.',
    tradition: 'vedic_shiva',
    intention: 'Balance',
    phonetic_guide: 'OHM SHIH-vah SHAHK-tee nah-MAH',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Shiva is pure awareness; Shakti is the dynamic energy of creation. Their union is the source of all existence.',
    go_deeper_teaser: 'The sacred marriage: Shiva and Shakti explained →',
  },
  {
    day_of_year: 9,
    original_script: 'ॐ महादेवाय नमः',
    transliteration: 'Om Mahadevaya Namah',
    english_translation: 'Om, I bow to the Great God — the supreme deity.',
    tradition: 'vedic_shiva',
    intention: 'Reverence',
    phonetic_guide: 'OHM mah-hah-DAY-vah-yah nah-MAH',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Mahadeva means "Great God" — one of Shiva\'s most exalted names, honoring his supremacy among the devas.',
    go_deeper_teaser: 'The 108 names of Shiva and their meanings →',
  },
  {
    day_of_year: 10,
    original_script: 'ॐ नीलकण्ठाय नमः',
    transliteration: 'Om Nilakanthaya Namah',
    english_translation: 'Om, I bow to the blue-throated one who swallowed poison to save the world.',
    tradition: 'vedic_shiva',
    intention: 'Courage',
    phonetic_guide: 'OHM nee-lah-KAHN-thah-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Nilakantha — "blue throat" — refers to Shiva holding the cosmic poison in his throat to protect all beings. A mantra of fearless compassion.',
    go_deeper_teaser: 'The churning of the ocean: Shiva\'s greatest sacrifice →',
  },
  {
    day_of_year: 11,
    original_script: 'ॐ नटराजाय नमः',
    transliteration: 'Om Natarajaya Namah',
    english_translation: 'Om, I bow to the Lord of the Cosmic Dance.',
    tradition: 'vedic_shiva',
    intention: 'Flow',
    phonetic_guide: 'OHM nah-tah-RAH-jah-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Nataraja — Shiva as the cosmic dancer — represents the continuous cycles of creation, preservation, and dissolution.',
    go_deeper_teaser: 'Nataraja: the physics of the cosmic dance →',
  },
  {
    day_of_year: 12,
    original_script: 'ॐ पशुपतये नमः',
    transliteration: 'Om Pashupataye Namah',
    english_translation: 'Om, I bow to the Lord of all creatures.',
    tradition: 'vedic_shiva',
    intention: 'Compassion',
    phonetic_guide: 'OHM pah-shoo-PAH-tah-yay nah-MAH',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Pashupati — "Lord of animals" — honors Shiva as the protector of all sentient beings, from the smallest creature to the greatest.',
    go_deeper_teaser: 'Shiva as the original animal protector →',
  },
  {
    day_of_year: 13,
    original_script: 'ॐ भवाय नमः',
    transliteration: 'Om Bhavaya Namah',
    english_translation: 'Om, I bow to the source of all existence.',
    tradition: 'vedic_shiva',
    intention: 'Gratitude',
    phonetic_guide: 'OHM bhah-VAH-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Bhava means "being" or "existence." This name honors Shiva as the ground of all being — the very fact that anything exists at all.',
    go_deeper_teaser: 'The miracle of existence: why being here matters →',
  },
  {
    day_of_year: 14,
    original_script: 'ॐ रुद्राय नमः',
    transliteration: 'Om Rudraya Namah',
    english_translation: 'Om, I bow to Rudra — the fierce one who removes suffering.',
    tradition: 'vedic_shiva',
    intention: 'Release',
    phonetic_guide: 'OHM ROOD-rah-yah nah-MAH',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Rudra is Shiva\'s Vedic form — the howling storm god who destroys what no longer serves. Chanting this releases stuck energy.',
    go_deeper_teaser: 'Rudra: the sacred power of divine anger →',
  },
  {
    day_of_year: 15,
    original_script: 'ॐ शंकराय नमः',
    transliteration: 'Om Shankaraya Namah',
    english_translation: 'Om, I bow to the one who brings blessings and auspiciousness.',
    tradition: 'vedic_shiva',
    intention: 'Blessings',
    phonetic_guide: 'OHM shahn-KAH-rah-yah nah-MAH',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Shankara — "conferring happiness" — is one of Shiva\'s most beloved names. This mantra opens the heart to receive grace.',
    go_deeper_teaser: 'Opening to grace: the practice of receptivity →',
  },
  {
    day_of_year: 16,
    original_script: 'ॐ गिरीशाय नमः',
    transliteration: 'Om Girishaya Namah',
    english_translation: 'Om, I bow to the Lord of the mountains.',
    tradition: 'vedic_shiva',
    intention: 'Stability',
    phonetic_guide: 'OHM gih-REE-shah-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Girisha — "mountain lord" — honors Shiva\'s home on Mount Kailash. Mountains represent the immovable foundation of consciousness.',
    go_deeper_teaser: 'Mount Kailash: the axis of the world →',
  },
  {
    day_of_year: 17,
    original_script: 'ॐ भोलेनाथाय नमः',
    transliteration: 'Om Bholenathaya Namah',
    english_translation: 'Om, I bow to the innocent lord — the simple-hearted one.',
    tradition: 'vedic_shiva',
    intention: 'Simplicity',
    phonetic_guide: 'OHM boh-lay-NAH-thah-yah nah-MAH',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Bholenath — "innocent lord" — is a beloved folk name for Shiva. He is easily pleased by sincere devotion, however simple.',
    go_deeper_teaser: 'Why Shiva is the easiest god to please →',
  },
  {
    day_of_year: 18,
    original_script: 'ॐ विश्वनाथाय नमः',
    transliteration: 'Om Vishwanathaya Namah',
    english_translation: 'Om, I bow to the Lord of the universe.',
    tradition: 'vedic_shiva',
    intention: 'Expansion',
    phonetic_guide: 'OHM vish-wah-NAH-thah-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Vishwanath — "Lord of all worlds" — is the presiding deity of Varanasi, the oldest living city on earth.',
    go_deeper_teaser: 'Varanasi: the city where Shiva never sleeps →',
  },
  {
    day_of_year: 19,
    original_script: 'ॐ आशुतोषाय नमः',
    transliteration: 'Om Ashutoshaya Namah',
    english_translation: 'Om, I bow to the one who is quickly satisfied.',
    tradition: 'vedic_shiva',
    intention: 'Contentment',
    phonetic_guide: 'OHM ah-shoo-TOH-shah-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Ashutosh — "quickly pleased" — teaches that Shiva asks for nothing more than sincere love. Contentment is the highest offering.',
    go_deeper_teaser: 'The art of contentment: Santosha in daily life →',
  },
  {
    day_of_year: 20,
    original_script: 'ॐ त्रिलोचनाय नमः',
    transliteration: 'Om Trilochanaya Namah',
    english_translation: 'Om, I bow to the three-eyed one who sees past, present, and future.',
    tradition: 'vedic_shiva',
    intention: 'Clarity',
    phonetic_guide: 'OHM tree-loh-CHAH-nah-yah nah-MAH',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Shiva\'s third eye represents the eye of wisdom — the ability to see beyond duality into the nature of reality.',
    go_deeper_teaser: 'Activating your third eye through mantra →',
  },
  {
    day_of_year: 21,
    original_script: 'ॐ सदाशिवाय नमः',
    transliteration: 'Om Sadashivaya Namah',
    english_translation: 'Om, I bow to the eternally auspicious one.',
    tradition: 'vedic_shiva',
    intention: 'Eternity',
    phonetic_guide: 'OHM sah-dah-SHIH-vah-yah nah-MAH',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Sadashiva — "always auspicious" — represents the eternal, unchanging aspect of Shiva beyond time and space.',
    go_deeper_teaser: 'What it means to touch the eternal →',
  },
  {
    day_of_year: 22,
    original_script: 'ॐ उमापतये नमः',
    transliteration: 'Om Umapataye Namah',
    english_translation: 'Om, I bow to the consort of Uma — the divine feminine.',
    tradition: 'vedic_shiva',
    intention: 'Love',
    phonetic_guide: 'OHM oo-mah-PAH-tah-yay nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Uma (Parvati) is Shiva\'s beloved. This mantra honors the sacred partnership of masculine and feminine principles.',
    go_deeper_teaser: 'Shiva and Parvati: the original love story →',
  },
  {
    day_of_year: 23,
    original_script: 'ॐ कपर्दिने नमः',
    transliteration: 'Om Kapardine Namah',
    english_translation: 'Om, I bow to the matted-haired one who holds the Ganges.',
    tradition: 'vedic_shiva',
    intention: 'Purification',
    phonetic_guide: 'OHM kah-pahr-DEE-nay nah-MAH',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Shiva\'s matted hair (jata) holds the sacred river Ganga, purifying all who touch her waters.',
    go_deeper_teaser: 'The Ganga in Shiva\'s hair: a story of grace →',
  },
  {
    day_of_year: 24,
    original_script: 'ॐ भस्माङ्गाय नमः',
    transliteration: 'Om Bhasmangaya Namah',
    english_translation: 'Om, I bow to the one adorned with sacred ash.',
    tradition: 'vedic_shiva',
    intention: 'Impermanence',
    phonetic_guide: 'OHM bahsh-MAHN-gah-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Shiva smears himself with ash from cremation grounds — a reminder that all bodies return to ash. This mantra cultivates non-attachment.',
    go_deeper_teaser: 'Sacred ash and the wisdom of impermanence →',
  },
  {
    day_of_year: 25,
    original_script: 'ॐ गङ्गाधराय नमः',
    transliteration: 'Om Gangadharaya Namah',
    english_translation: 'Om, I bow to the one who holds the sacred Ganga in his locks.',
    tradition: 'vedic_shiva',
    intention: 'Grace',
    phonetic_guide: 'OHM gahn-gah-DHAH-rah-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'When the heavenly Ganga descended to earth, Shiva caught her in his hair to prevent the earth from being destroyed by her force.',
    go_deeper_teaser: 'How Shiva saved the earth with his hair →',
  },
  {
    day_of_year: 26,
    original_script: 'ॐ जटाधराय नमः',
    transliteration: 'Om Jatadharaya Namah',
    english_translation: 'Om, I bow to the one with matted locks of an ascetic.',
    tradition: 'vedic_shiva',
    intention: 'Renunciation',
    phonetic_guide: 'OHM jah-tah-DHAH-rah-yah nah-MAH',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'The matted hair (jata) represents the renunciation of worldly vanity and the accumulation of tapas — spiritual heat.',
    go_deeper_teaser: 'Tapas: the sacred fire of spiritual discipline →',
  },
  {
    day_of_year: 27,
    original_script: 'ॐ कालेश्वराय नमः',
    transliteration: 'Om Kaleshwaraya Namah',
    english_translation: 'Om, I bow to the Lord of time who transcends all time.',
    tradition: 'vedic_shiva',
    intention: 'Presence',
    phonetic_guide: 'OHM kah-laysh-WAH-rah-yah nah-MAH',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Kaleshwara — "Lord of time" — reminds us that Shiva is both the master of time and beyond it. This mantra anchors us in the eternal now.',
    go_deeper_teaser: 'Living in the eternal now: Shiva\'s greatest teaching →',
  },
  {
    day_of_year: 28,
    original_script: 'ॐ ईशानाय नमः',
    transliteration: 'Om Ishanaya Namah',
    english_translation: 'Om, I bow to the ruler of the northeast — the direction of grace.',
    tradition: 'vedic_shiva',
    intention: 'Wisdom',
    phonetic_guide: 'OHM ee-SHAH-nah-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Ishana is Shiva\'s form ruling the northeast direction — associated with wisdom, grace, and the transmission of spiritual knowledge.',
    go_deeper_teaser: 'The five faces of Shiva: Panchamukha explained →',
  },
  {
    day_of_year: 29,
    original_script: 'ॐ तत्पुरुषाय नमः',
    transliteration: 'Om Tatpurushaya Namah',
    english_translation: 'Om, I bow to the supreme being — the highest self.',
    tradition: 'vedic_shiva',
    intention: 'Self-realization',
    phonetic_guide: 'OHM taht-poo-ROO-shah-yah nah-MAH',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Tatpurusha — "that supreme person" — is the east-facing form of Shiva, representing the transcendent self beyond ego.',
    go_deeper_teaser: 'Tat tvam asi: you are that →',
  },
  {
    day_of_year: 30,
    original_script: 'ॐ अघोराय नमः',
    transliteration: 'Om Aghoraya Namah',
    english_translation: 'Om, I bow to the non-terrible one — the gentle face of Shiva.',
    tradition: 'vedic_shiva',
    intention: 'Acceptance',
    phonetic_guide: 'OHM ah-GHOH-rah-yah nah-MAH',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Aghora — "not terrible" — is the south-facing form of Shiva, representing the dissolution of ego and acceptance of all aspects of existence.',
    go_deeper_teaser: 'The Aghori path: embracing what we fear →',
  },
  {
    day_of_year: 31,
    original_script: 'ॐ वामदेवाय नमः',
    transliteration: 'Om Vamadevaya Namah',
    english_translation: 'Om, I bow to the beautiful god — the graceful one.',
    tradition: 'vedic_shiva',
    intention: 'Beauty',
    phonetic_guide: 'OHM vah-mah-DAY-vah-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Vamadeva — "beautiful god" — is the north-facing form of Shiva, representing the creative, nurturing, and beautiful aspects of consciousness.',
    go_deeper_teaser: 'Beauty as a spiritual path →',
  },
  {
    day_of_year: 32,
    original_script: 'ॐ सद्योजाताय नमः',
    transliteration: 'Om Sadyojataya Namah',
    english_translation: 'Om, I bow to the instantly born — the creative impulse of consciousness.',
    tradition: 'vedic_shiva',
    intention: 'Creativity',
    phonetic_guide: 'OHM sahd-yoh-JAH-tah-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Sadyojata — "instantly born" — is the west-facing form of Shiva, representing the spontaneous creative power of consciousness.',
    go_deeper_teaser: 'Spontaneous creation: how inspiration really works →',
  },
  {
    day_of_year: 33,
    original_script: 'ॐ हरहर महादेव',
    transliteration: 'Om Hara Hara Mahadeva',
    english_translation: 'Om, remove, remove — O Great God, take away all that binds me.',
    tradition: 'vedic_shiva',
    intention: 'Liberation',
    phonetic_guide: 'OHM HAH-rah HAH-rah mah-hah-DAY-vah',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Hara means "one who removes" — Shiva removes sin, suffering, and the illusion of separation. A powerful mantra of liberation.',
    go_deeper_teaser: 'What Shiva removes and why you should let him →',
  },
  {
    day_of_year: 34,
    original_script: 'ॐ शिव शम्भो',
    transliteration: 'Om Shiva Shambho',
    english_translation: 'Om, Shiva — the self-luminous, the source of joy.',
    tradition: 'vedic_shiva',
    intention: 'Joy',
    phonetic_guide: 'OHM SHIH-vah SHAHM-boh',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Shambhu — "self-luminous" or "source of happiness" — is one of Shiva\'s most joyful names. This mantra invokes pure bliss.',
    go_deeper_teaser: 'Ananda: the bliss that is your true nature →',
  },
  {
    day_of_year: 35,
    original_script: 'ॐ नमः शिवाय गुरवे',
    transliteration: 'Om Namah Shivaya Gurave',
    english_translation: 'Om, I bow to Shiva who is the teacher within.',
    tradition: 'vedic_shiva',
    intention: 'Learning',
    phonetic_guide: 'OHM nah-MAH shih-VAH-yah goo-RAH-vay',
    sacred_geometry_type: 'lotus',
    context_note: 'The guru mantra of the Shaiva Siddhanta tradition. Shiva is the first guru — the inner teacher who guides all seekers.',
    go_deeper_teaser: 'The inner guru: how Shiva teaches from within →',
  },
  {
    day_of_year: 36,
    original_script: 'ॐ शिवाय गुरवे नमः',
    transliteration: 'Om Shivaya Gurave Namah',
    english_translation: 'Om, I bow to Shiva the teacher.',
    tradition: 'vedic_shiva',
    intention: 'Humility',
    phonetic_guide: 'OHM shih-VAH-yah goo-RAH-vay nah-MAH',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'The opening mantra of the Shiva Sutras tradition. Humility before the teacher opens the door to genuine wisdom.',
    go_deeper_teaser: 'The Shiva Sutras: Kashmir Shaivism\'s greatest text →',
  },
  {
    day_of_year: 37,
    original_script: 'ॐ शिवाय नमः शान्तिः',
    transliteration: 'Om Shivaya Namah Shantih',
    english_translation: 'Om, I bow to Shiva — peace, peace, peace.',
    tradition: 'vedic_shiva',
    intention: 'Peace',
    phonetic_guide: 'OHM shih-VAH-yah nah-MAH SHAHN-tih',
    sacred_geometry_type: 'lotus',
    context_note: 'The triple shanti at the end of Vedic recitations removes the three types of suffering: physical, mental, and cosmic.',
    go_deeper_teaser: 'The three types of suffering and how to end them →',
  },
  {
    day_of_year: 38,
    original_script: 'ॐ नमः शिवाय स्वाहा',
    transliteration: 'Om Namah Shivaya Svaha',
    english_translation: 'Om, I bow to Shiva — I offer this into the sacred fire.',
    tradition: 'vedic_shiva',
    intention: 'Offering',
    phonetic_guide: 'OHM nah-MAH shih-VAH-yah svah-HAH',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Svaha is the offering call of fire rituals. Adding it transforms any mantra into a complete act of surrender and offering.',
    go_deeper_teaser: 'Homa: the ancient practice of fire offering →',
  },
  {
    day_of_year: 39,
    original_script: 'ॐ शिव ॐ शिव ॐ शिव',
    transliteration: 'Om Shiva Om Shiva Om Shiva',
    english_translation: 'Om Shiva, Om Shiva, Om Shiva — pure consciousness, again and again.',
    tradition: 'vedic_shiva',
    intention: 'Absorption',
    phonetic_guide: 'OHM SHIH-vah OHM SHIH-vah OHM SHIH-vah',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Repetition of the divine name is itself the practice. Three repetitions honor the trimurti and the three states of consciousness.',
    go_deeper_teaser: 'The power of divine name repetition →',
  },
  {
    day_of_year: 40,
    original_script: 'ॐ नमः शिवाय शिवाय नमः ॐ',
    transliteration: 'Om Namah Shivaya Shivaya Namah Om',
    english_translation: 'Om, I bow to Shiva, to Shiva I bow, Om.',
    tradition: 'vedic_shiva',
    intention: 'Devotion',
    phonetic_guide: 'OHM nah-MAH shih-VAH-yah shih-VAH-yah nah-MAH OHM',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'A palindromic mantra — it reads the same forward and backward, representing the non-dual nature of Shiva consciousness.',
    go_deeper_teaser: 'Non-duality: the teaching that changes everything →',
  },
  {
    day_of_year: 41,
    original_script: 'ॐ शिवाय विद्महे',
    transliteration: 'Om Shivaya Vidmahe',
    english_translation: 'Om, may we know Shiva.',
    tradition: 'vedic_shiva',
    intention: 'Knowledge',
    phonetic_guide: 'OHM shih-VAH-yah vid-MAH-hay',
    sacred_geometry_type: 'lotus',
    context_note: 'The first line of the Shiva Gayatri — a request for direct knowledge of the divine, not merely belief or concept.',
    go_deeper_teaser: 'Direct knowing vs. belief: the Vedantic distinction →',
  },
  {
    day_of_year: 42,
    original_script: 'ॐ शिवाय विद्महे महादेवाय धीमहि',
    transliteration: 'Om Shivaya Vidmahe Mahadevaya Dhimahi',
    english_translation: 'Om, may we know Shiva, may we meditate on the Great God.',
    tradition: 'vedic_shiva',
    intention: 'Meditation',
    phonetic_guide: 'OHM shih-VAH-yah vid-MAH-hay mah-hah-DAY-vah-yah dhee-MAH-hee',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The Shiva Gayatri — a request for illumination through meditation on Shiva\'s supreme nature.',
    go_deeper_teaser: 'The Gayatri structure: the most powerful mantra form →',
  },
  {
    day_of_year: 43,
    original_script: 'तन्नो रुद्रः प्रचोदयात्',
    transliteration: 'Tanno Rudrah Prachodayat',
    english_translation: 'May Rudra illuminate and inspire us.',
    tradition: 'vedic_shiva',
    intention: 'Inspiration',
    phonetic_guide: 'tahn-NOH ROOD-rah prah-choh-DAH-yaht',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'The concluding line of the Rudra Gayatri. Prachodayat — "may he inspire" — is the same word used in the Gayatri Mantra.',
    go_deeper_teaser: 'Prachodayat: the prayer for divine inspiration →',
  },
  {
    day_of_year: 44,
    original_script: 'ॐ शिव तत्त्वम् अहम्',
    transliteration: 'Om Shiva Tattvam Aham',
    english_translation: 'Om, I am the principle of Shiva — pure consciousness.',
    tradition: 'vedic_shiva',
    intention: 'Self-realization',
    phonetic_guide: 'OHM SHIH-vah TAHT-tvahm AH-hahm',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'A mahavakya-style affirmation from Kashmir Shaivism. Tattva means "that-ness" or essential principle. You are not separate from Shiva.',
    go_deeper_teaser: 'The mahavakyas: four great sayings of the Upanishads →',
  },
  {
    day_of_year: 45,
    original_script: 'ॐ नमः शिवाय नित्यम्',
    transliteration: 'Om Namah Shivaya Nityam',
    english_translation: 'Om, I bow to Shiva eternally — always and forever.',
    tradition: 'vedic_shiva',
    intention: 'Commitment',
    phonetic_guide: 'OHM nah-MAH shih-VAH-yah NEET-yahm',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Nityam means "eternally" or "always." Adding this word transforms the mantra into a vow of perpetual devotion.',
    go_deeper_teaser: 'Making a spiritual vow: the power of commitment →',
  },
];
