// Minute Mantra — Part 2 of 4
// Days 92-182
// Auto-generated from mantras.json

module.exports = [
  {
    day_of_year: 92,
    original_script: 'ॐ दुर्गायै नमः',
    transliteration: 'Om Durgayai Namah',
    english_translation: 'Om, I bow to Durga — the invincible one who protects.',
    tradition: 'vedic_shakti',
    intention: 'Protection',
    phonetic_guide: 'OHM door-GAH-yay nah-MAH',
    context_note: 'Durga — "the invincible" or "the one who is difficult to approach" — is the warrior goddess who defeats all forms of evil and ignorance.',
    audio_filename: 'mantra-092.mp3',
    go_deeper_teaser: 'Durga\'s nine forms: the Navadurga →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 93,
    original_script: 'ॐ काल्यै नमः',
    transliteration: 'Om Kalyai Namah',
    english_translation: 'Om, I bow to Kali — the dark mother who liberates through transformation.',
    tradition: 'vedic_shakti',
    intention: 'Transformation',
    phonetic_guide: 'OHM KAH-lyay nah-MAH',
    context_note: 'Kali — "the dark one" or "time" — is the most powerful form of Shakti. She destroys ego and illusion to reveal the eternal self beneath.',
    audio_filename: 'mantra-093.mp3',
    go_deeper_teaser: 'Kali: the goddess who loves you enough to destroy your ego →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 94,
    original_script: 'ॐ श्रीं ह्रीं श्रीं',
    transliteration: 'Om Shrim Hrim Shrim',
    english_translation: 'Om — Lakshmi\'s seed — the heart — Lakshmi\'s seed again.',
    tradition: 'vedic_shakti',
    intention: 'Abundance',
    phonetic_guide: 'OHM shreem hreem shreem',
    context_note: 'Shrim is Lakshmi\'s bija — the seed of abundance, beauty, and grace. Hrim is the heart bija. Together they open the heart to receive.',
    audio_filename: 'mantra-094.mp3',
    go_deeper_teaser: 'Lakshmi\'s eight forms: the Ashtalakshmi →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 95,
    original_script: 'ॐ ऐं सरस्वत्यै नमः',
    transliteration: 'Om Aim Saraswatyai Namah',
    english_translation: 'Om, with the seed of wisdom, I bow to Saraswati.',
    tradition: 'vedic_shakti',
    intention: 'Wisdom',
    phonetic_guide: 'OHM AIM sah-rahs-WAHT-yay nah-MAH',
    context_note: 'Saraswati — "the flowing one" — is the goddess of wisdom, learning, music, and the arts. Aim is her bija, activating the intellect.',
    audio_filename: 'mantra-095.mp3',
    go_deeper_teaser: 'Saraswati\'s four arms: the tools of wisdom →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 96,
    original_script: 'ॐ श्रीं महालक्ष्म्यै नमः',
    transliteration: 'Om Shrim Mahalakshmyai Namah',
    english_translation: 'Om, I bow to the great Lakshmi — the goddess of all abundance.',
    tradition: 'vedic_shakti',
    intention: 'Prosperity',
    phonetic_guide: 'OHM shreem mah-hah-LAHK-shmyay nah-MAH',
    context_note: 'Mahalakshmi — "great Lakshmi" — is the supreme form of the goddess of abundance, encompassing all eight forms of wealth.',
    audio_filename: 'mantra-096.mp3',
    go_deeper_teaser: 'The eight forms of Lakshmi and what they offer →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 97,
    original_script: 'ॐ क्लीं काल्यै नमः',
    transliteration: 'Om Klim Kalyai Namah',
    english_translation: 'Om, with the seed of transformation, I bow to Kali.',
    tradition: 'vedic_shakti',
    intention: 'Release',
    phonetic_guide: 'OHM kleem KAH-lyay nah-MAH',
    context_note: 'Klim is the bija of attraction and transformation. Combined with Kali\'s name, it invokes the power to release what no longer serves.',
    audio_filename: 'mantra-097.mp3',
    go_deeper_teaser: 'What Kali wants you to release →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 98,
    original_script: 'ॐ चण्डिकायै नमः',
    transliteration: 'Om Chandikayai Namah',
    english_translation: 'Om, I bow to Chandika — the fierce, passionate one.',
    tradition: 'vedic_shakti',
    intention: 'Passion',
    phonetic_guide: 'OHM chahn-dee-KAH-yay nah-MAH',
    context_note: 'Chandika is the fierce form of Durga from the Devi Mahatmya. She embodies the passionate, unstoppable force of the divine feminine.',
    audio_filename: 'mantra-098.mp3',
    go_deeper_teaser: 'The Devi Mahatmya: the goddess\'s greatest battle →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 99,
    original_script: 'ॐ त्रिपुरसुन्दर्यै नमः',
    transliteration: 'Om Tripurasundaryai Namah',
    english_translation: 'Om, I bow to Tripurasundari — the beauty of the three worlds.',
    tradition: 'vedic_shakti',
    intention: 'Beauty',
    phonetic_guide: 'OHM tree-poo-rah-soon-DAH-ryay nah-MAH',
    context_note: 'Tripurasundari — "beautiful in the three worlds" — is the supreme goddess of the Sri Vidya tradition, presiding over the Sri Yantra.',
    audio_filename: 'mantra-099.mp3',
    go_deeper_teaser: 'Sri Vidya: the highest Shakta tradition →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 100,
    original_script: 'ॐ भुवनेश्वर्यै नमः',
    transliteration: 'Om Bhuvaneshwaryai Namah',
    english_translation: 'Om, I bow to Bhuvaneshwari — the queen of the universe.',
    tradition: 'vedic_shakti',
    intention: 'Sovereignty',
    phonetic_guide: 'OHM bhoo-vah-naysh-WAH-ryay nah-MAH',
    context_note: 'Bhuvaneshwari — "queen of the universe" — is the fourth of the ten Mahavidyas, representing the vast space of consciousness.',
    audio_filename: 'mantra-100.mp3',
    go_deeper_teaser: 'The ten Mahavidyas: the wisdom goddesses →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 101,
    original_script: 'ॐ भैरव्यै नमः',
    transliteration: 'Om Bhairavyai Namah',
    english_translation: 'Om, I bow to Bhairavi — the fierce, terrifying goddess of liberation.',
    tradition: 'vedic_shakti',
    intention: 'Fearlessness',
    phonetic_guide: 'OHM bhay-RAH-vyay nah-MAH',
    context_note: 'Bhairavi — "the terrifying one" — is the fifth Mahavidya. Her terror is only for the ego; to the true self, she is pure love.',
    audio_filename: 'mantra-101.mp3',
    go_deeper_teaser: 'What we fear and why the goddess is not it →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 102,
    original_script: 'ॐ छिन्नमस्तायै नमः',
    transliteration: 'Om Chhinnamastayai Namah',
    english_translation: 'Om, I bow to Chhinnamasta — the self-decapitated goddess of sacrifice.',
    tradition: 'vedic_shakti',
    intention: 'Sacrifice',
    phonetic_guide: 'OHM chhin-nah-MAHS-tah-yay nah-MAH',
    context_note: 'Chhinnamasta holds her own severed head, feeding her devotees with her blood. She teaches that the highest love is total self-giving.',
    audio_filename: 'mantra-102.mp3',
    go_deeper_teaser: 'The mystery of Chhinnamasta: love beyond the ego →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 103,
    original_script: 'ॐ धूमावत्यै नमः',
    transliteration: 'Om Dhumavatyai Namah',
    english_translation: 'Om, I bow to Dhumavati — the smoky widow goddess of dissolution.',
    tradition: 'vedic_shakti',
    intention: 'Acceptance',
    phonetic_guide: 'OHM dhoo-mah-VAH-tyay nah-MAH',
    context_note: 'Dhumavati — "the smoky one" — represents the void after dissolution. She teaches acceptance of loss, old age, and the wisdom of emptiness.',
    audio_filename: 'mantra-103.mp3',
    go_deeper_teaser: 'The wisdom of emptiness: Dhumavati\'s gift →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 104,
    original_script: 'ॐ बगलामुख्यै नमः',
    transliteration: 'Om Bagalamukhai Namah',
    english_translation: 'Om, I bow to Bagalamukhi — the crane-faced goddess who paralyzes enemies.',
    tradition: 'vedic_shakti',
    intention: 'Power',
    phonetic_guide: 'OHM bah-gah-lah-MOOK-hyay nah-MAH',
    context_note: 'Bagalamukhi — "crane-faced" — is the eighth Mahavidya who paralyzes negative forces. She stills the tongue of slander and the mind of confusion.',
    audio_filename: 'mantra-104.mp3',
    go_deeper_teaser: 'Bagalamukhi: the goddess who silences enemies →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 105,
    original_script: 'ॐ मातङ्ग्यै नमः',
    transliteration: 'Om Matangyai Namah',
    english_translation: 'Om, I bow to Matangi — the outcast goddess of inner wisdom.',
    tradition: 'vedic_shakti',
    intention: 'Authenticity',
    phonetic_guide: 'OHM mah-TAHN-gyay nah-MAH',
    context_note: 'Matangi — the "outcast" or "elephant" goddess — is the ninth Mahavidya, representing wisdom that comes from outside conventional boundaries.',
    audio_filename: 'mantra-105.mp3',
    go_deeper_teaser: 'Matangi: the wisdom of the outcast →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 106,
    original_script: 'ॐ कमलायै नमः',
    transliteration: 'Om Kamalayai Namah',
    english_translation: 'Om, I bow to Kamala — the lotus goddess, the tantric Lakshmi.',
    tradition: 'vedic_shakti',
    intention: 'Grace',
    phonetic_guide: 'OHM kah-mah-LAH-yay nah-MAH',
    context_note: 'Kamala — "lotus" — is the tenth Mahavidya, the tantric form of Lakshmi. She represents the fullness of grace and the beauty of pure consciousness.',
    audio_filename: 'mantra-106.mp3',
    go_deeper_teaser: 'The ten Mahavidyas: a complete map of divine feminine power →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 107,
    original_script: 'ॐ तारायै नमः',
    transliteration: 'Om Tarayai Namah',
    english_translation: 'Om, I bow to Tara — the star goddess who guides across the ocean of existence.',
    tradition: 'vedic_shakti',
    intention: 'Guidance',
    phonetic_guide: 'OHM TAH-rah-yay nah-MAH',
    context_note: 'Tara — "star" or "one who saves" — is the second Mahavidya and also a major Buddhist deity. She guides souls across the ocean of samsara.',
    audio_filename: 'mantra-107.mp3',
    go_deeper_teaser: 'Tara: the goddess shared by Hinduism and Buddhism →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 108,
    original_script: 'ॐ ऐं ह्रीं श्रीं त्रिपुर सुन्दरी',
    transliteration: 'Om Aim Hrim Shrim Tripura Sundari',
    english_translation: 'Om — wisdom, heart, abundance — beauty of the three worlds.',
    tradition: 'vedic_shakti',
    intention: 'Completeness',
    phonetic_guide: 'OHM AIM hreem shreem tree-POO-rah soon-DAH-ree',
    context_note: 'Day 108 — the sacred number of the mala. This mantra combines the three great bija mantras with the supreme goddess of the Sri Yantra.',
    audio_filename: 'mantra-108.mp3',
    go_deeper_teaser: 'Why 108 is the most sacred number →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 109,
    original_script: 'ॐ नमो देव्यै महादेव्यै',
    transliteration: 'Om Namo Devyai Mahadevyai',
    english_translation: 'Om, I bow to the goddess, the great goddess.',
    tradition: 'vedic_shakti',
    intention: 'Reverence',
    phonetic_guide: 'OHM nah-MOH DAY-vyay mah-hah-DAY-vyay',
    context_note: 'The opening invocation of the Devi Mahatmya — the most sacred text of the Shakta tradition, celebrating the goddess\'s cosmic victory.',
    audio_filename: 'mantra-109.mp3',
    go_deeper_teaser: 'The Devi Mahatmya: 700 verses of goddess power →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 110,
    original_script: 'या देवी सर्वभूतेषु',
    transliteration: 'Ya Devi Sarvabhuteshu',
    english_translation: 'The goddess who dwells in all beings...',
    tradition: 'vedic_shakti',
    intention: 'Omnipresence',
    phonetic_guide: 'yah DAY-vee sahr-vah-BHOO-tay-shoo',
    context_note: 'From the Devi Mahatmya. The full verse continues: "...in the form of consciousness, power, peace, faith, beauty, activity, memory, compassion, and error — I bow to her."',
    audio_filename: 'mantra-110.mp3',
    go_deeper_teaser: 'The goddess in all forms: the Devi Mahatmya\'s teaching →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 111,
    original_script: 'नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः',
    transliteration: 'Namastasyai Namastasyai Namastasyai Namo Namah',
    english_translation: 'I bow to her, I bow to her, I bow to her, I bow.',
    tradition: 'vedic_shakti',
    intention: 'Surrender',
    phonetic_guide: 'nah-mahs-TAHS-yay nah-mahs-TAHS-yay nah-mahs-TAHS-yay nah-MOH nah-MAH',
    context_note: 'The refrain of the Devi Mahatmya. Triple repetition of surrender to the goddess — a complete act of devotion.',
    audio_filename: 'mantra-111.mp3',
    go_deeper_teaser: 'The power of triple repetition in mantra →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 112,
    original_script: 'ॐ शक्ति शक्ति शक्ति',
    transliteration: 'Om Shakti Shakti Shakti',
    english_translation: 'Om, power, power, power — the divine feminine energy.',
    tradition: 'vedic_shakti',
    intention: 'Power',
    phonetic_guide: 'OHM SHAHK-tee SHAHK-tee SHAHK-tee',
    context_note: 'Shakti is the primordial energy of the universe — the force that animates all of creation. This mantra awakens your own inner Shakti.',
    audio_filename: 'mantra-112.mp3',
    go_deeper_teaser: 'Kundalini Shakti: the sleeping serpent power →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 113,
    original_script: 'ॐ जय माँ',
    transliteration: 'Om Jai Maa',
    english_translation: 'Om, victory to the Divine Mother.',
    tradition: 'vedic_shakti',
    intention: 'Devotion',
    phonetic_guide: 'OHM jay MAH',
    context_note: 'The simplest and most heartfelt invocation of the Divine Mother. Maa — "mother" — is the most intimate name for the goddess.',
    audio_filename: 'mantra-113.mp3',
    go_deeper_teaser: 'The Divine Mother: the most intimate face of God →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 114,
    original_script: 'ॐ गं गणपतये नमः',
    transliteration: 'Om Gam Ganapataye Namah',
    english_translation: 'Om, with the seed of Ganesha, I bow to the lord of all beginnings.',
    tradition: 'vedic_ganesha',
    intention: 'New Beginnings',
    phonetic_guide: 'OHM gahm gah-nah-PAH-tah-yay nah-MAH',
    context_note: 'Gam is Ganesha\'s bija mantra. Ganapati — "lord of the ganas" — is invoked at the beginning of every undertaking to remove obstacles.',
    audio_filename: 'mantra-114.mp3',
    go_deeper_teaser: 'Why Ganesha is invoked first in every ritual →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 115,
    original_script: 'ॐ नमो गणेशाय',
    transliteration: 'Om Namo Ganeshaya',
    english_translation: 'Om, I bow to Ganesha — the lord of hosts.',
    tradition: 'vedic_ganesha',
    intention: 'Beginnings',
    phonetic_guide: 'OHM nah-MOH gah-NAY-shah-yah',
    context_note: 'Ganesha — "lord of the ganas" — is the remover of obstacles and the bestower of wisdom. He is invoked before all sacred activities.',
    audio_filename: 'mantra-115.mp3',
    go_deeper_teaser: 'Ganesha\'s elephant head: the wisdom of the big picture →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 116,
    original_script: 'ॐ विघ्नराजाय नमः',
    transliteration: 'Om Vighnarajaya Namah',
    english_translation: 'Om, I bow to the king of obstacles — who removes all impediments.',
    tradition: 'vedic_ganesha',
    intention: 'Obstacle Removal',
    phonetic_guide: 'OHM vig-nah-RAH-jah-yah nah-MAH',
    context_note: 'Vighnaraja — "king of obstacles" — is Ganesha\'s paradoxical title. He both creates and removes obstacles, teaching that challenges are divine gifts.',
    audio_filename: 'mantra-116.mp3',
    go_deeper_teaser: 'Why Ganesha creates obstacles before removing them →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 117,
    original_script: 'ॐ एकदन्ताय नमः',
    transliteration: 'Om Ekadantaya Namah',
    english_translation: 'Om, I bow to the single-tusked one — the one who focuses on the essential.',
    tradition: 'vedic_ganesha',
    intention: 'Focus',
    phonetic_guide: 'OHM ay-kah-DAHN-tah-yah nah-MAH',
    context_note: 'Ekadanta — "single tusk" — refers to Ganesha breaking off one tusk to write the Mahabharata. He teaches us to sacrifice the non-essential for the essential.',
    audio_filename: 'mantra-117.mp3',
    go_deeper_teaser: 'Why Ganesha broke his tusk to write the Mahabharata →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 118,
    original_script: 'ॐ लम्बोदराय नमः',
    transliteration: 'Om Lambodaraya Namah',
    english_translation: 'Om, I bow to the large-bellied one who contains all universes.',
    tradition: 'vedic_ganesha',
    intention: 'Abundance',
    phonetic_guide: 'OHM lahm-boh-DAH-rah-yah nah-MAH',
    context_note: 'Lambodara — "large belly" — represents Ganesha\'s capacity to contain all of existence. His belly holds the entire cosmos.',
    audio_filename: 'mantra-118.mp3',
    go_deeper_teaser: 'Ganesha\'s belly: the universe within →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 119,
    original_script: 'ॐ विनायकाय नमः',
    transliteration: 'Om Vinayakaya Namah',
    english_translation: 'Om, I bow to Vinayaka — the supreme leader who guides without being led.',
    tradition: 'vedic_ganesha',
    intention: 'Leadership',
    phonetic_guide: 'OHM vih-nah-YAH-kah-yah nah-MAH',
    context_note: 'Vinayaka — "supreme leader" or "one who has no master" — is Ganesha\'s most common name in South India.',
    audio_filename: 'mantra-119.mp3',
    go_deeper_teaser: 'True leadership: the Vinayaka principle →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 120,
    original_script: 'ॐ गजाननाय नमः',
    transliteration: 'Om Gajananaya Namah',
    english_translation: 'Om, I bow to the elephant-faced one.',
    tradition: 'vedic_ganesha',
    intention: 'Wisdom',
    phonetic_guide: 'OHM gah-jah-NAH-nah-yah nah-MAH',
    context_note: 'Gajanana — "elephant-faced" — honors Ganesha\'s elephant head, which represents wisdom, memory, and the ability to remove obstacles with gentle power.',
    audio_filename: 'mantra-120.mp3',
    go_deeper_teaser: 'The elephant\'s wisdom: what Ganesha\'s head teaches →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 121,
    original_script: 'ॐ गणाधिपाय नमः',
    transliteration: 'Om Ganadhipaya Namah',
    english_translation: 'Om, I bow to the lord of all groups and communities.',
    tradition: 'vedic_ganesha',
    intention: 'Community',
    phonetic_guide: 'OHM gah-nah-dhih-PAH-yah nah-MAH',
    context_note: 'Ganadhipa — "lord of groups" — honors Ganesha as the presiding deity of all communities, councils, and collective endeavors.',
    audio_filename: 'mantra-121.mp3',
    go_deeper_teaser: 'Sangha: the power of spiritual community →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 122,
    original_script: 'ॐ सिद्धिविनायकाय नमः',
    transliteration: 'Om Siddhivinayakaya Namah',
    english_translation: 'Om, I bow to Siddhivinayaka — the bestower of all accomplishments.',
    tradition: 'vedic_ganesha',
    intention: 'Achievement',
    phonetic_guide: 'OHM sid-dhih-vih-nah-YAH-kah-yah nah-MAH',
    context_note: 'Siddhivinayaka — "bestower of siddhi" — is the most popular form of Ganesha in Mumbai. Siddhi means accomplishment, perfection, and supernatural power.',
    audio_filename: 'mantra-122.mp3',
    go_deeper_teaser: 'The eight siddhis: spiritual powers and how to use them →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 123,
    original_script: 'ॐ बुद्धिप्रियाय नमः',
    transliteration: 'Om Buddhipriyaya Namah',
    english_translation: 'Om, I bow to the one who loves intelligence.',
    tradition: 'vedic_ganesha',
    intention: 'Intelligence',
    phonetic_guide: 'OHM bood-dhih-PRIH-yah-yah nah-MAH',
    context_note: 'Buddhipriya — "lover of intelligence" — honors Ganesha as the patron of learning, scholarship, and all forms of intellectual endeavor.',
    audio_filename: 'mantra-123.mp3',
    go_deeper_teaser: 'Ganesha as the patron of learning: the student\'s mantra →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 124,
    original_script: 'ॐ विद्याधिपाय नमः',
    transliteration: 'Om Vidyadhipaya Namah',
    english_translation: 'Om, I bow to the lord of all knowledge.',
    tradition: 'vedic_ganesha',
    intention: 'Knowledge',
    phonetic_guide: 'OHM vid-yah-dhih-PAH-yah nah-MAH',
    context_note: 'Vidyadhipa — "lord of knowledge" — honors Ganesha as the supreme patron of all forms of learning, from the sacred to the mundane.',
    audio_filename: 'mantra-124.mp3',
    go_deeper_teaser: 'Para vidya and apara vidya: two kinds of knowledge →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 125,
    original_script: 'ॐ मूषकवाहनाय नमः',
    transliteration: 'Om Mushakavahanaya Namah',
    english_translation: 'Om, I bow to the one whose vehicle is the mouse.',
    tradition: 'vedic_ganesha',
    intention: 'Humility',
    phonetic_guide: 'OHM moo-shah-kah-VAH-hah-nah-yah nah-MAH',
    context_note: 'Ganesha rides a mouse — the smallest of vehicles for the largest of gods. The mouse represents the ego: small, quick, and capable of gnawing through obstacles.',
    audio_filename: 'mantra-125.mp3',
    go_deeper_teaser: 'Why Ganesha rides a mouse: the paradox of power →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 126,
    original_script: 'ॐ मोदकप्रियाय नमः',
    transliteration: 'Om Modakapriyaya Namah',
    english_translation: 'Om, I bow to the one who loves modaka — the sweet of bliss.',
    tradition: 'vedic_ganesha',
    intention: 'Sweetness',
    phonetic_guide: 'OHM moh-dah-kah-PRIH-yah-yah nah-MAH',
    context_note: 'Modaka — a sweet rice dumpling — is Ganesha\'s favorite offering. It represents the sweetness of spiritual realization.',
    audio_filename: 'mantra-126.mp3',
    go_deeper_teaser: 'Offering to Ganesha: the art of sacred giving →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 127,
    original_script: 'ॐ हेरम्बाय नमः',
    transliteration: 'Om Herambaya Namah',
    english_translation: 'Om, I bow to Heramba — the protector of the weak.',
    tradition: 'vedic_ganesha',
    intention: 'Protection',
    phonetic_guide: 'OHM hay-RAHM-bah-yah nah-MAH',
    context_note: 'Heramba — "protector of the weak" — is a five-headed form of Ganesha who specifically protects those who are vulnerable or in difficulty.',
    audio_filename: 'mantra-127.mp3',
    go_deeper_teaser: 'Heramba: Ganesha\'s fierce protective form →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 128,
    original_script: 'ॐ महागणपतये नमः',
    transliteration: 'Om Mahaganapataye Namah',
    english_translation: 'Om, I bow to the great lord of all hosts.',
    tradition: 'vedic_ganesha',
    intention: 'Greatness',
    phonetic_guide: 'OHM mah-hah-gah-nah-PAH-tah-yay nah-MAH',
    context_note: 'Mahaganapataye — "great Ganapati" — is the supreme form of Ganesha, combining all his powers and aspects into one.',
    audio_filename: 'mantra-128.mp3',
    go_deeper_teaser: 'The 32 forms of Ganesha: a complete guide →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 129,
    original_script: 'ॐ गणेशाय विद्महे',
    transliteration: 'Om Ganeshaya Vidmahe',
    english_translation: 'Om, may we know Ganesha.',
    tradition: 'vedic_ganesha',
    intention: 'Knowledge',
    phonetic_guide: 'OHM gah-NAY-shah-yah vid-MAH-hay',
    context_note: 'The opening of the Ganesha Gayatri — a prayer for direct knowledge of the remover of obstacles.',
    audio_filename: 'mantra-129.mp3',
    go_deeper_teaser: 'The Ganesha Gayatri: the most powerful Ganesha mantra →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 130,
    original_script: 'ॐ वक्रतुण्डाय धीमहि',
    transliteration: 'Om Vakratundaya Dhimahi',
    english_translation: 'Om, may we meditate on the curved-trunk one.',
    tradition: 'vedic_ganesha',
    intention: 'Meditation',
    phonetic_guide: 'OHM vahk-rah-TOON-dah-yah dhee-MAH-hee',
    context_note: 'Vakratunda — "curved trunk" — honors Ganesha\'s trunk, which curves to pick up the sweetness of life. The second line of the Ganesha Gayatri.',
    audio_filename: 'mantra-130.mp3',
    go_deeper_teaser: 'Ganesha\'s trunk: the power of discernment →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 131,
    original_script: 'तन्नो दन्तिः प्रचोदयात्',
    transliteration: 'Tanno Dantih Prachodayat',
    english_translation: 'May the tusked one inspire and illuminate us.',
    tradition: 'vedic_ganesha',
    intention: 'Inspiration',
    phonetic_guide: 'tahn-NOH DAHN-tih prah-choh-DAH-yaht',
    context_note: 'The concluding line of the Ganesha Gayatri. Danti — "tusked one" — refers to Ganesha\'s single tusk, the pen that wrote the Mahabharata.',
    audio_filename: 'mantra-131.mp3',
    go_deeper_teaser: 'The Mahabharata: the world\'s longest poem →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 132,
    original_script: 'वक्रतुण्ड महाकाय',
    transliteration: 'Vakratunda Mahakaya',
    english_translation: 'O curved-trunk one, O great-bodied one...',
    tradition: 'vedic_ganesha',
    intention: 'Blessings',
    phonetic_guide: 'vahk-rah-TOON-dah mah-hah-KAH-yah',
    context_note: 'The opening of the most popular Ganesha shloka. The full verse: "O curved-trunk, great-bodied, brilliant as a million suns — remove all obstacles from my work, always."',
    audio_filename: 'mantra-132.mp3',
    go_deeper_teaser: 'The Vakratunda shloka: Ganesha\'s most popular prayer →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 133,
    original_script: 'सूर्यकोटि समप्रभ',
    transliteration: 'Suryakoti Samaprabha',
    english_translation: 'Brilliant as ten million suns.',
    tradition: 'vedic_ganesha',
    intention: 'Radiance',
    phonetic_guide: 'soor-yah-KOH-tee sah-mah-PRAH-bhah',
    context_note: 'The second line of the Vakratunda shloka. Ganesha\'s radiance is compared to ten million suns — the light of consciousness itself.',
    audio_filename: 'mantra-133.mp3',
    go_deeper_teaser: 'The light of consciousness: what Ganesha\'s radiance means →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 134,
    original_script: 'निर्विघ्नं कुरु मे देव',
    transliteration: 'Nirvighnam Kuru Me Deva',
    english_translation: 'O God, make my work free from obstacles.',
    tradition: 'vedic_ganesha',
    intention: 'Success',
    phonetic_guide: 'neer-VIG-nahm KOO-roo may DAY-vah',
    context_note: 'The third line of the Vakratunda shloka — a direct prayer for obstacle-free action. Nirvighna means "without obstacles."',
    audio_filename: 'mantra-134.mp3',
    go_deeper_teaser: 'Removing obstacles: the Ganesha principle in action →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 135,
    original_script: 'सर्वकार्येषु सर्वदा',
    transliteration: 'Sarvakaryeshu Sarvada',
    english_translation: 'In all endeavors, always.',
    tradition: 'vedic_ganesha',
    intention: 'Constancy',
    phonetic_guide: 'sahr-vah-KAH-ryay-shoo sahr-VAH-dah',
    context_note: 'The final line of the Vakratunda shloka. Sarvada — "always" — transforms the prayer into a constant, living invocation.',
    audio_filename: 'mantra-135.mp3',
    go_deeper_teaser: 'Living in constant prayer: the practice of remembrance →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 136,
    original_script: 'ॐ गं ॐ गं ॐ गं',
    transliteration: 'Om Gam Om Gam Om Gam',
    english_translation: 'Om, Ganesha\'s seed — three times — opening all doors.',
    tradition: 'vedic_ganesha',
    intention: 'Opening',
    phonetic_guide: 'OHM gahm OHM gahm OHM gahm',
    context_note: 'The simplest Ganesha practice: just his bija, three times. Gam activates the root chakra and opens the path ahead.',
    audio_filename: 'mantra-136.mp3',
    go_deeper_teaser: 'The root chakra and Ganesha: the foundation of practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 137,
    original_script: 'I Am Divine Light',
    transliteration: 'I Am Divine Light',
    english_translation: 'I recognize and embody the eternal light that lives within me.',
    tradition: 'universal',
    intention: 'Self-Realization',
    phonetic_guide: 'I am divine light',
    context_note: 'A powerful affirmation rooted in Vedantic truth — you are not the body, not the mind, but the luminous awareness that witnesses all.',
    audio_filename: '',
    go_deeper_teaser: 'Why recognizing your inner light changes everything →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 138,
    original_script: 'तत् सवितुर् वरेण्यम्',
    transliteration: 'Tat Savitur Varenyam',
    english_translation: 'That divine solar radiance which is most adorable.',
    tradition: 'vedic_solar',
    intention: 'Reverence',
    phonetic_guide: 'taht sah-VEE-toor vah-REN-yahm',
    context_note: 'The second line of the Gayatri Mantra. Savitri is the solar deity — the divine light that illuminates both the outer sun and the inner light of consciousness.',
    audio_filename: 'mantra-138.mp3',
    go_deeper_teaser: 'Savitri: the solar deity behind the Gayatri →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 139,
    original_script: 'भर्गो देवस्य धीमहि',
    transliteration: 'Bhargo Devasya Dhimahi',
    english_translation: 'May we meditate on the divine radiance.',
    tradition: 'vedic_solar',
    intention: 'Meditation',
    phonetic_guide: 'BHAHR-goh DAY-vahs-yah dhee-MAH-hee',
    context_note: 'The third line of the Gayatri. Bhargo means "radiance" or "splendor" — the light that burns away ignorance.',
    audio_filename: 'mantra-139.mp3',
    go_deeper_teaser: 'Bhargo: the light that destroys darkness →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 140,
    original_script: 'धियो यो नः प्रचोदयात्',
    transliteration: 'Dhiyo Yo Nah Prachodayat',
    english_translation: 'May that divine light inspire and illuminate our intellect.',
    tradition: 'vedic_solar',
    intention: 'Illumination',
    phonetic_guide: 'DHEE-yoh yoh nah prah-choh-DAH-yaht',
    context_note: 'The final line of the Gayatri Mantra. Dhiyo — "intellect" — is what we offer to the divine light for purification and illumination.',
    audio_filename: 'mantra-140.mp3',
    go_deeper_teaser: 'The Gayatri Mantra: the most powerful mantra in the Vedas →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 141,
    original_script: 'I Am Worthy of Love',
    transliteration: 'I Am Worthy of Love',
    english_translation: 'I am inherently worthy of giving and receiving boundless love.',
    tradition: 'universal',
    intention: 'Self-Love',
    phonetic_guide: 'I am worthy of love',
    context_note: 'Love is not something you earn — it is your birthright. This affirmation dissolves the false belief that you must perform to be loved.',
    audio_filename: '',
    go_deeper_teaser: 'The spiritual truth about self-worth →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 142,
    original_script: 'ॐ सूर्याय नमः',
    transliteration: 'Om Suryaya Namah',
    english_translation: 'Om, I bow to Surya — the solar deity, the source of all light.',
    tradition: 'vedic_solar',
    intention: 'Vitality',
    phonetic_guide: 'OHM SOOR-yah-yah nah-MAH',
    context_note: 'Surya is the solar deity — the visible form of the divine. The sun is the source of all life on earth and a symbol of the inner light of consciousness.',
    audio_filename: 'mantra-142.mp3',
    go_deeper_teaser: 'Surya Namaskar: the sun salutation as prayer →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 143,
    original_script: 'ॐ आदित्याय नमः',
    transliteration: 'Om Adityaya Namah',
    english_translation: 'Om, I bow to Aditya — the son of Aditi, the infinite.',
    tradition: 'vedic_solar',
    intention: 'Infinity',
    phonetic_guide: 'OHM ah-DIT-yah-yah nah-MAH',
    context_note: 'Aditya — "son of Aditi" — is the sun as the child of the infinite. Aditi means "the boundless" — the cosmic mother of all the gods.',
    audio_filename: 'mantra-143.mp3',
    go_deeper_teaser: 'Aditi: the infinite mother of the gods →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 144,
    original_script: 'ॐ मित्राय नमः',
    transliteration: 'Om Mitraya Namah',
    english_translation: 'Om, I bow to Mitra — the sun as the universal friend.',
    tradition: 'vedic_solar',
    intention: 'Friendship',
    phonetic_guide: 'OHM MEET-rah-yah nah-MAH',
    context_note: 'Mitra — "friend" — is the sun as the universal benefactor. The sun shines equally on all without discrimination.',
    audio_filename: 'mantra-144.mp3',
    go_deeper_teaser: 'Mitra: the sun as the friend of all beings →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 145,
    original_script: 'ॐ रवये नमः',
    transliteration: 'Om Ravaye Namah',
    english_translation: 'Om, I bow to Ravi — the radiant one.',
    tradition: 'vedic_solar',
    intention: 'Radiance',
    phonetic_guide: 'OHM RAH-vah-yay nah-MAH',
    context_note: 'Ravi — "the radiant" — is one of the twelve names of the sun recited during Surya Namaskar. Radiance is the sun\'s essential nature.',
    audio_filename: 'mantra-145.mp3',
    go_deeper_teaser: 'The 12 names of the sun: the Surya Namaskar mantras →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 146,
    original_script: 'ॐ सूर्याय नमः भास्कराय नमः',
    transliteration: 'Om Suryaya Namah Bhaskaraya Namah',
    english_translation: 'Om, I bow to Surya, I bow to Bhaskara — the one who illuminates.',
    tradition: 'vedic_solar',
    intention: 'Clarity',
    phonetic_guide: 'OHM SOOR-yah-yah nah-MAH BHAHS-kah-rah-yah nah-MAH',
    context_note: 'Bhaskara — "the illuminator" — is the sun as the force that makes all things visible and knowable.',
    audio_filename: 'mantra-146.mp3',
    go_deeper_teaser: 'Light as a metaphor for consciousness →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 147,
    original_script: 'ॐ खगाय नमः',
    transliteration: 'Om Khagaya Namah',
    english_translation: 'Om, I bow to Khaga — the one who moves through the sky.',
    tradition: 'vedic_solar',
    intention: 'Freedom',
    phonetic_guide: 'OHM khah-GAH-yah nah-MAH',
    context_note: 'Khaga — "sky-mover" — honors the sun\'s daily journey across the heavens. The sun\'s freedom of movement is a symbol of liberated consciousness.',
    audio_filename: 'mantra-147.mp3',
    go_deeper_teaser: 'The sun\'s daily journey: a meditation on freedom →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 148,
    original_script: 'ॐ पूष्णे नमः',
    transliteration: 'Om Pushne Namah',
    english_translation: 'Om, I bow to Pushan — the nourisher of all.',
    tradition: 'vedic_solar',
    intention: 'Nourishment',
    phonetic_guide: 'OHM POOSH-nay nah-MAH',
    context_note: 'Pushan — "the nourisher" — is the sun as the source of all food and sustenance. The sun nourishes every living being without exception.',
    audio_filename: 'mantra-148.mp3',
    go_deeper_teaser: 'Pushan: the sun as the cosmic nourisher →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 149,
    original_script: 'ॐ हिरण्यगर्भाय नमः',
    transliteration: 'Om Hiranyagarbhaya Namah',
    english_translation: 'Om, I bow to Hiranyagarbha — the golden womb of creation.',
    tradition: 'vedic_solar',
    intention: 'Creation',
    phonetic_guide: 'OHM hih-rahn-yah-GAHR-bhah-yah nah-MAH',
    context_note: 'Hiranyagarbha — "golden womb" — is the cosmic egg from which the universe was born. The sun is its visible manifestation.',
    audio_filename: 'mantra-149.mp3',
    go_deeper_teaser: 'Hiranyagarbha: the golden egg of creation →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 150,
    original_script: 'ॐ मरीचये नमः',
    transliteration: 'Om Marichaye Namah',
    english_translation: 'Om, I bow to Marichi — the ray of light.',
    tradition: 'vedic_solar',
    intention: 'Subtlety',
    phonetic_guide: 'OHM mah-REE-chah-yay nah-MAH',
    context_note: 'Marichi — "ray of light" — honors the individual rays of the sun. Each ray is both part of the sun and distinct from it — like each soul in relation to the divine.',
    audio_filename: 'mantra-150.mp3',
    go_deeper_teaser: 'The ray and the sun: the relationship between soul and God →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 151,
    original_script: 'ॐ आदित्याय सवित्रे नमः',
    transliteration: 'Om Adityaya Savitre Namah',
    english_translation: 'Om, I bow to Aditya-Savitri — the solar deity who animates all life.',
    tradition: 'vedic_solar',
    intention: 'Animation',
    phonetic_guide: 'OHM ah-DIT-yah-yah sah-VIT-ray nah-MAH',
    context_note: 'Savitri — "the animating one" — is the sun as the force that animates all living beings. Without the sun, there is no life.',
    audio_filename: 'mantra-151.mp3',
    go_deeper_teaser: 'Prana: the solar life force within you →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 152,
    original_script: 'ॐ दिवाकराय नमः',
    transliteration: 'Om Divakaraya Namah',
    english_translation: 'Om, I bow to Divakara — the maker of the day.',
    tradition: 'vedic_solar',
    intention: 'New Day',
    phonetic_guide: 'OHM dee-vah-KAH-rah-yah nah-MAH',
    context_note: 'Divakara — "day-maker" — honors the sun as the creator of each new day. Every sunrise is a new beginning, a fresh opportunity.',
    audio_filename: 'mantra-152.mp3',
    go_deeper_teaser: 'The gift of each new day: a morning practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 153,
    original_script: 'ॐ प्रभाकराय नमः',
    transliteration: 'Om Prabhakaraya Namah',
    english_translation: 'Om, I bow to Prabhakara — the maker of light.',
    tradition: 'vedic_solar',
    intention: 'Enlightenment',
    phonetic_guide: 'OHM prah-bhah-KAH-rah-yah nah-MAH',
    context_note: 'Prabhakara — "maker of light" — honors the sun as the source of all illumination, both physical and spiritual.',
    audio_filename: 'mantra-153.mp3',
    go_deeper_teaser: 'Enlightenment: what it really means →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 154,
    original_script: 'ॐ विवस्वते नमः',
    transliteration: 'Om Vivasvate Namah',
    english_translation: 'Om, I bow to Vivasvat — the brilliant, shining one.',
    tradition: 'vedic_solar',
    intention: 'Brilliance',
    phonetic_guide: 'OHM vih-VAHS-vah-tay nah-MAH',
    context_note: 'Vivasvat — "the brilliant" — is the Vedic name of the sun. In the Bhagavad Gita, Krishna says he first taught this yoga to Vivasvat.',
    audio_filename: 'mantra-154.mp3',
    go_deeper_teaser: 'The eternal yoga: Krishna\'s teaching to the sun →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 155,
    original_script: 'ॐ सवित्रे नमः',
    transliteration: 'Om Savitre Namah',
    english_translation: 'Om, I bow to Savitri — the solar deity of the Gayatri.',
    tradition: 'vedic_solar',
    intention: 'Inspiration',
    phonetic_guide: 'OHM sah-VIT-ray nah-MAH',
    context_note: 'Savitri is the specific solar deity invoked in the Gayatri Mantra. The name means "one who inspires" or "one who animates."',
    audio_filename: 'mantra-155.mp3',
    go_deeper_teaser: 'Savitri: the goddess behind the Gayatri Mantra →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 156,
    original_script: 'ॐ आर्काय नमः',
    transliteration: 'Om Arkaya Namah',
    english_translation: 'Om, I bow to Arka — the sun as the worthy of praise.',
    tradition: 'vedic_solar',
    intention: 'Gratitude',
    phonetic_guide: 'OHM AHR-kah-yah nah-MAH',
    context_note: 'Arka — "worthy of praise" — honors the sun as the most visible and constant blessing in our lives. Gratitude for the sun is gratitude for life itself.',
    audio_filename: 'mantra-156.mp3',
    go_deeper_teaser: 'Gratitude as a spiritual practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 157,
    original_script: 'ॐ भानवे नमः',
    transliteration: 'Om Bhanave Namah',
    english_translation: 'Om, I bow to Bhanu — the luminous one.',
    tradition: 'vedic_solar',
    intention: 'Luminosity',
    phonetic_guide: 'OHM BHAH-nah-vay nah-MAH',
    context_note: 'Bhanu — "luminous" — is one of the twelve names of the sun. Luminosity is the sun\'s nature; it cannot help but shine.',
    audio_filename: 'mantra-157.mp3',
    go_deeper_teaser: 'Your natural luminosity: the practice of shining →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 158,
    original_script: 'ॐ इन्द्राय नमः',
    transliteration: 'Om Indraya Namah',
    english_translation: 'Om, I bow to Indra — the king of the gods, lord of lightning.',
    tradition: 'vedic_solar',
    intention: 'Power',
    phonetic_guide: 'OHM IN-drah-yah nah-MAH',
    context_note: 'Indra is the king of the Vedic gods, wielder of the thunderbolt (vajra). He represents the power of the awakened mind.',
    audio_filename: 'mantra-158.mp3',
    go_deeper_teaser: 'Indra and the thunderbolt: the power of awakening →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 159,
    original_script: 'ॐ वरुणाय नमः',
    transliteration: 'Om Varunaya Namah',
    english_translation: 'Om, I bow to Varuna — the lord of cosmic order and the waters.',
    tradition: 'vedic_solar',
    intention: 'Order',
    phonetic_guide: 'OHM vah-ROO-nah-yah nah-MAH',
    context_note: 'Varuna is the Vedic god of cosmic order (rita) and the waters. He sees all actions and maintains the moral order of the universe.',
    audio_filename: 'mantra-159.mp3',
    go_deeper_teaser: 'Rita: the cosmic order that underlies all existence →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 160,
    original_script: 'ॐ अग्नये नमः',
    transliteration: 'Om Agnaye Namah',
    english_translation: 'Om, I bow to Agni — the sacred fire, the divine messenger.',
    tradition: 'vedic_solar',
    intention: 'Purification',
    phonetic_guide: 'OHM AHG-nah-yay nah-MAH',
    context_note: 'Agni is the first word of the Rigveda. The sacred fire is the divine messenger between humans and gods, and the purifier of all offerings.',
    audio_filename: 'mantra-160.mp3',
    go_deeper_teaser: 'Agni: the first word of the Vedas →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 161,
    original_script: 'ॐ वायवे नमः',
    transliteration: 'Om Vayave Namah',
    english_translation: 'Om, I bow to Vayu — the wind, the breath of life.',
    tradition: 'vedic_solar',
    intention: 'Breath',
    phonetic_guide: 'OHM VAH-yah-vay nah-MAH',
    context_note: 'Vayu — "wind" or "breath" — is the Vedic god of air and prana. The breath is the most direct link between the physical and spiritual.',
    audio_filename: 'mantra-161.mp3',
    go_deeper_teaser: 'Pranayama: the yoga of the breath →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 162,
    original_script: 'ॐ पृथिव्यै नमः',
    transliteration: 'Om Prithivyai Namah',
    english_translation: 'Om, I bow to Prithivi — the earth, our mother.',
    tradition: 'vedic_solar',
    intention: 'Grounding',
    phonetic_guide: 'OHM prih-THIV-yay nah-MAH',
    context_note: 'Prithivi — "the broad one" — is the Vedic earth goddess. The earth supports all life without discrimination. Grounding is the foundation of all practice.',
    audio_filename: 'mantra-162.mp3',
    go_deeper_teaser: 'Prithivi: the earth as the divine mother →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 163,
    original_script: 'ॐ आपः शान्तिः',
    transliteration: 'Om Apah Shantih',
    english_translation: 'Om, may the waters bring peace.',
    tradition: 'vedic_solar',
    intention: 'Peace',
    phonetic_guide: 'OHM AH-pah SHAHN-tih',
    context_note: 'From the Shanti Patha — the Vedic peace invocation. The waters (apah) represent the flow of life and the cleansing power of grace.',
    audio_filename: 'mantra-163.mp3',
    go_deeper_teaser: 'The Shanti Patha: the Vedic prayer for universal peace →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 164,
    original_script: 'ॐ ओषधयः शान्तिः',
    transliteration: 'Om Oshadhayah Shantih',
    english_translation: 'Om, may the herbs and plants bring peace.',
    tradition: 'vedic_solar',
    intention: 'Healing',
    phonetic_guide: 'OHM oh-shah-DHAH-yah SHAHN-tih',
    context_note: 'From the Shanti Patha. The healing plants of the earth are invoked for peace — honoring the medicinal wisdom of the natural world.',
    audio_filename: 'mantra-164.mp3',
    go_deeper_teaser: 'Ayurveda: the Vedic science of healing →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 165,
    original_script: 'ॐ विश्वानि देव सवितर्',
    transliteration: 'Om Vishwani Deva Savitar',
    english_translation: 'O divine Savitri, remove all that is harmful from us.',
    tradition: 'vedic_solar',
    intention: 'Purification',
    phonetic_guide: 'OHM vish-WAH-nih DAY-vah sah-VEE-tahr',
    context_note: 'From the Yajurveda. A prayer to the solar deity to remove all that is harmful and bring only what is beneficial.',
    audio_filename: 'mantra-165.mp3',
    go_deeper_teaser: 'The Yajurveda: the Veda of ritual action →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 166,
    original_script: 'दुरितानि परासुव',
    transliteration: 'Duritani Parasuva',
    english_translation: 'Remove all our sins and shortcomings.',
    tradition: 'vedic_solar',
    intention: 'Forgiveness',
    phonetic_guide: 'doo-rih-TAH-nih pah-rah-SOO-vah',
    context_note: 'The second line of the Vishwani prayer. Duritani means "that which causes pain" — the prayer asks for removal of all inner obstacles.',
    audio_filename: 'mantra-166.mp3',
    go_deeper_teaser: 'Forgiveness as a spiritual practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 167,
    original_script: 'यद् भद्रं तन्न आसुव',
    transliteration: 'Yad Bhadram Tanna Asuva',
    english_translation: 'And bring to us all that is auspicious.',
    tradition: 'vedic_solar',
    intention: 'Auspiciousness',
    phonetic_guide: 'yahd BHAHD-rahm tahn-NAH ah-SOO-vah',
    context_note: 'The final line of the Vishwani prayer. Bhadram — "auspicious" — is the Vedic word for all that is good, beautiful, and beneficial.',
    audio_filename: 'mantra-167.mp3',
    go_deeper_teaser: 'Bhadram: the Vedic vision of the good life →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 168,
    original_script: 'ॐ सूर्य नमस्कार',
    transliteration: 'Om Surya Namaskar',
    english_translation: 'Om, salutation to the sun.',
    tradition: 'vedic_solar',
    intention: 'Gratitude',
    phonetic_guide: 'OHM SOOR-yah nah-mahs-KAHR',
    context_note: 'Surya Namaskar — "sun salutation" — is both a physical yoga practice and a devotional act. Each movement is accompanied by a mantra to the sun.',
    audio_filename: 'mantra-168.mp3',
    go_deeper_teaser: 'The complete Surya Namaskar practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 169,
    original_script: 'ॐ ह्रां ह्रीं ह्रौं सः सूर्याय नमः',
    transliteration: 'Om Hram Hrim Hraum Sah Suryaya Namah',
    english_translation: 'Om — the three solar bija mantras — I am that — I bow to Surya.',
    tradition: 'vedic_solar',
    intention: 'Solar Power',
    phonetic_guide: 'OHM hrahm hreem hrowm sah SOOR-yah-yah nah-MAH',
    context_note: 'The complete solar bija mantra. Hram, Hrim, Hraum are the three seed syllables of the sun, representing its three aspects: rising, noon, and setting.',
    audio_filename: 'mantra-169.mp3',
    go_deeper_teaser: 'Solar bija mantras: seeds of solar power →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 170,
    original_script: 'ॐ जपाकुसुमसङ्काशम्',
    transliteration: 'Om Japaakusumasankasham',
    english_translation: 'Om, the one who resembles the hibiscus flower.',
    tradition: 'vedic_solar',
    intention: 'Beauty',
    phonetic_guide: 'OHM jah-pah-koo-soo-mah-sahn-KAH-shahm',
    context_note: 'The opening of the Aditya Hridayam — the solar hymn from the Ramayana. The sun is compared to the red hibiscus flower at dawn.',
    audio_filename: 'mantra-170.mp3',
    go_deeper_teaser: 'The Aditya Hridayam: the heart of the sun →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 171,
    original_script: 'काश्यपेयं महाद्युतिम्',
    transliteration: 'Kashyapeyam Mahadyutim',
    english_translation: 'The son of Kashyapa, of great radiance.',
    tradition: 'vedic_solar',
    intention: 'Lineage',
    phonetic_guide: 'KAHSH-yah-pay-yahm mah-hah-DYOO-tihm',
    context_note: 'The second line of the Aditya Hridayam. The sun is the son of the sage Kashyapa — reminding us that even the sun has a lineage and a teacher.',
    audio_filename: 'mantra-171.mp3',
    go_deeper_teaser: 'Kashyapa: the progenitor of all life →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 172,
    original_script: 'तमोऽरिं सर्वपापघ्नम्',
    transliteration: 'Tamoriṃ Sarvapapagnam',
    english_translation: 'The enemy of darkness, the destroyer of all sins.',
    tradition: 'vedic_solar',
    intention: 'Liberation',
    phonetic_guide: 'tah-MOH-rim sahr-vah-PAH-pahg-nahm',
    context_note: 'The third line of the Aditya Hridayam. The sun destroys both physical darkness and the inner darkness of ignorance and sin.',
    audio_filename: 'mantra-172.mp3',
    go_deeper_teaser: 'The Aditya Hridayam: how Rama defeated Ravana →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 173,
    original_script: 'प्रणतोऽस्मि दिवाकरम्',
    transliteration: 'Pranato\'smi Divakaram',
    english_translation: 'I bow to the maker of the day.',
    tradition: 'vedic_solar',
    intention: 'Humility',
    phonetic_guide: 'prah-NAH-tohs-mih dee-vah-KAH-rahm',
    context_note: 'The final line of the Aditya Hridayam opening verse. Pranata — "bowing" — is the posture of humility before the divine light.',
    audio_filename: 'mantra-173.mp3',
    go_deeper_teaser: 'Pranama: the practice of sacred bowing →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 174,
    original_script: 'ॐ नमः सूर्याय शान्ताय',
    transliteration: 'Om Namah Suryaya Shantaya',
    english_translation: 'Om, I bow to the peaceful sun.',
    tradition: 'vedic_solar',
    intention: 'Equanimity',
    phonetic_guide: 'OHM nah-MAH SOOR-yah-yah SHAHN-tah-yah',
    context_note: 'The sun is peaceful — it shines without effort, without preference, without agitation. This mantra invokes solar equanimity.',
    audio_filename: 'mantra-174.mp3',
    go_deeper_teaser: 'Equanimity: the sun\'s greatest teaching →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 175,
    original_script: 'ॐ नमः सूर्याय सर्वदाय',
    transliteration: 'Om Namah Suryaya Sarvadaya',
    english_translation: 'Om, I bow to the sun who gives everything.',
    tradition: 'vedic_solar',
    intention: 'Generosity',
    phonetic_guide: 'OHM nah-MAH SOOR-yah-yah sahr-VAH-dah-yah',
    context_note: 'The sun gives its light freely to all — the saint and the sinner, the rich and the poor. This mantra invokes divine generosity.',
    audio_filename: 'mantra-175.mp3',
    go_deeper_teaser: 'The sun\'s generosity: giving without expectation →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 176,
    original_script: 'ॐ सूर्य देव नमोऽस्तु ते',
    transliteration: 'Om Surya Deva Namostu Te',
    english_translation: 'Om, I bow to you, O solar deity.',
    tradition: 'vedic_solar',
    intention: 'Reverence',
    phonetic_guide: 'OHM SOOR-yah DAY-vah nah-MOHS-too tay',
    context_note: 'A simple, direct salutation to the sun. Namostu — "may there be bowing" — expresses perpetual reverence.',
    audio_filename: 'mantra-176.mp3',
    go_deeper_teaser: 'Daily sun practice: the simplest solar sadhana →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 177,
    original_script: 'ॐ प्रसीद प्रसीद प्रभो',
    transliteration: 'Om Prasida Prasida Prabho',
    english_translation: 'Om, be pleased, be pleased, O Lord.',
    tradition: 'vedic_solar',
    intention: 'Grace',
    phonetic_guide: 'OHM prah-SEE-dah prah-SEE-dah PRAH-bhoh',
    context_note: 'Prasida — "be pleased" or "be gracious" — is a prayer for divine grace. The triple repetition intensifies the request.',
    audio_filename: 'mantra-177.mp3',
    go_deeper_teaser: 'Prasada: the grace that flows from the divine →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 178,
    original_script: 'ॐ सर्वदेवनमस्कारः',
    transliteration: 'Om Sarvadevanamaskarah',
    english_translation: 'Om, salutation to all the gods.',
    tradition: 'vedic_solar',
    intention: 'Inclusivity',
    phonetic_guide: 'OHM sahr-vah-DAY-vah-nah-mahs-KAH-rah',
    context_note: 'A universal salutation to all divine forms. The Vedas teach that all gods are aspects of the one divine reality.',
    audio_filename: 'mantra-178.mp3',
    go_deeper_teaser: 'Ekam sat vipra bahudha vadanti: one truth, many names →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 179,
    original_script: 'केशवं प्रति गच्छति',
    transliteration: 'Keshavam Prati Gacchati',
    english_translation: 'Reaches Keshava (the supreme).',
    tradition: 'vedic_solar',
    intention: 'Unity',
    phonetic_guide: 'KAY-shah-vahm PRAH-tih GAHCH-chah-tih',
    context_note: 'The second line of the universal salutation verse: "Salutation to all gods reaches the supreme." All paths lead to the same destination.',
    audio_filename: 'mantra-179.mp3',
    go_deeper_teaser: 'All paths lead to the same peak →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 180,
    original_script: 'ॐ तेजोऽसि तेजो मयि धेहि',
    transliteration: 'Om Tejo\'si Tejo Mayi Dhehi',
    english_translation: 'Om, you are radiance — place that radiance in me.',
    tradition: 'vedic_solar',
    intention: 'Empowerment',
    phonetic_guide: 'OHM tay-JOH-see tay-JOH mah-YEE DHAY-hee',
    context_note: 'From the Yajurveda. A prayer to receive the sun\'s radiance — not just its physical light, but its inner quality of brilliance and clarity.',
    audio_filename: 'mantra-180.mp3',
    go_deeper_teaser: 'Tejas: the inner radiance of the awakened person →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 181,
    original_script: 'ॐ वीर्यमसि वीर्यं मयि धेहि',
    transliteration: 'Om Viryamasi Viryam Mayi Dhehi',
    english_translation: 'Om, you are vitality — place that vitality in me.',
    tradition: 'vedic_solar',
    intention: 'Vitality',
    phonetic_guide: 'OHM veer-YAHM-ah-see veer-YAHM mah-YEE DHAY-hee',
    context_note: 'From the Yajurveda. Virya — "vitality" or "heroic energy" — is the solar quality of dynamic, purposeful action.',
    audio_filename: 'mantra-181.mp3',
    go_deeper_teaser: 'Virya: the heroic energy of the spiritual warrior →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 182,
    original_script: 'ॐ बलमसि बलं मयि धेहि',
    transliteration: 'Om Balamasi Balam Mayi Dhehi',
    english_translation: 'Om, you are strength — place that strength in me.',
    tradition: 'vedic_solar',
    intention: 'Strength',
    phonetic_guide: 'OHM bah-LAHM-ah-see bah-LAHM mah-YEE DHAY-hee',
    context_note: 'From the Yajurveda. Bala — "strength" — is the solar quality of physical and spiritual fortitude. The sun never wavers; neither should we.',
    audio_filename: 'mantra-182.mp3',
    go_deeper_teaser: 'Bala: the strength that comes from practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
];
