// Mantras Part 2: Days 46–136 — Vedic Vishnu, Shakti, Ganesha

module.exports = [
  // ── VEDIC VISHNU (days 46–90) ─────────────────────────────────────────────
  {
    day_of_year: 46,
    original_script: 'ॐ नमो नारायणाय',
    transliteration: 'Om Namo Narayanaya',
    english_translation: 'Om, I bow to Narayana — the one who dwells in all beings.',
    tradition: 'vedic_vishnu',
    intention: 'Devotion',
    phonetic_guide: 'OHM nah-MOH nah-rah-YAH-nah-yah',
    sacred_geometry_type: 'lotus',
    context_note: 'The Ashtakshara — eight-syllable mantra of Vishnu. Narayana means "the one who is the abode of all beings."',
    go_deeper_teaser: 'Narayana: the god who lives inside you →',
  },
  {
    day_of_year: 47,
    original_script: 'ॐ नमो भगवते वासुदेवाय',
    transliteration: 'Om Namo Bhagavate Vasudevaya',
    english_translation: 'Om, I bow to the Lord Vasudeva — the one who pervades all.',
    tradition: 'vedic_vishnu',
    intention: 'Surrender',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay vah-soo-DAY-vah-yah',
    sacred_geometry_type: 'lotus',
    context_note: 'The Dvadasakshara — twelve-syllable mantra of Vishnu. Vasudeva means "the one who dwells everywhere." From the Bhagavata Purana.',
    go_deeper_teaser: 'The Bhagavata Purana: Vishnu\'s greatest scripture →',
  },
  {
    day_of_year: 48,
    original_script: 'हरे कृष्ण हरे कृष्ण',
    transliteration: 'Hare Krishna Hare Krishna',
    english_translation: 'O Hari, O Krishna — O divine energy, O all-attractive one.',
    tradition: 'vedic_vishnu',
    intention: 'Joy',
    phonetic_guide: 'HAH-ray KRISH-nah HAH-ray KRISH-nah',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'The first half of the Maha Mantra. Hare addresses the divine energy (Radha); Krishna means "all-attractive." From the Kali Santarana Upanishad.',
    go_deeper_teaser: 'The Maha Mantra: why it works for everyone →',
  },
  {
    day_of_year: 49,
    original_script: 'हरे राम हरे राम',
    transliteration: 'Hare Rama Hare Rama',
    english_translation: 'O Hari, O Rama — O divine energy, O the one who gives joy.',
    tradition: 'vedic_vishnu',
    intention: 'Bliss',
    phonetic_guide: 'HAH-ray RAH-mah HAH-ray RAH-mah',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'The second half of the Maha Mantra. Rama means "the one who gives joy" or "the one in whom the yogis delight."',
    go_deeper_teaser: 'Rama and Krishna: two faces of the same light →',
  },
  {
    day_of_year: 50,
    original_script: 'ॐ श्री रामाय नमः',
    transliteration: 'Om Shri Ramaya Namah',
    english_translation: 'Om, I bow to the radiant Rama — the ideal of righteousness.',
    tradition: 'vedic_vishnu',
    intention: 'Righteousness',
    phonetic_guide: 'OHM shree RAH-mah-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Rama is the seventh avatar of Vishnu and the embodiment of dharma — right action, integrity, and noble character.',
    go_deeper_teaser: 'Dharma: the path of right action →',
  },
  {
    day_of_year: 51,
    original_script: 'ॐ श्री कृष्णाय नमः',
    transliteration: 'Om Shri Krishnaya Namah',
    english_translation: 'Om, I bow to the radiant Krishna — the all-attractive divine.',
    tradition: 'vedic_vishnu',
    intention: 'Love',
    phonetic_guide: 'OHM shree KRISH-nah-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Krishna is the eighth avatar of Vishnu and the teacher of the Bhagavad Gita. His name means "all-attractive" or "dark one."',
    go_deeper_teaser: 'The Bhagavad Gita in one sentence →',
  },
  {
    day_of_year: 52,
    original_script: 'ॐ विष्णवे नमः',
    transliteration: 'Om Vishnave Namah',
    english_translation: 'Om, I bow to Vishnu — the all-pervading one.',
    tradition: 'vedic_vishnu',
    intention: 'Omnipresence',
    phonetic_guide: 'OHM VISH-nah-vay nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Vishnu means "the all-pervading one" — the divine presence that permeates every atom of creation.',
    go_deeper_teaser: 'How to feel the divine presence everywhere →',
  },
  {
    day_of_year: 53,
    original_script: 'ॐ नारायणाय विद्महे',
    transliteration: 'Om Narayanaya Vidmahe',
    english_translation: 'Om, may we know Narayana.',
    tradition: 'vedic_vishnu',
    intention: 'Knowledge',
    phonetic_guide: 'OHM nah-rah-YAH-nah-yah vid-MAH-hay',
    sacred_geometry_type: 'lotus',
    context_note: 'The opening of the Vishnu Gayatri — a prayer for direct knowledge of the all-pervading divine presence.',
    go_deeper_teaser: 'The Vishnu Gayatri: Vaishnava\'s most sacred prayer →',
  },
  {
    day_of_year: 54,
    original_script: 'ॐ वासुदेवाय धीमहि',
    transliteration: 'Om Vasudevaya Dhimahi',
    english_translation: 'Om, may we meditate on Vasudeva.',
    tradition: 'vedic_vishnu',
    intention: 'Meditation',
    phonetic_guide: 'OHM vah-soo-DAY-vah-yah dhee-MAH-hee',
    sacred_geometry_type: 'lotus',
    context_note: 'The second line of the Vishnu Gayatri. Dhimahi — "may we meditate" — invites sustained contemplation of the divine.',
    go_deeper_teaser: 'How to meditate on a divine form →',
  },
  {
    day_of_year: 55,
    original_script: 'तन्नो विष्णुः प्रचोदयात्',
    transliteration: 'Tanno Vishnuh Prachodayat',
    english_translation: 'May Vishnu illuminate and inspire us.',
    tradition: 'vedic_vishnu',
    intention: 'Inspiration',
    phonetic_guide: 'tahn-NOH VISH-nooh prah-choh-DAH-yaht',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'The concluding line of the Vishnu Gayatri. A prayer for divine illumination in all endeavors.',
    go_deeper_teaser: 'Vishnu\'s grace: how the preserver works in your life →',
  },
  {
    day_of_year: 56,
    original_script: 'ॐ जय जगदीश हरे',
    transliteration: 'Om Jai Jagadish Hare',
    english_translation: 'Om, victory to the Lord of the universe who removes all suffering.',
    tradition: 'vedic_vishnu',
    intention: 'Victory',
    phonetic_guide: 'OHM jay jah-gah-DEESH HAH-ray',
    sacred_geometry_type: 'lotus',
    context_note: 'From the beloved Aarti prayer sung at Vishnu temples across India. Jagadish means "Lord of the world."',
    go_deeper_teaser: 'Aarti: the ritual of light and devotion →',
  },
  {
    day_of_year: 57,
    original_script: 'ॐ श्री विष्णवे नमः',
    transliteration: 'Om Shri Vishnave Namah',
    english_translation: 'Om, I bow to the radiant, all-pervading Vishnu.',
    tradition: 'vedic_vishnu',
    intention: 'Abundance',
    phonetic_guide: 'OHM shree VISH-nah-vay nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Shri (Lakshmi) is Vishnu\'s consort. Invoking both together brings the fullness of divine grace — both consciousness and abundance.',
    go_deeper_teaser: 'Lakshmi and Vishnu: the divine couple of abundance →',
  },
  {
    day_of_year: 58,
    original_script: 'ॐ हरये नमः',
    transliteration: 'Om Haraye Namah',
    english_translation: 'Om, I bow to Hari — the one who removes all suffering.',
    tradition: 'vedic_vishnu',
    intention: 'Relief',
    phonetic_guide: 'OHM HAH-rah-yay nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Hari means "the remover" — Vishnu removes the three types of suffering: physical, mental, and karmic.',
    go_deeper_teaser: 'How Vishnu removes suffering: the path of grace →',
  },
  {
    day_of_year: 59,
    original_script: 'ॐ केशवाय नमः',
    transliteration: 'Om Keshavaya Namah',
    english_translation: 'Om, I bow to Keshava — the one with beautiful hair.',
    tradition: 'vedic_vishnu',
    intention: 'Beauty',
    phonetic_guide: 'OHM kay-SHAH-vah-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Keshava — "beautiful-haired" or "slayer of Keshi" — is one of Krishna\'s most beloved names. Beauty is a form of the divine.',
    go_deeper_teaser: 'The 1000 names of Vishnu: the Vishnu Sahasranama →',
  },
  {
    day_of_year: 60,
    original_script: 'ॐ माधवाय नमः',
    transliteration: 'Om Madhavaya Namah',
    english_translation: 'Om, I bow to Madhava — the lord of spring, the sweet one.',
    tradition: 'vedic_vishnu',
    intention: 'Sweetness',
    phonetic_guide: 'OHM mah-DHAH-vah-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Madhava means "spring" or "sweet" — Krishna as the embodiment of sweetness, beauty, and the joy of creation.',
    go_deeper_teaser: 'Madhurya bhava: the sweetness of divine love →',
  },
  {
    day_of_year: 61,
    original_script: 'ॐ गोविन्दाय नमः',
    transliteration: 'Om Govindaya Namah',
    english_translation: 'Om, I bow to Govinda — the protector of cows and the earth.',
    tradition: 'vedic_vishnu',
    intention: 'Protection',
    phonetic_guide: 'OHM goh-VIN-dah-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Govinda — "protector of cows" — is one of Krishna\'s most beloved names, honoring his childhood as a cowherd in Vrindavan.',
    go_deeper_teaser: 'Vrindavan: the sacred forest of Krishna\'s childhood →',
  },
  {
    day_of_year: 62,
    original_script: 'ॐ विष्णवे नमः त्रिविक्रमाय',
    transliteration: 'Om Vishnave Namah Trivikramaya',
    english_translation: 'Om, I bow to Vishnu who took three steps to encompass the universe.',
    tradition: 'vedic_vishnu',
    intention: 'Expansion',
    phonetic_guide: 'OHM VISH-nah-vay nah-MAH tree-vik-RAH-mah-yah',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Trivikrama — "three steps" — refers to Vamana avatar who measured the entire universe in three strides. Consciousness is boundless.',
    go_deeper_teaser: 'Vamana: the dwarf who became the universe →',
  },
  {
    day_of_year: 63,
    original_script: 'ॐ अच्युताय नमः',
    transliteration: 'Om Achyutaya Namah',
    english_translation: 'Om, I bow to the infallible one who never falls.',
    tradition: 'vedic_vishnu',
    intention: 'Steadiness',
    phonetic_guide: 'OHM ah-CHYOO-tah-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Achyuta — "infallible" or "imperishable" — is one of Krishna\'s names in the Bhagavad Gita. The divine never wavers.',
    go_deeper_teaser: 'Steadiness in the storm: Arjuna\'s lesson →',
  },
  {
    day_of_year: 64,
    original_script: 'ॐ अनन्ताय नमः',
    transliteration: 'Om Anantaya Namah',
    english_translation: 'Om, I bow to the infinite, endless one.',
    tradition: 'vedic_vishnu',
    intention: 'Infinity',
    phonetic_guide: 'OHM ah-NAHN-tah-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Ananta — "infinite" — is both a name of Vishnu and the cosmic serpent on which he rests. Infinity is the ground of all existence.',
    go_deeper_teaser: 'Ananta Shesha: the serpent of eternity →',
  },
  {
    day_of_year: 65,
    original_script: 'ॐ पुण्डरीकाक्षाय नमः',
    transliteration: 'Om Pundarikakshaya Namah',
    english_translation: 'Om, I bow to the lotus-eyed one.',
    tradition: 'vedic_vishnu',
    intention: 'Purity',
    phonetic_guide: 'OHM poon-dah-ree-KAH-kshah-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Pundarikaksha — "lotus-eyed" — describes Vishnu\'s eyes as pure as lotus flowers. The lotus grows in mud but remains unstained.',
    go_deeper_teaser: 'The lotus: growing pure in an impure world →',
  },
  {
    day_of_year: 66,
    original_script: 'ॐ श्रीधराय नमः',
    transliteration: 'Om Shridharaya Namah',
    english_translation: 'Om, I bow to the one who holds Shri — the divine abundance.',
    tradition: 'vedic_vishnu',
    intention: 'Abundance',
    phonetic_guide: 'OHM shree-DHAH-rah-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Sridhara — "holder of Shri" — honors Vishnu as the one who sustains Lakshmi, the goddess of abundance, on his chest.',
    go_deeper_teaser: 'Lakshmi on Vishnu\'s chest: the secret of abundance →',
  },
  {
    day_of_year: 67,
    original_script: 'ॐ हृषीकेशाय नमः',
    transliteration: 'Om Hrishikeshaya Namah',
    english_translation: 'Om, I bow to the lord of the senses.',
    tradition: 'vedic_vishnu',
    intention: 'Mastery',
    phonetic_guide: 'OHM hrish-ee-KAY-shah-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Hrishikesha — "lord of the senses" — is the name Arjuna uses when asking Krishna to be his charioteer in the Bhagavad Gita.',
    go_deeper_teaser: 'Mastery of the senses: the Bhagavad Gita\'s teaching →',
  },
  {
    day_of_year: 68,
    original_script: 'ॐ पद्मनाभाय नमः',
    transliteration: 'Om Padmanabhaya Namah',
    english_translation: 'Om, I bow to the one with a lotus in his navel — the source of creation.',
    tradition: 'vedic_vishnu',
    intention: 'Creation',
    phonetic_guide: 'OHM pahd-mah-NAH-bhah-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'From Vishnu\'s navel grows a lotus, and from that lotus emerges Brahma, the creator. The navel is the center of creative power.',
    go_deeper_teaser: 'The cosmic navel: creation from the center →',
  },
  {
    day_of_year: 69,
    original_script: 'ॐ दामोदराय नमः',
    transliteration: 'Om Damodaraya Namah',
    english_translation: 'Om, I bow to Damodara — the one bound by love.',
    tradition: 'vedic_vishnu',
    intention: 'Love',
    phonetic_guide: 'OHM dah-moh-DAH-rah-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Damodara — "rope around the belly" — refers to Krishna being tied by his mother Yashoda. Love is the only force that can bind the infinite.',
    go_deeper_teaser: 'How love binds even God: the Damodara story →',
  },
  {
    day_of_year: 70,
    original_script: 'ॐ सङ्कर्षणाय नमः',
    transliteration: 'Om Sankarshanaya Namah',
    english_translation: 'Om, I bow to Sankarshana — the one who draws all toward the divine.',
    tradition: 'vedic_vishnu',
    intention: 'Attraction',
    phonetic_guide: 'OHM sahn-kar-SHAH-nah-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Sankarshana is one of the four vyuha (emanation) forms of Vishnu, representing the attractive power of divine love.',
    go_deeper_teaser: 'The four vyuhas: Vishnu\'s cosmic emanations →',
  },
  {
    day_of_year: 71,
    original_script: 'ॐ प्रद्युम्नाय नमः',
    transliteration: 'Om Pradyumnaya Namah',
    english_translation: 'Om, I bow to Pradyumna — the supremely luminous one.',
    tradition: 'vedic_vishnu',
    intention: 'Radiance',
    phonetic_guide: 'OHM prahd-YOOM-nah-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Pradyumna — "supremely luminous" — is the son of Krishna and Rukmini, representing the mind aspect of the divine.',
    go_deeper_teaser: 'The luminous mind: how consciousness illuminates →',
  },
  {
    day_of_year: 72,
    original_script: 'ॐ अनिरुद्धाय नमः',
    transliteration: 'Om Aniruddhaya Namah',
    english_translation: 'Om, I bow to Aniruddha — the unstoppable one.',
    tradition: 'vedic_vishnu',
    intention: 'Unstoppability',
    phonetic_guide: 'OHM ah-nee-ROOD-dhah-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Aniruddha — "unstoppable" — represents the ego aspect of the divine that cannot be obstructed. Your true nature cannot be stopped.',
    go_deeper_teaser: 'Your unstoppable nature: removing inner obstacles →',
  },
  {
    day_of_year: 73,
    original_script: 'ॐ पुरुषोत्तमाय नमः',
    transliteration: 'Om Purushottamaya Namah',
    english_translation: 'Om, I bow to the supreme person — the highest self.',
    tradition: 'vedic_vishnu',
    intention: 'Excellence',
    phonetic_guide: 'OHM poo-roo-SHOH-tah-mah-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Purushottama — "supreme person" — is described in the 15th chapter of the Bhagavad Gita as the highest reality beyond both the perishable and imperishable.',
    go_deeper_teaser: 'The three purushhas: Gita chapter 15 explained →',
  },
  {
    day_of_year: 74,
    original_script: 'ॐ विश्वम्भराय नमः',
    transliteration: 'Om Vishwambharaya Namah',
    english_translation: 'Om, I bow to the one who sustains the entire universe.',
    tradition: 'vedic_vishnu',
    intention: 'Trust',
    phonetic_guide: 'OHM vish-wahm-BHAH-rah-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Vishwambhara — "sustainer of the universe" — reminds us that the same intelligence sustaining the cosmos is sustaining you.',
    go_deeper_teaser: 'Trusting the intelligence that runs the universe →',
  },
  {
    day_of_year: 75,
    original_script: 'ॐ जनार्दनाय नमः',
    transliteration: 'Om Janardanaya Namah',
    english_translation: 'Om, I bow to the one who gives joy to all people.',
    tradition: 'vedic_vishnu',
    intention: 'Service',
    phonetic_guide: 'OHM jah-nahr-DAH-nah-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Janardana — "one who gives joy to people" — is the name used when Krishna acts as the divine servant of humanity.',
    go_deeper_teaser: 'Seva: the yoga of selfless service →',
  },
  {
    day_of_year: 76,
    original_script: 'ॐ उपेन्द्राय नमः',
    transliteration: 'Om Upendraya Namah',
    english_translation: 'Om, I bow to Upendra — the younger brother of Indra.',
    tradition: 'vedic_vishnu',
    intention: 'Humility',
    phonetic_guide: 'OHM oo-PEN-drah-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Upendra — "junior Indra" — refers to Vamana avatar. The infinite chose to appear as the smallest, most humble form to teach the greatest lesson.',
    go_deeper_teaser: 'The power of appearing small: Vamana\'s teaching →',
  },
  {
    day_of_year: 77,
    original_script: 'ॐ वामनाय नमः',
    transliteration: 'Om Vamanaya Namah',
    english_translation: 'Om, I bow to Vamana — the dwarf avatar who measured the cosmos.',
    tradition: 'vedic_vishnu',
    intention: 'Humility',
    phonetic_guide: 'OHM vah-MAH-nah-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Vamana took three steps to measure earth, sky, and heaven — teaching that the infinite can appear in the smallest form.',
    go_deeper_teaser: 'Small appearances, infinite reality →',
  },
  {
    day_of_year: 78,
    original_script: 'ॐ श्रीनिवासाय नमः',
    transliteration: 'Om Shrinivasaya Namah',
    english_translation: 'Om, I bow to Shrinivasa — the abode of Shri (Lakshmi).',
    tradition: 'vedic_vishnu',
    intention: 'Abundance',
    phonetic_guide: 'OHM shree-nih-VAH-sah-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Shrinivasa — "dwelling place of Shri" — is the name of Vishnu at Tirupati, the most visited temple in the world.',
    go_deeper_teaser: 'Tirupati: why 100,000 people visit every day →',
  },
  {
    day_of_year: 79,
    original_script: 'ॐ रङ्गनाथाय नमः',
    transliteration: 'Om Ranganathaya Namah',
    english_translation: 'Om, I bow to Ranganatha — the lord of the stage of creation.',
    tradition: 'vedic_vishnu',
    intention: 'Presence',
    phonetic_guide: 'OHM rahn-gah-NAH-thah-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Ranganatha — "lord of the stage" — is Vishnu reclining on Ananta at Srirangam. The universe is his stage; we are his players.',
    go_deeper_teaser: 'Srirangam: the largest functioning temple in the world →',
  },
  {
    day_of_year: 80,
    original_script: 'ॐ वेङ्कटेशाय नमः',
    transliteration: 'Om Venkatesaya Namah',
    english_translation: 'Om, I bow to Venkatesa — the lord of Venkata hill.',
    tradition: 'vedic_vishnu',
    intention: 'Grace',
    phonetic_guide: 'OHM ven-kah-TAY-shah-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Venkatesa is Vishnu at Tirumala-Tirupati. Venkata means "destroyer of sins." This mantra is believed to grant all desires.',
    go_deeper_teaser: 'The seven hills of Tirupati and their meaning →',
  },
  {
    day_of_year: 81,
    original_script: 'ॐ गोपालाय नमः',
    transliteration: 'Om Gopalaya Namah',
    english_translation: 'Om, I bow to Gopala — the protector of cows and souls.',
    tradition: 'vedic_vishnu',
    intention: 'Nurturing',
    phonetic_guide: 'OHM goh-PAH-lah-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Gopala — "protector of cows" — is Krishna as the divine cowherd who tenderly cares for all beings under his protection.',
    go_deeper_teaser: 'The cow in Vedic tradition: why she is sacred →',
  },
  {
    day_of_year: 82,
    original_script: 'ॐ मुकुन्दाय नमः',
    transliteration: 'Om Mukundaya Namah',
    english_translation: 'Om, I bow to Mukunda — the giver of liberation.',
    tradition: 'vedic_vishnu',
    intention: 'Liberation',
    phonetic_guide: 'OHM moo-KOON-dah-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Mukunda — "giver of mukti (liberation)" — is one of Krishna\'s most powerful names. Chanting it is said to dissolve karmic bondage.',
    go_deeper_teaser: 'Mukti: the four types of liberation in Vedanta →',
  },
  {
    day_of_year: 83,
    original_script: 'ॐ मधुसूदनाय नमः',
    transliteration: 'Om Madhusudanaya Namah',
    english_translation: 'Om, I bow to Madhusudhana — the slayer of the demon Madhu.',
    tradition: 'vedic_vishnu',
    intention: 'Courage',
    phonetic_guide: 'OHM mah-dhoo-SOO-dah-nah-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Madhusudhana — "slayer of Madhu" — refers to Vishnu defeating the demon of delusion. This mantra destroys inner demons of doubt and fear.',
    go_deeper_teaser: 'The inner demons: what Vishnu really slays →',
  },
  {
    day_of_year: 84,
    original_script: 'ॐ त्रिविक्रमाय नमः',
    transliteration: 'Om Trivikramaya Namah',
    english_translation: 'Om, I bow to Trivikrama — the one who strode across the three worlds.',
    tradition: 'vedic_vishnu',
    intention: 'Expansion',
    phonetic_guide: 'OHM tree-vik-RAH-mah-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Trivikrama\'s three steps represent past, present, and future — or earth, atmosphere, and heaven. Consciousness encompasses all.',
    go_deeper_teaser: 'The three worlds and how to inhabit them all →',
  },
  {
    day_of_year: 85,
    original_script: 'ॐ वराहाय नमः',
    transliteration: 'Om Varahaya Namah',
    english_translation: 'Om, I bow to Varaha — the boar avatar who rescued the earth.',
    tradition: 'vedic_vishnu',
    intention: 'Rescue',
    phonetic_guide: 'OHM vah-RAH-hah-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Varaha lifted the earth from the cosmic ocean on his tusks. This mantra invokes the power to rescue what is precious from darkness.',
    go_deeper_teaser: 'The Varaha avatar: diving into darkness to save the earth →',
  },
  {
    day_of_year: 86,
    original_script: 'ॐ नृसिंहाय नमः',
    transliteration: 'Om Nrisimhaya Namah',
    english_translation: 'Om, I bow to Narasimha — the man-lion who protects devotees.',
    tradition: 'vedic_vishnu',
    intention: 'Protection',
    phonetic_guide: 'OHM nree-SIM-hah-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Narasimha burst from a pillar to protect Prahlada — teaching that the divine is present everywhere, in every atom, at every moment.',
    go_deeper_teaser: 'Prahlada\'s faith: the devotee who couldn\'t be killed →',
  },
  {
    day_of_year: 87,
    original_script: 'ॐ परशुरामाय नमः',
    transliteration: 'Om Parashuramaya Namah',
    english_translation: 'Om, I bow to Parashurama — the warrior sage with the axe.',
    tradition: 'vedic_vishnu',
    intention: 'Justice',
    phonetic_guide: 'OHM pah-rah-shoo-RAH-mah-yah nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Parashurama — "Rama with the axe" — is the sixth avatar who restored cosmic justice. Sometimes fierce action is the most compassionate response.',
    go_deeper_teaser: 'When compassion requires fierceness →',
  },
  {
    day_of_year: 88,
    original_script: 'ॐ बलराम नमोऽस्तु ते',
    transliteration: 'Om Balarama Namostu Te',
    english_translation: 'Om, I bow to Balarama — the strong one, Krishna\'s elder brother.',
    tradition: 'vedic_vishnu',
    intention: 'Strength',
    phonetic_guide: 'OHM bah-lah-RAH-mah nah-MOHS-too tay',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Balarama — "strong Rama" — is the eighth avatar, representing the strength that supports and protects the divine play of consciousness.',
    go_deeper_teaser: 'Balarama: the strength behind Krishna\'s play →',
  },
  {
    day_of_year: 89,
    original_script: 'ॐ कल्किने नमः',
    transliteration: 'Om Kalkine Namah',
    english_translation: 'Om, I bow to Kalki — the future avatar who restores righteousness.',
    tradition: 'vedic_vishnu',
    intention: 'Hope',
    phonetic_guide: 'OHM KAHL-kih-nay nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Kalki is the tenth and final avatar, yet to come — riding a white horse to restore dharma at the end of the Kali Yuga.',
    go_deeper_teaser: 'The Kali Yuga: are we living in the dark age? →',
  },
  {
    day_of_year: 90,
    original_script: 'ॐ दशावताराय नमः',
    transliteration: 'Om Dashavataraaya Namah',
    english_translation: 'Om, I bow to the ten avatars — the divine in all its forms.',
    tradition: 'vedic_vishnu',
    intention: 'Wholeness',
    phonetic_guide: 'OHM dah-shah-vah-TAH-rah-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'The ten avatars of Vishnu trace the evolution of consciousness from fish to human — a map of spiritual evolution across cosmic time.',
    go_deeper_teaser: 'Darwin and the Dashavatara: evolution in the Vedas →',
  },

  // ── VEDIC SHAKTI (days 91–113) ────────────────────────────────────────────
  {
    day_of_year: 91,
    original_script: 'ॐ ऐं ह्रीं क्लीं',
    transliteration: 'Om Aim Hrim Klim',
    english_translation: 'Om — the seed of Saraswati, Lakshmi, and Kali — wisdom, abundance, and transformation.',
    tradition: 'vedic_shakti',
    intention: 'Empowerment',
    phonetic_guide: 'OHM AIM hreem kleem',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Three bija mantras of the divine feminine: Aim (Saraswati/wisdom), Hrim (Lakshmi/heart), Klim (Kali/transformation). Together they invoke the full power of Shakti.',
    go_deeper_teaser: 'The three great goddesses and their bija mantras →',
  },
  {
    day_of_year: 92,
    original_script: 'ॐ दुर्गायै नमः',
    transliteration: 'Om Durgayai Namah',
    english_translation: 'Om, I bow to Durga — the invincible one who protects.',
    tradition: 'vedic_shakti',
    intention: 'Protection',
    phonetic_guide: 'OHM door-GAH-yay nah-MAH',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Durga — "the invincible" or "the one who is difficult to approach" — is the warrior goddess who defeats all forms of evil and ignorance.',
    go_deeper_teaser: 'Durga\'s nine forms: the Navadurga →',
  },
  {
    day_of_year: 93,
    original_script: 'ॐ काल्यै नमः',
    transliteration: 'Om Kalyai Namah',
    english_translation: 'Om, I bow to Kali — the dark mother who liberates through transformation.',
    tradition: 'vedic_shakti',
    intention: 'Transformation',
    phonetic_guide: 'OHM KAH-lyay nah-MAH',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Kali — "the dark one" or "time" — is the most powerful form of Shakti. She destroys ego and illusion to reveal the eternal self beneath.',
    go_deeper_teaser: 'Kali: the goddess who loves you enough to destroy your ego →',
  },
  {
    day_of_year: 94,
    original_script: 'ॐ श्रीं ह्रीं श्रीं',
    transliteration: 'Om Shrim Hrim Shrim',
    english_translation: 'Om — Lakshmi\'s seed — the heart — Lakshmi\'s seed again.',
    tradition: 'vedic_shakti',
    intention: 'Abundance',
    phonetic_guide: 'OHM shreem hreem shreem',
    sacred_geometry_type: 'lotus',
    context_note: 'Shrim is Lakshmi\'s bija — the seed of abundance, beauty, and grace. Hrim is the heart bija. Together they open the heart to receive.',
    go_deeper_teaser: 'Lakshmi\'s eight forms: the Ashtalakshmi →',
  },
  {
    day_of_year: 95,
    original_script: 'ॐ ऐं सरस्वत्यै नमः',
    transliteration: 'Om Aim Saraswatyai Namah',
    english_translation: 'Om, with the seed of wisdom, I bow to Saraswati.',
    tradition: 'vedic_shakti',
    intention: 'Wisdom',
    phonetic_guide: 'OHM AIM sah-rahs-WAHT-yay nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Saraswati — "the flowing one" — is the goddess of wisdom, learning, music, and the arts. Aim is her bija, activating the intellect.',
    go_deeper_teaser: 'Saraswati\'s four arms: the tools of wisdom →',
  },
  {
    day_of_year: 96,
    original_script: 'ॐ श्रीं महालक्ष्म्यै नमः',
    transliteration: 'Om Shrim Mahalakshmyai Namah',
    english_translation: 'Om, I bow to the great Lakshmi — the goddess of all abundance.',
    tradition: 'vedic_shakti',
    intention: 'Prosperity',
    phonetic_guide: 'OHM shreem mah-hah-LAHK-shmyay nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Mahalakshmi — "great Lakshmi" — is the supreme form of the goddess of abundance, encompassing all eight forms of wealth.',
    go_deeper_teaser: 'The eight forms of Lakshmi and what they offer →',
  },
  {
    day_of_year: 97,
    original_script: 'ॐ क्लीं काल्यै नमः',
    transliteration: 'Om Klim Kalyai Namah',
    english_translation: 'Om, with the seed of transformation, I bow to Kali.',
    tradition: 'vedic_shakti',
    intention: 'Release',
    phonetic_guide: 'OHM kleem KAH-lyay nah-MAH',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Klim is the bija of attraction and transformation. Combined with Kali\'s name, it invokes the power to release what no longer serves.',
    go_deeper_teaser: 'What Kali wants you to release →',
  },
  {
    day_of_year: 98,
    original_script: 'ॐ चण्डिकायै नमः',
    transliteration: 'Om Chandikayai Namah',
    english_translation: 'Om, I bow to Chandika — the fierce, passionate one.',
    tradition: 'vedic_shakti',
    intention: 'Passion',
    phonetic_guide: 'OHM chahn-dee-KAH-yay nah-MAH',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Chandika is the fierce form of Durga from the Devi Mahatmya. She embodies the passionate, unstoppable force of the divine feminine.',
    go_deeper_teaser: 'The Devi Mahatmya: the goddess\'s greatest battle →',
  },
  {
    day_of_year: 99,
    original_script: 'ॐ त्रिपुरसुन्दर्यै नमः',
    transliteration: 'Om Tripurasundaryai Namah',
    english_translation: 'Om, I bow to Tripurasundari — the beauty of the three worlds.',
    tradition: 'vedic_shakti',
    intention: 'Beauty',
    phonetic_guide: 'OHM tree-poo-rah-soon-DAH-ryay nah-MAH',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Tripurasundari — "beautiful in the three worlds" — is the supreme goddess of the Sri Vidya tradition, presiding over the Sri Yantra.',
    go_deeper_teaser: 'Sri Vidya: the highest Shakta tradition →',
  },
  {
    day_of_year: 100,
    original_script: 'ॐ भुवनेश्वर्यै नमः',
    transliteration: 'Om Bhuvaneshwaryai Namah',
    english_translation: 'Om, I bow to Bhuvaneshwari — the queen of the universe.',
    tradition: 'vedic_shakti',
    intention: 'Sovereignty',
    phonetic_guide: 'OHM bhoo-vah-naysh-WAH-ryay nah-MAH',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Bhuvaneshwari — "queen of the universe" — is the fourth of the ten Mahavidyas, representing the vast space of consciousness.',
    go_deeper_teaser: 'The ten Mahavidyas: the wisdom goddesses →',
  },
  {
    day_of_year: 101,
    original_script: 'ॐ भैरव्यै नमः',
    transliteration: 'Om Bhairavyai Namah',
    english_translation: 'Om, I bow to Bhairavi — the fierce, terrifying goddess of liberation.',
    tradition: 'vedic_shakti',
    intention: 'Fearlessness',
    phonetic_guide: 'OHM bhay-RAH-vyay nah-MAH',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Bhairavi — "the terrifying one" — is the fifth Mahavidya. Her terror is only for the ego; to the true self, she is pure love.',
    go_deeper_teaser: 'What we fear and why the goddess is not it →',
  },
  {
    day_of_year: 102,
    original_script: 'ॐ छिन्नमस्तायै नमः',
    transliteration: 'Om Chhinnamastayai Namah',
    english_translation: 'Om, I bow to Chhinnamasta — the self-decapitated goddess of sacrifice.',
    tradition: 'vedic_shakti',
    intention: 'Sacrifice',
    phonetic_guide: 'OHM chhin-nah-MAHS-tah-yay nah-MAH',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Chhinnamasta holds her own severed head, feeding her devotees with her blood. She teaches that the highest love is total self-giving.',
    go_deeper_teaser: 'The mystery of Chhinnamasta: love beyond the ego →',
  },
  {
    day_of_year: 103,
    original_script: 'ॐ धूमावत्यै नमः',
    transliteration: 'Om Dhumavatyai Namah',
    english_translation: 'Om, I bow to Dhumavati — the smoky widow goddess of dissolution.',
    tradition: 'vedic_shakti',
    intention: 'Acceptance',
    phonetic_guide: 'OHM dhoo-mah-VAH-tyay nah-MAH',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Dhumavati — "the smoky one" — represents the void after dissolution. She teaches acceptance of loss, old age, and the wisdom of emptiness.',
    go_deeper_teaser: 'The wisdom of emptiness: Dhumavati\'s gift →',
  },
  {
    day_of_year: 104,
    original_script: 'ॐ बगलामुख्यै नमः',
    transliteration: 'Om Bagalamukhai Namah',
    english_translation: 'Om, I bow to Bagalamukhi — the crane-faced goddess who paralyzes enemies.',
    tradition: 'vedic_shakti',
    intention: 'Power',
    phonetic_guide: 'OHM bah-gah-lah-MOOK-hyay nah-MAH',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Bagalamukhi — "crane-faced" — is the eighth Mahavidya who paralyzes negative forces. She stills the tongue of slander and the mind of confusion.',
    go_deeper_teaser: 'Bagalamukhi: the goddess who silences enemies →',
  },
  {
    day_of_year: 105,
    original_script: 'ॐ मातङ्ग्यै नमः',
    transliteration: 'Om Matangyai Namah',
    english_translation: 'Om, I bow to Matangi — the outcast goddess of inner wisdom.',
    tradition: 'vedic_shakti',
    intention: 'Authenticity',
    phonetic_guide: 'OHM mah-TAHN-gyay nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Matangi — the "outcast" or "elephant" goddess — is the ninth Mahavidya, representing wisdom that comes from outside conventional boundaries.',
    go_deeper_teaser: 'Matangi: the wisdom of the outcast →',
  },
  {
    day_of_year: 106,
    original_script: 'ॐ कमलायै नमः',
    transliteration: 'Om Kamalayai Namah',
    english_translation: 'Om, I bow to Kamala — the lotus goddess, the tantric Lakshmi.',
    tradition: 'vedic_shakti',
    intention: 'Grace',
    phonetic_guide: 'OHM kah-mah-LAH-yay nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Kamala — "lotus" — is the tenth Mahavidya, the tantric form of Lakshmi. She represents the fullness of grace and the beauty of pure consciousness.',
    go_deeper_teaser: 'The ten Mahavidyas: a complete map of divine feminine power →',
  },
  {
    day_of_year: 107,
    original_script: 'ॐ तारायै नमः',
    transliteration: 'Om Tarayai Namah',
    english_translation: 'Om, I bow to Tara — the star goddess who guides across the ocean of existence.',
    tradition: 'vedic_shakti',
    intention: 'Guidance',
    phonetic_guide: 'OHM TAH-rah-yay nah-MAH',
    sacred_geometry_type: 'star_of_life',
    context_note: 'Tara — "star" or "one who saves" — is the second Mahavidya and also a major Buddhist deity. She guides souls across the ocean of samsara.',
    go_deeper_teaser: 'Tara: the goddess shared by Hinduism and Buddhism →',
  },
  {
    day_of_year: 108,
    original_script: 'ॐ ऐं ह्रीं श्रीं त्रिपुर सुन्दरी',
    transliteration: 'Om Aim Hrim Shrim Tripura Sundari',
    english_translation: 'Om — wisdom, heart, abundance — beauty of the three worlds.',
    tradition: 'vedic_shakti',
    intention: 'Completeness',
    phonetic_guide: 'OHM AIM hreem shreem tree-POO-rah soon-DAH-ree',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Day 108 — the sacred number of the mala. This mantra combines the three great bija mantras with the supreme goddess of the Sri Yantra.',
    go_deeper_teaser: 'Why 108 is the most sacred number →',
  },
  {
    day_of_year: 109,
    original_script: 'ॐ नमो देव्यै महादेव्यै',
    transliteration: 'Om Namo Devyai Mahadevyai',
    english_translation: 'Om, I bow to the goddess, the great goddess.',
    tradition: 'vedic_shakti',
    intention: 'Reverence',
    phonetic_guide: 'OHM nah-MOH DAY-vyay mah-hah-DAY-vyay',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The opening invocation of the Devi Mahatmya — the most sacred text of the Shakta tradition, celebrating the goddess\'s cosmic victory.',
    go_deeper_teaser: 'The Devi Mahatmya: 700 verses of goddess power →',
  },
  {
    day_of_year: 110,
    original_script: 'या देवी सर्वभूतेषु',
    transliteration: 'Ya Devi Sarvabhuteshu',
    english_translation: 'The goddess who dwells in all beings...',
    tradition: 'vedic_shakti',
    intention: 'Omnipresence',
    phonetic_guide: 'yah DAY-vee sahr-vah-BHOO-tay-shoo',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'From the Devi Mahatmya. The full verse continues: "...in the form of consciousness, power, peace, faith, beauty, activity, memory, compassion, and error — I bow to her."',
    go_deeper_teaser: 'The goddess in all forms: the Devi Mahatmya\'s teaching →',
  },
  {
    day_of_year: 111,
    original_script: 'नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः',
    transliteration: 'Namastasyai Namastasyai Namastasyai Namo Namah',
    english_translation: 'I bow to her, I bow to her, I bow to her, I bow.',
    tradition: 'vedic_shakti',
    intention: 'Surrender',
    phonetic_guide: 'nah-mahs-TAHS-yay nah-mahs-TAHS-yay nah-mahs-TAHS-yay nah-MOH nah-MAH',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The refrain of the Devi Mahatmya. Triple repetition of surrender to the goddess — a complete act of devotion.',
    go_deeper_teaser: 'The power of triple repetition in mantra →',
  },
  {
    day_of_year: 112,
    original_script: 'ॐ शक्ति शक्ति शक्ति',
    transliteration: 'Om Shakti Shakti Shakti',
    english_translation: 'Om, power, power, power — the divine feminine energy.',
    tradition: 'vedic_shakti',
    intention: 'Power',
    phonetic_guide: 'OHM SHAHK-tee SHAHK-tee SHAHK-tee',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Shakti is the primordial energy of the universe — the force that animates all of creation. This mantra awakens your own inner Shakti.',
    go_deeper_teaser: 'Kundalini Shakti: the sleeping serpent power →',
  },
  {
    day_of_year: 113,
    original_script: 'ॐ जय माँ',
    transliteration: 'Om Jai Maa',
    english_translation: 'Om, victory to the Divine Mother.',
    tradition: 'vedic_shakti',
    intention: 'Devotion',
    phonetic_guide: 'OHM jay MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'The simplest and most heartfelt invocation of the Divine Mother. Maa — "mother" — is the most intimate name for the goddess.',
    go_deeper_teaser: 'The Divine Mother: the most intimate face of God →',
  },

  // ── VEDIC GANESHA (days 114–136) ──────────────────────────────────────────
  {
    day_of_year: 114,
    original_script: 'ॐ गं गणपतये नमः',
    transliteration: 'Om Gam Ganapataye Namah',
    english_translation: 'Om, with the seed of Ganesha, I bow to the lord of all beginnings.',
    tradition: 'vedic_ganesha',
    intention: 'New Beginnings',
    phonetic_guide: 'OHM gahm gah-nah-PAH-tah-yay nah-MAH',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Gam is Ganesha\'s bija mantra. Ganapati — "lord of the ganas" — is invoked at the beginning of every undertaking to remove obstacles.',
    go_deeper_teaser: 'Why Ganesha is invoked first in every ritual →',
  },
  {
    day_of_year: 115,
    original_script: 'ॐ नमो गणेशाय',
    transliteration: 'Om Namo Ganeshaya',
    english_translation: 'Om, I bow to Ganesha — the lord of hosts.',
    tradition: 'vedic_ganesha',
    intention: 'Beginnings',
    phonetic_guide: 'OHM nah-MOH gah-NAY-shah-yah',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Ganesha — "lord of the ganas" — is the remover of obstacles and the bestower of wisdom. He is invoked before all sacred activities.',
    go_deeper_teaser: 'Ganesha\'s elephant head: the wisdom of the big picture →',
  },
  {
    day_of_year: 116,
    original_script: 'ॐ विघ्नराजाय नमः',
    transliteration: 'Om Vighnarajaya Namah',
    english_translation: 'Om, I bow to the king of obstacles — who removes all impediments.',
    tradition: 'vedic_ganesha',
    intention: 'Obstacle Removal',
    phonetic_guide: 'OHM vig-nah-RAH-jah-yah nah-MAH',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Vighnaraja — "king of obstacles" — is Ganesha\'s paradoxical title. He both creates and removes obstacles, teaching that challenges are divine gifts.',
    go_deeper_teaser: 'Why Ganesha creates obstacles before removing them →',
  },
  {
    day_of_year: 117,
    original_script: 'ॐ एकदन्ताय नमः',
    transliteration: 'Om Ekadantaya Namah',
    english_translation: 'Om, I bow to the single-tusked one — the one who focuses on the essential.',
    tradition: 'vedic_ganesha',
    intention: 'Focus',
    phonetic_guide: 'OHM ay-kah-DAHN-tah-yah nah-MAH',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Ekadanta — "single tusk" — refers to Ganesha breaking off one tusk to write the Mahabharata. He teaches us to sacrifice the non-essential for the essential.',
    go_deeper_teaser: 'Why Ganesha broke his tusk to write the Mahabharata →',
  },
  {
    day_of_year: 118,
    original_script: 'ॐ लम्बोदराय नमः',
    transliteration: 'Om Lambodaraya Namah',
    english_translation: 'Om, I bow to the large-bellied one who contains all universes.',
    tradition: 'vedic_ganesha',
    intention: 'Abundance',
    phonetic_guide: 'OHM lahm-boh-DAH-rah-yah nah-MAH',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Lambodara — "large belly" — represents Ganesha\'s capacity to contain all of existence. His belly holds the entire cosmos.',
    go_deeper_teaser: 'Ganesha\'s belly: the universe within →',
  },
  {
    day_of_year: 119,
    original_script: 'ॐ विनायकाय नमः',
    transliteration: 'Om Vinayakaya Namah',
    english_translation: 'Om, I bow to Vinayaka — the supreme leader who guides without being led.',
    tradition: 'vedic_ganesha',
    intention: 'Leadership',
    phonetic_guide: 'OHM vih-nah-YAH-kah-yah nah-MAH',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Vinayaka — "supreme leader" or "one who has no master" — is Ganesha\'s most common name in South India.',
    go_deeper_teaser: 'True leadership: the Vinayaka principle →',
  },
  {
    day_of_year: 120,
    original_script: 'ॐ गजाननाय नमः',
    transliteration: 'Om Gajananaya Namah',
    english_translation: 'Om, I bow to the elephant-faced one.',
    tradition: 'vedic_ganesha',
    intention: 'Wisdom',
    phonetic_guide: 'OHM gah-jah-NAH-nah-yah nah-MAH',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Gajanana — "elephant-faced" — honors Ganesha\'s elephant head, which represents wisdom, memory, and the ability to remove obstacles with gentle power.',
    go_deeper_teaser: 'The elephant\'s wisdom: what Ganesha\'s head teaches →',
  },
  {
    day_of_year: 121,
    original_script: 'ॐ गणाधिपाय नमः',
    transliteration: 'Om Ganadhipaya Namah',
    english_translation: 'Om, I bow to the lord of all groups and communities.',
    tradition: 'vedic_ganesha',
    intention: 'Community',
    phonetic_guide: 'OHM gah-nah-dhih-PAH-yah nah-MAH',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Ganadhipa — "lord of groups" — honors Ganesha as the presiding deity of all communities, councils, and collective endeavors.',
    go_deeper_teaser: 'Sangha: the power of spiritual community →',
  },
  {
    day_of_year: 122,
    original_script: 'ॐ सिद्धिविनायकाय नमः',
    transliteration: 'Om Siddhivinayakaya Namah',
    english_translation: 'Om, I bow to Siddhivinayaka — the bestower of all accomplishments.',
    tradition: 'vedic_ganesha',
    intention: 'Achievement',
    phonetic_guide: 'OHM sid-dhih-vih-nah-YAH-kah-yah nah-MAH',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Siddhivinayaka — "bestower of siddhi" — is the most popular form of Ganesha in Mumbai. Siddhi means accomplishment, perfection, and supernatural power.',
    go_deeper_teaser: 'The eight siddhis: spiritual powers and how to use them →',
  },
  {
    day_of_year: 123,
    original_script: 'ॐ बुद्धिप्रियाय नमः',
    transliteration: 'Om Buddhipriyaya Namah',
    english_translation: 'Om, I bow to the one who loves intelligence.',
    tradition: 'vedic_ganesha',
    intention: 'Intelligence',
    phonetic_guide: 'OHM bood-dhih-PRIH-yah-yah nah-MAH',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Buddhipriya — "lover of intelligence" — honors Ganesha as the patron of learning, scholarship, and all forms of intellectual endeavor.',
    go_deeper_teaser: 'Ganesha as the patron of learning: the student\'s mantra →',
  },
  {
    day_of_year: 124,
    original_script: 'ॐ विद्याधिपाय नमः',
    transliteration: 'Om Vidyadhipaya Namah',
    english_translation: 'Om, I bow to the lord of all knowledge.',
    tradition: 'vedic_ganesha',
    intention: 'Knowledge',
    phonetic_guide: 'OHM vid-yah-dhih-PAH-yah nah-MAH',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Vidyadhipa — "lord of knowledge" — honors Ganesha as the supreme patron of all forms of learning, from the sacred to the mundane.',
    go_deeper_teaser: 'Para vidya and apara vidya: two kinds of knowledge →',
  },
  {
    day_of_year: 125,
    original_script: 'ॐ मूषकवाहनाय नमः',
    transliteration: 'Om Mushakavahanaya Namah',
    english_translation: 'Om, I bow to the one whose vehicle is the mouse.',
    tradition: 'vedic_ganesha',
    intention: 'Humility',
    phonetic_guide: 'OHM moo-shah-kah-VAH-hah-nah-yah nah-MAH',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Ganesha rides a mouse — the smallest of vehicles for the largest of gods. The mouse represents the ego: small, quick, and capable of gnawing through obstacles.',
    go_deeper_teaser: 'Why Ganesha rides a mouse: the paradox of power →',
  },
  {
    day_of_year: 126,
    original_script: 'ॐ मोदकप्रियाय नमः',
    transliteration: 'Om Modakapriyaya Namah',
    english_translation: 'Om, I bow to the one who loves modaka — the sweet of bliss.',
    tradition: 'vedic_ganesha',
    intention: 'Sweetness',
    phonetic_guide: 'OHM moh-dah-kah-PRIH-yah-yah nah-MAH',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Modaka — a sweet rice dumpling — is Ganesha\'s favorite offering. It represents the sweetness of spiritual realization.',
    go_deeper_teaser: 'Offering to Ganesha: the art of sacred giving →',
  },
  {
    day_of_year: 127,
    original_script: 'ॐ हेरम्बाय नमः',
    transliteration: 'Om Herambaya Namah',
    english_translation: 'Om, I bow to Heramba — the protector of the weak.',
    tradition: 'vedic_ganesha',
    intention: 'Protection',
    phonetic_guide: 'OHM hay-RAHM-bah-yah nah-MAH',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Heramba — "protector of the weak" — is a five-headed form of Ganesha who specifically protects those who are vulnerable or in difficulty.',
    go_deeper_teaser: 'Heramba: Ganesha\'s fierce protective form →',
  },
  {
    day_of_year: 128,
    original_script: 'ॐ महागणपतये नमः',
    transliteration: 'Om Mahaganapataye Namah',
    english_translation: 'Om, I bow to the great lord of all hosts.',
    tradition: 'vedic_ganesha',
    intention: 'Greatness',
    phonetic_guide: 'OHM mah-hah-gah-nah-PAH-tah-yay nah-MAH',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Mahaganapataye — "great Ganapati" — is the supreme form of Ganesha, combining all his powers and aspects into one.',
    go_deeper_teaser: 'The 32 forms of Ganesha: a complete guide →',
  },
  {
    day_of_year: 129,
    original_script: 'ॐ गणेशाय विद्महे',
    transliteration: 'Om Ganeshaya Vidmahe',
    english_translation: 'Om, may we know Ganesha.',
    tradition: 'vedic_ganesha',
    intention: 'Knowledge',
    phonetic_guide: 'OHM gah-NAY-shah-yah vid-MAH-hay',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'The opening of the Ganesha Gayatri — a prayer for direct knowledge of the remover of obstacles.',
    go_deeper_teaser: 'The Ganesha Gayatri: the most powerful Ganesha mantra →',
  },
  {
    day_of_year: 130,
    original_script: 'ॐ वक्रतुण्डाय धीमहि',
    transliteration: 'Om Vakratundaya Dhimahi',
    english_translation: 'Om, may we meditate on the curved-trunk one.',
    tradition: 'vedic_ganesha',
    intention: 'Meditation',
    phonetic_guide: 'OHM vahk-rah-TOON-dah-yah dhee-MAH-hee',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Vakratunda — "curved trunk" — honors Ganesha\'s trunk, which curves to pick up the sweetness of life. The second line of the Ganesha Gayatri.',
    go_deeper_teaser: 'Ganesha\'s trunk: the power of discernment →',
  },
  {
    day_of_year: 131,
    original_script: 'तन्नो दन्तिः प्रचोदयात्',
    transliteration: 'Tanno Dantih Prachodayat',
    english_translation: 'May the tusked one inspire and illuminate us.',
    tradition: 'vedic_ganesha',
    intention: 'Inspiration',
    phonetic_guide: 'tahn-NOH DAHN-tih prah-choh-DAH-yaht',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'The concluding line of the Ganesha Gayatri. Danti — "tusked one" — refers to Ganesha\'s single tusk, the pen that wrote the Mahabharata.',
    go_deeper_teaser: 'The Mahabharata: the world\'s longest poem →',
  },
  {
    day_of_year: 132,
    original_script: 'वक्रतुण्ड महाकाय',
    transliteration: 'Vakratunda Mahakaya',
    english_translation: 'O curved-trunk one, O great-bodied one...',
    tradition: 'vedic_ganesha',
    intention: 'Blessings',
    phonetic_guide: 'vahk-rah-TOON-dah mah-hah-KAH-yah',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'The opening of the most popular Ganesha shloka. The full verse: "O curved-trunk, great-bodied, brilliant as a million suns — remove all obstacles from my work, always."',
    go_deeper_teaser: 'The Vakratunda shloka: Ganesha\'s most popular prayer →',
  },
  {
    day_of_year: 133,
    original_script: 'सूर्यकोटि समप्रभ',
    transliteration: 'Suryakoti Samaprabha',
    english_translation: 'Brilliant as ten million suns.',
    tradition: 'vedic_ganesha',
    intention: 'Radiance',
    phonetic_guide: 'soor-yah-KOH-tee sah-mah-PRAH-bhah',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'The second line of the Vakratunda shloka. Ganesha\'s radiance is compared to ten million suns — the light of consciousness itself.',
    go_deeper_teaser: 'The light of consciousness: what Ganesha\'s radiance means →',
  },
  {
    day_of_year: 134,
    original_script: 'निर्विघ्नं कुरु मे देव',
    transliteration: 'Nirvighnam Kuru Me Deva',
    english_translation: 'O God, make my work free from obstacles.',
    tradition: 'vedic_ganesha',
    intention: 'Success',
    phonetic_guide: 'neer-VIG-nahm KOO-roo may DAY-vah',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'The third line of the Vakratunda shloka — a direct prayer for obstacle-free action. Nirvighna means "without obstacles."',
    go_deeper_teaser: 'Removing obstacles: the Ganesha principle in action →',
  },
  {
    day_of_year: 135,
    original_script: 'सर्वकार्येषु सर्वदा',
    transliteration: 'Sarvakaryeshu Sarvada',
    english_translation: 'In all endeavors, always.',
    tradition: 'vedic_ganesha',
    intention: 'Constancy',
    phonetic_guide: 'sahr-vah-KAH-ryay-shoo sahr-VAH-dah',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'The final line of the Vakratunda shloka. Sarvada — "always" — transforms the prayer into a constant, living invocation.',
    go_deeper_teaser: 'Living in constant prayer: the practice of remembrance →',
  },
  {
    day_of_year: 136,
    original_script: 'ॐ गं ॐ गं ॐ गं',
    transliteration: 'Om Gam Om Gam Om Gam',
    english_translation: 'Om, Ganesha\'s seed — three times — opening all doors.',
    tradition: 'vedic_ganesha',
    intention: 'Opening',
    phonetic_guide: 'OHM gahm OHM gahm OHM gahm',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'The simplest Ganesha practice: just his bija, three times. Gam activates the root chakra and opens the path ahead.',
    go_deeper_teaser: 'The root chakra and Ganesha: the foundation of practice →',
  },
];
