module.exports = [
  {
    day_of_year: 274,
    original_script: 'ਸਰਬ ਕਲਾ ਭਰਪੂਰ',
    transliteration: 'Sarab Kala Bharpoor',
    english_translation: 'Fully pervading all with all powers.',
    tradition: 'sikh',
    intention: 'Omnipresence',
    phonetic_guide: 'sah-RAHB kah-LAH bhar-POOR',
    context_note: 'From the Guru Granth Sahib. Sarab — "all" — Kala — "powers" — Bharpoor — "fully pervading." The divine is fully present everywhere with all its powers.',
    audio_filename: 'sarab_kala_bharpoor.mp3',
    go_deeper_teaser: 'The omnipresent God of the Guru Granth Sahib →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 275,
    original_script: 'ॐ',
    transliteration: 'Om',
    english_translation: 'The primordial sound — the vibration from which all creation arises.',
    tradition: 'universal',
    intention: 'Source',
    phonetic_guide: 'OHM (hold for 5-7 seconds)',
    context_note: 'Om is the first sound — the vibration of pure consciousness before it becomes words or thoughts. It contains all sounds within it.',
    audio_filename: 'om.mp3',
    go_deeper_teaser: 'The physics of Om: why it is the primordial sound →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 276,
    original_script: 'ॐ ॐ ॐ',
    transliteration: 'Om Om Om',
    english_translation: 'Three Oms — for body, speech, and mind.',
    tradition: 'universal',
    intention: 'Integration',
    phonetic_guide: 'OHM... OHM... OHM... (pause between each)',
    context_note: 'Three Oms purify the three aspects of our being: the physical body, speech and breath, and the mind. A complete practice in three sounds.',
    audio_filename: 'om_om_om.mp3',
    go_deeper_teaser: 'The three Oms: a complete purification practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 277,
    original_script: 'ॐ शान्तिः शान्तिः शान्तिः',
    transliteration: 'Om Shantih Shantih Shantih',
    english_translation: 'Om — peace, peace, peace.',
    tradition: 'universal',
    intention: 'Peace',
    phonetic_guide: 'OHM SHAHN-tih SHAHN-tih SHAHN-tih',
    context_note: 'The universal peace invocation ending all Vedic prayers. Three repetitions address the three sources of suffering: adhyatmika (self), adhibhautika (others), adhidaivika (cosmos).',
    audio_filename: 'om_shantih_shantih_s.mp3',
    go_deeper_teaser: 'The three sources of suffering and their antidote →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 278,
    original_script: 'सोऽहम्',
    transliteration: 'So\'ham',
    english_translation: 'I am that — the breath itself is the mantra.',
    tradition: 'universal',
    intention: 'Identity',
    phonetic_guide: 'SOH-hahm (So on inhale, Ham on exhale)',
    context_note: 'So\'ham is the natural sound of the breath: So on the inhale, Ham on the exhale. The breath itself is saying "I am that" 21,600 times per day.',
    audio_filename: 'soham.mp3',
    go_deeper_teaser: 'So\'ham: the mantra you\'ve been chanting since birth →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 279,
    original_script: 'हंसः',
    transliteration: 'Hamsa',
    english_translation: 'The swan — the breath — I am that.',
    tradition: 'universal',
    intention: 'Breath',
    phonetic_guide: 'HAHM-sah (Ham on exhale, Sa on inhale)',
    context_note: 'Hamsa — "swan" or "I am that" — is So\'ham reversed. The swan is the symbol of the discriminating mind that separates milk from water.',
    audio_filename: 'hamsa.mp3',
    go_deeper_teaser: 'Hamsa: the swan of discernment →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 280,
    original_script: 'अहम् ब्रह्मास्मि',
    transliteration: 'Aham Brahmasmi',
    english_translation: 'I am Brahman — I am the infinite.',
    tradition: 'universal',
    intention: 'Self-Realization',
    phonetic_guide: 'AH-hahm BRAH-mahs-mih',
    context_note: 'One of the four mahavakyas — great sayings — of the Upanishads. From the Brihadaranyaka Upanishad. The direct declaration of identity with the infinite.',
    audio_filename: 'aham_brahmasmi.mp3',
    go_deeper_teaser: 'The four mahavakyas: the Upanishads\' greatest declarations →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 281,
    original_script: 'तत् त्वम् असि',
    transliteration: 'Tat Tvam Asi',
    english_translation: 'That thou art — you are that infinite reality.',
    tradition: 'universal',
    intention: 'Non-Duality',
    phonetic_guide: 'taht tvahm AH-see',
    context_note: 'The second mahavakya from the Chandogya Upanishad. The teacher\'s declaration to the student: you are not separate from the infinite.',
    audio_filename: 'tat_tvam_asi.mp3',
    go_deeper_teaser: 'Tat tvam asi: the teaching that changes everything →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 282,
    original_script: 'प्रज्ञानं ब्रह्म',
    transliteration: 'Prajnanam Brahma',
    english_translation: 'Consciousness is Brahman — awareness is the infinite.',
    tradition: 'universal',
    intention: 'Consciousness',
    phonetic_guide: 'PRAHJ-nyah-nahm BRAH-mah',
    context_note: 'The third mahavakya from the Aitareya Upanishad. Prajna — "consciousness" or "awareness" — is identified with the infinite ground of being.',
    audio_filename: 'prajnanam_brahma.mp3',
    go_deeper_teaser: 'Consciousness as the ground of being →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 283,
    original_script: 'अयम् आत्मा ब्रह्म',
    transliteration: 'Ayam Atma Brahma',
    english_translation: 'This self is Brahman — the individual self is the universal self.',
    tradition: 'universal',
    intention: 'Unity',
    phonetic_guide: 'AH-yahm AHT-mah BRAH-mah',
    context_note: 'The fourth mahavakya from the Mandukya Upanishad. The individual self (atman) is declared identical to the universal ground of being (brahman). The simplest and most direct of the four great sayings.',
    audio_filename: 'ayam_atma_brahma.mp3',
    go_deeper_teaser: 'The four mahavakyas: the great declarations of non-duality →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 284,
    original_script: '',
    transliteration: 'Burn the mask or be buried in it',
    english_translation: 'Burn the mask or be buried in it',
    tradition: 'universal',
    intention: 'Liberation',
    phonetic_guide: '',
    context_note: 'Letting go is not loss — it is making space for grace. Every release is an act of trust in the divine unfolding of your life.',
    audio_filename: null,
    go_deeper_teaser: 'The sacred art of letting go →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 285,
    original_script: '',
    transliteration: 'I am not this body or mind',
    english_translation: 'I am not this body or mind',
    tradition: 'universal',
    intention: 'Courage',
    phonetic_guide: '',
    context_note: 'An open heart is the most powerful force in the universe. When you lead with love, fear dissolves like shadows in sunlight.',
    audio_filename: null,
    go_deeper_teaser: 'Why an open heart is your greatest strength →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 286,
    original_script: '',
    transliteration: 'The false self crumbles — I remain',
    english_translation: 'The false self crumbles — I remain',
    tradition: 'universal',
    intention: 'Surrender',
    phonetic_guide: '',
    context_note: 'Your life is not random — it is orchestrated by a wisdom far greater than the mind can comprehend. Trust the process.',
    audio_filename: null,
    go_deeper_teaser: 'Surrendering to divine timing →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 287,
    original_script: 'ॐ सच्चिदानन्द',
    transliteration: 'Om Satchidananda',
    english_translation: 'Om — existence, consciousness, bliss.',
    tradition: 'universal',
    intention: 'Bliss',
    phonetic_guide: 'OHM saht-chid-AH-nahn-dah',
    context_note: 'Sat-Chit-Ananda — the three qualities of Brahman: pure existence, pure consciousness, and pure bliss. This is the nature of ultimate reality.',
    audio_filename: 'om_satchidananda.mp3',
    go_deeper_teaser: 'Satchidananda: the nature of ultimate reality →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 288,
    original_script: '',
    transliteration: 'I invented this Me — I can dissolve it',
    english_translation: 'I invented this Me — I can dissolve it',
    tradition: 'universal',
    intention: 'Awareness',
    phonetic_guide: '',
    context_note: 'The moment you realize you are watching your thoughts, you have stepped into your true nature — pure consciousness itself.',
    audio_filename: null,
    go_deeper_teaser: 'The observer effect in spiritual practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 289,
    original_script: '',
    transliteration: 'Nothing real about me can be diminished',
    english_translation: 'Nothing real about me can be diminished',
    tradition: 'universal',
    intention: 'Inner Peace',
    phonetic_guide: '',
    context_note: 'Peace is not the absence of chaos — it is the presence of awareness. You can access it anywhere, anytime, by turning inward.',
    audio_filename: null,
    go_deeper_teaser: 'Finding peace in the eye of the storm →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 290,
    original_script: '',
    transliteration: 'I am nothing — and everything at once',
    english_translation: 'I am nothing — and everything at once',
    tradition: 'universal',
    intention: 'Unity',
    phonetic_guide: '',
    context_note: 'Separation is the great illusion. The same divine spark that animates your heart beats in every creature on Earth.',
    audio_filename: null,
    go_deeper_teaser: 'The Vedantic truth of oneness →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 291,
    original_script: '',
    transliteration: 'The ego served me — now I release it',
    english_translation: 'The ego served me — now I release it',
    tradition: 'universal',
    intention: 'Abundance',
    phonetic_guide: '',
    context_note: 'Abundance is not something you chase — it is something you align with. When you vibrate at the frequency of gratitude, abundance finds you.',
    audio_filename: null,
    go_deeper_teaser: 'Aligning with the flow of abundance →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 292,
    original_script: 'ॐ ऐं सरस्वत्यै नमः',
    transliteration: 'Om Aim Sarasvatyai Namah',
    english_translation: 'Om — seed of Saraswati — I bow to the goddess of wisdom.',
    tradition: 'universal',
    intention: 'Wisdom',
    phonetic_guide: 'OHM aim sah-rahs-VAHT-yay nah-MAH',
    context_note: 'Saraswati is the goddess of learning, music, and wisdom. Aim is her seed syllable. This mantra is chanted before study and creative work.',
    audio_filename: 'om_aim_sarasvatyai_n.mp3',
    go_deeper_teaser: 'Saraswati: the goddess of creative wisdom →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 293,
    original_script: 'ॐ दुं दुर्गायै नमः',
    transliteration: 'Om Dum Durgayai Namah',
    english_translation: 'Om — seed of Durga — I bow to the invincible one.',
    tradition: 'universal',
    intention: 'Courage',
    phonetic_guide: 'OHM doom door-GAH-yay nah-MAH',
    context_note: 'Durga — "the invincible" — is the warrior goddess who protects against all evil. Dum is her seed syllable. This mantra invokes inner strength.',
    audio_filename: 'om_dum_durgayai_nama.mp3',
    go_deeper_teaser: 'Durga: the warrior goddess within you →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 294,
    original_script: 'ॐ क्लीं कृष्णाय नमः',
    transliteration: 'Om Klim Krishnaya Namah',
    english_translation: 'Om — seed of attraction — I bow to Krishna.',
    tradition: 'universal',
    intention: 'Love',
    phonetic_guide: 'OHM kleem krish-NAH-yah nah-MAH',
    context_note: 'Klim is the seed syllable of attraction and love. This mantra invokes Krishna\'s quality of divine love — the love that draws all things toward the divine.',
    audio_filename: 'om_klim_krishnaya_na.mp3',
    go_deeper_teaser: 'Klim: the seed syllable of divine love →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 295,
    original_script: '',
    transliteration: 'I am the witness, not the chaos',
    english_translation: 'I am the witness, not the chaos',
    tradition: 'universal',
    intention: 'Self-Forgiveness',
    phonetic_guide: '',
    context_note: 'Self-forgiveness is not weakness — it is the bravest act of love. You cannot heal what you refuse to hold with compassion.',
    audio_filename: null,
    go_deeper_teaser: 'Why forgiveness is not what you think →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 296,
    original_script: 'ॐ तत् सत्',
    transliteration: 'Om Tat Sat',
    english_translation: 'Om — that — truth.',
    tradition: 'universal',
    intention: 'Truth',
    phonetic_guide: 'OHM taht saht',
    context_note: 'From the Bhagavad Gita. Om Tat Sat — the three designations of Brahman. Om is the sound, Tat is the pointer, Sat is the reality.',
    audio_filename: 'om_tat_sat.mp3',
    go_deeper_teaser: 'Om Tat Sat: the three names of the absolute →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 297,
    original_script: '',
    transliteration: 'The past is a cancelled check',
    english_translation: 'The past is a cancelled check',
    tradition: 'universal',
    intention: 'Self-Acceptance',
    phonetic_guide: '',
    context_note: 'The spiritual path is not about becoming someone new — it is about remembering who you have always been beneath the layers of conditioning.',
    audio_filename: null,
    go_deeper_teaser: 'The radical truth of self-acceptance →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 298,
    original_script: 'ॐ श्री रामाय नमः',
    transliteration: 'Om Sri Ramaya Namah',
    english_translation: 'Om — I bow to the radiant Ram.',
    tradition: 'universal',
    intention: 'Virtue',
    phonetic_guide: 'OHM shree RAH-mah-yah nah-MAH',
    context_note: 'Ram — "the one who delights" — is the avatar of Vishnu who embodies dharma. Sri adds radiance and auspiciousness to the invocation.',
    audio_filename: 'om_sri_ramaya_namah.mp3',
    go_deeper_teaser: 'Ram: the avatar of perfect virtue →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 299,
    original_script: 'राम राम राम',
    transliteration: 'Ram Ram Ram',
    english_translation: 'Ram, Ram, Ram — the name that is the Vedas.',
    tradition: 'universal',
    intention: 'Liberation',
    phonetic_guide: 'rahm rahm rahm',
    context_note: 'Gandhi\'s dying words were "Hey Ram." The name Ram is said to contain the essence of all the Vedas. Simple, direct, and infinitely deep.',
    audio_filename: 'ram_ram_ram.mp3',
    go_deeper_teaser: 'Why Gandhi\'s last words were "Hey Ram" →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 300,
    original_script: 'ॐ हनुमते नमः',
    transliteration: 'Om Hanumate Namah',
    english_translation: 'Om — I bow to Hanuman — the devoted servant.',
    tradition: 'universal',
    intention: 'Devotion',
    phonetic_guide: 'OHM hah-noo-MAH-tay nah-MAH',
    context_note: 'Hanuman is the embodiment of devotion, strength, and selfless service. His devotion to Ram is the model for all spiritual practice.',
    audio_filename: 'om_hanumate_namah.mp3',
    go_deeper_teaser: 'Hanuman: the perfect devotee →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 301,
    original_script: 'ॐ श्री हनुमते नमः',
    transliteration: 'Om Sri Hanumate Namah',
    english_translation: 'Om — I bow to the radiant Hanuman.',
    tradition: 'universal',
    intention: 'Strength',
    phonetic_guide: 'OHM shree hah-noo-MAH-tay nah-MAH',
    context_note: 'Hanuman\'s strength comes from his devotion — not from ego or personal power. This mantra invokes strength that is rooted in love.',
    audio_filename: 'om_sri_hanumate_nama.mp3',
    go_deeper_teaser: 'Strength through devotion: Hanuman\'s secret →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 302,
    original_script: '',
    transliteration: 'I release what is not me — I find peace',
    english_translation: 'I release what is not me — I find peace',
    tradition: 'universal',
    intention: 'Inner Wisdom',
    phonetic_guide: '',
    context_note: 'Every external teacher points you back to the same truth — the guru within. Your own consciousness is the ultimate guide.',
    audio_filename: null,
    go_deeper_teaser: 'The inner guru awakens →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 303,
    original_script: '',
    transliteration: 'Feel everything — then let it burn',
    english_translation: 'Feel everything — then let it burn',
    tradition: 'universal',
    intention: 'Presence',
    phonetic_guide: '',
    context_note: 'The breath is the bridge between body and spirit. Each conscious breath is a prayer, a return to the sacred now.',
    audio_filename: null,
    go_deeper_teaser: 'The sacred art of breathwork →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 304,
    original_script: '',
    transliteration: 'I forgive to reclaim my own freedom',
    english_translation: 'I forgive to reclaim my own freedom',
    tradition: 'universal',
    intention: 'Trust',
    phonetic_guide: '',
    context_note: 'You are never alone. The same force that spins galaxies and grows forests is holding you right now.',
    audio_filename: null,
    go_deeper_teaser: 'Trusting the cosmic embrace →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 305,
    original_script: '',
    transliteration: 'Bolt the door shut and walk away',
    english_translation: 'Bolt the door shut and walk away',
    tradition: 'universal',
    intention: 'Unconditional Love',
    phonetic_guide: '',
    context_note: 'Unconditional love is not something you practice — it is what you are when you stop pretending to be something else.',
    audio_filename: null,
    go_deeper_teaser: 'Love as spiritual practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 306,
    original_script: 'ॐ भूमि माता',
    transliteration: 'Om Bhumi Mata',
    english_translation: 'Om — Earth Mother.',
    tradition: 'universal',
    intention: 'Earth',
    phonetic_guide: 'OHM BHOO-mih MAH-tah',
    context_note: 'A universal invocation of the earth as mother. All spiritual traditions recognize the earth as sacred. We are born from her and return to her.',
    audio_filename: 'om_bhumi_mata.mp3',
    go_deeper_teaser: 'Earth as mother: the universal teaching →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 307,
    original_script: 'ॐ द्यौः पिता',
    transliteration: 'Om Dyauh Pita',
    english_translation: 'Om — Sky Father.',
    tradition: 'universal',
    intention: 'Sky',
    phonetic_guide: 'OHM dyow PIH-tah',
    context_note: 'The sky as father — the vast, open awareness that contains all experience. The earth is our mother; the sky is our father. We are children of both.',
    audio_filename: 'om_dyauh_pita.mp3',
    go_deeper_teaser: 'Sky and earth: the universal parents →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 308,
    original_script: 'ॐ अन्तरिक्षम्',
    transliteration: 'Om Antariksha',
    english_translation: 'Om — the space between — the intermediate realm.',
    tradition: 'universal',
    intention: 'Space',
    phonetic_guide: 'OHM ahn-TAH-rik-shahm',
    context_note: 'Antariksha — "the space between" — is the intermediate realm between earth and sky. It represents the liminal space of transformation.',
    audio_filename: 'om_antariksha.mp3',
    go_deeper_teaser: 'The space between: where transformation happens →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 309,
    original_script: '',
    transliteration: 'The deeper I go, the freer I become',
    english_translation: 'The deeper I go, the freer I become',
    tradition: 'universal',
    intention: 'Growth',
    phonetic_guide: '',
    context_note: 'The soul does not grow in comfort — it grows in the fire of transformation. Every difficulty is grace in disguise.',
    audio_filename: null,
    go_deeper_teaser: 'Transforming obstacles into awakening →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 310,
    original_script: '',
    transliteration: 'My shame is an imagined prison — dissolved',
    english_translation: 'My shame is an imagined prison — dissolved',
    tradition: 'universal',
    intention: 'Gratitude',
    phonetic_guide: '',
    context_note: 'Gratitude is not just a feeling — it is a frequency. When you vibrate with thankfulness, the entire universe conspires in your favor.',
    audio_filename: null,
    go_deeper_teaser: 'The transformative power of gratitude →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 311,
    original_script: '',
    transliteration: 'I owe the past exactly nothing',
    english_translation: 'I owe the past exactly nothing',
    tradition: 'universal',
    intention: 'Compassion',
    phonetic_guide: '',
    context_note: 'When you send love outward, it multiplies and returns to you a thousandfold. This is the law of the heart.',
    audio_filename: null,
    go_deeper_teaser: 'The ripple effect of compassion →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 312,
    original_script: '',
    transliteration: 'I release the debt ledger permanently',
    english_translation: 'I release the debt ledger permanently',
    tradition: 'universal',
    intention: 'Body Reverence',
    phonetic_guide: '',
    context_note: 'Your body is not separate from spirit — it is spirit made visible. Treat it with the reverence it deserves.',
    audio_filename: null,
    go_deeper_teaser: 'The body as spiritual technology →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 313,
    original_script: '',
    transliteration: 'Head to the forest — scream with abandon',
    english_translation: 'Head to the forest — scream with abandon',
    tradition: 'universal',
    intention: 'Equanimity',
    phonetic_guide: '',
    context_note: 'The ocean\'s surface may rage, but its depths remain forever still. You are that depth.',
    audio_filename: null,
    go_deeper_teaser: 'Finding your unshakable center →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 314,
    original_script: '',
    transliteration: 'Surrender everything — She is far more capable',
    english_translation: 'Surrender everything — She is far more capable',
    tradition: 'universal',
    intention: 'Healing',
    phonetic_guide: '',
    context_note: 'Healing is not something that happens to you — it is something that happens through you when you stop resisting the flow of grace.',
    audio_filename: null,
    go_deeper_teaser: 'The body\'s innate wisdom to heal →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 315,
    original_script: '',
    transliteration: 'Control is futile — I consent to the flow',
    english_translation: 'Control is futile — I consent to the flow',
    tradition: 'universal',
    intention: 'Truth',
    phonetic_guide: '',
    context_note: 'Truth is not a concept — it is a vibration. When you live in alignment with truth, every part of your life begins to harmonize.',
    audio_filename: null,
    go_deeper_teaser: 'Living in radical truth →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 316,
    original_script: '',
    transliteration: 'I lay my burdens at Her feet',
    english_translation: 'I lay my burdens at Her feet',
    tradition: 'universal',
    intention: 'Grace',
    phonetic_guide: '',
    context_note: 'You do not need to generate grace — you need only to stop blocking it. Remove the resistance, and grace floods in.',
    audio_filename: null,
    go_deeper_teaser: 'Becoming a vessel for grace →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 317,
    original_script: '',
    transliteration: 'I pray like my soul depends on it',
    english_translation: 'I pray like my soul depends on it',
    tradition: 'universal',
    intention: 'Transformation',
    phonetic_guide: '',
    context_note: 'Your deepest pain holds your greatest teaching. The soul chose these experiences not to punish you, but to awaken you.',
    audio_filename: null,
    go_deeper_teaser: 'The alchemy of suffering →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 318,
    original_script: 'ॐ लोकाः समस्ताः सुखिनो भवन्तु',
    transliteration: 'Om Lokah Samastah Sukhino Bhavantu',
    english_translation: 'Om — may all beings in all worlds be happy and free.',
    tradition: 'universal',
    intention: 'Universal Welfare',
    phonetic_guide: 'OHM LOH-kah sah-MAHS-tah soo-KHIH-noh bhah-VAHN-too',
    context_note: 'The most universal of all mantras. Lokah — "worlds" — Samastah — "all." This prayer extends to all beings in all dimensions of existence.',
    audio_filename: 'om_lokah_samastah_su.mp3',
    go_deeper_teaser: 'Lokah Samastah: the prayer that changes the world →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 319,
    original_script: '',
    transliteration: 'I am not the mayhem — I am potential',
    english_translation: 'I am not the mayhem — I am potential',
    tradition: 'universal',
    intention: 'Self-Realization',
    phonetic_guide: '',
    context_note: 'This is the core teaching of Vedanta — you are Brahman, the absolute reality. Everything else is appearance.',
    audio_filename: null,
    go_deeper_teaser: 'The Vedantic truth of who you are →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 320,
    original_script: '',
    transliteration: 'Grace is my birthright — not earned, claimed',
    english_translation: 'Grace is my birthright — not earned, claimed',
    tradition: 'universal',
    intention: 'Inner Guidance',
    phonetic_guide: '',
    context_note: 'Your soul has walked a thousand lifetimes. It knows things your mind cannot fathom. Learn to listen.',
    audio_filename: null,
    go_deeper_teaser: 'Listening to your soul\'s wisdom →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 321,
    original_script: '',
    transliteration: 'I let The Divine see me naked',
    english_translation: 'I let The Divine see me naked',
    tradition: 'universal',
    intention: 'Faith',
    phonetic_guide: '',
    context_note: 'Faith is not believing without evidence — it is trusting the evidence of your own direct experience of the divine.',
    audio_filename: null,
    go_deeper_teaser: 'The difference between belief and faith →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 322,
    original_script: '',
    transliteration: 'I consecrate my life — or keep suffering',
    english_translation: 'I consecrate my life — or keep suffering',
    tradition: 'universal',
    intention: 'Joy',
    phonetic_guide: '',
    context_note: 'Joy is not frivolous — it is your natural state. The guilt around joy is a learned pattern, not a spiritual truth.',
    audio_filename: null,
    go_deeper_teaser: 'Reclaiming your birthright of joy →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 323,
    original_script: 'ॐ ह्रीं',
    transliteration: 'Om Hrim',
    english_translation: 'Om — the maya bija — the seed of divine power.',
    tradition: 'universal',
    intention: 'Power',
    phonetic_guide: 'OHM hreem',
    context_note: 'Hrim is the bija (seed syllable) of the goddess — the sound of maya, the creative power of the divine. It is the most powerful single syllable after Om.',
    audio_filename: 'om_hrim.mp3',
    go_deeper_teaser: 'Hrim: the seed syllable of the goddess →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 324,
    original_script: 'ॐ श्रीं',
    transliteration: 'Om Shrim',
    english_translation: 'Om — the Lakshmi bija — the seed of abundance.',
    tradition: 'universal',
    intention: 'Abundance',
    phonetic_guide: 'OHM shreem',
    context_note: 'Shrim is the bija of Lakshmi — the sound of abundance, beauty, and grace. It attracts all forms of prosperity: material, emotional, and spiritual.',
    audio_filename: 'om_shrim.mp3',
    go_deeper_teaser: 'Shrim: the sound of abundance →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 325,
    original_script: 'ॐ ऐं',
    transliteration: 'Om Aim',
    english_translation: 'Om — the Saraswati bija — the seed of wisdom.',
    tradition: 'universal',
    intention: 'Wisdom',
    phonetic_guide: 'OHM aim (rhymes with "time")',
    context_note: 'Aim is the bija of Saraswati — the sound of wisdom, learning, and creative intelligence. It activates the higher mind.',
    audio_filename: 'om_aim.mp3',
    go_deeper_teaser: 'Aim: the seed syllable of wisdom →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 326,
    original_script: 'ॐ क्लीं',
    transliteration: 'Om Klim',
    english_translation: 'Om — the Kama bija — the seed of love and attraction.',
    tradition: 'universal',
    intention: 'Love',
    phonetic_guide: 'OHM kleem',
    context_note: 'Klim is the bija of Kama — divine love and attraction. It draws all good things toward you and opens the heart to love.',
    audio_filename: 'om_klim.mp3',
    go_deeper_teaser: 'Klim: the seed syllable of divine love →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 327,
    original_script: 'ॐ क्रीं',
    transliteration: 'Om Krim',
    english_translation: 'Om — the Kali bija — the seed of transformation.',
    tradition: 'universal',
    intention: 'Transformation',
    phonetic_guide: 'OHM kreem',
    context_note: 'Krim is the bija of Kali — the sound of radical transformation. It destroys what is false and reveals what is true.',
    audio_filename: 'om_krim.mp3',
    go_deeper_teaser: 'Krim: the seed syllable of transformation →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 328,
    original_script: 'ॐ हूँ',
    transliteration: 'Om Hum',
    english_translation: 'Om — the Shiva bija — the seed of fire and protection.',
    tradition: 'universal',
    intention: 'Protection',
    phonetic_guide: 'OHM hoom',
    context_note: 'Hum is the bija of Shiva — the sound of fire, protection, and the destruction of obstacles. It is also the seed of the awakened mind in Buddhism.',
    audio_filename: 'om_hum.mp3',
    go_deeper_teaser: 'Hum: the seed syllable of fire and protection →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 329,
    original_script: 'ॐ फट्',
    transliteration: 'Om Phat',
    english_translation: 'Om — the weapon bija — the sound that cuts through all obstacles.',
    tradition: 'universal',
    intention: 'Cutting Through',
    phonetic_guide: 'OHM phaht (sharp, explosive)',
    context_note: 'Phat is the weapon bija — the sound of a sword cutting through obstacles. It is used at the end of protective mantras to seal and strengthen them.',
    audio_filename: 'om_phat.mp3',
    go_deeper_teaser: 'The weapon mantras: cutting through obstacles →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 330,
    original_script: 'ॐ स्वाहा',
    transliteration: 'Om Svaha',
    english_translation: 'Om — so be it — I offer this.',
    tradition: 'universal',
    intention: 'Offering',
    phonetic_guide: 'OHM svah-HAH',
    context_note: 'Svaha is the offering bija — the sound of fire sacrifice. It seals all offerings and prayers, surrendering them to the divine.',
    audio_filename: 'om_svaha.mp3',
    go_deeper_teaser: 'Svaha: the sound of sacred offering →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 331,
    original_script: 'ॐ नमः',
    transliteration: 'Om Namah',
    english_translation: 'Om — I bow — I offer myself.',
    tradition: 'universal',
    intention: 'Surrender',
    phonetic_guide: 'OHM nah-MAH',
    context_note: 'Namah — "I bow" — is the most universal act of spiritual surrender. It is the recognition that the divine is greater than the ego.',
    audio_filename: 'om_namah.mp3',
    go_deeper_teaser: 'Namah: the power of bowing →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 332,
    original_script: 'ॐ नमस्ते',
    transliteration: 'Om Namaste',
    english_translation: 'Om — I bow to the divine in you.',
    tradition: 'universal',
    intention: 'Recognition',
    phonetic_guide: 'OHM nah-mahs-TAY',
    context_note: 'Namaste — "I bow to the divine in you" — is the recognition that every being is a form of the divine. This is the most radical spiritual teaching.',
    audio_filename: 'om_namaste.mp3',
    go_deeper_teaser: 'Namaste: the greeting that changes how you see the world →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 333,
    original_script: 'ॐ तत् त्वम् असि',
    transliteration: 'Om Tat Tvam Asi',
    english_translation: 'Om — that thou art — you are the infinite.',
    tradition: 'universal',
    intention: 'Non-Duality',
    phonetic_guide: 'OHM taht tvahm AH-see',
    context_note: 'Day 333 — a triple number — for the triple teaching: the teacher (Tat), the student (Tvam), and the identity between them (Asi).',
    audio_filename: 'om_tat_tvam_asi.mp3',
    go_deeper_teaser: 'The teacher-student relationship in non-dual wisdom →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 334,
    original_script: 'ॐ अयम् आत्मा ब्रह्म',
    transliteration: 'Om Ayam Atma Brahma',
    english_translation: 'Om — this self is Brahman.',
    tradition: 'universal',
    intention: 'Self-Realization',
    phonetic_guide: 'OHM AH-yahm AHT-mah BRAH-mah',
    context_note: 'The Mandukya Upanishad mahavakya. This self — the one reading these words right now — is the infinite. Not after enlightenment. Now.',
    audio_filename: 'om_ayam_atma_brahma.mp3',
    go_deeper_teaser: 'The Mandukya Upanishad: the shortest and deepest Upanishad →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 335,
    original_script: 'ॐ प्रज्ञानं ब्रह्म',
    transliteration: 'Om Prajnanam Brahma',
    english_translation: 'Om — consciousness is Brahman.',
    tradition: 'universal',
    intention: 'Consciousness',
    phonetic_guide: 'OHM PRAHJ-nyah-nahm BRAH-mah',
    context_note: 'The Aitareya Upanishad mahavakya. The very awareness that is reading these words is the infinite. Consciousness is not produced by the brain — it is the ground of being.',
    audio_filename: 'om_prajnanam_brahma.mp3',
    go_deeper_teaser: 'Consciousness: the hard problem and the Upanishadic answer →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 336,
    original_script: 'ॐ अहम् ब्रह्मास्मि',
    transliteration: 'Om Aham Brahmasmi',
    english_translation: 'Om — I am Brahman.',
    tradition: 'universal',
    intention: 'Identity',
    phonetic_guide: 'OHM AH-hahm BRAH-mahs-mih',
    context_note: 'The Brihadaranyaka Upanishad mahavakya. The most direct declaration of identity with the infinite. Not a belief — a recognition.',
    audio_filename: 'om_aham_brahmasmi.mp3',
    go_deeper_teaser: 'Aham Brahmasmi: the most radical statement in human history →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 337,
    original_script: '',
    transliteration: 'When I pray, The Universe prays for me',
    english_translation: 'When I pray, The Universe prays for me',
    tradition: 'universal',
    intention: 'Self-Love',
    phonetic_guide: '',
    context_note: 'The greatest love story is the one between you and your own soul. Stop searching outside for what has always been within.',
    audio_filename: null,
    go_deeper_teaser: 'The inner beloved awakens →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 338,
    original_script: '',
    transliteration: 'Sound moves matter — mantra moves consciousness',
    english_translation: 'Sound moves matter — mantra moves consciousness',
    tradition: 'universal',
    intention: 'Surrender',
    phonetic_guide: '',
    context_note: 'Control is the mind\'s attempt to manage fear. Surrender is the soul\'s invitation to dance with the divine.',
    audio_filename: null,
    go_deeper_teaser: 'The freedom in letting go →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 339,
    original_script: 'ॐ नित्यानन्द',
    transliteration: 'Om Nityananda',
    english_translation: 'Om — eternal bliss.',
    tradition: 'universal',
    intention: 'Bliss',
    phonetic_guide: 'OHM nih-TYAH-nahn-dah',
    context_note: 'Nityananda — "eternal bliss" — is the name of several great masters. It points to the bliss that is the natural state of the self, not dependent on circumstances.',
    audio_filename: 'om_nityananda.mp3',
    go_deeper_teaser: 'Nityananda: the eternal bliss that is your nature →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 340,
    original_script: 'ॐ परमानन्द',
    transliteration: 'Om Paramananda',
    english_translation: 'Om — supreme bliss.',
    tradition: 'universal',
    intention: 'Supreme Joy',
    phonetic_guide: 'OHM pah-rah-MAH-nahn-dah',
    context_note: 'Paramananda — "supreme bliss" — is the highest state of consciousness. It is not an experience that comes and goes but the very nature of pure awareness.',
    audio_filename: 'om_paramananda.mp3',
    go_deeper_teaser: 'Ananda: the bliss that is the nature of the self →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 341,
    original_script: 'ॐ सोऽहम् सोऽहम् सोऽहम्',
    transliteration: 'Om Soham Soham Soham',
    english_translation: 'Om — I am that, I am that, I am that.',
    tradition: 'universal',
    intention: 'Identity',
    phonetic_guide: 'OHM SOH-hahm SOH-hahm SOH-hahm',
    context_note: 'Triple Soham — the breath mantra repeated three times to deepen the recognition. With every breath, the universe is saying: "I am that."',
    audio_filename: 'om_soham_soham_soham.mp3',
    go_deeper_teaser: 'The breath as the teacher: the Soham practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 342,
    original_script: '',
    transliteration: 'I am a wild light — vast and unbound',
    english_translation: 'I am a wild light — vast and unbound',
    tradition: 'universal',
    intention: 'Wonder',
    phonetic_guide: '',
    context_note: 'This is not metaphor — this is physics. The iron in your blood, the calcium in your bones, all of it was born in stellar furnaces billions of years ago.',
    audio_filename: null,
    go_deeper_teaser: 'You are made of stardust — literally →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 343,
    original_script: '',
    transliteration: 'I Am That — Tat Tvam Asi',
    english_translation: 'I Am That — Tat Tvam Asi',
    tradition: 'universal',
    intention: 'Presence',
    phonetic_guide: '',
    context_note: 'The most powerful thing you can bring to any situation is your full, undivided presence. It is the rarest gift in the modern world.',
    audio_filename: null,
    go_deeper_teaser: 'The power of conscious presence →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 344,
    original_script: '',
    transliteration: 'I am divine electricity born of light',
    english_translation: 'I am divine electricity born of light',
    tradition: 'universal',
    intention: 'Liberation',
    phonetic_guide: '',
    context_note: 'You are not your history. You are the awareness that can observe that history and choose a different path forward.',
    audio_filename: null,
    go_deeper_teaser: 'Breaking free from karmic patterns →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 345,
    original_script: '',
    transliteration: 'Liberation isn\'t achieved — it\'s remembered',
    english_translation: 'Liberation isn\'t achieved — it\'s remembered',
    tradition: 'universal',
    intention: 'Integration',
    phonetic_guide: '',
    context_note: 'The parts of yourself you reject become the chains that bind you. The parts you embrace become the wings that free you.',
    audio_filename: null,
    go_deeper_teaser: 'Shadow work as spiritual practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 346,
    original_script: '',
    transliteration: 'I am not seeking freedom — I am freedom',
    english_translation: 'I am not seeking freedom — I am freedom',
    tradition: 'universal',
    intention: 'Meditation',
    phonetic_guide: '',
    context_note: 'Meditation is not about stopping thoughts — it is about discovering the vast silence that was always there, holding every thought like the sky holds clouds.',
    audio_filename: null,
    go_deeper_teaser: 'The space between thoughts →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 347,
    original_script: '',
    transliteration: 'I am whole, covered in removable layers',
    english_translation: 'I am whole, covered in removable layers',
    tradition: 'universal',
    intention: 'Rest',
    phonetic_guide: '',
    context_note: 'In a world that glorifies hustle, choosing rest is a radical act of self-love. Your soul needs space to integrate and renew.',
    audio_filename: null,
    go_deeper_teaser: 'The spiritual necessity of rest →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 348,
    original_script: '',
    transliteration: 'I was born through The Universe loving Itself',
    english_translation: 'I was born through The Universe loving Itself',
    tradition: 'universal',
    intention: 'Authenticity',
    phonetic_guide: '',
    context_note: 'The spiritual warrior does not hide behind walls — they stand in the open field of their own heart, undefended and unafraid.',
    audio_filename: null,
    go_deeper_teaser: 'The courage of radical openness →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 349,
    original_script: '',
    transliteration: 'I am unlimited in every direction — no exceptions',
    english_translation: 'I am unlimited in every direction — no exceptions',
    tradition: 'universal',
    intention: 'Trust',
    phonetic_guide: '',
    context_note: 'There are no wrong turns on the soul\'s journey. Every detour was a necessary lesson. You are right on time.',
    audio_filename: null,
    go_deeper_teaser: 'Trusting your soul\'s perfect timing →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 350,
    original_script: '',
    transliteration: 'My emptiness is consciousness awaiting freedom',
    english_translation: 'My emptiness is consciousness awaiting freedom',
    tradition: 'universal',
    intention: 'Transmutation',
    phonetic_guide: '',
    context_note: 'The breath is the most powerful tool for emotional alchemy. Use it consciously and watch your inner world transform.',
    audio_filename: null,
    go_deeper_teaser: 'Breathwork as emotional alchemy →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 351,
    original_script: '',
    transliteration: 'I am the source and the signal',
    english_translation: 'I am the source and the signal',
    tradition: 'universal',
    intention: 'Perspective',
    phonetic_guide: '',
    context_note: 'This is the essence of Vedantic teaching — you are not the passing phenomena, you are the eternal substrate upon which all phenomena arise.',
    audio_filename: null,
    go_deeper_teaser: 'The ocean of consciousness →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 352,
    original_script: '',
    transliteration: 'I stop pretending — I remember who I am',
    english_translation: 'I stop pretending — I remember who I am',
    tradition: 'universal',
    intention: 'Self-Honor',
    phonetic_guide: '',
    context_note: 'Comparison is the thief of joy and the enemy of spiritual growth. Your soul chose this exact path for reasons only it understands.',
    audio_filename: null,
    go_deeper_teaser: 'Their highlight reel vs your raw footage →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 353,
    original_script: 'ॐ नमो गुरवे',
    transliteration: 'Om Namo Gurave',
    english_translation: 'Om — I bow to the Guru.',
    tradition: 'universal',
    intention: 'Gratitude',
    phonetic_guide: 'OHM nah-MOH GOO-rah-vay',
    context_note: 'A simple, direct bow to the teacher. The Guru is not a person — the Guru is the principle of awakening that appears in many forms.',
    audio_filename: 'om_namo_gurave.mp3',
    go_deeper_teaser: 'The Guru principle: beyond the personal teacher →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 354,
    original_script: 'ॐ सर्वे भवन्तु सुखिनः सर्वे सन्तु निरामयाः',
    transliteration: 'Om Sarve Bhavantu Sukhinah Sarve Santu Niramayah',
    english_translation: 'Om — may all be happy — may all be free from disease.',
    tradition: 'universal',
    intention: 'Universal Welfare',
    phonetic_guide: 'OHM SAHR-vay bhah-VAHN-too soo-KHIH-nah SAHR-vay SAHN-too nih-rah-MAH-yah',
    context_note: 'The first two lines of the universal prayer together. As the year nears its end, we return to the most basic wish: may all be happy and free from suffering.',
    audio_filename: 'om_sarve_bhavantu_su.mp3',
    go_deeper_teaser: 'The universal prayer as a year-end practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 355,
    original_script: 'सर्वे भद्राणि पश्यन्तु मा कश्चिद् दुःखभाग् भवेत्',
    transliteration: 'Sarve Bhadrani Pashyantu Ma Kashchid Duhkhabhag Bhavet',
    english_translation: 'May all see what is auspicious — may no one suffer.',
    tradition: 'universal',
    intention: 'Compassion',
    phonetic_guide: 'SAHR-vay BHAHD-rah-nih PAHSH-yahn-too mah KAHSH-chid DOOH-khah-bhahg BHAH-vayt',
    context_note: 'The final two lines of the universal prayer together. The complete prayer for all beings in four wishes.',
    audio_filename: 'sarve_bhadrani_pashy.mp3',
    go_deeper_teaser: 'The complete universal prayer: a year-end reflection →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 356,
    original_script: '',
    transliteration: 'Faking it is a spiritual disease',
    english_translation: 'Faking it is a spiritual disease',
    tradition: 'universal',
    intention: 'Wonder',
    phonetic_guide: '',
    context_note: 'The probability of you existing exactly as you are is essentially zero — and yet here you are. You are the universe\'s way of knowing itself.',
    audio_filename: null,
    go_deeper_teaser: 'The miracle of your existence →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 357,
    original_script: 'ॐ असतो मा सद्गमय तमसो मा ज्योतिर्गमय',
    transliteration: 'Om Asato Ma Sadgamaya Tamaso Ma Jyotirgamaya',
    english_translation: 'Om — lead me from unreal to real — from darkness to light.',
    tradition: 'universal',
    intention: 'Awakening',
    phonetic_guide: 'OHM ah-SAH-toh mah sahd-GAH-mah-yah tah-MAH-soh mah JYOH-tir-gah-mah-yah',
    context_note: 'The first two lines of the Pavamana Mantra together. As the year ends, we renew the prayer: lead me from what is false to what is true.',
    audio_filename: 'om_asato_ma_sadgamay.mp3',
    go_deeper_teaser: 'The Pavamana Mantra: the three great transitions →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 358,
    original_script: 'मृत्योर्मा अमृतं गमय ॐ शान्तिः शान्तिः शान्तिः',
    transliteration: 'Mrityorma Amritam Gamaya Om Shantih Shantih Shantih',
    english_translation: 'Lead me from death to immortality — Om peace, peace, peace.',
    tradition: 'universal',
    intention: 'Immortality',
    phonetic_guide: 'mrih-TYOR-mah AHM-rih-tahm GAH-mah-yah OHM SHAHN-tih SHAHN-tih SHAHN-tih',
    context_note: 'The complete Pavamana Mantra with its closing peace invocation. The three prayers and the three peaces — a complete practice.',
    audio_filename: 'mrityorma_amritam_ga.mp3',
    go_deeper_teaser: 'The complete Pavamana Mantra: a year-end practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 359,
    original_script: '',
    transliteration: 'I rip the mask off my polite spiritual act',
    english_translation: 'I rip the mask off my polite spiritual act',
    tradition: 'universal',
    intention: 'Wholeness',
    phonetic_guide: '',
    context_note: 'The word \'holy\' comes from the same root as \'whole.\' To be holy is simply to be complete — and you already are.',
    audio_filename: null,
    go_deeper_teaser: 'Remembering your original wholeness →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 360,
    original_script: '',
    transliteration: 'My fire is not an obstacle — it\'s fuel',
    english_translation: 'My fire is not an obstacle — it\'s fuel',
    tradition: 'universal',
    intention: 'Namaste',
    phonetic_guide: '',
    context_note: 'Namaste in action — recognizing the divine in every face you encounter. Their light does not diminish yours; it amplifies it.',
    audio_filename: null,
    go_deeper_teaser: 'Seeing the divine in everyone →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 361,
    original_script: '',
    transliteration: 'I let the world fall apart — I stay real',
    english_translation: 'I let the world fall apart — I stay real',
    tradition: 'universal',
    intention: 'Self-Knowledge',
    phonetic_guide: '',
    context_note: 'This is the English expression of the highest Vedantic truth. You are not seeking bliss — you ARE bliss, temporarily forgetting itself.',
    audio_filename: null,
    go_deeper_teaser: 'Sat-Chit-Ananda: your true nature →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 362,
    original_script: 'ॐ शिवोऽहम् शिवोऽहम्',
    transliteration: 'Om Shivoham Shivoham',
    english_translation: 'Om — I am Shiva, I am Shiva.',
    tradition: 'universal',
    intention: 'Identity',
    phonetic_guide: 'OHM shih-VOH-hahm shih-VOH-hahm',
    context_note: 'Day 362 — four days from the end. The recognition deepens: not just "I am that" but "I am Shiva" — pure consciousness, pure bliss, pure awareness.',
    audio_filename: 'om_shivoham_shivoham.mp3',
    go_deeper_teaser: 'The recognition that deepens with practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 363,
    original_script: '',
    transliteration: 'I am done shrinking for anyone\'s comfort',
    english_translation: 'I am done shrinking for anyone\'s comfort',
    tradition: 'universal',
    intention: 'Being',
    phonetic_guide: '',
    context_note: 'The most ancient declaration of truth, found in every wisdom tradition. Not I am this or that — simply I AM.',
    audio_filename: null,
    go_deeper_teaser: 'The power of pure being →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 364,
    original_script: '',
    transliteration: 'I speak like I\'m casting my next incarnation',
    english_translation: 'I speak like I\'m casting my next incarnation',
    tradition: 'universal',
    intention: 'Renewal',
    phonetic_guide: '',
    context_note: 'Every sunrise is an invitation to start fresh. No matter what yesterday held, today you can choose love again.',
    audio_filename: null,
    go_deeper_teaser: 'The gift of new beginnings →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 365,
    original_script: '',
    transliteration: 'Every word is a boomerang — I speak liberation',
    english_translation: 'Every word is a boomerang — I speak liberation',
    tradition: 'universal',
    intention: 'Completion',
    phonetic_guide: '',
    context_note: 'The final mantra of the year — a recognition that the entire journey was a circle leading you back to yourself. You are home.',
    audio_filename: null,
    go_deeper_teaser: 'The journey home to yourself →',
    go_deeper_url: 'https://paulwagner.com',
  },
];
