// Minute Mantra — Part 1 of 4
// Days 1-91
// Auto-generated from mantras.json

module.exports = [
  {
    day_of_year: 1,
    original_script: 'ॐ नमः शिवाय',
    transliteration: 'Om Namah Shivaya',
    english_translation: 'I bow to Shiva — the auspicious one, the pure consciousness within all.',
    tradition: 'vedic_shiva',
    intention: 'Purification',
    phonetic_guide: 'OHM nah-MAH shih-VAH-yah',
    context_note: 'The Panchakshara mantra — five sacred syllables representing the five elements. The most widely chanted Shaivite mantra.',
    audio_filename: 'mantra-001.mp3',
    go_deeper_teaser: 'Why Om Namah Shivaya changes your nervous system →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 2,
    original_script: 'ॐ त्र्यम्बकं यजामहे',
    transliteration: 'Om Tryambakam Yajamahe',
    english_translation: 'We worship the three-eyed one who nourishes and liberates us from the bondage of death.',
    tradition: 'vedic_shiva',
    intention: 'Healing',
    phonetic_guide: 'OHM tree-AHM-bah-kahm yah-JAH-mah-hay',
    context_note: 'The Maha Mrityunjaya mantra from the Rigveda. Chanted for healing, longevity, and liberation from fear.',
    audio_filename: 'mantra-002.mp3',
    go_deeper_teaser: 'The science of the Maha Mrityunjaya mantra →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 3,
    original_script: 'ॐ नमः शिवाय शुभम् शुभम् करु',
    transliteration: 'Om Namah Shivaya Shubham Shubham Kuru',
    english_translation: 'Om, I bow to Shiva — bring auspiciousness, bring auspiciousness.',
    tradition: 'vedic_shiva',
    intention: 'Blessings',
    phonetic_guide: 'OHM nah-MAH shih-VAH-yah SHOO-bahm SHOO-bahm KOO-roo',
    context_note: 'An expanded form of the Panchakshara invoking blessings and positive energy into daily life.',
    audio_filename: 'mantra-003.mp3',
    go_deeper_teaser: 'Morning mantras that shift your entire day →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 4,
    original_script: 'शिवोऽहम् शिवोऽहम्',
    transliteration: 'Shivo\'ham Shivo\'ham',
    english_translation: 'I am Shiva. I am Shiva.',
    tradition: 'vedic_shiva',
    intention: 'Self-realization',
    phonetic_guide: 'shih-VOH-hahm shih-VOH-hahm',
    context_note: 'From Adi Shankaracharya\'s Nirvana Shatakam. A direct affirmation of identity with pure consciousness.',
    audio_filename: 'mantra-004.mp3',
    go_deeper_teaser: 'The Nirvana Shatakam: Shankara\'s greatest poem →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 5,
    original_script: 'ॐ हौं जूं सः',
    transliteration: 'Om Haum Jum Sah',
    english_translation: 'Om — the seed of Shiva — the seed of life — I am that.',
    tradition: 'vedic_shiva',
    intention: 'Vitality',
    phonetic_guide: 'OHM howm joom sah',
    context_note: 'The Maha Mrityunjaya bija mantra. Haum is the seed syllable of Shiva; Jum is the seed of life force.',
    audio_filename: 'mantra-005.mp3',
    go_deeper_teaser: 'Bija mantras: seeds of cosmic power →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 6,
    original_script: 'ॐ नमः शिवाय नमः',
    transliteration: 'Om Namah Shivaya Namah',
    english_translation: 'Om, I bow to Shiva, I bow.',
    tradition: 'vedic_shiva',
    intention: 'Devotion',
    phonetic_guide: 'OHM nah-MAH shih-VAH-yah nah-MAH',
    context_note: 'An extended form adding a second namah — deepening the gesture of surrender and reverence.',
    audio_filename: 'mantra-006.mp3',
    go_deeper_teaser: 'What surrender really means in spiritual practice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 7,
    original_script: 'ॐ शं शिवाय नमः',
    transliteration: 'Om Sham Shivaya Namah',
    english_translation: 'Om, I bow to Shiva who brings peace and auspiciousness.',
    tradition: 'vedic_shiva',
    intention: 'Peace',
    phonetic_guide: 'OHM shahm shih-VAH-yah nah-MAH',
    context_note: 'Sham is the bija of peace and cooling. This mantra soothes the nervous system and calms mental agitation.',
    audio_filename: 'mantra-007.mp3',
    go_deeper_teaser: 'How mantra activates the parasympathetic nervous system →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 8,
    original_script: 'ॐ शिव शक्ति नमः',
    transliteration: 'Om Shiva Shakti Namah',
    english_translation: 'Om, I bow to the union of Shiva and Shakti — consciousness and energy.',
    tradition: 'vedic_shiva',
    intention: 'Balance',
    phonetic_guide: 'OHM SHIH-vah SHAHK-tee nah-MAH',
    context_note: 'Shiva is pure awareness; Shakti is the dynamic energy of creation. Their union is the source of all existence.',
    audio_filename: 'mantra-008.mp3',
    go_deeper_teaser: 'The sacred marriage: Shiva and Shakti explained →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 9,
    original_script: 'ॐ महादेवाय नमः',
    transliteration: 'Om Mahadevaya Namah',
    english_translation: 'Om, I bow to the Great God — the supreme deity.',
    tradition: 'vedic_shiva',
    intention: 'Reverence',
    phonetic_guide: 'OHM mah-hah-DAY-vah-yah nah-MAH',
    context_note: 'Mahadeva means "Great God" — one of Shiva\'s most exalted names, honoring his supremacy among the devas.',
    audio_filename: 'mantra-009.mp3',
    go_deeper_teaser: 'The 108 names of Shiva and their meanings →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 10,
    original_script: 'ॐ नीलकण्ठाय नमः',
    transliteration: 'Om Nilakanthaya Namah',
    english_translation: 'Om, I bow to the blue-throated one who swallowed poison to save the world.',
    tradition: 'vedic_shiva',
    intention: 'Courage',
    phonetic_guide: 'OHM nee-lah-KAHN-thah-yah nah-MAH',
    context_note: 'Nilakantha — "blue throat" — refers to Shiva holding the cosmic poison in his throat to protect all beings. A mantra of fearless compassion.',
    audio_filename: 'mantra-010.mp3',
    go_deeper_teaser: 'The churning of the ocean: Shiva\'s greatest sacrifice →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 11,
    original_script: 'ॐ नटराजाय नमः',
    transliteration: 'Om Natarajaya Namah',
    english_translation: 'Om, I bow to the Lord of the Cosmic Dance.',
    tradition: 'vedic_shiva',
    intention: 'Flow',
    phonetic_guide: 'OHM nah-tah-RAH-jah-yah nah-MAH',
    context_note: 'Nataraja — Shiva as the cosmic dancer — represents the continuous cycles of creation, preservation, and dissolution.',
    audio_filename: 'mantra-011.mp3',
    go_deeper_teaser: 'Nataraja: the physics of the cosmic dance →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 12,
    original_script: 'ॐ पशुपतये नमः',
    transliteration: 'Om Pashupataye Namah',
    english_translation: 'Om, I bow to the Lord of all creatures.',
    tradition: 'vedic_shiva',
    intention: 'Compassion',
    phonetic_guide: 'OHM pah-shoo-PAH-tah-yay nah-MAH',
    context_note: 'Pashupati — "Lord of animals" — honors Shiva as the protector of all sentient beings, from the smallest creature to the greatest.',
    audio_filename: 'mantra-012.mp3',
    go_deeper_teaser: 'Shiva as the original animal protector →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 13,
    original_script: 'ॐ भवाय नमः',
    transliteration: 'Om Bhavaya Namah',
    english_translation: 'Om, I bow to the source of all existence.',
    tradition: 'vedic_shiva',
    intention: 'Gratitude',
    phonetic_guide: 'OHM bhah-VAH-yah nah-MAH',
    context_note: 'Bhava means "being" or "existence." This name honors Shiva as the ground of all being — the very fact that anything exists at all.',
    audio_filename: 'mantra-013.mp3',
    go_deeper_teaser: 'The miracle of existence: why being here matters →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 14,
    original_script: 'ॐ रुद्राय नमः',
    transliteration: 'Om Rudraya Namah',
    english_translation: 'Om, I bow to Rudra — the fierce one who removes suffering.',
    tradition: 'vedic_shiva',
    intention: 'Release',
    phonetic_guide: 'OHM ROOD-rah-yah nah-MAH',
    context_note: 'Rudra is Shiva\'s Vedic form — the howling storm god who destroys what no longer serves. Chanting this releases stuck energy.',
    audio_filename: 'mantra-014.mp3',
    go_deeper_teaser: 'Rudra: the sacred power of divine anger →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 15,
    original_script: 'ॐ शंकराय नमः',
    transliteration: 'Om Shankaraya Namah',
    english_translation: 'Om, I bow to the one who brings blessings and auspiciousness.',
    tradition: 'vedic_shiva',
    intention: 'Blessings',
    phonetic_guide: 'OHM shahn-KAH-rah-yah nah-MAH',
    context_note: 'Shankara — "conferring happiness" — is one of Shiva\'s most beloved names. This mantra opens the heart to receive grace.',
    audio_filename: 'mantra-015.mp3',
    go_deeper_teaser: 'Opening to grace: the practice of receptivity →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 16,
    original_script: 'ॐ गिरीशाय नमः',
    transliteration: 'Om Girishaya Namah',
    english_translation: 'Om, I bow to the Lord of the mountains.',
    tradition: 'vedic_shiva',
    intention: 'Stability',
    phonetic_guide: 'OHM gih-REE-shah-yah nah-MAH',
    context_note: 'Girisha — "mountain lord" — honors Shiva\'s home on Mount Kailash. Mountains represent the immovable foundation of consciousness.',
    audio_filename: 'mantra-016.mp3',
    go_deeper_teaser: 'Mount Kailash: the axis of the world →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 17,
    original_script: 'ॐ भोलेनाथाय नमः',
    transliteration: 'Om Bholenathaya Namah',
    english_translation: 'Om, I bow to the innocent lord — the simple-hearted one.',
    tradition: 'vedic_shiva',
    intention: 'Simplicity',
    phonetic_guide: 'OHM boh-lay-NAH-thah-yah nah-MAH',
    context_note: 'Bholenath — "innocent lord" — is a beloved folk name for Shiva. He is easily pleased by sincere devotion, however simple.',
    audio_filename: 'mantra-017.mp3',
    go_deeper_teaser: 'Why Shiva is the easiest god to please →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 18,
    original_script: 'ॐ विश्वनाथाय नमः',
    transliteration: 'Om Vishwanathaya Namah',
    english_translation: 'Om, I bow to the Lord of the universe.',
    tradition: 'vedic_shiva',
    intention: 'Expansion',
    phonetic_guide: 'OHM vish-wah-NAH-thah-yah nah-MAH',
    context_note: 'Vishwanath — "Lord of all worlds" — is the presiding deity of Varanasi, the oldest living city on earth.',
    audio_filename: 'mantra-018.mp3',
    go_deeper_teaser: 'Varanasi: the city where Shiva never sleeps →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 19,
    original_script: 'ॐ आशुतोषाय नमः',
    transliteration: 'Om Ashutoshaya Namah',
    english_translation: 'Om, I bow to the one who is quickly satisfied.',
    tradition: 'vedic_shiva',
    intention: 'Contentment',
    phonetic_guide: 'OHM ah-shoo-TOH-shah-yah nah-MAH',
    context_note: 'Ashutosh — "quickly pleased" — teaches that Shiva asks for nothing more than sincere love. Contentment is the highest offering.',
    audio_filename: 'mantra-019.mp3',
    go_deeper_teaser: 'The art of contentment: Santosha in daily life →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 20,
    original_script: 'ॐ त्रिलोचनाय नमः',
    transliteration: 'Om Trilochanaya Namah',
    english_translation: 'Om, I bow to the three-eyed one who sees past, present, and future.',
    tradition: 'vedic_shiva',
    intention: 'Clarity',
    phonetic_guide: 'OHM tree-loh-CHAH-nah-yah nah-MAH',
    context_note: 'Shiva\'s third eye represents the eye of wisdom — the ability to see beyond duality into the nature of reality.',
    audio_filename: 'mantra-020.mp3',
    go_deeper_teaser: 'Activating your third eye through mantra →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 21,
    original_script: 'ॐ सदाशिवाय नमः',
    transliteration: 'Om Sadashivaya Namah',
    english_translation: 'Om, I bow to the eternally auspicious one.',
    tradition: 'vedic_shiva',
    intention: 'Eternity',
    phonetic_guide: 'OHM sah-dah-SHIH-vah-yah nah-MAH',
    context_note: 'Sadashiva — "always auspicious" — represents the eternal, unchanging aspect of Shiva beyond time and space.',
    audio_filename: 'mantra-021.mp3',
    go_deeper_teaser: 'What it means to touch the eternal →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 22,
    original_script: 'ॐ उमापतये नमः',
    transliteration: 'Om Umapataye Namah',
    english_translation: 'Om, I bow to the consort of Uma — the divine feminine.',
    tradition: 'vedic_shiva',
    intention: 'Love',
    phonetic_guide: 'OHM oo-mah-PAH-tah-yay nah-MAH',
    context_note: 'Uma (Parvati) is Shiva\'s beloved. This mantra honors the sacred partnership of masculine and feminine principles.',
    audio_filename: 'mantra-022.mp3',
    go_deeper_teaser: 'Shiva and Parvati: the original love story →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 23,
    original_script: 'ॐ कपर्दिने नमः',
    transliteration: 'Om Kapardine Namah',
    english_translation: 'Om, I bow to the matted-haired one who holds the Ganges.',
    tradition: 'vedic_shiva',
    intention: 'Purification',
    phonetic_guide: 'OHM kah-pahr-DEE-nay nah-MAH',
    context_note: 'Shiva\'s matted hair (jata) holds the sacred river Ganga, purifying all who touch her waters.',
    audio_filename: 'mantra-023.mp3',
    go_deeper_teaser: 'The Ganga in Shiva\'s hair: a story of grace →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 24,
    original_script: 'ॐ भस्माङ्गाय नमः',
    transliteration: 'Om Bhasmangaya Namah',
    english_translation: 'Om, I bow to the one adorned with sacred ash.',
    tradition: 'vedic_shiva',
    intention: 'Impermanence',
    phonetic_guide: 'OHM bahsh-MAHN-gah-yah nah-MAH',
    context_note: 'Shiva smears himself with ash from cremation grounds — a reminder that all bodies return to ash. This mantra cultivates non-attachment.',
    audio_filename: 'mantra-024.mp3',
    go_deeper_teaser: 'Sacred ash and the wisdom of impermanence →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 25,
    original_script: 'ॐ गङ्गाधराय नमः',
    transliteration: 'Om Gangadharaya Namah',
    english_translation: 'Om, I bow to the one who holds the sacred Ganga in his locks.',
    tradition: 'vedic_shiva',
    intention: 'Grace',
    phonetic_guide: 'OHM gahn-gah-DHAH-rah-yah nah-MAH',
    context_note: 'When the heavenly Ganga descended to earth, Shiva caught her in his hair to prevent the earth from being destroyed by her force.',
    audio_filename: 'mantra-025.mp3',
    go_deeper_teaser: 'How Shiva saved the earth with his hair →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 26,
    original_script: 'ॐ जटाधराय नमः',
    transliteration: 'Om Jatadharaya Namah',
    english_translation: 'Om, I bow to the one with matted locks of an ascetic.',
    tradition: 'vedic_shiva',
    intention: 'Renunciation',
    phonetic_guide: 'OHM jah-tah-DHAH-rah-yah nah-MAH',
    context_note: 'The matted hair (jata) represents the renunciation of worldly vanity and the accumulation of tapas — spiritual heat.',
    audio_filename: 'mantra-026.mp3',
    go_deeper_teaser: 'Tapas: the sacred fire of spiritual discipline →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 27,
    original_script: 'ॐ कालेश्वराय नमः',
    transliteration: 'Om Kaleshwaraya Namah',
    english_translation: 'Om, I bow to the Lord of time who transcends all time.',
    tradition: 'vedic_shiva',
    intention: 'Presence',
    phonetic_guide: 'OHM kah-laysh-WAH-rah-yah nah-MAH',
    context_note: 'Kaleshwara — "Lord of time" — reminds us that Shiva is both the master of time and beyond it. This mantra anchors us in the eternal now.',
    audio_filename: 'mantra-027.mp3',
    go_deeper_teaser: 'Living in the eternal now: Shiva\'s greatest teaching →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 28,
    original_script: 'ॐ ईशानाय नमः',
    transliteration: 'Om Ishanaya Namah',
    english_translation: 'Om, I bow to the ruler of the northeast — the direction of grace.',
    tradition: 'vedic_shiva',
    intention: 'Wisdom',
    phonetic_guide: 'OHM ee-SHAH-nah-yah nah-MAH',
    context_note: 'Ishana is Shiva\'s form ruling the northeast direction — associated with wisdom, grace, and the transmission of spiritual knowledge.',
    audio_filename: 'mantra-028.mp3',
    go_deeper_teaser: 'The five faces of Shiva: Panchamukha explained →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 29,
    original_script: 'ॐ तत्पुरुषाय नमः',
    transliteration: 'Om Tatpurushaya Namah',
    english_translation: 'Om, I bow to the supreme being — the highest self.',
    tradition: 'vedic_shiva',
    intention: 'Self-realization',
    phonetic_guide: 'OHM taht-poo-ROO-shah-yah nah-MAH',
    context_note: 'Tatpurusha — "that supreme person" — is the east-facing form of Shiva, representing the transcendent self beyond ego.',
    audio_filename: 'mantra-029.mp3',
    go_deeper_teaser: 'Tat tvam asi: you are that →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 30,
    original_script: 'ॐ अघोराय नमः',
    transliteration: 'Om Aghoraya Namah',
    english_translation: 'Om, I bow to the non-terrible one — the gentle face of Shiva.',
    tradition: 'vedic_shiva',
    intention: 'Acceptance',
    phonetic_guide: 'OHM ah-GHOH-rah-yah nah-MAH',
    context_note: 'Aghora — "not terrible" — is the south-facing form of Shiva, representing the dissolution of ego and acceptance of all aspects of existence.',
    audio_filename: 'mantra-030.mp3',
    go_deeper_teaser: 'The Aghori path: embracing what we fear →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 31,
    original_script: 'ॐ वामदेवाय नमः',
    transliteration: 'Om Vamadevaya Namah',
    english_translation: 'Om, I bow to the beautiful god — the graceful one.',
    tradition: 'vedic_shiva',
    intention: 'Beauty',
    phonetic_guide: 'OHM vah-mah-DAY-vah-yah nah-MAH',
    context_note: 'Vamadeva — "beautiful god" — is the north-facing form of Shiva, representing the creative, nurturing, and beautiful aspects of consciousness.',
    audio_filename: 'mantra-031.mp3',
    go_deeper_teaser: 'Beauty as a spiritual path →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 32,
    original_script: 'ॐ सद्योजाताय नमः',
    transliteration: 'Om Sadyojataya Namah',
    english_translation: 'Om, I bow to the instantly born — the creative impulse of consciousness.',
    tradition: 'vedic_shiva',
    intention: 'Creativity',
    phonetic_guide: 'OHM sahd-yoh-JAH-tah-yah nah-MAH',
    context_note: 'Sadyojata — "instantly born" — is the west-facing form of Shiva, representing the spontaneous creative power of consciousness.',
    audio_filename: 'mantra-032.mp3',
    go_deeper_teaser: 'Spontaneous creation: how inspiration really works →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 33,
    original_script: 'ॐ हरहर महादेव',
    transliteration: 'Om Hara Hara Mahadeva',
    english_translation: 'Om, remove, remove — O Great God, take away all that binds me.',
    tradition: 'vedic_shiva',
    intention: 'Liberation',
    phonetic_guide: 'OHM HAH-rah HAH-rah mah-hah-DAY-vah',
    context_note: 'Hara means "one who removes" — Shiva removes sin, suffering, and the illusion of separation. A powerful mantra of liberation.',
    audio_filename: 'mantra-033.mp3',
    go_deeper_teaser: 'What Shiva removes and why you should let him →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 34,
    original_script: 'ॐ शिव शम्भो',
    transliteration: 'Om Shiva Shambho',
    english_translation: 'Om, Shiva — the self-luminous, the source of joy.',
    tradition: 'vedic_shiva',
    intention: 'Joy',
    phonetic_guide: 'OHM SHIH-vah SHAHM-boh',
    context_note: 'Shambhu — "self-luminous" or "source of happiness" — is one of Shiva\'s most joyful names. This mantra invokes pure bliss.',
    audio_filename: 'mantra-034.mp3',
    go_deeper_teaser: 'Ananda: the bliss that is your true nature →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 35,
    original_script: 'ॐ नमः शिवाय गुरवे',
    transliteration: 'Om Namah Shivaya Gurave',
    english_translation: 'Om, I bow to Shiva who is the teacher within.',
    tradition: 'vedic_shiva',
    intention: 'Learning',
    phonetic_guide: 'OHM nah-MAH shih-VAH-yah goo-RAH-vay',
    context_note: 'The guru mantra of the Shaiva Siddhanta tradition. Shiva is the first guru — the inner teacher who guides all seekers.',
    audio_filename: 'mantra-035.mp3',
    go_deeper_teaser: 'The inner guru: how Shiva teaches from within →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 36,
    original_script: 'ॐ शिवाय गुरवे नमः',
    transliteration: 'Om Shivaya Gurave Namah',
    english_translation: 'Om, I bow to Shiva the teacher.',
    tradition: 'vedic_shiva',
    intention: 'Humility',
    phonetic_guide: 'OHM shih-VAH-yah goo-RAH-vay nah-MAH',
    context_note: 'The opening mantra of the Shiva Sutras tradition. Humility before the teacher opens the door to genuine wisdom.',
    audio_filename: 'mantra-036.mp3',
    go_deeper_teaser: 'The Shiva Sutras: Kashmir Shaivism\'s greatest text →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 37,
    original_script: 'ॐ शिवाय नमः शान्तिः',
    transliteration: 'Om Shivaya Namah Shantih',
    english_translation: 'Om, I bow to Shiva — peace, peace, peace.',
    tradition: 'vedic_shiva',
    intention: 'Peace',
    phonetic_guide: 'OHM shih-VAH-yah nah-MAH SHAHN-tih',
    context_note: 'The triple shanti at the end of Vedic recitations removes the three types of suffering: physical, mental, and cosmic.',
    audio_filename: 'mantra-037.mp3',
    go_deeper_teaser: 'The three types of suffering and how to end them →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 38,
    original_script: 'ॐ नमः शिवाय स्वाहा',
    transliteration: 'Om Namah Shivaya Svaha',
    english_translation: 'Om, I bow to Shiva — I offer this into the sacred fire.',
    tradition: 'vedic_shiva',
    intention: 'Offering',
    phonetic_guide: 'OHM nah-MAH shih-VAH-yah svah-HAH',
    context_note: 'Svaha is the offering call of fire rituals. Adding it transforms any mantra into a complete act of surrender and offering.',
    audio_filename: 'mantra-038.mp3',
    go_deeper_teaser: 'Homa: the ancient practice of fire offering →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 39,
    original_script: 'ॐ शिव ॐ शिव ॐ शिव',
    transliteration: 'Om Shiva Om Shiva Om Shiva',
    english_translation: 'Om Shiva, Om Shiva, Om Shiva — pure consciousness, again and again.',
    tradition: 'vedic_shiva',
    intention: 'Absorption',
    phonetic_guide: 'OHM SHIH-vah OHM SHIH-vah OHM SHIH-vah',
    context_note: 'Repetition of the divine name is itself the practice. Three repetitions honor the trimurti and the three states of consciousness.',
    audio_filename: 'mantra-039.mp3',
    go_deeper_teaser: 'The power of divine name repetition →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 40,
    original_script: 'ॐ नमः शिवाय शिवाय नमः ॐ',
    transliteration: 'Om Namah Shivaya Shivaya Namah Om',
    english_translation: 'Om, I bow to Shiva, to Shiva I bow, Om.',
    tradition: 'vedic_shiva',
    intention: 'Devotion',
    phonetic_guide: 'OHM nah-MAH shih-VAH-yah shih-VAH-yah nah-MAH OHM',
    context_note: 'A palindromic mantra — it reads the same forward and backward, representing the non-dual nature of Shiva consciousness.',
    audio_filename: 'mantra-040.mp3',
    go_deeper_teaser: 'Non-duality: the teaching that changes everything →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 41,
    original_script: 'ॐ शिवाय विद्महे',
    transliteration: 'Om Shivaya Vidmahe',
    english_translation: 'Om, may we know Shiva.',
    tradition: 'vedic_shiva',
    intention: 'Knowledge',
    phonetic_guide: 'OHM shih-VAH-yah vid-MAH-hay',
    context_note: 'The first line of the Shiva Gayatri — a request for direct knowledge of the divine, not merely belief or concept.',
    audio_filename: 'mantra-041.mp3',
    go_deeper_teaser: 'Direct knowing vs. belief: the Vedantic distinction →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 42,
    original_script: 'ॐ शिवाय विद्महे महादेवाय धीमहि',
    transliteration: 'Om Shivaya Vidmahe Mahadevaya Dhimahi',
    english_translation: 'Om, may we know Shiva, may we meditate on the Great God.',
    tradition: 'vedic_shiva',
    intention: 'Meditation',
    phonetic_guide: 'OHM shih-VAH-yah vid-MAH-hay mah-hah-DAY-vah-yah dhee-MAH-hee',
    context_note: 'The Shiva Gayatri — a request for illumination through meditation on Shiva\'s supreme nature.',
    audio_filename: 'mantra-042.mp3',
    go_deeper_teaser: 'The Gayatri structure: the most powerful mantra form →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 43,
    original_script: 'तन्नो रुद्रः प्रचोदयात्',
    transliteration: 'Tanno Rudrah Prachodayat',
    english_translation: 'May Rudra illuminate and inspire us.',
    tradition: 'vedic_shiva',
    intention: 'Inspiration',
    phonetic_guide: 'tahn-NOH ROOD-rah prah-choh-DAH-yaht',
    context_note: 'The concluding line of the Rudra Gayatri. Prachodayat — "may he inspire" — is the same word used in the Gayatri Mantra.',
    audio_filename: 'mantra-043.mp3',
    go_deeper_teaser: 'Prachodayat: the prayer for divine inspiration →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 44,
    original_script: 'ॐ शिव तत्त्वम् अहम्',
    transliteration: 'Om Shiva Tattvam Aham',
    english_translation: 'Om, I am the principle of Shiva — pure consciousness.',
    tradition: 'vedic_shiva',
    intention: 'Self-realization',
    phonetic_guide: 'OHM SHIH-vah TAHT-tvahm AH-hahm',
    context_note: 'A mahavakya-style affirmation from Kashmir Shaivism. Tattva means "that-ness" or essential principle. You are not separate from Shiva.',
    audio_filename: 'mantra-044.mp3',
    go_deeper_teaser: 'The mahavakyas: four great sayings of the Upanishads →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 45,
    original_script: 'ॐ नमः शिवाय नित्यम्',
    transliteration: 'Om Namah Shivaya Nityam',
    english_translation: 'Om, I bow to Shiva eternally — always and forever.',
    tradition: 'vedic_shiva',
    intention: 'Commitment',
    phonetic_guide: 'OHM nah-MAH shih-VAH-yah NEET-yahm',
    context_note: 'Nityam means "eternally" or "always." Adding this word transforms the mantra into a vow of perpetual devotion.',
    audio_filename: 'mantra-045.mp3',
    go_deeper_teaser: 'Making a spiritual vow: the power of commitment →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 46,
    original_script: 'ॐ नमो नारायणाय',
    transliteration: 'Om Namo Narayanaya',
    english_translation: 'Om, I bow to Narayana — the one who dwells in all beings.',
    tradition: 'vedic_vishnu',
    intention: 'Devotion',
    phonetic_guide: 'OHM nah-MOH nah-rah-YAH-nah-yah',
    context_note: 'The Ashtakshara — eight-syllable mantra of Vishnu. Narayana means "the one who is the abode of all beings."',
    audio_filename: 'mantra-046.mp3',
    go_deeper_teaser: 'Narayana: the god who lives inside you →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 47,
    original_script: 'ॐ नमो भगवते वासुदेवाय',
    transliteration: 'Om Namo Bhagavate Vasudevaya',
    english_translation: 'Om, I bow to the Lord Vasudeva — the one who pervades all.',
    tradition: 'vedic_vishnu',
    intention: 'Surrender',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay vah-soo-DAY-vah-yah',
    context_note: 'The Dvadasakshara — twelve-syllable mantra of Vishnu. Vasudeva means "the one who dwells everywhere." From the Bhagavata Purana.',
    audio_filename: 'mantra-047.mp3',
    go_deeper_teaser: 'The Bhagavata Purana: Vishnu\'s greatest scripture →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 48,
    original_script: 'हरे कृष्ण हरे कृष्ण',
    transliteration: 'Hare Krishna Hare Krishna',
    english_translation: 'O Hari, O Krishna — O divine energy, O all-attractive one.',
    tradition: 'vedic_vishnu',
    intention: 'Joy',
    phonetic_guide: 'HAH-ray KRISH-nah HAH-ray KRISH-nah',
    context_note: 'The first half of the Maha Mantra. Hare addresses the divine energy (Radha); Krishna means "all-attractive." From the Kali Santarana Upanishad.',
    audio_filename: 'mantra-048.mp3',
    go_deeper_teaser: 'The Maha Mantra: why it works for everyone →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 49,
    original_script: 'हरे राम हरे राम',
    transliteration: 'Hare Rama Hare Rama',
    english_translation: 'O Hari, O Rama — O divine energy, O the one who gives joy.',
    tradition: 'vedic_vishnu',
    intention: 'Bliss',
    phonetic_guide: 'HAH-ray RAH-mah HAH-ray RAH-mah',
    context_note: 'The second half of the Maha Mantra. Rama means "the one who gives joy" or "the one in whom the yogis delight."',
    audio_filename: 'mantra-049.mp3',
    go_deeper_teaser: 'Rama and Krishna: two faces of the same light →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 50,
    original_script: 'ॐ श्री रामाय नमः',
    transliteration: 'Om Shri Ramaya Namah',
    english_translation: 'Om, I bow to the radiant Rama — the ideal of righteousness.',
    tradition: 'vedic_vishnu',
    intention: 'Righteousness',
    phonetic_guide: 'OHM shree RAH-mah-yah nah-MAH',
    context_note: 'Rama is the seventh avatar of Vishnu and the embodiment of dharma — right action, integrity, and noble character.',
    audio_filename: 'mantra-050.mp3',
    go_deeper_teaser: 'Dharma: the path of right action →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 51,
    original_script: 'ॐ श्री कृष्णाय नमः',
    transliteration: 'Om Shri Krishnaya Namah',
    english_translation: 'Om, I bow to the radiant Krishna — the all-attractive divine.',
    tradition: 'vedic_vishnu',
    intention: 'Love',
    phonetic_guide: 'OHM shree KRISH-nah-yah nah-MAH',
    context_note: 'Krishna is the eighth avatar of Vishnu and the teacher of the Bhagavad Gita. His name means "all-attractive" or "dark one."',
    audio_filename: 'mantra-051.mp3',
    go_deeper_teaser: 'The Bhagavad Gita in one sentence →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 52,
    original_script: 'ॐ विष्णवे नमः',
    transliteration: 'Om Vishnave Namah',
    english_translation: 'Om, I bow to Vishnu — the all-pervading one.',
    tradition: 'vedic_vishnu',
    intention: 'Omnipresence',
    phonetic_guide: 'OHM VISH-nah-vay nah-MAH',
    context_note: 'Vishnu means "the all-pervading one" — the divine presence that permeates every atom of creation.',
    audio_filename: 'mantra-052.mp3',
    go_deeper_teaser: 'How to feel the divine presence everywhere →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 53,
    original_script: 'ॐ नारायणाय विद्महे',
    transliteration: 'Om Narayanaya Vidmahe',
    english_translation: 'Om, may we know Narayana.',
    tradition: 'vedic_vishnu',
    intention: 'Knowledge',
    phonetic_guide: 'OHM nah-rah-YAH-nah-yah vid-MAH-hay',
    context_note: 'The opening of the Vishnu Gayatri — a prayer for direct knowledge of the all-pervading divine presence.',
    audio_filename: 'mantra-053.mp3',
    go_deeper_teaser: 'The Vishnu Gayatri: Vaishnava\'s most sacred prayer →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 54,
    original_script: 'ॐ वासुदेवाय धीमहि',
    transliteration: 'Om Vasudevaya Dhimahi',
    english_translation: 'Om, may we meditate on Vasudeva.',
    tradition: 'vedic_vishnu',
    intention: 'Meditation',
    phonetic_guide: 'OHM vah-soo-DAY-vah-yah dhee-MAH-hee',
    context_note: 'The second line of the Vishnu Gayatri. Dhimahi — "may we meditate" — invites sustained contemplation of the divine.',
    audio_filename: 'mantra-054.mp3',
    go_deeper_teaser: 'How to meditate on a divine form →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 55,
    original_script: 'तन्नो विष्णुः प्रचोदयात्',
    transliteration: 'Tanno Vishnuh Prachodayat',
    english_translation: 'May Vishnu illuminate and inspire us.',
    tradition: 'vedic_vishnu',
    intention: 'Inspiration',
    phonetic_guide: 'tahn-NOH VISH-nooh prah-choh-DAH-yaht',
    context_note: 'The concluding line of the Vishnu Gayatri. A prayer for divine illumination in all endeavors.',
    audio_filename: 'mantra-055.mp3',
    go_deeper_teaser: 'Vishnu\'s grace: how the preserver works in your life →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 56,
    original_script: 'ॐ जय जगदीश हरे',
    transliteration: 'Om Jai Jagadish Hare',
    english_translation: 'Om, victory to the Lord of the universe who removes all suffering.',
    tradition: 'vedic_vishnu',
    intention: 'Victory',
    phonetic_guide: 'OHM jay jah-gah-DEESH HAH-ray',
    context_note: 'From the beloved Aarti prayer sung at Vishnu temples across India. Jagadish means "Lord of the world."',
    audio_filename: 'mantra-056.mp3',
    go_deeper_teaser: 'Aarti: the ritual of light and devotion →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 57,
    original_script: 'ॐ श्री विष्णवे नमः',
    transliteration: 'Om Shri Vishnave Namah',
    english_translation: 'Om, I bow to the radiant, all-pervading Vishnu.',
    tradition: 'vedic_vishnu',
    intention: 'Abundance',
    phonetic_guide: 'OHM shree VISH-nah-vay nah-MAH',
    context_note: 'Shri (Lakshmi) is Vishnu\'s consort. Invoking both together brings the fullness of divine grace — both consciousness and abundance.',
    audio_filename: 'mantra-057.mp3',
    go_deeper_teaser: 'Lakshmi and Vishnu: the divine couple of abundance →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 58,
    original_script: 'ॐ हरये नमः',
    transliteration: 'Om Haraye Namah',
    english_translation: 'Om, I bow to Hari — the one who removes all suffering.',
    tradition: 'vedic_vishnu',
    intention: 'Relief',
    phonetic_guide: 'OHM HAH-rah-yay nah-MAH',
    context_note: 'Hari means "the remover" — Vishnu removes the three types of suffering: physical, mental, and karmic.',
    audio_filename: 'mantra-058.mp3',
    go_deeper_teaser: 'How Vishnu removes suffering: the path of grace →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 59,
    original_script: 'ॐ केशवाय नमः',
    transliteration: 'Om Keshavaya Namah',
    english_translation: 'Om, I bow to Keshava — the one with beautiful hair.',
    tradition: 'vedic_vishnu',
    intention: 'Beauty',
    phonetic_guide: 'OHM kay-SHAH-vah-yah nah-MAH',
    context_note: 'Keshava — "beautiful-haired" or "slayer of Keshi" — is one of Krishna\'s most beloved names. Beauty is a form of the divine.',
    audio_filename: 'mantra-059.mp3',
    go_deeper_teaser: 'The 1000 names of Vishnu: the Vishnu Sahasranama →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 60,
    original_script: 'ॐ माधवाय नमः',
    transliteration: 'Om Madhavaya Namah',
    english_translation: 'Om, I bow to Madhava — the lord of spring, the sweet one.',
    tradition: 'vedic_vishnu',
    intention: 'Sweetness',
    phonetic_guide: 'OHM mah-DHAH-vah-yah nah-MAH',
    context_note: 'Madhava means "spring" or "sweet" — Krishna as the embodiment of sweetness, beauty, and the joy of creation.',
    audio_filename: 'mantra-060.mp3',
    go_deeper_teaser: 'Madhurya bhava: the sweetness of divine love →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 61,
    original_script: 'ॐ गोविन्दाय नमः',
    transliteration: 'Om Govindaya Namah',
    english_translation: 'Om, I bow to Govinda — the protector of cows and the earth.',
    tradition: 'vedic_vishnu',
    intention: 'Protection',
    phonetic_guide: 'OHM goh-VIN-dah-yah nah-MAH',
    context_note: 'Govinda — "protector of cows" — is one of Krishna\'s most beloved names, honoring his childhood as a cowherd in Vrindavan.',
    audio_filename: 'mantra-061.mp3',
    go_deeper_teaser: 'Vrindavan: the sacred forest of Krishna\'s childhood →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 62,
    original_script: 'ॐ विष्णवे नमः त्रिविक्रमाय',
    transliteration: 'Om Vishnave Namah Trivikramaya',
    english_translation: 'Om, I bow to Vishnu who took three steps to encompass the universe.',
    tradition: 'vedic_vishnu',
    intention: 'Expansion',
    phonetic_guide: 'OHM VISH-nah-vay nah-MAH tree-vik-RAH-mah-yah',
    context_note: 'Trivikrama — "three steps" — refers to Vamana avatar who measured the entire universe in three strides. Consciousness is boundless.',
    audio_filename: 'mantra-062.mp3',
    go_deeper_teaser: 'Vamana: the dwarf who became the universe →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 63,
    original_script: 'ॐ अच्युताय नमः',
    transliteration: 'Om Achyutaya Namah',
    english_translation: 'Om, I bow to the infallible one who never falls.',
    tradition: 'vedic_vishnu',
    intention: 'Steadiness',
    phonetic_guide: 'OHM ah-CHYOO-tah-yah nah-MAH',
    context_note: 'Achyuta — "infallible" or "imperishable" — is one of Krishna\'s names in the Bhagavad Gita. The divine never wavers.',
    audio_filename: 'mantra-063.mp3',
    go_deeper_teaser: 'Steadiness in the storm: Arjuna\'s lesson →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 64,
    original_script: 'ॐ अनन्ताय नमः',
    transliteration: 'Om Anantaya Namah',
    english_translation: 'Om, I bow to the infinite, endless one.',
    tradition: 'vedic_vishnu',
    intention: 'Infinity',
    phonetic_guide: 'OHM ah-NAHN-tah-yah nah-MAH',
    context_note: 'Ananta — "infinite" — is both a name of Vishnu and the cosmic serpent on which he rests. Infinity is the ground of all existence.',
    audio_filename: 'mantra-064.mp3',
    go_deeper_teaser: 'Ananta Shesha: the serpent of eternity →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 65,
    original_script: 'ॐ पुण्डरीकाक्षाय नमः',
    transliteration: 'Om Pundarikakshaya Namah',
    english_translation: 'Om, I bow to the lotus-eyed one.',
    tradition: 'vedic_vishnu',
    intention: 'Purity',
    phonetic_guide: 'OHM poon-dah-ree-KAH-kshah-yah nah-MAH',
    context_note: 'Pundarikaksha — "lotus-eyed" — describes Vishnu\'s eyes as pure as lotus flowers. The lotus grows in mud but remains unstained.',
    audio_filename: 'mantra-065.mp3',
    go_deeper_teaser: 'The lotus: growing pure in an impure world →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 66,
    original_script: 'ॐ श्रीधराय नमः',
    transliteration: 'Om Shridharaya Namah',
    english_translation: 'Om, I bow to the one who holds Shri — the divine abundance.',
    tradition: 'vedic_vishnu',
    intention: 'Abundance',
    phonetic_guide: 'OHM shree-DHAH-rah-yah nah-MAH',
    context_note: 'Sridhara — "holder of Shri" — honors Vishnu as the one who sustains Lakshmi, the goddess of abundance, on his chest.',
    audio_filename: 'mantra-066.mp3',
    go_deeper_teaser: 'Lakshmi on Vishnu\'s chest: the secret of abundance →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 67,
    original_script: 'ॐ हृषीकेशाय नमः',
    transliteration: 'Om Hrishikeshaya Namah',
    english_translation: 'Om, I bow to the lord of the senses.',
    tradition: 'vedic_vishnu',
    intention: 'Mastery',
    phonetic_guide: 'OHM hrish-ee-KAY-shah-yah nah-MAH',
    context_note: 'Hrishikesha — "lord of the senses" — is the name Arjuna uses when asking Krishna to be his charioteer in the Bhagavad Gita.',
    audio_filename: 'mantra-067.mp3',
    go_deeper_teaser: 'Mastery of the senses: the Bhagavad Gita\'s teaching →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 68,
    original_script: 'ॐ पद्मनाभाय नमः',
    transliteration: 'Om Padmanabhaya Namah',
    english_translation: 'Om, I bow to the one with a lotus in his navel — the source of creation.',
    tradition: 'vedic_vishnu',
    intention: 'Creation',
    phonetic_guide: 'OHM pahd-mah-NAH-bhah-yah nah-MAH',
    context_note: 'From Vishnu\'s navel grows a lotus, and from that lotus emerges Brahma, the creator. The navel is the center of creative power.',
    audio_filename: 'mantra-068.mp3',
    go_deeper_teaser: 'The cosmic navel: creation from the center →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 69,
    original_script: 'ॐ दामोदराय नमः',
    transliteration: 'Om Damodaraya Namah',
    english_translation: 'Om, I bow to Damodara — the one bound by love.',
    tradition: 'vedic_vishnu',
    intention: 'Love',
    phonetic_guide: 'OHM dah-moh-DAH-rah-yah nah-MAH',
    context_note: 'Damodara — "rope around the belly" — refers to Krishna being tied by his mother Yashoda. Love is the only force that can bind the infinite.',
    audio_filename: 'mantra-069.mp3',
    go_deeper_teaser: 'How love binds even God: the Damodara story →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 70,
    original_script: 'ॐ सङ्कर्षणाय नमः',
    transliteration: 'Om Sankarshanaya Namah',
    english_translation: 'Om, I bow to Sankarshana — the one who draws all toward the divine.',
    tradition: 'vedic_vishnu',
    intention: 'Attraction',
    phonetic_guide: 'OHM sahn-kar-SHAH-nah-yah nah-MAH',
    context_note: 'Sankarshana is one of the four vyuha (emanation) forms of Vishnu, representing the attractive power of divine love.',
    audio_filename: 'mantra-070.mp3',
    go_deeper_teaser: 'The four vyuhas: Vishnu\'s cosmic emanations →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 71,
    original_script: 'ॐ प्रद्युम्नाय नमः',
    transliteration: 'Om Pradyumnaya Namah',
    english_translation: 'Om, I bow to Pradyumna — the supremely luminous one.',
    tradition: 'vedic_vishnu',
    intention: 'Radiance',
    phonetic_guide: 'OHM prahd-YOOM-nah-yah nah-MAH',
    context_note: 'Pradyumna — "supremely luminous" — is the son of Krishna and Rukmini, representing the mind aspect of the divine.',
    audio_filename: 'mantra-071.mp3',
    go_deeper_teaser: 'The luminous mind: how consciousness illuminates →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 72,
    original_script: 'ॐ अनिरुद्धाय नमः',
    transliteration: 'Om Aniruddhaya Namah',
    english_translation: 'Om, I bow to Aniruddha — the unstoppable one.',
    tradition: 'vedic_vishnu',
    intention: 'Unstoppability',
    phonetic_guide: 'OHM ah-nee-ROOD-dhah-yah nah-MAH',
    context_note: 'Aniruddha — "unstoppable" — represents the ego aspect of the divine that cannot be obstructed. Your true nature cannot be stopped.',
    audio_filename: 'mantra-072.mp3',
    go_deeper_teaser: 'Your unstoppable nature: removing inner obstacles →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 73,
    original_script: 'ॐ पुरुषोत्तमाय नमः',
    transliteration: 'Om Purushottamaya Namah',
    english_translation: 'Om, I bow to the supreme person — the highest self.',
    tradition: 'vedic_vishnu',
    intention: 'Excellence',
    phonetic_guide: 'OHM poo-roo-SHOH-tah-mah-yah nah-MAH',
    context_note: 'Purushottama — "supreme person" — is described in the 15th chapter of the Bhagavad Gita as the highest reality beyond both the perishable and imperishable.',
    audio_filename: 'mantra-073.mp3',
    go_deeper_teaser: 'The three purushhas: Gita chapter 15 explained →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 74,
    original_script: 'ॐ विश्वम्भराय नमः',
    transliteration: 'Om Vishwambharaya Namah',
    english_translation: 'Om, I bow to the one who sustains the entire universe.',
    tradition: 'vedic_vishnu',
    intention: 'Trust',
    phonetic_guide: 'OHM vish-wahm-BHAH-rah-yah nah-MAH',
    context_note: 'Vishwambhara — "sustainer of the universe" — reminds us that the same intelligence sustaining the cosmos is sustaining you.',
    audio_filename: 'mantra-074.mp3',
    go_deeper_teaser: 'Trusting the intelligence that runs the universe →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 75,
    original_script: 'ॐ जनार्दनाय नमः',
    transliteration: 'Om Janardanaya Namah',
    english_translation: 'Om, I bow to the one who gives joy to all people.',
    tradition: 'vedic_vishnu',
    intention: 'Service',
    phonetic_guide: 'OHM jah-nahr-DAH-nah-yah nah-MAH',
    context_note: 'Janardana — "one who gives joy to people" — is the name used when Krishna acts as the divine servant of humanity.',
    audio_filename: 'mantra-075.mp3',
    go_deeper_teaser: 'Seva: the yoga of selfless service →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 76,
    original_script: 'ॐ उपेन्द्राय नमः',
    transliteration: 'Om Upendraya Namah',
    english_translation: 'Om, I bow to Upendra — the younger brother of Indra.',
    tradition: 'vedic_vishnu',
    intention: 'Humility',
    phonetic_guide: 'OHM oo-PEN-drah-yah nah-MAH',
    context_note: 'Upendra — "junior Indra" — refers to Vamana avatar. The infinite chose to appear as the smallest, most humble form to teach the greatest lesson.',
    audio_filename: 'mantra-076.mp3',
    go_deeper_teaser: 'The power of appearing small: Vamana\'s teaching →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 77,
    original_script: 'ॐ वामनाय नमः',
    transliteration: 'Om Vamanaya Namah',
    english_translation: 'Om, I bow to Vamana — the dwarf avatar who measured the cosmos.',
    tradition: 'vedic_vishnu',
    intention: 'Humility',
    phonetic_guide: 'OHM vah-MAH-nah-yah nah-MAH',
    context_note: 'Vamana took three steps to measure earth, sky, and heaven — teaching that the infinite can appear in the smallest form.',
    audio_filename: 'mantra-077.mp3',
    go_deeper_teaser: 'Small appearances, infinite reality →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 78,
    original_script: 'ॐ श्रीनिवासाय नमः',
    transliteration: 'Om Shrinivasaya Namah',
    english_translation: 'Om, I bow to Shrinivasa — the abode of Shri (Lakshmi).',
    tradition: 'vedic_vishnu',
    intention: 'Abundance',
    phonetic_guide: 'OHM shree-nih-VAH-sah-yah nah-MAH',
    context_note: 'Shrinivasa — "dwelling place of Shri" — is the name of Vishnu at Tirupati, the most visited temple in the world.',
    audio_filename: 'mantra-078.mp3',
    go_deeper_teaser: 'Tirupati: why 100,000 people visit every day →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 79,
    original_script: 'ॐ रङ्गनाथाय नमः',
    transliteration: 'Om Ranganathaya Namah',
    english_translation: 'Om, I bow to Ranganatha — the lord of the stage of creation.',
    tradition: 'vedic_vishnu',
    intention: 'Presence',
    phonetic_guide: 'OHM rahn-gah-NAH-thah-yah nah-MAH',
    context_note: 'Ranganatha — "lord of the stage" — is Vishnu reclining on Ananta at Srirangam. The universe is his stage; we are his players.',
    audio_filename: 'mantra-079.mp3',
    go_deeper_teaser: 'Srirangam: the largest functioning temple in the world →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 80,
    original_script: 'ॐ वेङ्कटेशाय नमः',
    transliteration: 'Om Venkatesaya Namah',
    english_translation: 'Om, I bow to Venkatesa — the lord of Venkata hill.',
    tradition: 'vedic_vishnu',
    intention: 'Grace',
    phonetic_guide: 'OHM ven-kah-TAY-shah-yah nah-MAH',
    context_note: 'Venkatesa is Vishnu at Tirumala-Tirupati. Venkata means "destroyer of sins." This mantra is believed to grant all desires.',
    audio_filename: 'mantra-080.mp3',
    go_deeper_teaser: 'The seven hills of Tirupati and their meaning →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 81,
    original_script: 'ॐ गोपालाय नमः',
    transliteration: 'Om Gopalaya Namah',
    english_translation: 'Om, I bow to Gopala — the protector of cows and souls.',
    tradition: 'vedic_vishnu',
    intention: 'Nurturing',
    phonetic_guide: 'OHM goh-PAH-lah-yah nah-MAH',
    context_note: 'Gopala — "protector of cows" — is Krishna as the divine cowherd who tenderly cares for all beings under his protection.',
    audio_filename: 'mantra-081.mp3',
    go_deeper_teaser: 'The cow in Vedic tradition: why she is sacred →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 82,
    original_script: 'ॐ मुकुन्दाय नमः',
    transliteration: 'Om Mukundaya Namah',
    english_translation: 'Om, I bow to Mukunda — the giver of liberation.',
    tradition: 'vedic_vishnu',
    intention: 'Liberation',
    phonetic_guide: 'OHM moo-KOON-dah-yah nah-MAH',
    context_note: 'Mukunda — "giver of mukti (liberation)" — is one of Krishna\'s most powerful names. Chanting it is said to dissolve karmic bondage.',
    audio_filename: 'mantra-082.mp3',
    go_deeper_teaser: 'Mukti: the four types of liberation in Vedanta →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 83,
    original_script: 'ॐ मधुसूदनाय नमः',
    transliteration: 'Om Madhusudanaya Namah',
    english_translation: 'Om, I bow to Madhusudhana — the slayer of the demon Madhu.',
    tradition: 'vedic_vishnu',
    intention: 'Courage',
    phonetic_guide: 'OHM mah-dhoo-SOO-dah-nah-yah nah-MAH',
    context_note: 'Madhusudhana — "slayer of Madhu" — refers to Vishnu defeating the demon of delusion. This mantra destroys inner demons of doubt and fear.',
    audio_filename: 'mantra-083.mp3',
    go_deeper_teaser: 'The inner demons: what Vishnu really slays →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 84,
    original_script: 'ॐ त्रिविक्रमाय नमः',
    transliteration: 'Om Trivikramaya Namah',
    english_translation: 'Om, I bow to Trivikrama — the one who strode across the three worlds.',
    tradition: 'vedic_vishnu',
    intention: 'Expansion',
    phonetic_guide: 'OHM tree-vik-RAH-mah-yah nah-MAH',
    context_note: 'Trivikrama\'s three steps represent past, present, and future — or earth, atmosphere, and heaven. Consciousness encompasses all.',
    audio_filename: 'mantra-084.mp3',
    go_deeper_teaser: 'The three worlds and how to inhabit them all →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 85,
    original_script: 'ॐ वराहाय नमः',
    transliteration: 'Om Varahaya Namah',
    english_translation: 'Om, I bow to Varaha — the boar avatar who rescued the earth.',
    tradition: 'vedic_vishnu',
    intention: 'Rescue',
    phonetic_guide: 'OHM vah-RAH-hah-yah nah-MAH',
    context_note: 'Varaha lifted the earth from the cosmic ocean on his tusks. This mantra invokes the power to rescue what is precious from darkness.',
    audio_filename: 'mantra-085.mp3',
    go_deeper_teaser: 'The Varaha avatar: diving into darkness to save the earth →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 86,
    original_script: 'ॐ नृसिंहाय नमः',
    transliteration: 'Om Nrisimhaya Namah',
    english_translation: 'Om, I bow to Narasimha — the man-lion who protects devotees.',
    tradition: 'vedic_vishnu',
    intention: 'Protection',
    phonetic_guide: 'OHM nree-SIM-hah-yah nah-MAH',
    context_note: 'Narasimha burst from a pillar to protect Prahlada — teaching that the divine is present everywhere, in every atom, at every moment.',
    audio_filename: 'mantra-086.mp3',
    go_deeper_teaser: 'Prahlada\'s faith: the devotee who couldn\'t be killed →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 87,
    original_script: 'ॐ परशुरामाय नमः',
    transliteration: 'Om Parashuramaya Namah',
    english_translation: 'Om, I bow to Parashurama — the warrior sage with the axe.',
    tradition: 'vedic_vishnu',
    intention: 'Justice',
    phonetic_guide: 'OHM pah-rah-shoo-RAH-mah-yah nah-MAH',
    context_note: 'Parashurama — "Rama with the axe" — is the sixth avatar who restored cosmic justice. Sometimes fierce action is the most compassionate response.',
    audio_filename: 'mantra-087.mp3',
    go_deeper_teaser: 'When compassion requires fierceness →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 88,
    original_script: 'ॐ बलराम नमोऽस्तु ते',
    transliteration: 'Om Balarama Namostu Te',
    english_translation: 'Om, I bow to Balarama — the strong one, Krishna\'s elder brother.',
    tradition: 'vedic_vishnu',
    intention: 'Strength',
    phonetic_guide: 'OHM bah-lah-RAH-mah nah-MOHS-too tay',
    context_note: 'Balarama — "strong Rama" — is the eighth avatar, representing the strength that supports and protects the divine play of consciousness.',
    audio_filename: 'mantra-088.mp3',
    go_deeper_teaser: 'Balarama: the strength behind Krishna\'s play →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 89,
    original_script: 'ॐ कल्किने नमः',
    transliteration: 'Om Kalkine Namah',
    english_translation: 'Om, I bow to Kalki — the future avatar who restores righteousness.',
    tradition: 'vedic_vishnu',
    intention: 'Hope',
    phonetic_guide: 'OHM KAHL-kih-nay nah-MAH',
    context_note: 'Kalki is the tenth and final avatar, yet to come — riding a white horse to restore dharma at the end of the Kali Yuga.',
    audio_filename: 'mantra-089.mp3',
    go_deeper_teaser: 'The Kali Yuga: are we living in the dark age? →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 90,
    original_script: 'ॐ दशावताराय नमः',
    transliteration: 'Om Dashavataraaya Namah',
    english_translation: 'Om, I bow to the ten avatars — the divine in all its forms.',
    tradition: 'vedic_vishnu',
    intention: 'Wholeness',
    phonetic_guide: 'OHM dah-shah-vah-TAH-rah-yah nah-MAH',
    context_note: 'The ten avatars of Vishnu trace the evolution of consciousness from fish to human — a map of spiritual evolution across cosmic time.',
    audio_filename: 'mantra-090.mp3',
    go_deeper_teaser: 'Darwin and the Dashavatara: evolution in the Vedas →',
    go_deeper_url: 'https://paulwagner.com',
  },
  {
    day_of_year: 91,
    original_script: 'ॐ ऐं ह्रीं क्लीं',
    transliteration: 'Om Aim Hrim Klim',
    english_translation: 'Om — the seed of Saraswati, Lakshmi, and Kali — wisdom, abundance, and transformation.',
    tradition: 'vedic_shakti',
    intention: 'Empowerment',
    phonetic_guide: 'OHM AIM hreem kleem',
    context_note: 'Three bija mantras of the divine feminine: Aim (Saraswati/wisdom), Hrim (Lakshmi/heart), Klim (Kali/transformation). Together they invoke the full power of Shakti.',
    audio_filename: 'mantra-091.mp3',
    go_deeper_teaser: 'The three great goddesses and their bija mantras →',
    go_deeper_url: 'https://paulwagner.com',
  },
];
