// Mantras Part 4: Days 284–365 — Universal (continued)

module.exports = [
  {
    day_of_year: 284,
    original_script: 'ॐ पूर्णमदः पूर्णमिदम्',
    transliteration: 'Om Purnamadah Purnamidam',
    english_translation: 'Om — that is whole, this is whole.',
    tradition: 'universal',
    intention: 'Wholeness',
    phonetic_guide: 'OHM POOR-nah-mah-dah POOR-nah-mih-dahm',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'The Shanti Patha of the Isha Upanishad. The infinite is whole; the finite is also whole. When wholeness is taken from wholeness, wholeness remains.',
    go_deeper_teaser: 'The Isha Upanishad: the wholeness that cannot be diminished →',
  },
  {
    day_of_year: 285,
    original_script: 'पूर्णात् पूर्णमुदच्यते',
    transliteration: 'Purnat Purnamudachyate',
    english_translation: 'From wholeness, wholeness arises.',
    tradition: 'universal',
    intention: 'Abundance',
    phonetic_guide: 'POOR-naht POOR-nahm-oo-DAHCH-yah-tay',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'The second line of the Isha Upanishad Shanti Patha. The infinite gives rise to infinite worlds without being diminished.',
    go_deeper_teaser: 'Infinite abundance: the Upanishadic view →',
  },
  {
    day_of_year: 286,
    original_script: 'पूर्णस्य पूर्णमादाय पूर्णमेवावशिष्यते',
    transliteration: 'Purnasya Purnamadaya Purnamevavashishyate',
    english_translation: 'When wholeness is taken from wholeness, wholeness alone remains.',
    tradition: 'universal',
    intention: 'Completeness',
    phonetic_guide: 'POOR-nahs-yah POOR-nahm-ah-DAH-yah POOR-nah-may-VAH-vah-shish-yah-tay',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'The complete Isha Upanishad Shanti Patha. This is the mathematics of infinity: infinity minus infinity equals infinity.',
    go_deeper_teaser: 'The mathematics of the infinite: beyond ordinary logic →',
  },
  {
    day_of_year: 287,
    original_script: 'ॐ सच्चिदानन्द',
    transliteration: 'Om Satchidananda',
    english_translation: 'Om — existence, consciousness, bliss.',
    tradition: 'universal',
    intention: 'Bliss',
    phonetic_guide: 'OHM saht-chid-AH-nahn-dah',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Sat-Chit-Ananda — the three qualities of Brahman: pure existence, pure consciousness, and pure bliss. This is the nature of ultimate reality.',
    go_deeper_teaser: 'Satchidananda: the nature of ultimate reality →',
  },
  {
    day_of_year: 288,
    original_script: 'ॐ नमः शिवाय',
    transliteration: 'Om Namah Shivaya',
    english_translation: 'Om — I bow to Shiva — the auspicious one within.',
    tradition: 'universal',
    intention: 'Surrender',
    phonetic_guide: 'OHM nah-MAH shih-VAH-yah',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The Panchakshara — five-syllable mantra — is one of the most universal mantras. Na-Ma-Shi-Va-Ya represents the five elements and the five acts of Shiva.',
    go_deeper_teaser: 'The five syllables: Na Ma Shi Va Ya →',
  },
  {
    day_of_year: 289,
    original_script: 'ॐ मणि पद्मे हूँ',
    transliteration: 'Om Mani Padme Hum',
    english_translation: 'Om — the jewel in the lotus — hum.',
    tradition: 'universal',
    intention: 'Compassion',
    phonetic_guide: 'OHM mah-NEE pahd-MAY hoom',
    sacred_geometry_type: 'lotus',
    context_note: 'Returning to the most universal of all mantras. The jewel of awakened mind resting in the lotus of the world. Compassion is the universal path.',
    go_deeper_teaser: 'Why Om Mani Padme Hum is the most chanted mantra →',
  },
  {
    day_of_year: 290,
    original_script: 'ॐ गं गणपतये नमः',
    transliteration: 'Om Gam Ganapataye Namah',
    english_translation: 'Om — seed of Ganesha — I bow to the lord of beginnings.',
    tradition: 'universal',
    intention: 'New Beginnings',
    phonetic_guide: 'OHM gahm gah-nah-PAH-tah-yay nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Ganesha is invoked at the beginning of all undertakings. Gam is his seed syllable. This mantra removes obstacles and opens new paths.',
    go_deeper_teaser: 'Ganesha: the remover of obstacles →',
  },
  {
    day_of_year: 291,
    original_script: 'ॐ श्रीं महालक्ष्म्यै नमः',
    transliteration: 'Om Shrim Mahalakshmyai Namah',
    english_translation: 'Om — seed of Lakshmi — I bow to the great Lakshmi.',
    tradition: 'universal',
    intention: 'Abundance',
    phonetic_guide: 'OHM shreem mah-hah-LAHK-shmy-ay nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Lakshmi is the goddess of abundance — not just material wealth but spiritual richness. Shrim is her seed syllable, the sound of prosperity.',
    go_deeper_teaser: 'Lakshmi: the goddess of true abundance →',
  },
  {
    day_of_year: 292,
    original_script: 'ॐ ऐं सरस्वत्यै नमः',
    transliteration: 'Om Aim Sarasvatyai Namah',
    english_translation: 'Om — seed of Saraswati — I bow to the goddess of wisdom.',
    tradition: 'universal',
    intention: 'Wisdom',
    phonetic_guide: 'OHM aim sah-rahs-VAHT-yay nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Saraswati is the goddess of learning, music, and wisdom. Aim is her seed syllable. This mantra is chanted before study and creative work.',
    go_deeper_teaser: 'Saraswati: the goddess of creative wisdom →',
  },
  {
    day_of_year: 293,
    original_script: 'ॐ दुं दुर्गायै नमः',
    transliteration: 'Om Dum Durgayai Namah',
    english_translation: 'Om — seed of Durga — I bow to the invincible one.',
    tradition: 'universal',
    intention: 'Courage',
    phonetic_guide: 'OHM doom door-GAH-yay nah-MAH',
    sacred_geometry_type: 'lotus',
    context_note: 'Durga — "the invincible" — is the warrior goddess who protects against all evil. Dum is her seed syllable. This mantra invokes inner strength.',
    go_deeper_teaser: 'Durga: the warrior goddess within you →',
  },
  {
    day_of_year: 294,
    original_script: 'ॐ क्लीं कृष्णाय नमः',
    transliteration: 'Om Klim Krishnaya Namah',
    english_translation: 'Om — seed of attraction — I bow to Krishna.',
    tradition: 'universal',
    intention: 'Love',
    phonetic_guide: 'OHM kleem krish-NAH-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Klim is the seed syllable of attraction and love. This mantra invokes Krishna\'s quality of divine love — the love that draws all things toward the divine.',
    go_deeper_teaser: 'Klim: the seed syllable of divine love →',
  },
  {
    day_of_year: 295,
    original_script: 'ॐ नमो नारायणाय',
    transliteration: 'Om Namo Narayanaya',
    english_translation: 'Om — I bow to Narayana — the one who rests in all beings.',
    tradition: 'universal',
    intention: 'Presence',
    phonetic_guide: 'OHM nah-MOH nah-rah-YAH-nah-yah',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Narayana — "the one who rests in all beings" — is the universal form of Vishnu. This mantra recognizes the divine presence in every living being.',
    go_deeper_teaser: 'Narayana: the divine presence in all beings →',
  },
  {
    day_of_year: 296,
    original_script: 'ॐ तत् सत्',
    transliteration: 'Om Tat Sat',
    english_translation: 'Om — that — truth.',
    tradition: 'universal',
    intention: 'Truth',
    phonetic_guide: 'OHM taht saht',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'From the Bhagavad Gita. Om Tat Sat — the three designations of Brahman. Om is the sound, Tat is the pointer, Sat is the reality.',
    go_deeper_teaser: 'Om Tat Sat: the three names of the absolute →',
  },
  {
    day_of_year: 297,
    original_script: 'ॐ नमो भगवते वासुदेवाय',
    transliteration: 'Om Namo Bhagavate Vasudevaya',
    english_translation: 'Om — I bow to the blessed Vasudeva — the all-pervading one.',
    tradition: 'universal',
    intention: 'Pervasion',
    phonetic_guide: 'OHM nah-MOH bhah-gah-VAH-tay VAH-soo-DAY-vah-yah',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'The Dvadasakshara — twelve-syllable mantra — of Vishnu. Vasudeva — "the one who dwells in all" — is the all-pervading divine.',
    go_deeper_teaser: 'The twelve-syllable mantra of Vishnu →',
  },
  {
    day_of_year: 298,
    original_script: 'ॐ श्री रामाय नमः',
    transliteration: 'Om Sri Ramaya Namah',
    english_translation: 'Om — I bow to the radiant Ram.',
    tradition: 'universal',
    intention: 'Virtue',
    phonetic_guide: 'OHM shree RAH-mah-yah nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Ram — "the one who delights" — is the avatar of Vishnu who embodies dharma. Sri adds radiance and auspiciousness to the invocation.',
    go_deeper_teaser: 'Ram: the avatar of perfect virtue →',
  },
  {
    day_of_year: 299,
    original_script: 'राम राम राम',
    transliteration: 'Ram Ram Ram',
    english_translation: 'Ram, Ram, Ram — the name that is the Vedas.',
    tradition: 'universal',
    intention: 'Liberation',
    phonetic_guide: 'rahm rahm rahm',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Gandhi\'s dying words were "Hey Ram." The name Ram is said to contain the essence of all the Vedas. Simple, direct, and infinitely deep.',
    go_deeper_teaser: 'Why Gandhi\'s last words were "Hey Ram" →',
  },
  {
    day_of_year: 300,
    original_script: 'ॐ हनुमते नमः',
    transliteration: 'Om Hanumate Namah',
    english_translation: 'Om — I bow to Hanuman — the devoted servant.',
    tradition: 'universal',
    intention: 'Devotion',
    phonetic_guide: 'OHM hah-noo-MAH-tay nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Hanuman is the embodiment of devotion, strength, and selfless service. His devotion to Ram is the model for all spiritual practice.',
    go_deeper_teaser: 'Hanuman: the perfect devotee →',
  },
  {
    day_of_year: 301,
    original_script: 'ॐ श्री हनुमते नमः',
    transliteration: 'Om Sri Hanumate Namah',
    english_translation: 'Om — I bow to the radiant Hanuman.',
    tradition: 'universal',
    intention: 'Strength',
    phonetic_guide: 'OHM shree hah-noo-MAH-tay nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Hanuman\'s strength comes from his devotion — not from ego or personal power. This mantra invokes strength that is rooted in love.',
    go_deeper_teaser: 'Strength through devotion: Hanuman\'s secret →',
  },
  {
    day_of_year: 302,
    original_script: 'ॐ नमः शिवाय गुरवे',
    transliteration: 'Om Namah Shivaya Gurave',
    english_translation: 'Om — I bow to Shiva who is the Guru.',
    tradition: 'universal',
    intention: 'Guidance',
    phonetic_guide: 'OHM nah-MAH shih-VAH-yah goo-RAH-vay',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The opening of the Anusara yoga invocation. The Guru is not separate from Shiva — the teacher is the divine in human form.',
    go_deeper_teaser: 'The Guru principle: the divine as teacher →',
  },
  {
    day_of_year: 303,
    original_script: 'सच्चिदानन्द मूर्तये',
    transliteration: 'Satchidananda Murtaye',
    english_translation: 'Who is the embodiment of existence, consciousness, and bliss.',
    tradition: 'universal',
    intention: 'Embodiment',
    phonetic_guide: 'saht-chid-AH-nahn-dah MOOR-tah-yay',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The second line of the Anusara invocation. The Guru embodies the three qualities of ultimate reality in human form.',
    go_deeper_teaser: 'The living embodiment of truth →',
  },
  {
    day_of_year: 304,
    original_script: 'निष्प्रपञ्चाय शान्ताय',
    transliteration: 'Nishprapanchaya Shantaya',
    english_translation: 'Who is free from all illusion, who is peace itself.',
    tradition: 'universal',
    intention: 'Peace',
    phonetic_guide: 'nish-prah-PAHN-chah-yah SHAHN-tah-yah',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'From the Anusara invocation. Nishprapanchaya — "free from the world of appearances." The Guru is not bound by the illusions that bind ordinary beings.',
    go_deeper_teaser: 'Freedom from illusion: the Guru\'s gift →',
  },
  {
    day_of_year: 305,
    original_script: 'निरालम्बाय तेजसे',
    transliteration: 'Niralambaya Tejase',
    english_translation: 'Who is independent of all support, who is radiance itself.',
    tradition: 'universal',
    intention: 'Independence',
    phonetic_guide: 'nih-rah-LAHM-bah-yah TAY-jah-say',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The final line of the Anusara invocation. The Guru needs nothing — not even our devotion. The divine is self-sufficient radiance.',
    go_deeper_teaser: 'The complete Anusara invocation →',
  },
  {
    day_of_year: 306,
    original_script: 'ॐ भूमि माता',
    transliteration: 'Om Bhumi Mata',
    english_translation: 'Om — Earth Mother.',
    tradition: 'universal',
    intention: 'Earth',
    phonetic_guide: 'OHM BHOO-mih MAH-tah',
    sacred_geometry_type: 'lotus',
    context_note: 'A universal invocation of the earth as mother. All spiritual traditions recognize the earth as sacred. We are born from her and return to her.',
    go_deeper_teaser: 'Earth as mother: the universal teaching →',
  },
  {
    day_of_year: 307,
    original_script: 'ॐ द्यौः पिता',
    transliteration: 'Om Dyauh Pita',
    english_translation: 'Om — Sky Father.',
    tradition: 'universal',
    intention: 'Sky',
    phonetic_guide: 'OHM dyow PIH-tah',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'The sky as father — the vast, open awareness that contains all experience. The earth is our mother; the sky is our father. We are children of both.',
    go_deeper_teaser: 'Sky and earth: the universal parents →',
  },
  {
    day_of_year: 308,
    original_script: 'ॐ अन्तरिक्षम्',
    transliteration: 'Om Antariksha',
    english_translation: 'Om — the space between — the intermediate realm.',
    tradition: 'universal',
    intention: 'Space',
    phonetic_guide: 'OHM ahn-TAH-rik-shahm',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Antariksha — "the space between" — is the intermediate realm between earth and sky. It represents the liminal space of transformation.',
    go_deeper_teaser: 'The space between: where transformation happens →',
  },
  {
    day_of_year: 309,
    original_script: 'ॐ आकाशात् पतितं तोयम्',
    transliteration: 'Om Akashat Patitam Toyam',
    english_translation: 'Om — water fallen from the sky reaches the ocean.',
    tradition: 'universal',
    intention: 'Return',
    phonetic_guide: 'OHM AH-kah-shaht pah-TIH-tahm TOH-yahm',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'A universal teaching: all rivers return to the ocean, as all prayers return to the divine. The path may differ; the destination is one.',
    go_deeper_teaser: 'All rivers return to the ocean: the unity of all paths →',
  },
  {
    day_of_year: 310,
    original_script: 'यथा गच्छति सागरम्',
    transliteration: 'Yatha Gacchati Sagaram',
    english_translation: 'So all worship reaches the one God.',
    tradition: 'universal',
    intention: 'Unity',
    phonetic_guide: 'YAH-thah GAHCH-chah-tih SAH-gah-rahm',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'The second line of the universal prayer verse. Just as water always finds its way to the ocean, all sincere worship reaches the divine.',
    go_deeper_teaser: 'The unity of all religions: the perennial philosophy →',
  },
  {
    day_of_year: 311,
    original_script: 'ॐ सर्वे भवन्तु सुखिनः',
    transliteration: 'Om Sarve Bhavantu Sukhinah',
    english_translation: 'Om — may all be happy.',
    tradition: 'universal',
    intention: 'Happiness',
    phonetic_guide: 'OHM SAHR-vay bhah-VAHN-too soo-KHIH-nah',
    sacred_geometry_type: 'lotus',
    context_note: 'The universal prayer for happiness. Sarve — "all" — includes all beings without exception: humans, animals, plants, and all forms of life.',
    go_deeper_teaser: 'The universal prayer: may all beings be happy →',
  },
  {
    day_of_year: 312,
    original_script: 'सर्वे सन्तु निरामयाः',
    transliteration: 'Sarve Santu Niramayah',
    english_translation: 'May all be free from disease.',
    tradition: 'universal',
    intention: 'Health',
    phonetic_guide: 'SAHR-vay SAHN-too nih-rah-MAH-yah',
    sacred_geometry_type: 'lotus',
    context_note: 'The second line of the universal prayer. Niramaya — "free from disease" — extends to all forms of suffering, not just physical illness.',
    go_deeper_teaser: 'The four wishes of the universal prayer →',
  },
  {
    day_of_year: 313,
    original_script: 'सर्वे भद्राणि पश्यन्तु',
    transliteration: 'Sarve Bhadrani Pashyantu',
    english_translation: 'May all see what is auspicious.',
    tradition: 'universal',
    intention: 'Auspiciousness',
    phonetic_guide: 'SAHR-vay BHAHD-rah-nih PAHSH-yahn-too',
    sacred_geometry_type: 'lotus',
    context_note: 'The third line of the universal prayer. May all beings have the eyes to see the goodness and beauty in the world.',
    go_deeper_teaser: 'Seeing the auspicious: a practice of perception →',
  },
  {
    day_of_year: 314,
    original_script: 'मा कश्चिद् दुःखभाग् भवेत्',
    transliteration: 'Ma Kashchid Duhkhabhag Bhavet',
    english_translation: 'May no one suffer.',
    tradition: 'universal',
    intention: 'Compassion',
    phonetic_guide: 'mah KAHSH-chid DOOH-khah-bhahg BHAH-vayt',
    sacred_geometry_type: 'lotus',
    context_note: 'The final line of the universal prayer. A direct, simple wish: may no being suffer. This is the essence of compassion.',
    go_deeper_teaser: 'The complete universal prayer: a daily practice →',
  },
  {
    day_of_year: 315,
    original_script: 'ॐ असतो मा सद्गमय',
    transliteration: 'Om Asato Ma Sadgamaya',
    english_translation: 'Om — lead me from the unreal to the real.',
    tradition: 'universal',
    intention: 'Truth',
    phonetic_guide: 'OHM ah-SAH-toh mah sahd-GAH-mah-yah',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The Pavamana Mantra from the Brihadaranyaka Upanishad. Three prayers for the three great transitions: from unreal to real, darkness to light, death to immortality.',
    go_deeper_teaser: 'The Pavamana Mantra: the three great prayers →',
  },
  {
    day_of_year: 316,
    original_script: 'तमसो मा ज्योतिर्गमय',
    transliteration: 'Tamaso Ma Jyotirgamaya',
    english_translation: 'Lead me from darkness to light.',
    tradition: 'universal',
    intention: 'Enlightenment',
    phonetic_guide: 'tah-MAH-soh mah JYOH-tir-gah-mah-yah',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The second line of the Pavamana Mantra. Tamas — "darkness" — is ignorance. Jyoti — "light" — is knowledge. The prayer is for the light of wisdom.',
    go_deeper_teaser: 'From darkness to light: the path of awakening →',
  },
  {
    day_of_year: 317,
    original_script: 'मृत्योर्मा अमृतं गमय',
    transliteration: 'Mrityorma Amritam Gamaya',
    english_translation: 'Lead me from death to immortality.',
    tradition: 'universal',
    intention: 'Immortality',
    phonetic_guide: 'mrih-TYOR-mah AHM-rih-tahm GAH-mah-yah',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The third line of the Pavamana Mantra. Mrityu — "death" — Amrita — "immortality." Not physical immortality, but the recognition of the deathless self.',
    go_deeper_teaser: 'Amrita: the nectar of immortality →',
  },
  {
    day_of_year: 318,
    original_script: 'ॐ लोकाः समस्ताः सुखिनो भवन्तु',
    transliteration: 'Om Lokah Samastah Sukhino Bhavantu',
    english_translation: 'Om — may all beings in all worlds be happy and free.',
    tradition: 'universal',
    intention: 'Universal Welfare',
    phonetic_guide: 'OHM LOH-kah sah-MAHS-tah soo-KHIH-noh bhah-VAHN-too',
    sacred_geometry_type: 'lotus',
    context_note: 'The most universal of all mantras. Lokah — "worlds" — Samastah — "all." This prayer extends to all beings in all dimensions of existence.',
    go_deeper_teaser: 'Lokah Samastah: the prayer that changes the world →',
  },
  {
    day_of_year: 319,
    original_script: 'ॐ सर्वमंगलमांगल्ये',
    transliteration: 'Om Sarvamangalamangalye',
    english_translation: 'Om — the auspiciousness of all auspicious things.',
    tradition: 'universal',
    intention: 'Auspiciousness',
    phonetic_guide: 'OHM sahr-vah-mahn-gah-lah-MAHN-gah-lyay',
    sacred_geometry_type: 'lotus',
    context_note: 'The opening of the Devi Stuti — the hymn to the goddess. The divine feminine is the source of all auspiciousness in the universe.',
    go_deeper_teaser: 'The divine feminine: the source of all blessings →',
  },
  {
    day_of_year: 320,
    original_script: 'शिवे सर्वार्थसाधिके',
    transliteration: 'Shive Sarvarthasadhike',
    english_translation: 'O Shiva — the one who fulfills all purposes.',
    tradition: 'universal',
    intention: 'Fulfillment',
    phonetic_guide: 'shih-VAY sahr-VAHR-thah-SAH-dhih-kay',
    sacred_geometry_type: 'lotus',
    context_note: 'The second line of the Devi Stuti. Shiva here refers to the goddess — the auspicious one who fulfills all spiritual and material purposes.',
    go_deeper_teaser: 'Shiva as the divine feminine: the auspicious one →',
  },
  {
    day_of_year: 321,
    original_script: 'शरण्ये त्र्यम्बके गौरि',
    transliteration: 'Sharanyе Tryambake Gauri',
    english_translation: 'O refuge — three-eyed one — O Gauri.',
    tradition: 'universal',
    intention: 'Refuge',
    phonetic_guide: 'shah-RAHN-yay TRYAHM-bah-kay GOW-ree',
    sacred_geometry_type: 'lotus',
    context_note: 'The third line of the Devi Stuti. Tryambake — "three-eyed" — Gauri — "the fair one." The goddess is the ultimate refuge.',
    go_deeper_teaser: 'Gauri: the radiant goddess →',
  },
  {
    day_of_year: 322,
    original_script: 'नारायणि नमोऽस्तु ते',
    transliteration: 'Narayani Namostu Te',
    english_translation: 'O Narayani — may there be bowing to you.',
    tradition: 'universal',
    intention: 'Devotion',
    phonetic_guide: 'nah-rah-YAH-nih nah-MOHS-too tay',
    sacred_geometry_type: 'lotus',
    context_note: 'The final line of the Devi Stuti. Narayani — the feminine form of Narayana — is the goddess as the all-pervading divine.',
    go_deeper_teaser: 'The complete Devi Stuti: a hymn to the goddess →',
  },
  {
    day_of_year: 323,
    original_script: 'ॐ ह्रीं',
    transliteration: 'Om Hrim',
    english_translation: 'Om — the maya bija — the seed of divine power.',
    tradition: 'universal',
    intention: 'Power',
    phonetic_guide: 'OHM hreem',
    sacred_geometry_type: 'lotus',
    context_note: 'Hrim is the bija (seed syllable) of the goddess — the sound of maya, the creative power of the divine. It is the most powerful single syllable after Om.',
    go_deeper_teaser: 'Hrim: the seed syllable of the goddess →',
  },
  {
    day_of_year: 324,
    original_script: 'ॐ श्रीं',
    transliteration: 'Om Shrim',
    english_translation: 'Om — the Lakshmi bija — the seed of abundance.',
    tradition: 'universal',
    intention: 'Abundance',
    phonetic_guide: 'OHM shreem',
    sacred_geometry_type: 'lotus',
    context_note: 'Shrim is the bija of Lakshmi — the sound of abundance, beauty, and grace. It attracts all forms of prosperity: material, emotional, and spiritual.',
    go_deeper_teaser: 'Shrim: the sound of abundance →',
  },
  {
    day_of_year: 325,
    original_script: 'ॐ ऐं',
    transliteration: 'Om Aim',
    english_translation: 'Om — the Saraswati bija — the seed of wisdom.',
    tradition: 'universal',
    intention: 'Wisdom',
    phonetic_guide: 'OHM aim (rhymes with "time")',
    sacred_geometry_type: 'lotus',
    context_note: 'Aim is the bija of Saraswati — the sound of wisdom, learning, and creative intelligence. It activates the higher mind.',
    go_deeper_teaser: 'Aim: the seed syllable of wisdom →',
  },
  {
    day_of_year: 326,
    original_script: 'ॐ क्लीं',
    transliteration: 'Om Klim',
    english_translation: 'Om — the Kama bija — the seed of love and attraction.',
    tradition: 'universal',
    intention: 'Love',
    phonetic_guide: 'OHM kleem',
    sacred_geometry_type: 'lotus',
    context_note: 'Klim is the bija of Kama — divine love and attraction. It draws all good things toward you and opens the heart to love.',
    go_deeper_teaser: 'Klim: the seed syllable of divine love →',
  },
  {
    day_of_year: 327,
    original_script: 'ॐ क्रीं',
    transliteration: 'Om Krim',
    english_translation: 'Om — the Kali bija — the seed of transformation.',
    tradition: 'universal',
    intention: 'Transformation',
    phonetic_guide: 'OHM kreem',
    sacred_geometry_type: 'lotus',
    context_note: 'Krim is the bija of Kali — the sound of radical transformation. It destroys what is false and reveals what is true.',
    go_deeper_teaser: 'Krim: the seed syllable of transformation →',
  },
  {
    day_of_year: 328,
    original_script: 'ॐ हूँ',
    transliteration: 'Om Hum',
    english_translation: 'Om — the Shiva bija — the seed of fire and protection.',
    tradition: 'universal',
    intention: 'Protection',
    phonetic_guide: 'OHM hoom',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Hum is the bija of Shiva — the sound of fire, protection, and the destruction of obstacles. It is also the seed of the awakened mind in Buddhism.',
    go_deeper_teaser: 'Hum: the seed syllable of fire and protection →',
  },
  {
    day_of_year: 329,
    original_script: 'ॐ फट्',
    transliteration: 'Om Phat',
    english_translation: 'Om — the weapon bija — the sound that cuts through all obstacles.',
    tradition: 'universal',
    intention: 'Cutting Through',
    phonetic_guide: 'OHM phaht (sharp, explosive)',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Phat is the weapon bija — the sound of a sword cutting through obstacles. It is used at the end of protective mantras to seal and strengthen them.',
    go_deeper_teaser: 'The weapon mantras: cutting through obstacles →',
  },
  {
    day_of_year: 330,
    original_script: 'ॐ स्वाहा',
    transliteration: 'Om Svaha',
    english_translation: 'Om — so be it — I offer this.',
    tradition: 'universal',
    intention: 'Offering',
    phonetic_guide: 'OHM svah-HAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Svaha is the offering bija — the sound of fire sacrifice. It seals all offerings and prayers, surrendering them to the divine.',
    go_deeper_teaser: 'Svaha: the sound of sacred offering →',
  },
  {
    day_of_year: 331,
    original_script: 'ॐ नमः',
    transliteration: 'Om Namah',
    english_translation: 'Om — I bow — I offer myself.',
    tradition: 'universal',
    intention: 'Surrender',
    phonetic_guide: 'OHM nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Namah — "I bow" — is the most universal act of spiritual surrender. It is the recognition that the divine is greater than the ego.',
    go_deeper_teaser: 'Namah: the power of bowing →',
  },
  {
    day_of_year: 332,
    original_script: 'ॐ नमस्ते',
    transliteration: 'Om Namaste',
    english_translation: 'Om — I bow to the divine in you.',
    tradition: 'universal',
    intention: 'Recognition',
    phonetic_guide: 'OHM nah-mahs-TAY',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'Namaste — "I bow to the divine in you" — is the recognition that every being is a form of the divine. This is the most radical spiritual teaching.',
    go_deeper_teaser: 'Namaste: the greeting that changes how you see the world →',
  },
  {
    day_of_year: 333,
    original_script: 'ॐ तत् त्वम् असि',
    transliteration: 'Om Tat Tvam Asi',
    english_translation: 'Om — that thou art — you are the infinite.',
    tradition: 'universal',
    intention: 'Non-Duality',
    phonetic_guide: 'OHM taht tvahm AH-see',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Day 333 — a triple number — for the triple teaching: the teacher (Tat), the student (Tvam), and the identity between them (Asi).',
    go_deeper_teaser: 'The teacher-student relationship in non-dual wisdom →',
  },
  {
    day_of_year: 334,
    original_script: 'ॐ अयम् आत्मा ब्रह्म',
    transliteration: 'Om Ayam Atma Brahma',
    english_translation: 'Om — this self is Brahman.',
    tradition: 'universal',
    intention: 'Self-Realization',
    phonetic_guide: 'OHM AH-yahm AHT-mah BRAH-mah',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The Mandukya Upanishad mahavakya. This self — the one reading these words right now — is the infinite. Not after enlightenment. Now.',
    go_deeper_teaser: 'The Mandukya Upanishad: the shortest and deepest Upanishad →',
  },
  {
    day_of_year: 335,
    original_script: 'ॐ प्रज्ञानं ब्रह्म',
    transliteration: 'Om Prajnanam Brahma',
    english_translation: 'Om — consciousness is Brahman.',
    tradition: 'universal',
    intention: 'Consciousness',
    phonetic_guide: 'OHM PRAHJ-nyah-nahm BRAH-mah',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The Aitareya Upanishad mahavakya. The very awareness that is reading these words is the infinite. Consciousness is not produced by the brain — it is the ground of being.',
    go_deeper_teaser: 'Consciousness: the hard problem and the Upanishadic answer →',
  },
  {
    day_of_year: 336,
    original_script: 'ॐ अहम् ब्रह्मास्मि',
    transliteration: 'Om Aham Brahmasmi',
    english_translation: 'Om — I am Brahman.',
    tradition: 'universal',
    intention: 'Identity',
    phonetic_guide: 'OHM AH-hahm BRAH-mahs-mih',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The Brihadaranyaka Upanishad mahavakya. The most direct declaration of identity with the infinite. Not a belief — a recognition.',
    go_deeper_teaser: 'Aham Brahmasmi: the most radical statement in human history →',
  },
  {
    day_of_year: 337,
    original_script: 'ॐ शिवोऽहम्',
    transliteration: 'Om Shivoham',
    english_translation: 'Om — I am Shiva.',
    tradition: 'universal',
    intention: 'Identity',
    phonetic_guide: 'OHM shih-VOH-hahm',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'From Adi Shankaracharya\'s Nirvana Shatakam. Not "I worship Shiva" but "I am Shiva" — the direct recognition of identity with pure consciousness.',
    go_deeper_teaser: 'The Nirvana Shatakam: Shankara\'s song of liberation →',
  },
  {
    day_of_year: 338,
    original_script: 'चिदानन्दरूपः शिवोऽहम् शिवोऽहम्',
    transliteration: 'Chidanandarupah Shivoham Shivoham',
    english_translation: 'I am the form of consciousness and bliss — I am Shiva, I am Shiva.',
    tradition: 'universal',
    intention: 'Bliss',
    phonetic_guide: 'chid-AH-nahn-dah-ROO-pah shih-VOH-hahm shih-VOH-hahm',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The refrain of the Nirvana Shatakam. Chidanandarupah — "form of consciousness-bliss." The self is not the body, mind, or ego — it is pure conscious bliss.',
    go_deeper_teaser: 'The Nirvana Shatakam: the complete text →',
  },
  {
    day_of_year: 339,
    original_script: 'ॐ नित्यानन्द',
    transliteration: 'Om Nityananda',
    english_translation: 'Om — eternal bliss.',
    tradition: 'universal',
    intention: 'Bliss',
    phonetic_guide: 'OHM nih-TYAH-nahn-dah',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Nityananda — "eternal bliss" — is the name of several great masters. It points to the bliss that is the natural state of the self, not dependent on circumstances.',
    go_deeper_teaser: 'Nityananda: the eternal bliss that is your nature →',
  },
  {
    day_of_year: 340,
    original_script: 'ॐ परमानन्द',
    transliteration: 'Om Paramananda',
    english_translation: 'Om — supreme bliss.',
    tradition: 'universal',
    intention: 'Supreme Joy',
    phonetic_guide: 'OHM pah-rah-MAH-nahn-dah',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Paramananda — "supreme bliss" — is the highest state of consciousness. It is not an experience that comes and goes but the very nature of pure awareness.',
    go_deeper_teaser: 'Ananda: the bliss that is the nature of the self →',
  },
  {
    day_of_year: 341,
    original_script: 'ॐ सोऽहम् सोऽहम् सोऽहम्',
    transliteration: 'Om Soham Soham Soham',
    english_translation: 'Om — I am that, I am that, I am that.',
    tradition: 'universal',
    intention: 'Identity',
    phonetic_guide: 'OHM SOH-hahm SOH-hahm SOH-hahm',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Triple Soham — the breath mantra repeated three times to deepen the recognition. With every breath, the universe is saying: "I am that."',
    go_deeper_teaser: 'The breath as the teacher: the Soham practice →',
  },
  {
    day_of_year: 342,
    original_script: 'ॐ ब्रह्मानन्दं परमसुखदम्',
    transliteration: 'Om Brahmananda Paramasukhadam',
    english_translation: 'Om — the bliss of Brahman — the giver of supreme happiness.',
    tradition: 'universal',
    intention: 'Bliss',
    phonetic_guide: 'OHM BRAH-mah-nahn-dahm pah-rah-mah-soo-KHAH-dahm',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The opening of the Guru Stotram — the hymn to the Guru. The Guru is the one who gives access to the bliss of Brahman.',
    go_deeper_teaser: 'The Guru Stotram: the complete hymn to the teacher →',
  },
  {
    day_of_year: 343,
    original_script: 'केवलं ज्ञानमूर्तिम्',
    transliteration: 'Kevalam Jnanamurtim',
    english_translation: 'The embodiment of pure knowledge alone.',
    tradition: 'universal',
    intention: 'Knowledge',
    phonetic_guide: 'KAY-vah-lahm JNYAH-nah-MOOR-tihm',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'From the Guru Stotram. The Guru is not a person with knowledge — the Guru is knowledge itself in human form.',
    go_deeper_teaser: 'The Guru as knowledge itself →',
  },
  {
    day_of_year: 344,
    original_script: 'द्वन्द्वातीतं गगनसदृशम्',
    transliteration: 'Dvandvatitam Gaganasadrisham',
    english_translation: 'Beyond all duality — like the sky.',
    tradition: 'universal',
    intention: 'Non-Duality',
    phonetic_guide: 'dvahn-DVAH-tee-tahm GAH-gah-nah-SAH-drih-shahm',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'From the Guru Stotram. The Guru is beyond all opposites — like the sky that contains all weather without being affected by it.',
    go_deeper_teaser: 'The sky mind: the Guru\'s consciousness →',
  },
  {
    day_of_year: 345,
    original_script: 'तत्त्वमस्यादि लक्ष्यम्',
    transliteration: 'Tattvamasyadi Laksyam',
    english_translation: 'Whose goal is "That thou art" and similar teachings.',
    tradition: 'universal',
    intention: 'Teaching',
    phonetic_guide: 'taht-tvahm-AHS-yah-dee LAHK-shyahm',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'From the Guru Stotram. The Guru\'s purpose is to point the student toward the mahavakyas — the great teachings of identity with the infinite.',
    go_deeper_teaser: 'The Guru\'s purpose: pointing to the self →',
  },
  {
    day_of_year: 346,
    original_script: 'एकं नित्यं विमलमचलम्',
    transliteration: 'Ekam Nityam Vimalachalam',
    english_translation: 'One, eternal, pure, and immovable.',
    tradition: 'universal',
    intention: 'Eternity',
    phonetic_guide: 'AY-kahm NIH-tyahm vih-MAH-lah-CHAH-lahm',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'From the Guru Stotram. The four qualities of ultimate reality: one (not many), eternal (not temporal), pure (not defiled), immovable (not changing).',
    go_deeper_teaser: 'The four qualities of ultimate reality →',
  },
  {
    day_of_year: 347,
    original_script: 'सर्वधी साक्षिभूतम्',
    transliteration: 'Sarvadhī Sakshibhutam',
    english_translation: 'The witness of all minds.',
    tradition: 'universal',
    intention: 'Witnessing',
    phonetic_guide: 'SAHR-vah-dhee SAHK-shih-BHOO-tahm',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'From the Guru Stotram. The ultimate reality is the witness of all minds — the awareness that watches all thoughts without being a thought itself.',
    go_deeper_teaser: 'The witness: the awareness behind all experience →',
  },
  {
    day_of_year: 348,
    original_script: 'भावातीतं त्रिगुणरहितम्',
    transliteration: 'Bhavatitam Trigunarahitam',
    english_translation: 'Beyond all becoming — free from the three qualities.',
    tradition: 'universal',
    intention: 'Freedom',
    phonetic_guide: 'bhah-VAH-tee-tahm trih-GOO-nah-rah-HIH-tahm',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'From the Guru Stotram. Trigunarahitam — "free from the three gunas" — the three qualities of nature: tamas, rajas, and sattva. Pure consciousness is beyond all three.',
    go_deeper_teaser: 'The three gunas: the qualities of nature →',
  },
  {
    day_of_year: 349,
    original_script: 'ॐ गुरुर्ब्रह्मा गुरुर्विष्णुः',
    transliteration: 'Om Gurur Brahma Gurur Vishnuh',
    english_translation: 'Om — the Guru is Brahma, the Guru is Vishnu.',
    tradition: 'universal',
    intention: 'Guru',
    phonetic_guide: 'OHM GOO-roor BRAH-mah GOO-roor VISH-noo',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'The Guru Brahma Stotram. The Guru embodies all three aspects of the divine: Brahma the creator, Vishnu the sustainer, Shiva the transformer.',
    go_deeper_teaser: 'The Guru as the trinity: creator, sustainer, transformer →',
  },
  {
    day_of_year: 350,
    original_script: 'गुरुर्देवो महेश्वरः',
    transliteration: 'Gurur Devo Maheshvarah',
    english_translation: 'The Guru is the great lord Shiva.',
    tradition: 'universal',
    intention: 'Transformation',
    phonetic_guide: 'GOO-roor DAY-voh mah-HAYSH-vah-rah',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'The second line of the Guru Brahma Stotram. Maheshvara — "great lord" — is Shiva as the supreme transformer.',
    go_deeper_teaser: 'The transforming power of the Guru →',
  },
  {
    day_of_year: 351,
    original_script: 'गुरुः साक्षात् परं ब्रह्म',
    transliteration: 'Guruh Sakshat Param Brahma',
    english_translation: 'The Guru is directly the supreme Brahman.',
    tradition: 'universal',
    intention: 'Identity',
    phonetic_guide: 'GOO-roo SAHK-shaht PAH-rahm BRAH-mah',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'The third line of the Guru Brahma Stotram. Sakshat — "directly" — the Guru is not a representative of Brahman but Brahman itself in human form.',
    go_deeper_teaser: 'The Guru as Brahman: the highest teaching →',
  },
  {
    day_of_year: 352,
    original_script: 'तस्मै श्री गुरवे नमः',
    transliteration: 'Tasmai Sri Gurave Namah',
    english_translation: 'To that radiant Guru — I bow.',
    tradition: 'universal',
    intention: 'Gratitude',
    phonetic_guide: 'TAHS-my shree GOO-rah-vay nah-MAH',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'The final line of the Guru Brahma Stotram. Tasmai — "to that one." After recognizing the Guru as Brahman, the only appropriate response is bowing.',
    go_deeper_teaser: 'The complete Guru Brahma Stotram →',
  },
  {
    day_of_year: 353,
    original_script: 'ॐ नमो गुरवे',
    transliteration: 'Om Namo Gurave',
    english_translation: 'Om — I bow to the Guru.',
    tradition: 'universal',
    intention: 'Gratitude',
    phonetic_guide: 'OHM nah-MOH GOO-rah-vay',
    sacred_geometry_type: 'flower_of_life',
    context_note: 'A simple, direct bow to the teacher. The Guru is not a person — the Guru is the principle of awakening that appears in many forms.',
    go_deeper_teaser: 'The Guru principle: beyond the personal teacher →',
  },
  {
    day_of_year: 354,
    original_script: 'ॐ सर्वे भवन्तु सुखिनः सर्वे सन्तु निरामयाः',
    transliteration: 'Om Sarve Bhavantu Sukhinah Sarve Santu Niramayah',
    english_translation: 'Om — may all be happy — may all be free from disease.',
    tradition: 'universal',
    intention: 'Universal Welfare',
    phonetic_guide: 'OHM SAHR-vay bhah-VAHN-too soo-KHIH-nah SAHR-vay SAHN-too nih-rah-MAH-yah',
    sacred_geometry_type: 'lotus',
    context_note: 'The first two lines of the universal prayer together. As the year nears its end, we return to the most basic wish: may all be happy and free from suffering.',
    go_deeper_teaser: 'The universal prayer as a year-end practice →',
  },
  {
    day_of_year: 355,
    original_script: 'सर्वे भद्राणि पश्यन्तु मा कश्चिद् दुःखभाग् भवेत्',
    transliteration: 'Sarve Bhadrani Pashyantu Ma Kashchid Duhkhabhag Bhavet',
    english_translation: 'May all see what is auspicious — may no one suffer.',
    tradition: 'universal',
    intention: 'Compassion',
    phonetic_guide: 'SAHR-vay BHAHD-rah-nih PAHSH-yahn-too mah KAHSH-chid DOOH-khah-bhahg BHAH-vayt',
    sacred_geometry_type: 'lotus',
    context_note: 'The final two lines of the universal prayer together. The complete prayer for all beings in four wishes.',
    go_deeper_teaser: 'The complete universal prayer: a year-end reflection →',
  },
  {
    day_of_year: 356,
    original_script: 'ॐ लोकाः समस्ताः सुखिनो भवन्तु',
    transliteration: 'Om Lokah Samastah Sukhino Bhavantu',
    english_translation: 'Om — may all beings in all worlds be happy and free.',
    tradition: 'universal',
    intention: 'Universal Welfare',
    phonetic_guide: 'OHM LOH-kah sah-MAHS-tah soo-KHIH-noh bhah-VAHN-too',
    sacred_geometry_type: 'lotus',
    context_note: 'Returning to this universal prayer as the year nears its end. Lokah — "worlds" — includes all dimensions of existence. The prayer is infinite in scope.',
    go_deeper_teaser: 'Lokah Samastah: the prayer that never gets old →',
  },
  {
    day_of_year: 357,
    original_script: 'ॐ असतो मा सद्गमय तमसो मा ज्योतिर्गमय',
    transliteration: 'Om Asato Ma Sadgamaya Tamaso Ma Jyotirgamaya',
    english_translation: 'Om — lead me from unreal to real — from darkness to light.',
    tradition: 'universal',
    intention: 'Awakening',
    phonetic_guide: 'OHM ah-SAH-toh mah sahd-GAH-mah-yah tah-MAH-soh mah JYOH-tir-gah-mah-yah',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The first two lines of the Pavamana Mantra together. As the year ends, we renew the prayer: lead me from what is false to what is true.',
    go_deeper_teaser: 'The Pavamana Mantra: the three great transitions →',
  },
  {
    day_of_year: 358,
    original_script: 'मृत्योर्मा अमृतं गमय ॐ शान्तिः शान्तिः शान्तिः',
    transliteration: 'Mrityorma Amritam Gamaya Om Shantih Shantih Shantih',
    english_translation: 'Lead me from death to immortality — Om peace, peace, peace.',
    tradition: 'universal',
    intention: 'Immortality',
    phonetic_guide: 'mrih-TYOR-mah AHM-rih-tahm GAH-mah-yah OHM SHAHN-tih SHAHN-tih SHAHN-tih',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'The complete Pavamana Mantra with its closing peace invocation. The three prayers and the three peaces — a complete practice.',
    go_deeper_teaser: 'The complete Pavamana Mantra: a year-end practice →',
  },
  {
    day_of_year: 359,
    original_script: 'ॐ पूर्णमदः पूर्णमिदम् पूर्णात् पूर्णमुदच्यते',
    transliteration: 'Om Purnamadah Purnamidam Purnat Purnamudachyate',
    english_translation: 'Om — that is whole, this is whole — from wholeness, wholeness arises.',
    tradition: 'universal',
    intention: 'Wholeness',
    phonetic_guide: 'OHM POOR-nah-mah-dah POOR-nah-mih-dahm POOR-naht POOR-nahm-oo-DAHCH-yah-tay',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'The first two lines of the Isha Upanishad Shanti Patha together. As the year nears completion, we contemplate the wholeness that was always here.',
    go_deeper_teaser: 'Wholeness: the teaching that the year has been complete all along →',
  },
  {
    day_of_year: 360,
    original_script: 'पूर्णस्य पूर्णमादाय पूर्णमेवावशिष्यते ॐ शान्तिः',
    transliteration: 'Purnasya Purnamadaya Purnamevavashishyate Om Shantih',
    english_translation: 'When wholeness is taken from wholeness, wholeness remains — Om peace.',
    tradition: 'universal',
    intention: 'Completeness',
    phonetic_guide: 'POOR-nahs-yah POOR-nahm-ah-DAH-yah POOR-nah-may-VAH-vah-shish-yah-tay OHM SHAHN-tih',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'The complete Isha Upanishad Shanti Patha. 360 days — and the teaching is: nothing has been lost. You are as whole today as you were on day one.',
    go_deeper_teaser: 'The Isha Upanishad: the shortest and most complete Upanishad →',
  },
  {
    day_of_year: 361,
    original_script: 'ॐ सच्चिदानन्द',
    transliteration: 'Om Satchidananda',
    english_translation: 'Om — existence, consciousness, bliss.',
    tradition: 'universal',
    intention: 'Bliss',
    phonetic_guide: 'OHM saht-chid-AH-nahn-dah',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Day 361 — five days from the end. Returning to the three qualities of ultimate reality. This is what you are. This is what you have always been.',
    go_deeper_teaser: 'Satchidananda: the nature of your true self →',
  },
  {
    day_of_year: 362,
    original_script: 'ॐ शिवोऽहम् शिवोऽहम्',
    transliteration: 'Om Shivoham Shivoham',
    english_translation: 'Om — I am Shiva, I am Shiva.',
    tradition: 'universal',
    intention: 'Identity',
    phonetic_guide: 'OHM shih-VOH-hahm shih-VOH-hahm',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Day 362 — four days from the end. The recognition deepens: not just "I am that" but "I am Shiva" — pure consciousness, pure bliss, pure awareness.',
    go_deeper_teaser: 'The recognition that deepens with practice →',
  },
  {
    day_of_year: 363,
    original_script: 'ॐ तत् त्वम् असि',
    transliteration: 'Om Tat Tvam Asi',
    english_translation: 'Om — that thou art.',
    tradition: 'universal',
    intention: 'Non-Duality',
    phonetic_guide: 'OHM taht tvahm AH-see',
    sacred_geometry_type: 'sri_yantra',
    context_note: 'Day 363 — three days from the end. The teacher\'s greatest gift: you are not separate from the infinite. You never were. You never will be.',
    go_deeper_teaser: 'Tat tvam asi: the teaching that ends all seeking →',
  },
  {
    day_of_year: 364,
    original_script: 'ॐ लोकाः समस्ताः सुखिनो भवन्तु',
    transliteration: 'Om Lokah Samastah Sukhino Bhavantu',
    english_translation: 'Om — may all beings in all worlds be happy and free.',
    tradition: 'universal',
    intention: 'Universal Welfare',
    phonetic_guide: 'OHM LOH-kah sah-MAHS-tah soo-KHIH-noh bhah-VAHN-too',
    sacred_geometry_type: 'lotus',
    context_note: 'Day 364 — the penultimate day. After a year of practice, the prayer naturally expands: not just "may I be happy" but "may all beings be happy."',
    go_deeper_teaser: 'How a year of practice changes your prayers →',
  },
  {
    day_of_year: 365,
    original_script: 'ॐ शान्तिः शान्तिः शान्तिः',
    transliteration: 'Om Shantih Shantih Shantih',
    english_translation: 'Om — peace, peace, peace.',
    tradition: 'universal',
    intention: 'Peace',
    phonetic_guide: 'OHM SHAHN-tih SHAHN-tih SHAHN-tih',
    sacred_geometry_type: 'seed_of_life',
    context_note: 'Day 365 — the final day of the year. The year began with Om and ends with peace. Three repetitions for body, speech, and mind. The practice is complete — and it begins again.',
    go_deeper_teaser: 'The end that is a beginning: starting the cycle again →',
  },
];
